src/main/asciidoc/dns.adoc
src/main/asciidoc/eventbus.adoc
src/main/asciidoc/index.adoc

Signed-off-by: Alain Penders <alain@rexorient.com>

Documentation fixes

---

src/main/java/io/vertx/core/file/impl/WindowsFileSystem.java
src/main/java/io/vertx/core/impl/Utils.java
src/main/java/io/vertx/core/impl/VertxImpl.java
src/main/java/io/vertx/core/logging/impl/VertxLoggerFormatter.java
src/test/java/io/vertx/test/core/DNSTest.java
src/test/java/io/vertx/test/core/FileResolverTestBase.java
src/test/java/io/vertx/test/core/FileSystemFileResolverTest.java
src/test/java/io/vertx/test/core/FileSystemTest.java
src/test/java/io/vertx/test/core/HttpTest.java
src/test/java/io/vertx/test/core/JsonArrayTest.java
src/test/java/io/vertx/test/core/JsonObjectTest.java
src/test/java/io/vertx/test/core/NetTest.java
src/test/java/io/vertx/test/core/RedeploymentTest.java
src/test/java/io/vertx/test/fakedns/FakeDNSServer.java

Signed-off-by: Alain Penders <alain@rexorient.com>

Fix unit tests so they pass on Windows (tested on 8.1).

---

src/main/asciidoc/java/metrics.adoc
src/main/java/examples/MetricsExamples.java
src/main/java/io/vertx/core/datagram/impl/DatagramSocketImpl.java
src/main/java/io/vertx/core/eventbus/impl/EventBusImpl.java
src/main/java/io/vertx/core/http/impl/HttpClientImpl.java
src/main/java/io/vertx/core/http/impl/HttpServerImpl.java
src/main/java/io/vertx/core/impl/VertxImpl.java
src/main/java/io/vertx/core/metrics/Measured.java
src/main/java/io/vertx/core/metrics/impl/DummyVertxMetrics.java
src/main/java/io/vertx/core/net/impl/NetClientImpl.java
src/main/java/io/vertx/core/net/impl/NetServerImpl.java
src/main/java/io/vertx/core/spi/metrics/EventBusMetrics.java
src/main/java/io/vertx/core/spi/metrics/Metrics.java
src/main/java/io/vertx/core/spi/metrics/MetricsProvider.java
src/main/java/io/vertx/core/spi/metrics/NetMetrics.java
src/main/java/io/vertx/core/spi/metrics/VertxMetrics.java
src/test/java/io/vertx/test/core/DummyMetricsTest.java

@purplefox please review, thanks

Decouple metrics retrieval from vertx core + cleanup

---

src/main/java/io/vertx/core/eventbus/impl/EventBusImpl.java
src/main/java/io/vertx/core/metrics/impl/DummyVertxMetrics.java
src/main/java/io/vertx/core/spi/metrics/EventBusMetrics.java
src/test/java/io/vertx/test/core/MetricsTest.java
src/test/java/io/vertx/test/core/VertxTestBase.java
src/test/java/io/vertx/test/fakemetrics/FakeEventBusMetrics.java
src/test/java/io/vertx/test/fakemetrics/FakeMetricsFactory.java
src/test/java/io/vertx/test/fakemetrics/FakeVertxMetrics.java
src/test/java/io/vertx/test/fakemetrics/HandlerMetric.java
src/test/java/io/vertx/test/fakemetrics/HandlerRegistration.java
src/test/java/io/vertx/test/fakemetrics/ReceivedMessage.java
src/test/java/io/vertx/test/fakemetrics/SentMessage.java
src/test/resources/META-INF/services/io.vertx.core.spi.VertxMetricsFactory

Changes to improve eventbus metrics reporting to provide additional and more accurate metrics.

Eventbus metrics

---

src/main/java/io/vertx/core/file/impl/AsyncFileImpl.java
src/main/java/io/vertx/core/file/impl/FileSystemImpl.java
src/main/java/io/vertx/core/impl/ContextImpl.java
src/main/java/io/vertx/core/impl/DeploymentManager.java
src/main/java/io/vertx/core/impl/EventLoopContext.java
src/main/java/io/vertx/core/impl/HAManager.java
src/main/java/io/vertx/core/impl/VertxImpl.java
src/main/java/io/vertx/core/impl/VertxInternal.java
src/main/java/io/vertx/core/impl/WorkerContext.java

@vietj please review
Previously we weren't using the correct pools for different types of operations, this commit fixes it.

Use correct thread pools

---

pom.xml
src/main/java/io/vertx/core/eventbus/impl/EventBusImpl.java
src/main/java/io/vertx/core/http/HttpServerRequest.java
src/main/java/io/vertx/core/http/impl/HttpClientImpl.java
src/main/java/io/vertx/core/http/impl/HttpServerImpl.java
src/main/java/io/vertx/core/http/impl/HttpServerRequestImpl.java
src/main/java/io/vertx/core/impl/ContextImpl.java
src/main/java/io/vertx/core/impl/DeploymentManager.java
src/main/java/io/vertx/core/impl/FutureImpl.java
src/main/java/io/vertx/core/impl/HAManager.java
src/main/java/io/vertx/core/impl/VertxImpl.java
src/main/java/io/vertx/core/net/impl/NetServerImpl.java
src/test/java/io/vertx/test/core/HATest.java
src/test/java/io/vertx/test/core/HttpTest.java
src/test/java/io/vertx/test/core/MetricsTest.java
src/test/java/io/vertx/test/core/NetTest.java

Request ended

---

src/main/java/io/vertx/core/Context.java
src/main/java/io/vertx/core/datagram/impl/DatagramSocketImpl.java
src/main/java/io/vertx/core/dns/impl/DnsClientImpl.java
src/main/java/io/vertx/core/eventbus/impl/EventBusImpl.java
src/main/java/io/vertx/core/http/impl/HttpClientImpl.java
src/main/java/io/vertx/core/impl/ContextImpl.java
src/main/java/io/vertx/core/impl/EventLoopContext.java
src/main/java/io/vertx/core/impl/FailoverCompleteHandler.java
src/main/java/io/vertx/core/impl/HAManager.java
src/main/java/io/vertx/core/impl/VertxImpl.java
src/main/java/io/vertx/core/impl/VertxInternal.java
src/main/java/io/vertx/core/net/impl/HandlerManager.java
src/main/java/io/vertx/core/net/impl/NetClientImpl.java
src/main/java/io/vertx/core/shareddata/impl/AsynchronousCounter.java
src/main/java/io/vertx/core/shareddata/impl/AsynchronousLock.java
src/test/java/io/vertx/test/core/ClusteredEventBusTest.java
src/test/java/io/vertx/test/core/ComplexHATest.java
src/test/java/io/vertx/test/core/CreateVertxTest.java
src/test/java/io/vertx/test/core/HATest.java
src/test/java/io/vertx/test/core/VertxTestBase.java
src/test/java/io/vertx/test/fakecluster/FakeClusterManager.java

Clustering fixes

---

gradle.properties
vertx-core/src/main/java/org/vertx/java/core/eventbus/impl/DefaultEventBus.java
vertx-core/src/main/java/org/vertx/java/core/impl/DefaultVertx.java
vertx-hazelcast/src/main/java/org/vertx/java/spi/cluster/impl/hazelcast/HazelcastAsyncMultiMap.java
vertx-platform/src/main/java/org/vertx/java/platform/impl/DefaultPlatformManager.java
vertx-platform/src/main/java/org/vertx/java/platform/impl/FailoverCompleteHandler.java
vertx-platform/src/main/java/org/vertx/java/platform/impl/HAManager.java
vertx-testsuite/src/test/java/org/vertx/java/tests/platform/ha/HATest.java
vertx-testsuite/src/test/java/org/vertx/java/tests/platform/ha/TestPlatformManager.java
vertx-testsuite/src/test/java/vertx/tests/core/websockets/WebsocketsTestClient.java

2.x clustering fixes

---

src/main/java/io/vertx/core/VertxOptions.java
src/main/java/io/vertx/core/eventbus/impl/EventBusImpl.java
src/main/java/io/vertx/core/impl/HAManager.java
src/main/java/io/vertx/core/impl/VertxImpl.java
src/test/java/io/vertx/test/core/ClusteredEventBusTest.java
src/test/java/io/vertx/test/core/HATest.java
src/test/java/io/vertx/test/core/HZBugTest.java
src/test/java/io/vertx/test/core/VertxOptionsTest.java

More clustering fixes

---

src/main/java/io/vertx/core/eventbus/impl/EventBusImpl.java
src/test/java/io/vertx/test/core/LocalEventBusTest.java

@purplefox please review this fix

MessageConsumer#endHandler should be invoked with the registration context

---

src/main/java/io/vertx/core/eventbus/impl/EventBusImpl.java
src/main/java/io/vertx/core/http/impl/HttpServerImpl.java
src/main/java/io/vertx/core/http/impl/ServerConnection.java
src/main/java/io/vertx/core/metrics/impl/DummyVertxMetrics.java
src/main/java/io/vertx/core/spi/VertxMetricsFactory.java
src/main/java/io/vertx/core/spi/metrics/DatagramSocketMetrics.java
src/main/java/io/vertx/core/spi/metrics/EventBusMetrics.java
src/main/java/io/vertx/core/spi/metrics/HttpClientMetrics.java
src/main/java/io/vertx/core/spi/metrics/HttpServerMetrics.java
src/main/java/io/vertx/core/spi/metrics/Metrics.java
src/main/java/io/vertx/core/spi/metrics/NetworkMetrics.java
src/main/java/io/vertx/core/spi/metrics/TCPMetrics.java
src/main/java/io/vertx/core/spi/metrics/VertxMetrics.java
src/test/java/io/vertx/test/core/AsyncTestBase.java
src/test/java/io/vertx/test/core/ConfigurableMetricsFactory.java
src/test/java/io/vertx/test/core/MetricsContextTest.java
src/test/java/io/vertx/test/core/MetricsTest.java
src/test/java/io/vertx/test/core/VertxTestBase.java
src/test/java/io/vertx/test/fakemetrics/FakeEventBusMetrics.java
src/test/java/io/vertx/test/fakemetrics/FakeHttpServerMetrics.java
src/test/resources/META-INF/services/io.vertx.core.spi.VertxMetricsFactory

Metrics context/thread fixed and javadoc

---

src/main/java/io/vertx/core/http/impl/ClientConnection.java
src/test/java/io/vertx/test/core/WebsocketTest.java

Bug with client websocket worker

---

src/main/java/examples/ConfigurableVerticleExamples.java
src/main/java/io/vertx/core/package-info.java

Two small paragraphs explaining how to retrieve the configuration from a vertical as well as system and environment variables.

Verticle configuration documentation.

---

src/main/java/io/vertx/core/json/JsonArray.java
src/test/java/io/vertx/test/core/JsonArrayTest.java

JsonArray::addAll method

---

src/main/java/io/vertx/core/datagram/impl/DatagramServerHandler.java
src/main/java/io/vertx/core/dns/impl/netty/DnsMessage.java
src/main/java/io/vertx/core/dns/impl/netty/decoder/RecordDecoderFactory.java
src/main/java/io/vertx/core/dns/impl/netty/decoder/TextDecoder.java
src/main/java/io/vertx/core/eventbus/impl/BodyReadStream.java
src/main/java/io/vertx/core/eventbus/impl/EventBusImpl.java
src/main/java/io/vertx/core/http/impl/HttpClientRequestImpl.java
src/main/java/io/vertx/core/http/impl/ServerConnection.java
src/main/java/io/vertx/core/impl/DeploymentManager.java
src/main/java/io/vertx/core/impl/FutureFactoryImpl.java
src/main/java/io/vertx/core/impl/verticle/PackageHelper.java
src/main/java/io/vertx/core/net/impl/ConnectionBase.java
src/main/java/io/vertx/core/net/impl/HandlerManager.java
src/main/java/io/vertx/core/net/impl/KeyStoreHelper.java
src/main/java/io/vertx/core/net/impl/NetClientImpl.java
src/main/java/io/vertx/core/net/impl/NetSocketImpl.java
src/test/java/io/vertx/test/core/ClusteredEventBusTest.java

I found that there are places in the code which do not use new features of java 7 and 8. I've committed  a handful of them. I've seen that static analysis found much more places that could be easily refactored. 
If you think it's worth to commit such improvements in the Vert.x project, I would be glad to spend some more time to help improve the code quality by refactoring.

Code refactor 

---

src/main/java/io/vertx/core/package-info.java

Not sure the English is very accurate, but at least we can keep track this note should be added to the documentation

Add a note on setPeriodic vs. setTimer

---

src/main/asciidoc/java/index.adoc
src/main/java/io/vertx/core/package-info.java

Just the HA / fail over documentation.

Add high availability documentation

---

src/main/asciidoc/java/index.adoc
src/main/java/examples/CoreExamples.java
src/main/java/io/vertx/core/package-info.java

Add the documentation related to the Context object.

---

src/main/java/io/vertx/core/impl/DeploymentManager.java

Log the deploy redeploy error

---

src/main/java/io/vertx/core/logging/LoggerFactory.java
src/test/java/io/vertx/core/logging/LoggerFactoryTest.java

Fix for bug
470205
https://bugs.eclipse.org/bugs/show_bug.cgi?id=470205

Fixed logging from anonymous class- https://bugs.eclipse.org/bugs/show_bug.cgi?id=470205

---

src/main/java/io/vertx/core/http/impl/HttpServerRequestImpl.java
src/main/java/io/vertx/core/http/impl/ServerConnection.java
src/test/java/io/vertx/test/core/HttpTest.java

@cescoffier @pmlopes @vietj please review
Fix for https://bugs.eclipse.org/bugs/show_bug.cgi?id=470125

Fix behaviour of absoluteURI

---

src/main/java/io/vertx/core/Context.java
src/main/java/io/vertx/core/impl/ContextImpl.java
src/test/java/io/vertx/test/core/DeploymentTest.java
src/test/java/io/vertx/test/core/TestVerticle3.java

Signed-off-by: Jeremy Truelove <jtruelove@gmail.com>

exposed the number of instances of a verticle that were started

---

src/main/java/io/vertx/core/http/impl/ClientConnection.java
src/test/java/io/vertx/test/core/HttpTest.java
src/test/java/io/vertx/test/core/NetTest.java

This is a fix for https://bugs.eclipse.org/bugs/show_bug.cgi?id=470228
@vietj @cescoffier @pmlopes please review

Make sure exception is provided if connection is closed

---

src/main/asciidoc/java/http.adoc
src/main/java/io/vertx/core/http/package-info.java

Replace Apex with Web

---

vertx-testsuite/src/test/resources/langs.properties

Signed-off-by: Toby Crawley <toby@tcrawley.org>

update to mod-lang-clojure 1.0.5

---

src/main/java/io/vertx/core/http/impl/HttpServerImpl.java
src/main/java/io/vertx/core/http/impl/ServerConnection.java
src/main/java/io/vertx/core/http/impl/ServerWebSocketImpl.java
src/main/java/io/vertx/core/http/impl/WebSocketImpl.java
src/main/java/io/vertx/core/http/impl/WebSocketImplBase.java
src/main/java/io/vertx/core/impl/FileResolver.java
src/test/java/io/vertx/test/core/HttpTest.java

This PR should fix the deadlock as reported here:
https://groups.google.com/forum/?fromgroups#!topic/vertx/LIVo9qrZrTg

Synchronize on connection not websocket to remove deadlock

---

src/main/asciidoc/cheatsheet/DatagramSocketOptions.adoc
src/main/asciidoc/cheatsheet/DeliveryOptions.adoc
src/main/asciidoc/cheatsheet/DeploymentOptions.adoc
src/main/asciidoc/cheatsheet/HttpClientOptions.adoc
src/main/asciidoc/cheatsheet/HttpServerOptions.adoc
src/main/asciidoc/cheatsheet/NetClientOptions.adoc
src/main/asciidoc/cheatsheet/NetServerOptions.adoc
src/main/asciidoc/cheatsheet/OpenOptions.adoc
src/main/asciidoc/cheatsheet/PemKeyCertOptions.adoc
src/main/asciidoc/cheatsheet/VertxOptions.adoc
src/main/asciidoc/java/override/dependencies.adoc
src/main/java/io/vertx/core/http/impl/ServerConnection.java
src/main/java/io/vertx/core/metrics/impl/DummyVertxMetrics.java
src/main/java/io/vertx/core/spi/metrics/HttpServerMetrics.java
src/test/java/io/vertx/test/core/MetricsTest.java
src/test/java/io/vertx/test/fakemetrics/FakeHttpServerMetrics.java

reported in vertx-dropwizard-metrics project https://github.com/vert-x3/vertx-dropwizard-metrics/issues/10

Fix metrics SPI http request upgrade to websocket

---

src/main/java/io/vertx/core/buffer/Buffer.java
src/main/java/io/vertx/core/buffer/impl/BufferImpl.java
src/test/java/io/vertx/test/core/BufferTest.java

Helpful methods for decoding bandwith-optimized network protocols.
Signed-off-by: Thomas Segismont <tsegismont@gmail.com>

Add #getUnsignedXXX methods to Buffer class

---

src/main/java/examples/BufferExamples.java
src/main/java/io/vertx/core/buffer/package-info.java

Document new buffer unsignedXXX methods
I've checked generated Java and JS doc.

Document new buffer unsignedXXX methods

---

src/main/java/io/vertx/core/impl/DeploymentManager.java
src/test/java/io/vertx/test/core/DeploymentTest.java

@cescoffier @pmlopes please review

don't add parent verticle if deployment fails

---

src/main/asciidoc/java/override/json.adoc
src/main/java/io/vertx/core/json/JsonArray.java
src/main/java/io/vertx/core/json/JsonObject.java
src/test/java/io/vertx/test/core/JsonArrayTest.java
src/test/java/io/vertx/test/core/JsonObjectTest.java

This completes the implementation of I-JSON

Implement Temporal Support for JSON

---

src/main/java/io/vertx/core/http/HttpClientResponse.java
src/main/java/io/vertx/core/http/HttpServerRequest.java
src/main/java/io/vertx/core/http/impl/HttpClientRequestImpl.java
src/main/java/io/vertx/core/http/impl/HttpClientResponseImpl.java
src/main/java/io/vertx/core/http/impl/HttpServerRequestImpl.java
src/test/java/io/vertx/test/core/HttpTest.java

It should be all right now.
Signed-off-by: Ingo Weiss <ingo@redhat.com>

Implementation of Eclipse bug #469623

---

src/main/asciidoc/cheatsheet/VertxOptions.adoc
src/main/generated/io/vertx/core/VertxOptionsConverter.java
src/main/java/io/vertx/core/VertxOptions.java
src/main/java/io/vertx/core/impl/VertxImpl.java
src/main/java/io/vertx/core/metrics/MetricsOptions.java
src/test/java/io/vertx/test/core/StarterTest.java
src/test/java/io/vertx/test/core/VertxOptionsTest.java

@cescoffier @pmlopes please review.

Cluster public props

---

src/main/java/io/vertx/core/eventbus/impl/EventBusImpl.java
src/main/java/io/vertx/core/impl/BlockedThreadChecker.java
src/main/java/io/vertx/core/impl/DeploymentManager.java
src/test/java/io/vertx/test/core/DeploymentTest.java

Fix for https://bugs.eclipse.org/bugs/show_bug.cgi?id=473714

Handler outside sync

---

src/main/asciidoc/java/http.adoc
src/main/asciidoc/java/override/json.adoc
src/main/generated/io/vertx/core/DeploymentOptionsConverter.java
src/main/generated/io/vertx/core/VertxOptionsConverter.java
src/main/generated/io/vertx/core/datagram/DatagramSocketOptionsConverter.java
src/main/generated/io/vertx/core/file/OpenOptionsConverter.java
src/main/generated/io/vertx/core/http/HttpClientOptionsConverter.java
src/main/generated/io/vertx/core/http/HttpServerOptionsConverter.java
src/main/generated/io/vertx/core/metrics/MetricsOptionsConverter.java
src/main/generated/io/vertx/core/net/ClientOptionsBaseConverter.java
src/main/generated/io/vertx/core/net/JksOptionsConverter.java
src/main/generated/io/vertx/core/net/NetClientOptionsConverter.java
src/main/generated/io/vertx/core/net/NetServerOptionsConverter.java
src/main/generated/io/vertx/core/net/NetworkOptionsConverter.java
src/main/generated/io/vertx/core/net/PemKeyCertOptionsConverter.java
src/main/generated/io/vertx/core/net/PemTrustOptionsConverter.java
src/main/generated/io/vertx/core/net/PfxOptionsConverter.java
src/main/generated/io/vertx/core/net/TCPSSLOptionsConverter.java
src/main/resources/vertx-java/template/dataObjectConverter.templ

Add license header to the converter template
Compute the Converter class javadoc

Add license and javadoc to Converters

---

src/main/java/io/vertx/core/http/impl/HttpServerResponseImpl.java
src/test/java/io/vertx/test/core/HttpTest.java

#48 escape special chars on status message

---

src/main/java/io/vertx/core/http/impl/HttpServerResponseImpl.java
src/test/java/io/vertx/test/core/HttpTest.java

Solves: https://github.com/vert-x3/issues/issues/51

#51: check if file exists before send

---

src/main/java/io/vertx/core/http/impl/HttpClientImpl.java

I've added cause to SSLHandshakeException. Otherwise the real cause is lost.

added cause of SSLHandshakeException

---

src/main/java/io/vertx/core/shareddata/impl/AsynchronousLock.java

Signed-off-by: Testo Nakada <test1@doramail.com>

Fix some typo and clean up AsynchronousLock class

---

src/main/java/io/vertx/core/impl/DeploymentManager.java
src/main/java/io/vertx/core/spi/VerticleFactory.java
src/test/java/io/vertx/test/core/VerticleFactoryTest.java

Allow createVerticle to run on a worker thread

---

src/main/java/io/vertx/core/net/impl/HandlerManager.java
src/test/java/io/vertx/test/core/HttpTest.java

Fixes https://bugs.eclipse.org/bugs/show_bug.cgi?id=477822

Don't set server to no handlers unless all handlers are removed

---

src/main/java/io/vertx/core/json/Json.java
src/main/java/io/vertx/core/json/JsonArray.java
src/main/java/io/vertx/core/json/JsonObject.java
src/test/java/io/vertx/test/core/JsonArrayTest.java
src/test/java/io/vertx/test/core/JsonObjectTest.java

Fix for https://bugs.eclipse.org/bugs/show_bug.cgi?id=477756

Make sure stream() for JsonObject/JsonArray returns correct types

---

src/main/java/io/vertx/core/cli/UsageMessageFormatter.java
src/main/java/io/vertx/core/impl/launcher/commands/RunCommand.java
src/main/java/io/vertx/core/impl/launcher/commands/StopCommand.java
src/test/java/io/vertx/core/cli/impl/DefaultCLITest.java

Display argument in the usage message

CLI usage argument

---

src/main/java/io/vertx/core/logging/JULLogDelegate.java
src/main/java/io/vertx/core/logging/Log4jLogDelegate.java
src/main/java/io/vertx/core/logging/Logger.java
src/main/java/io/vertx/core/logging/SLF4JLogDelegate.java
src/main/java/io/vertx/core/spi/logging/LogDelegate.java

Signed-off-by: Manish Kumar <manishk@vmware.com>
Added the ability to pass the additional argument to be printed in the logs.

Added support for parametrized logging(similar to how SLF4J API).

---

src/main/java/io/vertx/core/impl/FileResolver.java

Extend the FileResolver to support OSGi bundles

---

src/main/asciidoc/java/cli-for-java.adoc
src/main/asciidoc/java/cli.adoc
src/main/generated/io/vertx/core/cli/ArgumentConverter.java
src/main/generated/io/vertx/core/cli/OptionConverter.java
src/main/java/examples/cli/CLIExamples.java
src/main/java/io/vertx/core/Launcher.java
src/main/java/io/vertx/core/cli/Argument.java
src/main/java/io/vertx/core/cli/CommandLine.java
src/main/java/io/vertx/core/cli/Option.java
src/main/java/io/vertx/core/cli/TypedArgument.java
src/main/java/io/vertx/core/cli/TypedOption.java
src/main/java/io/vertx/core/cli/UsageMessageFormatter.java
src/main/java/io/vertx/core/cli/annotations/CLIConfigurator.java
src/main/java/io/vertx/core/cli/annotations/Option.java
src/main/java/io/vertx/core/cli/annotations/package-info.java
src/main/java/io/vertx/core/cli/impl/DefaultCLI.java
src/main/java/io/vertx/core/cli/impl/DefaultCommandLine.java
src/main/java/io/vertx/core/cli/impl/DefaultParser.java
src/main/java/io/vertx/core/cli/package-info.java
src/main/java/io/vertx/core/impl/launcher/commands/BareCommand.java
src/test/java/io/vertx/core/cli/impl/DefaultCLITest.java
src/test/java/io/vertx/core/cli/impl/DefaultParserTest.java
src/test/java/io/vertx/core/cli/impl/TypedArgumentTest.java
src/test/java/io/vertx/test/core/LauncherTest.java

Some improvement around the CLI system:
* provide multiple argument
* provide 'help' flag to options
* provide validity of command line support
* provide options with choices

Various cli improvements

---

src/main/java/io/vertx/core/Context.java
src/main/java/io/vertx/core/MultiMap.java
src/main/java/io/vertx/core/Vertx.java
src/main/java/io/vertx/core/cli/CLI.java
src/main/java/io/vertx/core/cli/CommandLine.java
src/main/java/io/vertx/core/datagram/DatagramSocket.java
src/main/java/io/vertx/core/dns/DnsClient.java
src/main/java/io/vertx/core/dns/SrvRecord.java
src/main/java/io/vertx/core/eventbus/Message.java
src/main/java/io/vertx/core/file/FileSystem.java
src/main/java/io/vertx/core/http/HttpClientRequest.java
src/main/java/io/vertx/core/http/HttpClientResponse.java
src/main/java/io/vertx/core/http/HttpServer.java
src/main/java/io/vertx/core/http/HttpServerRequest.java
src/main/java/io/vertx/core/http/HttpServerResponse.java
src/main/java/io/vertx/core/http/ServerWebSocket.java
src/main/java/io/vertx/core/http/WebSocketBase.java
src/main/java/io/vertx/core/net/NetServer.java
src/main/java/io/vertx/core/net/NetSocket.java
src/main/java/io/vertx/core/streams/ReadStream.java
src/main/java/io/vertx/core/streams/StreamBase.java
src/main/java/io/vertx/core/streams/WriteStream.java

the api has been annotated with `@Nullable` where it makes sense to improve the polyglot API.
please review

annotate api with @Nullable

---

src/main/asciidoc/java/index.adoc
src/main/java/io/vertx/core/Launcher.java
src/main/java/io/vertx/core/cli/UsageMessageFormatter.java
src/main/java/io/vertx/core/cli/annotations/CLIConfigurator.java
src/main/java/io/vertx/core/impl/launcher/VertxCommandLauncher.java
src/main/java/io/vertx/core/impl/launcher/commands/BareCommand.java
src/main/java/io/vertx/core/impl/launcher/commands/Watcher.java
src/main/java/io/vertx/core/package-info.java
src/test/java/io/vertx/core/cli/impl/CLIConfiguratorTest.java
src/test/java/io/vertx/core/cli/impl/DefaultCLITest.java
src/test/java/io/vertx/core/impl/launcher/DefaultCommandTest.java
src/test/java/io/vertx/core/impl/launcher/LauncherExtensibilityTest.java

* Add the possibility to add/remove command in the launcher subclasses
* Improve extendability of the Launcher class
* Some cosmetic and minor fixes

Improve the launcher extensibility

---

src/main/java/io/vertx/core/impl/HAManager.java

Signed-off-by: Andrey Gura <andreyn.gura@gmail.com>

Race fixed in HAManager

---

src/main/java/io/vertx/core/streams/impl/PumpFactoryImpl.java
src/test/java/io/vertx/test/core/PumpTest.java

added Objects.requireNonNull and the unit tests for that

BZ482023: Pump.pump does not check that the streams != null

---

src/main/generated/io/vertx/core/http/HttpClientOptionsConverter.java
src/main/generated/io/vertx/core/http/HttpServerOptionsConverter.java
src/main/java/io/vertx/core/http/HttpClientOptions.java
src/main/java/io/vertx/core/http/HttpServerOptions.java
src/main/java/io/vertx/core/http/impl/HttpClientImpl.java
src/main/java/io/vertx/core/http/impl/HttpServerImpl.java
src/test/java/io/vertx/test/core/HttpTest.java

Signed-off-by: Testo Nakada <test1@doramail.com>

Add an option to set max chunk size for large file upload/download

---

src/main/java/io/vertx/core/http/impl/ConnectionManager.java
src/main/java/io/vertx/core/http/impl/HttpClientImpl.java
src/main/java/io/vertx/core/http/impl/HttpClientRequestImpl.java
src/test/java/io/vertx/test/core/HttpTest.java

Handle timed out waiting requests without causing a connect/close.

---

src/main/java/io/vertx/core/buffer/Buffer.java
src/main/java/io/vertx/core/buffer/impl/BufferImpl.java
src/test/java/io/vertx/test/core/BufferTest.java

To make it easier to work with Charset instead of String

Add toString(Charset) method

---

src/main/asciidoc/dataobjects.adoc
src/main/generated/io/vertx/core/http/HttpClientOptionsConverter.java
src/main/java/io/vertx/core/http/ConnectionPoolTooBusyException.java
src/main/java/io/vertx/core/http/HttpClientOptions.java
src/main/java/io/vertx/core/http/impl/ConnectionManager.java
src/main/java/io/vertx/core/http/impl/HttpClientImpl.java
src/test/asciidoc/dataobjects.adoc
src/test/java/io/vertx/test/core/HttpTest.java

Ported 2.x support for setting maxWaitQueueSize on HttpClient to master.

---

src/main/asciidoc/dataobjects.adoc
src/main/asciidoc/java/http.adoc
src/main/java/io/vertx/core/http/impl/ConnectionManager.java
src/main/java/io/vertx/core/http/impl/HttpClientImpl.java
src/main/java/io/vertx/core/http/impl/HttpClientRequestImpl.java
src/main/java/io/vertx/core/http/package-info.java
src/test/java/io/vertx/test/core/HttpTest.java

HttpClient sharing clarifications and warns - fixes #1266

---

src/main/asciidoc/java/index.adoc
src/main/java/examples/CoreExamples.java
src/main/java/io/vertx/core/CompositeFuture.java
src/main/java/io/vertx/core/Future.java
src/main/java/io/vertx/core/impl/CompositeFutureImpl.java
src/main/java/io/vertx/core/impl/FutureImpl.java
src/main/java/io/vertx/core/package-info.java
src/test/java/io/vertx/test/core/FutureTest.java

See https://github.com/vert-x3/issues/issues/84

Composite future implementation

---

src/main/java/io/vertx/core/file/package-info.java
src/main/java/io/vertx/core/http/package-info.java
src/main/java/io/vertx/core/net/package-info.java

Signed-off-by: Jens Baitinger <bait@gmx.de>

Added documentation about classpath resolution and restrictions

---

pom.xml

Update parent pom and integrate changes proposed in https://github.com/eclipse/vert.x/pull/1305.

Update parent, dependencies and plugins

---

src/main/asciidoc/java/override/dependencies.adoc
src/main/java/io/vertx/core/Launcher.java
src/main/java/io/vertx/core/impl/launcher/VertxLifecycleHooks.java
src/main/java/io/vertx/core/impl/launcher/commands/RunCommand.java
src/test/asciidoc/dataobjects.adoc
src/test/java/io/vertx/test/core/LauncherTest.java

Signed-off-by: Jeremy Truelove <jtruelove@gmail.com>

expose the config after parsing to the Launcher

---

src/main/java/io/vertx/core/AbstractVerticle.java
src/main/java/io/vertx/core/net/TCPSSLOptions.java

Default values added in TCPSSLOptions
Typo corrected in AbstractVerticle
Signed-off-by: Harisankar <s_harisankar@yahoo.com>

[1313] Javadoc corrections

---

src/main/asciidoc/dataobjects.adoc
src/main/java/io/vertx/core/impl/launcher/commands/RunCommand.java
src/test/asciidoc/dataobjects.adoc
src/test/java/io/vertx/core/impl/launcher/commands/RunCommandTest.java

Fix #1328
Do not display the configuration in the log as it can contain sensitive data.

Do not dump the configuration in the log

---

src/main/asciidoc/dataobjects.adoc
src/main/asciidoc/java/net.adoc
src/main/generated/io/vertx/core/eventbus/EventBusOptionsConverter.java
src/main/generated/io/vertx/core/net/TCPSSLOptionsConverter.java
src/main/java/examples/NetExamples.java
src/main/java/io/vertx/core/http/HttpClientOptions.java
src/main/java/io/vertx/core/http/HttpServerOptions.java
src/main/java/io/vertx/core/net/NetClientOptions.java
src/main/java/io/vertx/core/net/NetServerOptions.java
src/main/java/io/vertx/core/net/TCPSSLOptions.java
src/main/java/io/vertx/core/net/impl/SSLHelper.java
src/main/java/io/vertx/core/net/package-info.java
src/test/java/io/vertx/test/core/HttpTLSTest.java
src/test/java/io/vertx/test/core/NetTest.java

Rebased PR #1276 onto http2-openssl as suggested by @vietj. Had to rewrite some of the tests because of the refactoring on this branch. Thus the ignored test mentioned in PR #1276 is no longer part of this PR.

Rebase PR #1276 on http2-openssl

---

src/main/asciidoc/java/override/verticles.adoc
src/main/java/docoverride/verticles/package-info.java

Issue reported in https://github.com/vert-x3/vertx-web-site/issues/150.

Fix typo in verticle doc

---

src/main/java/io/vertx/core/eventbus/impl/CodecManager.java
src/test/java/io/vertx/test/core/ClusteredEventBusTest.java
src/test/java/io/vertx/test/core/EventBusTestBase.java
src/test/java/io/vertx/test/core/LocalEventBusTest.java

Signed-off-by: Dan O'Reilly <oreilldf@gmail.com>

Support codecs of ReplyException sub-classes.

---

BUILD_README.md
pom.xml

* Fix the coverage profile
* Update the build documentation

Fix coverage profile and build instructions

---

src/main/java/io/vertx/core/impl/launcher/commands/Watcher.java

Signed-off-by: msanguineti <mirco@sanguineti.gr>

Fix for issue#1411

---

src/main/java/io/vertx/core/buffer/Buffer.java
src/main/java/io/vertx/core/buffer/impl/BufferImpl.java
src/test/java/io/vertx/test/core/BufferTest.java

Hi 
This PR include some Little Endian operations which in Netty 4.1
Signed-off-by: stream <stream1984@gmail.com>

add more buffer feature.

---

src/main/java/io/vertx/core/json/Json.java
src/test/java/io/vertx/test/core/JsonObjectTest.java

Allow java.time.Instant in JsonObject/JsonArray put as java.lang.Object

---

src/main/java/io/vertx/core/http/impl/ClientConnection.java
src/main/java/io/vertx/core/http/impl/ConnectionManager.java
src/main/java/io/vertx/core/http/impl/Http1xPool.java
src/main/java/io/vertx/core/http/impl/Http2ClientConnection.java
src/main/java/io/vertx/core/http/impl/Http2Pool.java
src/main/java/io/vertx/core/http/impl/HttpClientImpl.java
src/main/java/io/vertx/core/http/impl/Waiter.java
src/main/java/io/vertx/core/impl/VertxImpl.java
src/main/java/io/vertx/core/metrics/impl/DummyVertxMetrics.java
src/main/java/io/vertx/core/spi/metrics/HttpClientMetrics.java
src/main/java/io/vertx/core/spi/metrics/VertxMetrics.java
src/test/java/io/vertx/test/core/CustomMetricsFactory.java
src/test/java/io/vertx/test/core/MetricsContextTest.java
src/test/java/io/vertx/test/core/MetricsOptionsTest.java
src/test/java/io/vertx/test/core/MetricsTest.java
src/test/java/io/vertx/test/fakemetrics/EndpointMetric.java
src/test/java/io/vertx/test/fakemetrics/FakeHttpClientMetrics.java
src/test/java/io/vertx/test/fakemetrics/FakePoolMetrics.java
src/test/java/io/vertx/test/fakemetrics/FakeVertxMetrics.java
src/test/java/io/vertx/test/fakemetrics/HttpClientMetric.java

Provides HttpClient endpoint monitoring providing per endpoint queing / connections / usage

Metrics for endpoints + make dummy metrics singleton instances

---

src/main/java/io/vertx/core/http/HttpClient.java
src/main/java/io/vertx/core/net/NetClientOptions.java
src/main/java/io/vertx/core/net/TCPSSLOptions.java
src/test/java/io/vertx/test/core/NetClientOptionsTest.java

- the equals check NetClientOptions was wrong for hostnameVerificationAlgorithm, added a unit test for that and changed to equals
- a few comment typo corrections

change String comparison with == in NetClientOptions

---

src/main/java/io/vertx/core/http/impl/MimeMapping.java

Spec: 15 March 2016 (https://www.w3.org/TR/WOFF2/#IMT)
PR for the issue: #1440

Mapping added for woff2 files following the latest W3C recommendation

---

pom.xml
src/main/asciidoc/dataobjects.adoc
src/main/asciidoc/java/index.adoc
src/main/generated/io/vertx/core/dns/AddressResolverOptionsConverter.java
src/main/java/examples/CoreExamples.java
src/main/java/io/vertx/core/dns/AddressResolverOptions.java
src/main/java/io/vertx/core/dns/impl/fix/DnsNameResolver.java
src/main/java/io/vertx/core/dns/impl/fix/DnsNameResolverBuilder.java
src/main/java/io/vertx/core/dns/impl/fix/package-info.java
src/main/java/io/vertx/core/impl/AddressResolver.java
src/main/java/io/vertx/core/package-info.java
src/test/java/io/vertx/test/core/HostnameResolutionTest.java
src/test/java/io/vertx/test/fakedns/FakeDNSServer.java

Implement search domains - fixes #1475

---

src/main/asciidoc/java/override/dependencies.adoc
src/main/asciidoc/java/shareddata.adoc
src/main/java/io/vertx/core/shareddata/AsyncMap.java
src/main/java/io/vertx/core/shareddata/package-info.java

Addresses comments from #1320:
* add a note about the behavior of distributed data structure
* fix mistake in the AsyncMap javadoc

Fix #1320 - improve shared data documentation

---

src/main/asciidoc/java/override/dependencies.adoc
src/main/java/io/vertx/core/eventbus/impl/EventBusImpl.java
src/main/java/io/vertx/core/eventbus/impl/MessageImpl.java
src/main/java/io/vertx/core/eventbus/impl/clustered/ClusteredMessage.java
src/main/java/io/vertx/core/metrics/impl/DummyVertxMetrics.java
src/main/java/io/vertx/core/spi/metrics/EventBusMetrics.java
src/test/java/io/vertx/test/core/MetricsTest.java
src/test/java/io/vertx/test/fakemetrics/FakeEventBusMetrics.java
src/test/java/io/vertx/test/fakemetrics/HandlerMetric.java

Eventbusmetrics schedule message

---

src/main/asciidoc/java/override/dependencies.adoc
src/main/java/io/vertx/core/dns/impl/fix/DnsNameResolver.java
src/main/java/io/vertx/core/dns/impl/fix/DnsNameResolverBuilder.java
src/main/java/io/vertx/core/dns/impl/fix/DnsQueryContext.java

AddressResolver should not bind locally - fixes #1479

---

src/main/asciidoc/java/index.adoc
src/main/java/examples/CoreExamples.java
src/main/java/io/vertx/core/Future.java
src/main/java/io/vertx/core/package-info.java

Related to https://github.com/vert-x3/vertx-web-site/issues/160
Improved the async operation composition section in the documentation.

Improved the async operation composition doc

---

src/main/java/io/vertx/core/impl/launcher/commands/Watcher.java
src/test/java/io/vertx/core/impl/launcher/commands/WatcherAbsolutePathTest.java
src/test/java/io/vertx/core/impl/launcher/commands/WatcherTest.java

Fix https://github.com/vert-x3/issues/issues/156
* Add support for absolute path pattern in the redeploy commands
* Fix a race condition in the modification test

Add support for redeploy patterns using absolute paths

---

src/test/java/io/vertx/test/core/HostnameResolutionTest.java

fixes #1524 
add test to resolve localhost with different case spellings and check that the returned address
object has the hostname localhost set.
the issue itself didn't require changes in vert.x as it is fixed by the update to netty 4.1.4

unit test for #1524 localhost resolve issue with netty in Windows

---

src/main/java/io/vertx/core/http/impl/ConnectionManager.java
src/test/java/io/vertx/test/core/Http1xTest.java

the requests were not sent via proxy, added unit test for this

fix http 1.1 requests with socks proxy

---

src/main/java/io/vertx/core/net/impl/SSLHelper.java
src/main/java/io/vertx/core/net/package-info.java
src/test/java/io/vertx/test/core/HttpTLSTest.java

Remove openssl keycert format limitations

---

src/main/asciidoc/java/index.adoc
src/main/java/examples/CoreExamples.java
src/main/java/io/vertx/core/CompositeFuture.java
src/main/java/io/vertx/core/impl/CompositeFutureImpl.java
src/main/java/io/vertx/core/package-info.java
src/test/java/io/vertx/test/core/FutureTest.java

Composite future join composition

---

src/main/java/io/vertx/core/impl/ContextImpl.java
src/main/java/io/vertx/core/impl/VertxImpl.java
src/main/java/io/vertx/core/impl/WorkerPool.java
src/test/java/io/vertx/test/core/NamedWorkerPoolTest.java

Worker pool fixes

---

src/main/asciidoc/java/index.adoc
src/main/java/io/vertx/core/package-info.java

Add some details about the configuration of the cache behavior
It's related to https://github.com/eclipse/vert.x/issues/1528 and to https://github.com/eclipse/vert.x/issues/1528

Add documentation on the Vert.x cache and how to configure it.

---

src/test/java/io/vertx/test/core/NetTest.java

remove TODO and explain the test properly

clarify comment to NetTest#testHostVerificationHttpsMatching

---

src/main/asciidoc/java/index.adoc

The title pretty much says it I guess 😉

Documentation fix for running bare instances

---

src/main/java/io/vertx/core/CompositeFuture.java

The comments for CompositeFuture.join() method is vague. So I adjust it.

revise CompositeFuture.join() comments

---

src/test/java/io/vertx/test/core/ClusterWideMapTest.java
src/test/java/io/vertx/test/core/ClusteredAsynchronousLockTest.java
src/test/java/io/vertx/test/fakecluster/FakeClusterManager.java

- put with ttl
- putIfAbsent with ttl
- lock is released when owning node goes down

More cluster tests

---

src/main/asciidoc/dataobjects.adoc
src/main/generated/io/vertx/core/net/ClientOptionsBaseConverter.java
src/main/java/io/vertx/core/http/HttpClientOptions.java
src/main/java/io/vertx/core/http/impl/ConnectionManager.java
src/main/java/io/vertx/core/net/ClientOptionsBase.java
src/main/java/io/vertx/core/net/NetClientOptions.java
src/main/java/io/vertx/core/net/impl/NetClientImpl.java
src/test/java/io/vertx/test/core/Http1xTest.java
src/test/java/io/vertx/test/core/HttpTest.java
src/test/java/io/vertx/test/core/NetTest.java

@pmlopes @tsegismont @cescoffier please review

Support local address for TCP clients - fixes #1569

---

src/main/java/io/vertx/core/http/HttpClientRequest.java
src/main/java/io/vertx/core/http/impl/ClientConnection.java
src/main/java/io/vertx/core/http/impl/HttpClientRequestImpl.java
src/main/java/io/vertx/core/http/impl/HttpClientRequestPushPromise.java
src/test/java/io/vertx/test/core/Http1xTest.java
src/test/java/io/vertx/test/core/Http2Test.java

@cescoffier @pmlopes @tsegismont please review

Improve HttpClientRequest reset support - fixes #1642

---

src/main/asciidoc/java/cli-for-java.adoc
src/main/asciidoc/java/index.adoc
src/main/java/io/vertx/core/http/impl/HttpServerImpl.java
src/test/java/io/vertx/test/core/HttpConnectionEarlyResetTest.java

Override exceptionCaught, log at trace level and close channel

Fixes #1619 Too many log generation - LoadBalancer Heartbeat

---

src/main/java/io/vertx/core/impl/AddressResolver.java

I noticed a similar problem as @luengnat with the DNS vert.x client which did not use inflight dns resolver and caused too much load on our DNS server. So I cook up a patch that should address the issue

Use inflight DNS client instead

---

CONTRIBUTING.md

This one of the results from the F2F meeting

updated doc as per f2f discussion

---

src/main/java/io/vertx/core/DeploymentOptions.java
src/main/java/io/vertx/core/VertxOptions.java

Signed-off-by: Emad Alblueshi emad.albloushi@gmail.com

Fixes time unit in doc

---

src/main/java/io/vertx/core/net/package-info.java

Signed-off-by: Julian Ladisch <eclipse.org-rtn@ladisch.de>

fix SLF4J/Log4j typo

---

src/main/java/io/vertx/core/http/HttpClient.java
src/main/java/io/vertx/core/http/impl/HttpClientImpl.java
src/test/java/io/vertx/test/core/HttpClientRequestBuilderTest.java

Signed-off-by: Paul Bakker <paul.bakker@luminis.eu>

Added more create* methods httpclientbuilder

---

src/main/asciidoc/java/cli-for-java.adoc
src/main/java/io/vertx/core/impl/WorkerExecutorImpl.java
src/main/java/io/vertx/core/impl/WorkerExecutorInternal.java

Needed for vert-x3/vertx-rx#46

Extract a WorkerExecutorInternal interface

---

src/main/asciidoc/java/cli-for-java.adoc
src/main/resources/vertx-java/template/dataObjectConverter.templ
src/test/asciidoc/dataobjects.adoc
src/test/generated/io/vertx/test/codegen/TestDataObjectConverter.java
src/test/java/io/vertx/test/codegen/DataObjectTest.java
src/test/java/io/vertx/test/codegen/TestDataObject.java

please review @tsegismont @cescoffier @jponge

Support map entry adder in data object converters - fixes #1462

---

src/main/java/io/vertx/core/impl/FileResolver.java
src/test/java/io/vertx/test/core/FileResolverTestBase.java

Fix #1472.
Synchronize the resolveFile method to avoid concurrent accesses.

Fix race condition in the FileResolver

---

src/main/generated/io/vertx/core/DeploymentOptionsConverter.java
src/main/generated/io/vertx/core/cli/OptionConverter.java
src/main/generated/io/vertx/core/dns/AddressResolverOptionsConverter.java
src/main/generated/io/vertx/core/eventbus/EventBusOptionsConverter.java
src/main/generated/io/vertx/core/http/HttpClientOptionsConverter.java
src/main/generated/io/vertx/core/http/HttpServerOptionsConverter.java
src/main/generated/io/vertx/core/net/ClientOptionsBaseConverter.java
src/main/generated/io/vertx/core/net/PemTrustOptionsConverter.java
src/main/generated/io/vertx/core/net/TCPSSLOptionsConverter.java
src/main/java/io/vertx/core/net/JksOptions.java
src/main/java/io/vertx/core/net/PemKeyCertOptions.java
src/main/java/io/vertx/core/net/PemTrustOptions.java
src/main/java/io/vertx/core/net/PfxOptions.java
src/main/java/io/vertx/core/net/ProxyOptions.java
src/main/resources/vertx-java/template/dataObjectConverter.templ
src/test/generated/io/vertx/test/codegen/TestDataObjectConverter.java
src/test/java/io/vertx/core/cli/OptionTest.java
src/test/java/io/vertx/test/core/KeyStoreTest.java

more toJson() methods

---

src/main/java/io/vertx/core/json/JsonObject.java
src/test/java/io/vertx/test/core/JsonPOJOMapperTest.java

Signed-off-by: Luke Hutchison <luke.hutch@gmail.com>

Add JsonObject POJO mapping convenience methods

---

src/main/generated/io/vertx/core/http/HttpClientOptionsConverter.java
src/main/generated/io/vertx/core/http/HttpServerOptionsConverter.java
src/main/java/io/vertx/core/http/HttpClientOptions.java
src/main/java/io/vertx/core/http/HttpServerOptions.java
src/main/java/io/vertx/core/http/impl/ClientConnection.java
src/main/java/io/vertx/core/http/impl/HttpServerImpl.java
src/test/java/io/vertx/test/core/Http1xTest.java
src/test/java/io/vertx/test/core/WebsocketTest.java

Signed-off-by: stecolet@gmail.com <stecolet@gmail.com>

Unmasking frame on websocket

---

src/main/asciidoc/dataobjects.adoc
src/main/asciidoc/java/http.adoc
src/main/generated/io/vertx/core/http/HttpClientOptionsConverter.java
src/main/java/examples/HTTPExamples.java
src/main/java/io/vertx/core/http/HttpClient.java
src/main/java/io/vertx/core/http/HttpClientOptions.java
src/main/java/io/vertx/core/http/HttpClientRequest.java
src/main/java/io/vertx/core/http/RequestOptions.java
src/main/java/io/vertx/core/http/impl/ClientConnection.java
src/main/java/io/vertx/core/http/impl/ConnectionManager.java
src/main/java/io/vertx/core/http/impl/Http2ClientConnection.java
src/main/java/io/vertx/core/http/impl/HttpClientImpl.java
src/main/java/io/vertx/core/http/impl/HttpClientRequestBase.java
src/main/java/io/vertx/core/http/impl/HttpClientRequestImpl.java
src/main/java/io/vertx/core/http/impl/HttpClientRequestPushPromise.java
src/main/java/io/vertx/core/http/impl/HttpUtils.java
src/main/java/io/vertx/core/http/package-info.java
src/test/java/io/vertx/test/core/Http1xTLSTest.java
src/test/java/io/vertx/test/core/Http2ClientTest.java
src/test/java/io/vertx/test/core/Http2ServerTest.java
src/test/java/io/vertx/test/core/Http2TestBase.java
src/test/java/io/vertx/test/core/HttpTLSTest.java
src/test/java/io/vertx/test/core/HttpTest.java
src/test/java/io/vertx/test/core/HttpTestBase.java
src/test/java/io/vertx/test/core/URITest.java
src/test/java/io/vertx/test/core/WebsocketTest.java

Http client redirect - fixes #1779

---

src/main/java/io/vertx/core/eventbus/impl/clustered/ClusteredEventBus.java
src/test/java/io/vertx/test/core/EventBusTestBase.java

Replaces PR #1766
Fixed a failing test (the flag to stop publishing was never updated)

Fixes #1765 NullPointer in sendToSubs

---

src/main/java/io/vertx/core/impl/VertxImpl.java
src/test/java/io/vertx/test/core/CreateVertxTest.java
src/test/java/io/vertx/test/core/VertxTest.java

Signed-off-by: Oded Arbel <oded@geek.co.il>
Fixes issue #1797

notify caller that the cluster manager they requested failed to join

---

src/main/java/io/vertx/core/impl/VertxImpl.java

Fixes #1810 
Signed-off-by: Oded Arbel <oded@geek.co.il>

Verify pool size against the correct parameter

---

src/main/asciidoc/dataobjects.adoc
src/main/generated/io/vertx/core/eventbus/EventBusOptionsConverter.java
src/main/generated/io/vertx/core/net/TCPSSLOptionsConverter.java
src/main/java/io/vertx/core/http/HttpClientOptions.java
src/main/java/io/vertx/core/http/HttpServerOptions.java
src/main/java/io/vertx/core/net/ClientOptionsBase.java
src/main/java/io/vertx/core/net/JdkSSLEngineOptions.java
src/main/java/io/vertx/core/net/NetServerOptions.java
src/main/java/io/vertx/core/net/NetworkOptions.java
src/main/java/io/vertx/core/net/TCPSSLOptions.java
src/test/java/io/vertx/test/core/Http1xTest.java
src/test/java/io/vertx/test/core/TestUtils.java

Fixes Http*Options serialization

---

src/test/java/io/vertx/test/core/ClusteredEventBusWithSSLTest.java
src/test/java/io/vertx/test/core/EventBusTestBase.java

Avoid sending too many messages

Refactored tests unregister while sending/publishing

---

src/main/java/io/vertx/core/Future.java
src/test/java/io/vertx/test/core/FutureTest.java

I believe these are very useful methods (at least for me)

Future recovering methods

---

src/main/asciidoc/java/net.adoc
src/main/java/examples/NetExamples.java
src/main/java/io/vertx/core/net/SelfSignedCertificate.java
src/main/java/io/vertx/core/net/impl/SelfSignedCertificateImpl.java
src/main/java/io/vertx/core/net/package-info.java
src/test/java/io/vertx/test/core/NetTest.java

This is useful for testing and development purposes.

Helper for self-signed certificates

---

src/main/java/io/vertx/core/http/impl/HttpClientImpl.java

Fixes java.lang.IllegalArgumentException: port out of range:-1

Default redirect handler: do not fail on URIs without explicit port

---

src/main/asciidoc/dataobjects.adoc
src/main/asciidoc/java/index.adoc
src/main/generated/io/vertx/core/dns/AddressResolverOptionsConverter.java
src/main/java/io/vertx/core/dns/AddressResolverOptions.java
src/main/java/io/vertx/core/impl/AddressResolver.java
src/main/java/io/vertx/core/package-info.java
src/test/java/io/vertx/test/core/HostnameResolutionTest.java
src/test/java/io/vertx/test/fakedns/FakeDNSServer.java

Hostname resolver improvements

---

src/main/asciidoc/java/index.adoc
src/main/java/io/vertx/core/package-info.java

Add a section in the doc mentioning:
* the connection reset
* the SLF4J message

Logging troubleshooting section in doc

---

src/test/java/io/vertx/test/core/FaultToleranceTest.java
src/test/java/io/vertx/test/core/FaultToleranceVerticle.java

- log failure if not expected in verticle
- no send timeout in verticle as on CI the instance can be slow
- make fields accessible to subclasses
- expose hooks
- more informative messages in case of failures

Improve FaultToleranceTest

---

src/test/java/io/vertx/test/fakecluster/FakeClusterManager.java

The FakeCM could complete the execute blocking future twice.
And there was an issue iterating over the nodes map keys, it needs to be synchronized.

Fixed io.vertx.test.core.ClusteredEventBusWithSSLTest

---

src/main/asciidoc/java/cli-for-java.adoc
src/main/asciidoc/java/override/dependencies.adoc
src/test/java/io/vertx/test/core/AsyncTestBase.java
src/test/java/io/vertx/test/core/DeploymentTest.java
src/test/java/io/vertx/test/core/EventBusFlowControlTest.java
src/test/java/io/vertx/test/core/HATest.java
src/test/java/io/vertx/test/core/Http1xTest.java
src/test/java/io/vertx/test/core/Http2ClientTest.java
src/test/java/io/vertx/test/core/Http2Test.java
src/test/java/io/vertx/test/core/HttpMetricsTest.java
src/test/java/io/vertx/test/core/LauncherTest.java
src/test/java/io/vertx/test/core/MetricsContextTest.java
src/test/java/io/vertx/test/core/MetricsTest.java
src/test/java/io/vertx/test/core/NamedWorkerPoolTest.java
src/test/java/io/vertx/test/core/NetTest.java
src/test/java/io/vertx/test/core/StarterTest.java

More tests fixes

---

src/main/java/io/vertx/core/spi/cluster/AsyncMultiMap.java

* A typo
* The values are (conceptually) in a Set, not in a List
* Add what the boolean means for remove
* Detail the behavior of all the removes

Add precision to the AsyncMultiMap javadoc

---

src/main/asciidoc/dataobjects.adoc
src/main/java/io/vertx/core/shareddata/LocalMap.java
src/main/java/io/vertx/core/shareddata/impl/LocalMapImpl.java
src/test/asciidoc/dataobjects.adoc
src/test/java/io/vertx/test/core/LocalSharedDataTest.java

Fix https://github.com/eclipse/vert.x/issues/1348
Extend the `LocalMap` interface to implement `Map`.

Make LocalMap extends Map

---

src/main/java/io/vertx/core/impl/FailedFuture.java
src/main/java/io/vertx/core/impl/FutureFactoryImpl.java
src/main/java/io/vertx/core/impl/FutureImpl.java
src/main/java/io/vertx/core/impl/SucceededFuture.java

please review @pmlopes @tsegismont

Make Future thread safe

---

src/main/java/io/vertx/core/impl/FailedFuture.java
src/main/java/io/vertx/core/impl/FutureImpl.java
src/main/java/io/vertx/core/impl/SucceededFuture.java
src/test/java/io/vertx/test/core/FutureTest.java

Having a proper toString() implementation helps while debugging.

Meaningful Future toString()

---

src/main/java/io/vertx/core/json/JsonArray.java
src/main/java/io/vertx/core/json/JsonObject.java

Signed-off-by: Emad Alblueshi <emad.albloushi@gmail.com>

Javadoc enhancement for JsonObject and JsonArray

---

src/main/java/io/vertx/core/file/FileSystem.java

Signed-off-by: Ruslan Sennov <ruslan.sennov@gmail.com>

minor javadoc fix

---

src/main/java/io/vertx/core/net/SelfSignedCertificate.java
src/main/java/io/vertx/core/net/impl/SelfSignedCertificateImpl.java

Allow passing FQDNs for self-signed certificates

---

src/main/java/io/vertx/core/json/Json.java
src/test/java/io/vertx/test/core/JsonMapperTest.java

Add support for RFC-7493 to Json

---

src/main/java/io/vertx/core/http/package-info.java

http pkg apidoc: Add link from SNI server docs to related net pkg apidoc

---

.editorconfig

Fixes #1707 
This is the minimal impact change, as we edit files we can check-in the formatting fixes on the go...

Add editorconfig file as per wiki

---

src/main/java/io/vertx/core/json/Json.java
src/test/java/io/vertx/test/core/JsonPOJOMapperTest.java

Base64 was not properly handled when dealing with POJOs

---

src/main/java/io/vertx/core/http/impl/HttpServerResponseImpl.java
src/test/java/io/vertx/test/core/Http1xTest.java
src/test/java/io/vertx/test/core/HttpTest.java

Fixes: vert-x3/issues#80
Manually tested as per issue description.

Avoid NPE and call handler with Failed Future

---

src/main/java/io/vertx/core/http/impl/Http1xOrH2CHandler.java
src/main/java/io/vertx/core/http/impl/HttpServerImpl.java
src/test/java/io/vertx/test/core/Http1xTest.java
src/test/java/io/vertx/test/core/Http2ServerTest.java

Packet lost in Http1xOrHttp2Handler - fixes #2007

---

src/main/java/io/vertx/core/CompositeFuture.java

Signed-off-by: Emmanuele Abbenante <emmanuele.abbenante@gmail.com>
Added some information about the behavior of the CompositeFuture regarding the handlers of the coordinated futures.

Clarified behavior of CompositeFuture on JavaDoc.

---

src/main/java/io/vertx/core/http/Http2Settings.java
src/test/java/io/vertx/core/http/Http2SettingsTest.java

Http2Settings.hashCode() does not conform to contract

---

src/test/java/io/vertx/test/core/ClusterWideMapTest.java

Missing Test for AsyncMap<X,Buffer> in ClusterWideMapTest.java

---

src/main/asciidoc/dataobjects.adoc
src/main/generated/io/vertx/core/file/CopyOptionsConverter.java
src/main/java/io/vertx/core/file/CopyOptions.java
src/main/java/io/vertx/core/file/FileSystem.java
src/main/java/io/vertx/core/file/impl/FileSystemImpl.java
src/test/java/io/vertx/core/file/CopyOptionsTest.java
src/test/java/io/vertx/core/file/impl/FileSystemImplTest.java
src/test/java/io/vertx/test/core/FileSystemTest.java

Fixes #2032
Added new copy/move methods with CopyOptions.

FileSystem methods do not accept options

---

src/main/java/io/vertx/core/http/impl/ServerConnection.java
src/test/java/io/vertx/test/core/Http1xTest.java
src/test/java/io/vertx/test/core/HttpTest.java

HttpServerRequest exception handler is not called when conn closed

---

src/main/java/io/vertx/core/http/impl/HttpClientResponseImpl.java

HttpClientResponseImpl doesnt log when no handler is set

---

src/main/java/io/vertx/core/eventbus/DeliveryOptions.java
src/test/java/io/vertx/core/eventbus/DeliveryOptionsTest.java

Added a toJson method to DeliveryOptions

---

src/main/asciidoc/dataobjects.adoc
src/main/generated/io/vertx/core/file/OpenOptionsConverter.java
src/main/java/io/vertx/core/file/OpenOptions.java
src/main/java/io/vertx/core/file/impl/AsyncFileImpl.java
src/test/java/io/vertx/test/core/FileSystemTest.java

Allow AsyncFile's to be opened in append mode

---

src/main/java/io/vertx/core/shareddata/LocalMap.java

Mismatch between documentation and implementation for LocalMap

---

src/main/java/io/vertx/core/http/impl/HttpClientImpl.java
src/test/java/io/vertx/test/core/WebsocketTest.java

WebSocket request options not honored

---

src/main/java/io/vertx/core/eventbus/impl/clustered/ConnectionHolder.java

Add error log output for cluster connection failures

---

src/main/java/io/vertx/core/Vertx.java
src/main/java/io/vertx/core/impl/DeploymentManager.java
src/main/java/io/vertx/core/impl/VertxImpl.java
src/test/java/io/vertx/test/core/DeploymentTest.java

Deploy verticles with a supplier or a class

---

src/main/java/io/vertx/core/AsyncResult.java

this fixes the wrong docs mentioned in #2099 
Also fixes two instances of future where it should be async result

Fixed docs

---

src/main/java/io/vertx/core/logging/Log4j2LogDelegate.java

Based on [discussion](https://groups.google.com/d/msg/vertx/oYQhzlSikPU/EJeKIwJUAgAJ).

Fix Map Lookup feature for Log4j 2

---

src/main/java/io/vertx/core/http/WebSocketBase.java
src/main/java/io/vertx/core/http/WebSocketFrame.java
src/main/java/io/vertx/core/http/impl/ClientHandler.java
src/main/java/io/vertx/core/http/impl/HttpServerImpl.java
src/main/java/io/vertx/core/http/impl/WebSocketFrameFactoryImpl.java
src/main/java/io/vertx/core/http/impl/WebSocketImplBase.java
src/main/java/io/vertx/core/spi/WebSocketFrameFactory.java
src/test/java/io/vertx/test/core/Http1xTest.java
src/test/java/io/vertx/test/core/WebsocketTest.java

In response to https://github.com/vert-x3/issues/issues/290

Add Websocket Ping/Pong API methods and fix ping response (Issue #290)

---

src/main/java/io/vertx/core/http/Http2Settings.java
src/test/java/io/vertx/test/core/Http2ClientTest.java

bug: second part of the test was always true

---

src/main/java/io/vertx/core/http/HttpClient.java
src/main/java/io/vertx/core/http/RequestOptions.java
src/main/java/io/vertx/core/http/impl/HttpClientImpl.java
src/test/java/io/vertx/test/core/WebsocketTest.java

Let users connect with absolute websocket urls

---

src/test/java/io/vertx/test/core/ProxyErrorTest.java

the test would fail if the provider's dns returns a adserver as unknown hostname
Signed-off-by: alexlehm <alexlehm@gmail.com>

issue #2141: use fakedns to avoid resolving unknown.hostname

---

src/main/asciidoc/java/datagrams.adoc
src/main/asciidoc/java/http.adoc
src/main/asciidoc/java/index.adoc
src/main/java/io/vertx/core/datagram/package-info.java
src/main/java/io/vertx/core/http/package-info.java
src/main/java/io/vertx/core/package-info.java

Signed-off-by: Benjamin Porter <freedomben@protonmail.com>

Documentation fixes:  Fix up typos, grammar

---

src/main/java/io/vertx/core/impl/DeploymentManager.java
src/test/java/io/vertx/test/core/BlockedThreadCheckerTest.java
src/test/java/io/vertx/test/core/BlockedThreadWarning.java
src/test/java/io/vertx/test/core/NamedWorkerPoolTest.java

DeploymentOptions#setMaxWorkerExecuteTime not honored if pool name is set

---

src/main/java/io/vertx/core/Vertx.java
src/main/java/io/vertx/core/impl/VertxImpl.java
src/main/java/io/vertx/core/impl/resolver/DnsResolverProvider.java
src/test/java/io/vertx/test/core/DNSTest.java

Signed-off-by: Pavel Drankov <titantins@gmail.com>
A solution for https://github.com/eclipse/vert.x/issues/2239

Default configuration for vertx dns client

---

src/main/java/io/vertx/core/net/impl/VertxSniHandler.java

Use new SniCompletionEvent from Netty

---

src/main/java/io/vertx/core/eventbus/MessageConsumer.java

Signed-off-by: Ranger Tsao <cao.zhifu@gmail.com>

fix java doc error in MessageConsumer

---

src/main/java/io/vertx/core/shareddata/impl/LocalMapImpl.java
src/test/java/io/vertx/test/core/LocalSharedDataTest.java

A solution for https://github.com/vert-x3/issues/issues/313

LocalMap computeIfPresent, compute, merge incorrect behavior

---

src/main/java/io/vertx/core/http/impl/HttpClientImpl.java
src/main/java/io/vertx/core/http/impl/HttpUtils.java
src/test/java/io/vertx/test/core/HttpTest.java

Redirect handler should not decode query params

---

src/main/java/io/vertx/core/http/impl/HttpClientRequestBase.java

Allow access to host() field

---

src/main/java/io/vertx/core/net/impl/transport/Transport.java

Signed-off-by: guoyu511 <guoyu.511@gmail.com>

Set SO_REUSEPORT to ServerBootstrap instead of child options

---

src/main/java/io/vertx/core/http/impl/Http1xServerConnection.java
src/test/java/io/vertx/test/core/Http1xTest.java

HTTP server connection keeps processing pending pipelined requests

---

src/main/asciidoc/dataobjects.adoc
src/main/generated/io/vertx/core/http/HttpClientOptionsConverter.java
src/main/java/io/vertx/core/http/HttpClientOptions.java
src/main/java/io/vertx/core/http/RecyclePolicy.java
src/main/java/io/vertx/core/http/impl/ConnectionManager.java
src/main/java/io/vertx/core/http/impl/HttpClientImpl.java
src/main/java/io/vertx/core/http/impl/pool/Pool.java
src/test/java/io/vertx/test/core/net/ConnectionPoolTest.java

Signed-off-by: Michael Pogrebinsky <smichpog2@gmail.com>
https://github.com/vert-x3/issues/issues/350

The HTTP client uses a LIFO strategy for connection pooling instead of a FIFO strategy

---

vertx-hazelcast/src/main/java/org/vertx/java/spi/cluster/impl/hazelcast/HazelcastAsyncMultiMap.java

Signed-off-by: nevesmarcio nevesmarcio@gmail.com

Memory leak fix in the subscribers cache

---

src/main/java/io/vertx/core/buffer/Buffer.java
src/main/java/io/vertx/core/json/JsonArray.java
src/main/java/io/vertx/core/json/JsonObject.java
src/main/java/io/vertx/core/shareddata/LocalMap.java
src/main/java/io/vertx/core/shareddata/Shareable.java
src/main/java/io/vertx/core/shareddata/impl/Checker.java
src/test/java/io/vertx/test/core/LocalSharedDataTest.java

Allow to store mutable objects in local map

---

src/main/java/io/vertx/core/impl/launcher/commands/ExecUtils.java
src/test/java/io/vertx/core/impl/launcher/LauncherExtensibilityTest.java
src/test/java/io/vertx/core/impl/launcher/commands/BareCommandTest.java
src/test/java/io/vertx/core/impl/launcher/commands/ClasspathHandlerTest.java
src/test/java/io/vertx/core/impl/launcher/commands/CommandTestBase.java
src/test/java/io/vertx/core/impl/launcher/commands/ExecUtilsTest.java
src/test/java/io/vertx/core/impl/launcher/commands/RedeployTest.java
src/test/java/io/vertx/core/impl/launcher/commands/RunCommandTest.java
src/test/java/io/vertx/core/impl/launcher/commands/StartStopListCommandsTest.java
src/test/java/io/vertx/core/impl/launcher/commands/WatcherAbsolutePathTest.java
src/test/java/io/vertx/core/impl/launcher/commands/WatcherTest.java
src/test/java/io/vertx/test/core/AsyncTestBase.java
src/test/java/io/vertx/test/core/BlockedThreadWarning.java
src/test/java/io/vertx/test/core/ClusteredEventBusTestBase.java
src/test/java/io/vertx/test/core/DNSTest.java
src/test/java/io/vertx/test/core/EventBusTestBase.java
src/test/java/io/vertx/test/core/HostnameResolutionTest.java
src/test/java/io/vertx/test/core/Http1xTest.java
src/test/java/io/vertx/test/core/HttpTest.java
src/test/java/io/vertx/test/core/MetricsTest.java
src/test/java/io/vertx/test/core/NetTest.java
src/test/java/io/vertx/test/core/ProxyErrorTest.java
src/test/java/io/vertx/test/core/TestUtils.java
src/test/java/io/vertx/test/fakedns/FakeDNSServer.java

Open PR for fixing various issues with Windows OS
a few commits needs validation from @tsegismont and @cescoffier

Windows test fixes

---

src/test/java/io/vertx/test/core/AsynchronousLockTest.java
src/test/java/io/vertx/test/core/ClusteredAsynchronousLockTest.java

Test acquiring different locks on same event loop

---

src/main/asciidoc/eventbus.adoc

Also some small formatting improvements.
Signed-off-by: Sébastien Le Callonnec <sebastien@weblogism.com>

Fix minor typos and grammar

---

src/main/java/io/vertx/core/http/HttpHeaders.java
src/main/java/io/vertx/core/http/impl/Http1xClientConnection.java
src/main/java/io/vertx/core/http/impl/HttpServerRequestImpl.java
src/test/java/io/vertx/test/core/Http1xTest.java
src/test/java/io/vertx/test/core/HttpTest.java

...instead of keeping our own with uppercase letters (not HTTP/2 friendly)

Use Netty's HTTP header constants

---

src/main/java/io/vertx/core/http/HttpClientResponse.java
src/main/java/io/vertx/core/http/impl/Http1xClientConnection.java
src/main/java/io/vertx/core/http/impl/Http2ClientConnection.java
src/main/java/io/vertx/core/http/impl/HttpClientResponseImpl.java
src/test/java/io/vertx/test/core/Http1xTest.java

HttpClient response chunk handling rework

---

src/main/java/io/vertx/core/shareddata/SharedData.java

Document lock semantics wrt single threaded ordering

---

src/main/asciidoc/dataobjects.adoc
src/main/asciidoc/filesystem.adoc
src/main/generated/io/vertx/core/VertxOptionsConverter.java
src/main/generated/io/vertx/core/file/FileSystemOptionsConverter.java
src/main/java/io/vertx/core/VertxOptions.java
src/main/java/io/vertx/core/file/FileSystemOptions.java
src/main/java/io/vertx/core/file/impl/FileResolver.java
src/main/java/io/vertx/core/impl/VertxImpl.java
src/test/java/io/vertx/test/core/FileSystemOptionsTest.java
src/test/java/io/vertx/test/core/VertxOptionsTest.java

Addresses: #2550 
Signed-off-by: Mark Arbogast <mark.t.arbogast@gmail.com>

Add FileSystemOptions and use in FileResolver

---

src/main/java/io/vertx/core/dns/DnsException.java

With this PR I wanted to provide fix for https://github.com/eclipse/vert.x/issues/2493

DnsException improvements #2493

---

src/test/java/io/vertx/test/core/instrumentation/MetricsTest.java
src/test/java/io/vertx/test/core/instrumentation/tracer/Scope.java
src/test/java/io/vertx/test/core/instrumentation/tracer/Span.java
src/test/java/io/vertx/test/core/instrumentation/tracer/Tracer.java

Use simple tracer implementation in instrumentation tests.
Signed-off-by: Pavol Loffay <ploffay@redhat.com>

Use simple tracer in continuation POC

---

src/test/java/io/vertx/core/eventbus/FaultToleranceTest.java

Move FaultToleranceTest to eventbus package

---

src/main/asciidoc/dataobjects.adoc
src/main/asciidoc/filesystem.adoc
src/main/generated/io/vertx/core/file/FileSystemOptionsConverter.java
src/main/java/io/vertx/core/VertxOptions.java
src/main/java/io/vertx/core/file/FileSystemOptions.java
src/main/java/io/vertx/core/file/impl/FileResolver.java
src/test/java/io/vertx/core/VertxOptionsTest.java
src/test/java/io/vertx/core/file/FileSystemOptionsTest.java

Signed-off-by: Julien Viet <julien@julienviet.com>

Rework FileSystemOptions data object

---

src/test/java/io/vertx/core/dns/DNSTest.java

Signed-off-by: Ruslan Sennov <ruslan.sennov@gmail.com>

minor: call super.tearDown() in DNSTest

---

src/main/java/io/vertx/core/json/Json.java
src/test/java/io/vertx/core/json/JsonArrayTest.java
src/test/java/io/vertx/core/json/JsonMapperTest.java
src/test/java/io/vertx/core/json/JsonObjectTest.java
src/test/java/io/vertx/core/json/JsonPOJOMapperTest.java

JsonObject cannot map to class with Instant or byte array field

---

src/main/java/io/vertx/core/http/impl/ConnectionManager.java
src/main/java/io/vertx/core/http/impl/Http1xClientConnection.java
src/main/java/io/vertx/core/http/impl/Http2ClientConnection.java
src/main/java/io/vertx/core/http/impl/Http2ConnectionBase.java
src/main/java/io/vertx/core/http/impl/HttpChannelConnector.java
src/main/java/io/vertx/core/http/impl/VertxHttp2ConnectionHandler.java
src/main/java/io/vertx/core/http/impl/pool/ConnectResult.java
src/main/java/io/vertx/core/http/impl/pool/ConnectionListener.java
src/main/java/io/vertx/core/http/impl/pool/ConnectionProvider.java
src/main/java/io/vertx/core/http/impl/pool/Pool.java
src/main/java/io/vertx/core/http/impl/pool/Waiter.java
src/main/java/io/vertx/core/net/impl/ConnectionBase.java
src/main/java/io/vertx/core/net/impl/VertxHandler.java
src/test/java/io/vertx/core/http/Http1xTest.java
src/test/java/io/vertx/core/net/ConnectionPoolTest.java

Http client pool improvements

---

src/main/java/io/vertx/core/buffer/Buffer.java
src/main/java/io/vertx/core/json/Json.java
src/test/java/io/vertx/core/json/JsonMapperTest.java

JSON decoding without knowledge of the content

---

src/main/java/io/vertx/core/http/impl/HttpServerImpl.java
src/test/java/io/vertx/core/http/HttpServerCloseHookTest.java

HttpServer close handler not invoked if actual server is null

---

src/main/asciidoc/override/configuring-eventbus.adoc
src/main/java/io/vertx/core/Starter.java
src/main/java/io/vertx/core/VertxOptions.java
src/main/java/io/vertx/core/eventbus/EventBusOptions.java
src/main/java/io/vertx/core/impl/VertxFactoryImpl.java
src/main/java/io/vertx/core/impl/VertxImpl.java
src/main/java/io/vertx/core/impl/launcher/commands/BareCommand.java
src/main/java/io/vertx/core/impl/launcher/commands/RunCommand.java
src/test/java/io/vertx/core/CreateVertxTest.java
src/test/java/io/vertx/core/HATest.java
src/test/java/io/vertx/core/LauncherTest.java
src/test/java/io/vertx/core/VertxOptionsTest.java
src/test/java/io/vertx/core/eventbus/ClusteredEventBusStartFailureTest.java
src/test/java/io/vertx/core/eventbus/ClusteredEventBusTest.java
src/test/java/io/vertx/core/impl/launcher/LauncherExtensibilityTest.java
src/test/java/io/vertx/core/spi/metrics/MetricsContextTest.java
src/test/java/io/vertx/test/core/VertxTestBase.java

Deprecate EventBusOptions delegates in VertxOptions

---

src/main/asciidoc/dataobjects.adoc
src/main/generated/io/vertx/core/file/FileSystemOptionsConverter.java
src/main/java/io/vertx/core/file/FileSystemOptions.java
src/main/java/io/vertx/core/file/impl/FileResolver.java
src/test/java/io/vertx/core/file/FileResolverTestBase.java

Set the cachedir to /tmp

---

src/main/java/io/vertx/core/eventbus/impl/EventBusImpl.java
src/main/java/io/vertx/core/eventbus/impl/HandlerHolder.java
src/main/java/io/vertx/core/eventbus/impl/HandlerRegistration.java
src/test/java/io/vertx/core/eventbus/ClusteredEventBusTest.java
src/test/java/io/vertx/core/eventbus/LocalEventBusTest.java
src/test/java/io/vertx/core/spi/metrics/MetricsTest.java
src/test/java/io/vertx/test/fakemetrics/FakeEventBusMetrics.java

Also fixes https://github.com/eclipse-vertx/vert.x/issues/2892

Fix racy event bus cluster registration

---

src/main/java/io/vertx/core/http/impl/HttpChannelConnector.java
src/main/java/io/vertx/core/http/impl/HttpServerImpl.java
src/test/java/io/vertx/core/http/HttpCompressionTest.java

#2920 HttpContentDecompressor Compression level becomes more lenient fashion

---

src/main/asciidoc/dataobjects.adoc
src/main/generated/io/vertx/core/eventbus/EventBusOptionsConverter.java
src/main/generated/io/vertx/core/net/TCPSSLOptionsConverter.java
src/main/java/io/vertx/core/eventbus/EventBusOptions.java
src/main/java/io/vertx/core/http/HttpClientOptions.java
src/main/java/io/vertx/core/http/HttpServerOptions.java
src/main/java/io/vertx/core/net/NetClientOptions.java
src/main/java/io/vertx/core/net/NetServerOptions.java
src/main/java/io/vertx/core/net/TCPSSLOptions.java
src/main/java/io/vertx/core/net/impl/ChannelProvider.java
src/main/java/io/vertx/core/net/impl/NetServerImpl.java
src/main/java/io/vertx/core/net/impl/NetSocketImpl.java
src/main/java/io/vertx/core/net/impl/SSLHelper.java
src/test/java/io/vertx/core/net/NetTest.java

Expose netty's SSL Handshake Timeout

---

src/main/asciidoc/index.adoc
src/main/asciidoc/json-pointers.adoc
src/main/asciidoc/override/json.adoc
src/main/java/docoverride/json/Examples.java
src/main/java/examples/JsonPointerExamples.java
src/main/java/io/vertx/core/json/pointer/JsonPointer.java
src/main/java/io/vertx/core/json/pointer/JsonPointerIterator.java
src/main/java/io/vertx/core/json/pointer/impl/JsonPointerImpl.java
src/main/java/io/vertx/core/json/pointer/impl/JsonPointerIteratorImpl.java
src/test/java/io/vertx/core/json/pointer/impl/JsonPointerTest.java

Implementation of RFC6901 - Json Pointer
Revisited #2330 
Signed-off-by: slinkydeveloper <francescoguard@gmail.com>

Json Pointer implementation

---

src/main/asciidoc/index.adoc
src/main/asciidoc/json-pointers.adoc
src/main/java/docoverride/json/Examples.java
src/main/java/examples/JsonPointerExamples.java
src/main/java/io/vertx/core/json/pointer/JsonPointer.java
src/main/java/io/vertx/core/json/pointer/JsonPointerIterator.java
src/main/java/io/vertx/core/json/pointer/impl/JsonPointerImpl.java
src/main/java/io/vertx/core/json/pointer/impl/JsonPointerIteratorImpl.java
src/test/java/io/vertx/core/json/pointer/impl/JsonPointerTest.java

Json Pointer implementation (#2898)

---

src/main/asciidoc/http.adoc
src/main/java/io/vertx/core/http/impl/HttpClientImpl.java
src/test/java/io/vertx/core/http/HttpTest.java

Support http status code 308 redirection

---

src/main/java/io/vertx/core/net/impl/NetServerImpl.java

Fixes #2922
When a connection is established, a Vert.x handler is created and added to the channel pipeline.
The internal NetSocketImpl object is created only when the handler added event is fired, but it might not always happen immediately.

Race condition in NetServer connection management

---

src/main/java/io/vertx/core/parsetools/impl/RecordParserImpl.java
src/test/java/io/vertx/core/parsetools/RecordParserTest.java

RecordParser delimited parsing does not read the last file line

---

src/main/java/io/vertx/core/json/JsonArray.java
src/test/java/io/vertx/core/json/JsonArrayTest.java

Fixes https://github.com/vert-x3/issues/issues/488

JsonArray methods for insertion of data at given position

---

src/main/java/io/vertx/core/http/impl/HttpServerImpl.java
src/main/java/io/vertx/core/net/impl/NetServerImpl.java

Synchronize access to shared http server map

---

src/main/asciidoc/cli.adoc
src/main/java/io/vertx/core/cli/impl/DefaultCLI.java
src/main/java/io/vertx/core/cli/impl/DefaultParser.java
src/test/java/io/vertx/core/cli/impl/DefaultCLITest.java
src/test/java/io/vertx/core/cli/impl/DefaultParserTest.java

Finally got around to addressing #2844.  Let me know if there's any formatting issues or anything like that - first time contributing in this code base.

Make CLI options case sensitive for short names (#2844).

---

src/main/java/io/vertx/core/http/impl/Http1xUpgradeToH2CHandler.java
src/main/java/io/vertx/core/http/impl/HttpServerChannelInitializer.java
src/test/java/io/vertx/core/http/Http2CompressionTest.java

Signed-off-by: Kowalczyk <bkowalczyyk@gmail.com>

2934 make compressed http2 request possible

---

src/main/java/io/vertx/core/impl/AbstractContext.java
src/main/java/io/vertx/core/impl/ContextInternal.java
src/main/java/io/vertx/core/impl/VertxImpl.java
src/main/java/io/vertx/core/impl/VertxInternal.java
src/test/java/io/vertx/core/TimerTest.java

This can simplify code when a component is bound to a context and we have to schedule async tasks

Expose setTimer and setPeriodic on ContextInternal

---

src/main/asciidoc/index.adoc
src/main/java/examples/CompletionStageInteropExamples.java
src/main/java/io/vertx/core/Future.java
src/main/java/io/vertx/core/impl/ContextImpl.java
src/test/java/io/vertx/core/FutureTest.java

This is a proposal for a `Future` and `CompletionStage` interoperability.

CompletionStage interoperability

---

src/main/asciidoc/enums.adoc
src/main/asciidoc/http.adoc
src/main/java/io/vertx/core/http/HttpClientRequest.java
src/main/java/io/vertx/core/http/HttpMethod.java
src/main/java/io/vertx/core/http/HttpServerRequest.java
src/main/java/io/vertx/core/http/impl/Http1xClientConnection.java
src/main/java/io/vertx/core/http/impl/Http1xServerRequest.java
src/main/java/io/vertx/core/http/impl/Http2ClientConnection.java
src/main/java/io/vertx/core/http/impl/Http2ServerConnection.java
src/main/java/io/vertx/core/http/impl/Http2ServerRequestImpl.java
src/main/java/io/vertx/core/http/impl/Http2ServerStream.java
src/main/java/io/vertx/core/http/impl/Http2UpgradedClientConnection.java
src/main/java/io/vertx/core/http/impl/HttpClientRequestImpl.java
src/main/java/io/vertx/core/http/impl/HttpClientRequestPushPromise.java
src/main/java/io/vertx/core/http/impl/HttpClientStream.java
src/main/java/io/vertx/core/http/impl/HttpMethodImpl.java
src/main/java/io/vertx/core/http/impl/HttpUtils.java
src/test/java/io/vertx/core/http/Http1xTest.java
src/test/java/io/vertx/core/http/HttpMethodTest.java
src/test/java/io/vertx/core/http/HttpTest.java
src/test/java/io/vertx/core/json/JsonCodecTest.java

HttpMethod is an interface

---

src/test/java/io/vertx/core/shareddata/AsynchronousLockTest.java

Added test for worker starvation when lock concurrency is greater than worker pool size

---

src/main/asciidoc/index.adoc

Removed multithreaded worker verticles from the doc

---

src/main/java/io/vertx/core/http/ServerWebSocket.java
src/main/java/io/vertx/core/http/impl/ServerWebSocketImpl.java
src/test/java/io/vertx/core/http/WebSocketTest.java

Signed-off-by: Dimitris Zenios <dimitris.zenios@gmail.com>

Fixes #3368 ServerWebSocket does not expose host() and scheme()

---

src/main/java/io/vertx/core/http/impl/HttpServerWorker.java
src/test/java/io/vertx/core/http/Http2Test.java

Signed-off-by: Dimitris Zenios <dimitris.zenios@gmail.com>

Fixes #3362 SslHandskaheTImeout is not applied on HttpServer

---

src/main/java/io/vertx/core/impl/launcher/commands/StopCommand.java

wmic deprecated in win10, replace with powershell command

---

src/main/java/io/vertx/core/file/impl/AsyncFileImpl.java
src/test/java/io/vertx/core/file/FileSystemTest.java

Cannot close file if one of the write operations fails

---

src/main/java/io/vertx/core/eventbus/impl/EventBusImpl.java
src/main/java/io/vertx/core/eventbus/impl/HandlerRegistration.java
src/test/java/io/vertx/core/eventbus/EventBusRegistrationRaceTest.java
src/test/java/io/vertx/core/spi/metrics/MetricsContextTest.java

Implementation of a fix for #3427 and proper testing. Testing for metrics race has also been added.

Issue 3427

---

src/main/java/io/vertx/core/Vertx.java
src/main/java/io/vertx/core/eventbus/impl/EventBusImpl.java
src/main/java/io/vertx/core/impl/AbstractContext.java
src/main/java/io/vertx/core/impl/ContextImpl.java
src/main/java/io/vertx/core/impl/ContextInternal.java
src/main/java/io/vertx/core/impl/EventLoopContext.java
src/main/java/io/vertx/core/impl/VertxImpl.java
src/main/java/io/vertx/core/impl/VertxInternal.java
src/main/java/io/vertx/core/impl/WorkerContext.java
src/test/java/io/vertx/core/ContextTaskTest.java
src/test/java/io/vertx/core/ContextTest.java
src/test/java/io/vertx/core/TimerTest.java
src/test/java/io/vertx/core/VertxTest.java
src/test/java/io/vertx/core/http/Http1xTest.java
src/test/java/io/vertx/core/http/HttpTest.java
src/test/java/io/vertx/core/net/NetTest.java
src/test/java/io/vertx/core/spi/metrics/MetricsTest.java

Implementation of https://github.com/eclipse-vertx/vert.x/issues/3430

Event loop affinity

---

src/main/java/io/vertx/core/parsetools/impl/RecordParserImpl.java

Signed-off-by: Thomas Cataldo <thomas.cataldo@blue-mind.net>
Same one as the PR merged on master.

Prevent extra buffer copies when parsing did not extract anything

---

src/test/java/io/vertx/core/http/HttpTest.java

Signed-off-by: Gordon Hutchison <Gordon.Hutchison@gmail.com>
This is a backport of #3443 to the 3.9 branch.
See #3443 for documentation.

Backport 3443 to 3.9 - reuse an assigned port in testListenInvalidPort

---

src/main/asciidoc/dataobjects.adoc
src/main/java/io/vertx/core/net/JksOptions.java
src/main/java/io/vertx/core/net/PemKeyCertOptions.java
src/main/java/io/vertx/core/net/PemTrustOptions.java
src/main/java/io/vertx/core/net/PfxOptions.java

backporting #3429 = commit 92179f610af5bba72735c573c5c45acec665553e

Replace readFileSync by readFileBlocking in javadoc

---

src/main/java/io/vertx/core/http/Cookie.java
src/main/java/io/vertx/core/http/impl/CookieImpl.java
src/test/java/io/vertx/core/http/HttpTest.java

Follow up from: https://github.com/eclipse-vertx/vert.x/pull/3484

#3482 Add getSameSite, isHttpOnly and isSecure to Cookie interface

---

src/main/java/io/vertx/core/http/impl/headers/HeadersMultiMap.java
src/test/java/io/vertx/core/http/headers/VertxHttpHeadersTest.java

Signed-off-by: Adam Dickmeiss <adam@indexdata.dk>

Fix Null pointer exception in MultiMap.set #3487

---

.editorconfig
src/main/java/io/vertx/core/json/JsonArray.java
src/main/java/io/vertx/core/json/JsonObject.java
src/main/java/io/vertx/core/json/impl/JsonUtil.java
src/test/java/io/vertx/core/json/JsonArrayTest.java
src/test/java/io/vertx/core/json/JsonObjectTest.java

Add getNumber() to JSON types

---

src/main/java/io/vertx/core/http/impl/HttpServerImpl.java
src/test/java/io/vertx/core/http/Http1xTest.java

Current if a wildcard port is select each IO thread will
bind to its own port. This changes things so that all IO 
threads bind to a single port when deployed from the
same verticle. 
This means that wildcard binding outside a verticle will
work the way they currently do, however if a wildcard binding
is done from a verticle with numInstance >1 then all the
instances will share the wildcard port.
Fixes #3493
Signed-off-by: Stuart Douglas <sdouglas@redhat.com>

If port 0 is selected only select a single port

---

src/main/java/io/vertx/core/eventbus/Message.java
src/test/java/io/vertx/core/spi/metrics/MetricsTest.java

Deprecate Message replyAddress method

---

src/main/asciidoc/http.adoc
src/main/java/examples/HTTPExamples.java
src/main/java/io/vertx/core/http/HttpServerResponse.java
src/test/java/io/vertx/core/http/HttpTest.java

HttpServerResponse send method

---

src/main/java/io/vertx/core/shareddata/impl/LocalAsyncLocks.java
src/main/java/io/vertx/core/shareddata/impl/LockInternal.java
src/test/java/io/vertx/core/shareddata/AsynchronousLockTest.java

Local lock improvements

---

src/test/java/io/vertx/test/core/AsyncTestBase.java

Motivation:
I'm trying to debug a race condition on sockjs tests, and it would be good to see the cause of ISE

Adding the cause to the ISE

---

src/main/java/io/vertx/core/impl/DeploymentManager.java
src/test/java/io/vertx/core/DeploymentTest.java

Deployment failure was reported on wrong context

---

src/test/java/io/vertx/core/DeploymentTest.java

Parent child deployment: verify context

---

src/main/java/io/vertx/core/impl/VertxImpl.java

Fixes https://github.com/eclipse-vertx/vert.x/issues/3616

Don't disable resource leak detector if set by user

---

src/main/java/io/vertx/core/eventbus/impl/clustered/ClusteredEventBus.java
src/main/java/io/vertx/core/eventbus/impl/clustered/Serializer.java

The three first commits simplify a bit the event-bus serializer implementation.
The fourth commit rewrites the event-bus serializer dequeuing algorithm to use a tail recursion style to avoid stack overflows.

Event bus improvements

---

src/main/java/io/vertx/core/file/impl/FileResolver.java

Allow space in Windows file path.

---

src/main/java/io/vertx/core/file/impl/FileResolver.java

Reverts eclipse-vertx/vert.x#3644

Revert "Allow space in Windows file path."

---

src/main/java/io/vertx/core/eventbus/impl/HandlerRegistration.java
src/test/java/io/vertx/core/eventbus/EventBusInterceptorTest.java

Execute inbound delivery on context

---

src/main/java/io/vertx/core/eventbus/impl/EventBusImpl.java
src/main/java/io/vertx/core/eventbus/impl/clustered/ClusteredEventBus.java
src/test/java/io/vertx/core/eventbus/ClusteredEventBusTestBase.java

Clustered consumer keeps local registration when unregistered

---

src/main/asciidoc/index.adoc
src/main/java/examples/CoreExamples.java

We are missing a couple of key elements such as putting more emphasis on Futures which are one of the important v4 theme.

Doc improvements for v4

---

src/main/java/io/vertx/core/buffer/impl/BufferImpl.java
src/main/java/io/vertx/core/cli/UsageMessageFormatter.java
src/main/java/io/vertx/core/eventbus/impl/HandlerHolder.java
src/main/java/io/vertx/core/http/impl/FrameType.java
src/main/java/io/vertx/core/http/impl/Http1xClientConnection.java
src/main/java/io/vertx/core/http/impl/Http1xUpgradeToH2CHandler.java
src/main/java/io/vertx/core/http/impl/headers/HeadersMultiMap.java
src/main/java/io/vertx/core/impl/AbstractContext.java
src/main/java/io/vertx/core/impl/CloseHooks.java
src/main/java/io/vertx/core/net/impl/ServerID.java
src/main/java/io/vertx/core/net/impl/SocketAddressImpl.java
src/main/java/io/vertx/core/net/impl/VertxEventLoopGroup.java

- using JDK methods when possible (Arrays.fill, Math.max, Objects.equal)
- diamond operator
- dandling javadoc

minor cleanups

---

src/main/java/io/vertx/core/impl/launcher/commands/RunCommand.java
src/test/java/io/vertx/core/impl/launcher/commands/OptionsRecordingLauncher.java
src/test/java/io/vertx/core/impl/launcher/commands/RedeployTest.java

Redeploy mode ignores --options arg

---

src/test/java/io/vertx/core/eventbus/ClusteredEventBusTest.java

Fixes vert-x3/vertx-zookeeper#111

Fix intermittent failure with ZK cluster manager

---

src/main/java/io/vertx/core/http/impl/Http1xServerRequest.java
src/main/java/io/vertx/core/http/impl/NettyFileUploadDataFactory.java
src/main/java/io/vertx/core/http/impl/VertxHttp2Stream.java
src/test/java/io/vertx/core/http/HttpServerFileUploadTest.java

Add context to file upload handlers

---

src/main/java/io/vertx/core/http/HttpClientOptions.java
src/main/java/io/vertx/core/http/HttpServerOptions.java
src/main/java/io/vertx/core/http/impl/Http1xServerConnection.java
src/main/java/io/vertx/core/http/impl/ServerWebSocketImpl.java
src/main/java/io/vertx/core/http/impl/WebSocketImpl.java
src/main/java/io/vertx/core/http/impl/WebSocketImplBase.java
src/test/java/io/vertx/core/http/WebSocketTest.java

A few improvements related to the WebSocket close handshake and the TCP connection close.

A few WebSocket improvements - close #3716 - close #3715 - close #3714

---

src/main/java/io/vertx/core/http/impl/Http1xServerRequest.java
src/test/java/io/vertx/core/http/HttpServerFileUploadTest.java

Invoke uploadHandler on request context

---

src/main/java/io/vertx/core/http/impl/Http1xServerRequest.java
src/main/java/io/vertx/core/http/impl/Http2ServerRequestImpl.java
src/main/java/io/vertx/core/http/impl/NettyFileUploadDataFactory.java
src/test/java/io/vertx/core/http/Http2ServerTest.java
src/test/java/io/vertx/core/http/HttpServerFileUploadTest.java

Avoid lazy server form upload attribute creation

---

src/main/java/io/vertx/core/eventbus/DeliveryOptions.java
src/main/java/io/vertx/core/eventbus/impl/OutboundDeliveryContext.java
src/test/java/io/vertx/core/eventbus/DeliveryOptionsTest.java
src/test/java/io/vertx/core/spi/tracing/EventBusTracingTestBase.java
src/test/java/io/vertx/test/faketracer/FakeTracer.java

Configurable tracing policy in DeliveryOptions

---

src/main/java/io/vertx/core/eventbus/impl/MessageTagExtractor.java
src/test/java/io/vertx/core/spi/tracing/EventBusTracerTestBase.java

MessageTagExtractor: change message tag name to message_bus.destination

---

pom.xml
src/main/java/io/vertx/core/http/impl/Http1xClientConnection.java
src/main/java/io/vertx/core/http/impl/Http1xServerConnection.java
src/main/java/io/vertx/core/http/impl/Http2ServerRequestImpl.java
src/main/java/io/vertx/core/http/impl/Http2UpgradedClientConnection.java
src/main/java/io/vertx/core/http/impl/HttpServerRequestImpl.java
src/main/java/io/vertx/core/http/impl/WebSocketHandshakeInboundHandler.java
src/main/java/io/vertx/core/impl/VertxImpl.java
src/main/java/io/vertx/core/net/impl/NetSocketImpl.java
src/main/java/io/vertx/core/net/impl/VertxHandler.java
src/test/java/io/vertx/core/EventLoopGroupTest.java
src/test/java/io/vertx/core/eventbus/LocalEventBusTest.java
src/test/java/io/vertx/core/file/FileResolverTestBase.java
src/test/java/io/vertx/core/http/Http1xTest.java
src/test/java/io/vertx/core/http/Http2ClientTest.java
src/test/java/io/vertx/core/http/Http2ServerTest.java
src/test/java/io/vertx/core/http/WebSocketTest.java
src/test/java/io/vertx/core/net/ProxyErrorTest.java
src/test/java/io/vertx/core/shareddata/AsyncMapTest.java
src/test/java/io/vertx/test/proxy/HttpProxy.java

Backport work done in master around ByteBuf leaks.
There are also open file descriptor due not vertx instances not released in the test suite.

Byte buf leak fixes

---

src/main/java/io/vertx/core/impl/launcher/commands/BareCommand.java
src/test/java/io/vertx/core/impl/launcher/LauncherExtensibilityTest.java

Make sure metrics and cluster manager can be customized in Launcher

---

src/main/asciidoc/dataobjects.adoc
src/main/generated/io/vertx/core/http/RequestOptionsConverter.java
src/main/java/io/vertx/core/http/RequestOptions.java
src/test/java/io/vertx/core/http/RequestOptionsTest.java

RequestOptions: improve json conversion

---

src/main/java/io/vertx/core/parsetools/impl/JsonParserImpl.java
src/test/java/io/vertx/core/parsetools/JsonParserTest.java

It must be guarded by a flag to avoid strange failures.
Fixes #3822

JsonParserImpl checkPending method is not reentrant

---

src/main/java/io/vertx/core/spi/cluster/impl/selector/SelectorEntry.java
src/main/java/io/vertx/core/spi/cluster/impl/selector/Selectors.java
src/main/java/io/vertx/core/spi/cluster/impl/selector/Weight.java
src/main/java/io/vertx/core/spi/cluster/impl/selector/WeightedRoundRobinSelector.java
src/test/java/io/vertx/core/spi/cluster/impl/selector/WeightedRoundRobinSelectorTest.java

A couple of improvements found while profiling an application that handles a lot of subscription events.
Each commit message describe the changes.
Related to #3797

Perf improvements in subscrition event handling

---

src/main/java/io/vertx/core/http/impl/Http1xClientConnection.java
src/test/java/io/vertx/core/http/HttpTest.java

See https://github.com/eclipse-vertx/vert.x/issues/3849

HTTP/1.x client auto-read status race fixes

---

src/main/asciidoc/index.adoc

Typo in the text

---

src/main/java/io/vertx/core/http/Cookie.java
src/main/java/io/vertx/core/http/impl/CookieImpl.java
src/test/java/io/vertx/core/http/HttpTest.java

Motivation:
Implement enhancement [Add cookie maxAge getter](https://github.com/eclipse-vertx/vert.x/issues/3906).

Add cookie maxAge getter

---

src/main/java/io/vertx/core/impl/future/FutureImpl.java
src/test/java/io/vertx/core/FutureTest.java

see issue:  about future tryComplete #3923

Fix future tryComplete.

---

src/main/java/io/vertx/core/http/impl/Http1xServerConnection.java
src/main/java/io/vertx/core/http/impl/HttpClientRequestImpl.java
src/main/java/io/vertx/core/http/impl/HttpUtils.java
src/test/java/io/vertx/core/http/HttpTest.java
src/test/java/io/vertx/core/http/WebSocketTest.java

Incorrect sec websocket location for v00

---

src/main/java/io/vertx/core/file/impl/FileResolver.java

Allow jrt protocol

---

src/main/java/io/vertx/core/net/impl/NetSocketInternal.java

Motivation:
Fixing JavaDoc Typo

Fix the JavaDoc  for writeMessage

---

src/main/java/io/vertx/core/impl/WorkerPool.java

This would be very useful to improve integration in Quarkus.
Thanks!

Make methods on io.vertx.core.impl.WorkerPool public

---

src/main/java/io/vertx/core/impl/BlockedThreadChecker.java

Motivation:
Backport of pr #4047

Have BlockedThreadChecker release memory on shutdown

---

src/main/asciidoc/filesystem.adoc

Motivation:
Update manual to match code expectation.

Fix #4168: Update manual to match code expectation

---

src/main/asciidoc/http.adoc
src/main/generated/io/vertx/core/http/HttpClientOptionsConverter.java
src/main/java/examples/HTTPExamples.java
src/main/java/io/vertx/core/Vertx.java
src/main/java/io/vertx/core/http/HttpClientOptions.java
src/main/java/io/vertx/core/http/impl/HttpClientHolder.java
src/main/java/io/vertx/core/http/impl/HttpClientImpl.java
src/main/java/io/vertx/core/http/impl/SharedClientHttpStreamEndpoint.java
src/main/java/io/vertx/core/http/impl/SharedHttpClient.java
src/main/java/io/vertx/core/impl/VertxImpl.java
src/test/java/io/vertx/core/http/Http1xTest.java
src/test/java/io/vertx/core/http/SharedHttpClientTest.java

Tsegismont shared http client

---

src/main/java/io/vertx/core/http/impl/Http2ClientConnection.java
src/main/java/io/vertx/core/http/impl/Http2UpgradedClientConnection.java
src/main/java/io/vertx/core/http/impl/HttpChannelConnector.java
src/main/java/io/vertx/core/http/impl/HttpClientImpl.java
src/main/java/io/vertx/core/net/impl/NetClientImpl.java
src/test/java/io/vertx/core/http/HttpMetricsTestBase.java
src/test/java/io/vertx/core/spi/metrics/MetricsTest.java
src/test/java/io/vertx/test/fakemetrics/EndpointMetric.java
src/test/java/io/vertx/test/fakemetrics/FakeHttpClientMetrics.java
src/test/java/io/vertx/test/fakemetrics/FakeHttpServerMetrics.java
src/test/java/io/vertx/test/fakemetrics/FakeMetricsBase.java
src/test/java/io/vertx/test/fakemetrics/FakeTCPMetrics.java
src/test/java/io/vertx/test/fakemetrics/FakeVertxMetrics.java

Reported initially by https://github.com/vert-x3/vertx-micrometer-metrics/issues/131

HTTP client will not update correctly the underlying TCP client metrics

---

src/main/java/io/vertx/core/http/impl/Http2ServerResponse.java
src/test/java/io/vertx/core/http/HttpTest.java

Signed-off-by: Markus Spika <markus.spika@gmail.com>
Motivation:
https://github.com/eclipse-vertx/vert.x/issues/4233
Conformance:

bugfix: future for empty http 2 response does not complete. fixes #4233

---

src/main/java/io/vertx/core/http/impl/HttpClientRequestImpl.java

The HttpClientRequest implementation will always log an error when the request has already been ended. Instead we only log when the request is not yet ended and an exception handler was not set.

Ended HttpClientRequest error logging

---

src/main/asciidoc/index.adoc

 Fix wrong word quora; it must be quorum

---

src/main/asciidoc/net.adoc

Motivation:
Place correct example under the feature Description
Conformance:

ASCIIDOC Change: Set Correct Example for Feature Description

---

src/main/java/io/vertx/core/net/impl/pool/SimpleConnectionPool.java
src/test/java/io/vertx/core/net/impl/pool/ConnectionPoolTest.java

The pool state machine implementation does not notify the connection slot promise on a connect failure after the pool is closed. It is required to resolve this promise so pool implementation using the state machine can progress.
The ConnectFailed post task has been updated to resolve the promise when the pool has already been closed.
see #4284

Closed pool connect failure should notify the connection slot future

---

src/main/java/io/vertx/core/impl/DeploymentManager.java
src/test/java/io/vertx/core/VerticleFactoryTest.java

Fixes #4278 
When multiple threads try to register or unregister verticle factories concurrently, a `ConcurrentModificationException` or `IllegalArgumentException` can be thrown.
This change consists in updating the `verticleFactories` atomically.

VerticleFactory registration is not thread-safe

---

src/main/java/io/vertx/core/shareddata/AsyncMap.java
src/main/java/io/vertx/core/shareddata/impl/Checker.java
src/test/java/io/vertx/core/shareddata/LocalSharedDataTest.java

Closes #4186, closes #2733
Commits can be reviewed individually

Shared data enhancements

---

src/main/java/io/vertx/core/datagram/impl/DatagramSocketImpl.java
src/main/java/io/vertx/core/http/impl/SharedHttpClient.java
src/main/java/io/vertx/core/impl/CloseFuture.java
src/main/java/io/vertx/core/impl/VertxImpl.java
src/main/java/io/vertx/core/impl/WorkerExecutorImpl.java
src/main/java/io/vertx/core/net/impl/NetClientImpl.java
src/main/java/io/vertx/core/net/impl/TCPServerBase.java
src/test/java/io/vertx/core/VertxTest.java
src/test/java/io/vertx/core/impl/CloseFutureTest.java

Collected shared worker executor does not release resources

---

src/main/java/io/vertx/core/eventbus/impl/EventBusImpl.java
src/main/java/io/vertx/core/eventbus/impl/clustered/ClusteredEventBus.java
src/main/java/io/vertx/core/impl/utils/ConcurrentCyclicSequence.java
src/test/java/io/vertx/core/eventbus/ClusteredEventBusTest.java
src/test/java/io/vertx/core/impl/utils/ConcurrentCyclicSequenceTest.java

Fixes #4116
When a node has a mix of local and clustered consumers registered to a single address, a message sent from a remote node may be delivered to the local consumers, which is unexpected.
This happens because when the node receives the clustered message, it invokes deliverMessageLocally which does not inspect the type of handlers.
So, in case of point to point messaging, we need to iterate over the content of the sequence of handlers until we find one which is either a reply handler or not local only.
For pub/sub, we need to filter out local-only consumers.

Local consumer should never get a message sent or published remotely

---

src/main/java/io/vertx/core/datagram/impl/DatagramSocketImpl.java
src/main/java/io/vertx/core/http/impl/Http2ClientConnection.java
src/main/java/io/vertx/core/http/impl/Http2ServerConnection.java
src/main/java/io/vertx/core/http/impl/Http2UpgradedClientConnection.java
src/main/java/io/vertx/core/http/impl/HttpChannelConnector.java
src/main/java/io/vertx/core/http/impl/SharedHttpClient.java
src/main/java/io/vertx/core/http/impl/VertxHttp2ConnectionHandler.java
src/main/java/io/vertx/core/impl/CloseFuture.java
src/main/java/io/vertx/core/impl/VertxImpl.java
src/main/java/io/vertx/core/impl/WorkerExecutorImpl.java
src/main/java/io/vertx/core/net/impl/NetClientImpl.java
src/main/java/io/vertx/core/net/impl/TCPServerBase.java
src/test/java/io/vertx/core/VertxTest.java
src/test/java/io/vertx/core/http/Http2ClientTest.java
src/test/java/io/vertx/core/impl/CloseFutureTest.java

Direct h2c client should handle invalid servers

---

src/main/asciidoc/index.adoc
src/main/java/examples/CoreExamples.java

Add Documentation Describing The Duality of Future/Promise

---

src/main/generated/io/vertx/core/eventbus/EventBusOptionsConverter.java
src/main/generated/io/vertx/core/net/TCPSSLOptionsConverter.java
src/main/java/io/vertx/core/eventbus/EventBusOptions.java
src/main/java/io/vertx/core/http/HttpClientOptions.java
src/main/java/io/vertx/core/net/ClientOptionsBase.java
src/main/java/io/vertx/core/net/TCPSSLOptions.java
src/main/java/io/vertx/core/net/impl/transport/EpollTransport.java

add TCP_USER_TIMEOUT config to EpollTransport

---

src/main/java/io/vertx/core/impl/AddressResolver.java
src/test/java/io/vertx/core/dns/HostnameResolutionTest.java

This is the result of the following discussion: https://groups.google.com/g/vertx/c/_ZvZRh4uC08/m/S-X-lhY7AAAJ?pli=1

 feat(Address Resolver): expose resolveAll method 

---

src/main/java/io/vertx/core/file/impl/FileResolverImpl.java
src/test/java/io/vertx/core/file/NestedRootJarResolverTest.java

Motivation:
Trying to add the fix to https://github.com/eclipse-vertx/vert.x/issues/1623 back.
Conformance:
This also relates to https://github.com/vert-x3/vertx-web/issues/2183

Support classpath root nested in JAR

---

src/main/java/io/vertx/core/http/impl/Http1xConnectionBase.java

Motivation:
[Netty's issue](https://github.com/netty/netty/issues/12708) has introduced a preference of type check ordering to prevent https://bugs.openjdk.org/browse/JDK-8295496 to happen; that same order should be used on vert-x to prevent metrics enabled applications to cause again a scalability issue

Save HTTP Netty types unlucky type checks (https://github.com/netty/netty/issues/12708)

---

src/main/generated/io/vertx/core/VertxOptionsConverter.java
src/main/java/io/vertx/core/VertxOptions.java
src/main/java/io/vertx/core/impl/VertxImpl.java
src/test/java/io/vertx/core/VertxOptionsTest.java
src/test/java/io/vertx/core/VertxUseDaemonThreadTest.java

Introduce a ThreadOptions for setting daemon, priority and uncaughtExceptionHandler for VertxThread
For #4464

Allow vertx thread to be daemon

---

src/main/java/io/vertx/core/impl/VertxImpl.java
src/test/java/io/vertx/core/impl/VertxFactoryTest.java

The wrapper of the vertx factory that is passed to the SPI relies on the vertx instance and it is not properly constructed when the thread factory SPI uses the wrapper when it is initialized.
The wrapper is now initialized with the resources it needs instead of retrieving them from the vertx instance.

The thread factory SPI should be able to use the thread factory wrapper when it is created

---

src/main/java/io/vertx/core/parsetools/impl/JsonParserImpl.java
src/test/java/io/vertx/core/parsetools/JsonParserTest.java

JsonParser: checkExceptions() before calling endHandler

---

.github/workflows/ci.yml
README.md
pom.xml
src/main/java/io/vertx/core/Vertx.java
src/main/java/io/vertx/core/http/impl/Http1xUpgradeToH2CHandler.java
src/main/java/io/vertx/core/http/impl/HttpServerWorker.java
src/main/java/io/vertx/core/impl/VertxImpl.java
src/main/java/io/vertx/core/net/impl/ConnectionBase.java
src/main/java/io/vertx/core/net/impl/NetClientImpl.java
src/main/java/io/vertx/core/net/impl/NetServerImpl.java
src/main/java/io/vertx/core/net/impl/transport/EpollTransport.java
src/main/java/io/vertx/core/net/impl/transport/IOUringTransport.java
src/main/java/io/vertx/core/net/impl/transport/KQueueTransport.java
src/main/java/io/vertx/core/net/impl/transport/Transport.java
src/test/java/io/vertx/core/datagram/DatagramTest.java
src/test/java/io/vertx/core/http/HttpTest.java
src/test/java/io/vertx/core/net/NetTest.java
src/test/java/io/vertx/it/TransportTest.java

Support IO_URING transport

---

src/main/java/io/vertx/core/http/impl/Http2ServerRequest.java
src/main/java/io/vertx/core/http/impl/HttpClientRequestBase.java
src/main/java/io/vertx/core/http/impl/HttpClientRequestImpl.java
src/main/java/io/vertx/core/http/impl/HttpRequestHead.java
src/main/java/io/vertx/core/http/impl/HttpUtils.java
src/test/java/io/vertx/core/http/HttpTest.java

see https://github.com/eclipse-vertx/vert.x/pull/4627

HTTP client should rewrite the empty path to / for HTTP/2

---

src/main/java/io/vertx/core/http/impl/Http1xClientConnection.java
src/test/java/io/vertx/core/http/HttpTest.java

When a HTTP/1.1 client stream is reset by the API, it might evict the stream from the connection a bit too aggressively leading to a corrupted connection state that will handle message with the corresponding stream to receive it.
The stream should be evicted only when no message has been sent yet (that is, the client acquired a stream but has not yet used and would like to dispose it so the connection can be used for other requests).
Fixes https://github.com/eclipse-vertx/vertx-http-proxy/issues/45

HTTP/1.1 client connection API reset might lead corrupt the connection state

---

src/main/java/io/vertx/core/http/impl/Http1xClientConnection.java
src/main/java/io/vertx/core/http/impl/Http2ClientConnection.java
src/main/java/io/vertx/core/http/impl/Http2UpgradeClientConnection.java
src/main/java/io/vertx/core/http/impl/HttpClientStream.java
src/test/java/io/vertx/core/spi/tracing/Http2TracerTest.java
src/test/java/io/vertx/core/spi/tracing/HttpTracerTestBase.java

Fix https://github.com/eclipse-vertx/vert.x/issues/4630

Propagate trace when upgrading connections

---

src/main/java/io/vertx/core/http/impl/WebSocketImplBase.java
src/test/java/io/vertx/core/http/WebSocketTest.java

Motivation:
back port of #4660

fix #4660: incrementing the fetch for ping/pong

---

src/main/java/io/vertx/core/http/impl/WebSocketImplBase.java
src/test/java/io/vertx/core/http/WebSocketTest.java

Reverts eclipse-vertx/vert.x#4666

Revert "fix #4660: incrementing the fetch for ping/pong"

---

src/test/java/io/vertx/core/http/Http1xTest.java
src/test/java/io/vertx/core/net/NetTest.java

This correct the tests and make sure we have servers shared on the event-loops.

Current shared server tests are not correct since the changes done in Vert.x 4 about non vertx thread event-loop assignment.

---

src/main/java/io/vertx/core/net/KeyStoreOptionsBase.java
src/main/java/io/vertx/core/net/PemKeyCertOptions.java
src/main/java/io/vertx/core/net/PemTrustOptions.java
src/main/java/io/vertx/core/net/SSLOptions.java
src/main/java/io/vertx/core/net/impl/NetClientImpl.java
src/main/java/io/vertx/core/net/impl/SSLHelper.java
src/main/java/io/vertx/core/net/impl/SslContextUpdate.java
src/main/java/io/vertx/core/net/impl/TCPServerBase.java
src/test/java/io/vertx/core/http/HttpTLSTest.java

Fixes https://github.com/eclipse-vertx/vert.x/issues/4696

SSLOptions update improvements

---

src/main/java/io/vertx/core/json/jackson/JsonArrayDeserializer.java
src/main/java/io/vertx/core/json/jackson/JsonObjectDeserializer.java
src/main/java/io/vertx/core/json/jackson/VertxModule.java
src/test/java/io/vertx/core/json/JacksonDatabindTest.java

Motivation:
Add ability to deserialize JsonArrays and JsonObjects natively

Add JsonArrayDeserializer and JsonObjectDeserializer

---

src/main/java/io/vertx/core/file/impl/FileResolverImpl.java
src/test/java/io/vertx/core/file/WarFileResolverTest.java

Supported WAR files in FileResolver

---

src/main/java/io/vertx/core/net/impl/pool/CombinerExecutor.java

This is fixing the comments at https://github.com/eclipse-vertx/vert.x/pull/4754#discussion_r1241097512 by @He-Pin

Makes CombinerExecutor batchy again InProgressTail static

---

src/main/java/io/vertx/core/eventbus/impl/DeliveryContextBase.java
src/test/java/io/vertx/core/eventbus/EventBusInterceptorTest.java

Event bus interceptor delivery should synchronously happen from the interceptor chain

---

src/main/java/io/vertx/core/net/SSLOptions.java

Fix SSLOptions equals method to use sslHandshakeTimeout from argument

---

src/main/java/io/vertx/core/http/impl/WebSocketImplBase.java

The WebSocketBase implementation reuses the frame handler to aggregate binary/text frames, this overrides a frame handler that could be set to handle frames in addition of processing them.
The implementation has been modified so that the frame aggregator for binary/text frames has its own handler, the frame aggregator and the frame handler are both notified with incoming frames.

Decouple the WebSocketBase frame aggregator from the frame handler

---

src/main/java/io/vertx/core/file/impl/FileResolverImpl.java

This is undocumented and was only used in vertx-examples before Vert.x 5

Remove vertx.cwd system property support

---

src/main/java/io/vertx/core/Future.java
src/main/java/io/vertx/core/impl/future/FutureImpl.java
src/test/java/io/vertx/core/FutureTest.java

Motivation:
Add onComplete method to Future class with onSuccess and onFailure mappers
Closes #4829

feat: Add onComplete method with dual handler signature

---

src/main/java/io/vertx/core/eventbus/ReplyException.java

bugfix: https://github.com/eclipse-vertx/vert.x/issues/4840

#4840 bugfix Disable ReplyException stacktrace

---

src/main/generated/io/vertx/core/http/WebSocketClientOptionsConverter.java
src/main/java/io/vertx/core/http/ClientWebSocket.java
src/main/java/io/vertx/core/http/HttpClient.java
src/main/java/io/vertx/core/http/WebSocketClient.java
src/main/java/io/vertx/core/http/WebSocketClientOptions.java
src/main/java/io/vertx/core/http/impl/CleanableHttpClient.java
src/main/java/io/vertx/core/http/impl/HttpClientImpl.java
src/main/java/io/vertx/core/impl/VertxImpl.java

Default host and port were not added to WebSocketClient, they should be added

Add WebSocketClient default host and port

---

src/main/java/io/vertx/core/eventbus/ReplyException.java

Add ctor with cause
https://github.com/eclipse-vertx/vert.x/issues/4861

EventBus swallows original cause and only reports failureCode and message #4861

---

src/main/java/io/vertx/core/impl/DeploymentManager.java
src/test/java/io/vertx/core/NamedWorkerPoolTest.java

The recent changes in worker pool affected worker verticles with a regression: the named verticle worker pool is closed before undeploying the verticle which leads to have the worker verticle undeployment fail when the worker pool is used only by this verticle.
Close the worker pool after the verticle has been deployed instead of before.

Fix worker verticle using a named pool regression

---

src/main/generated/io/vertx/core/http/HttpServerOptionsConverter.java
src/main/java/io/vertx/core/eventbus/impl/EventBusImpl.java
src/main/java/io/vertx/core/eventbus/impl/HandlerRegistration.java
src/main/java/io/vertx/core/eventbus/impl/MessageConsumerImpl.java
src/main/java/io/vertx/core/eventbus/impl/ReplyHandler.java
src/main/java/io/vertx/core/eventbus/impl/clustered/ClusteredEventBus.java

Interesting feedback was made in https://github.com/eclipse-vertx/vert.x/pull/4859/files, since we reworked some internal of the event-bus, this applies the suggested changes https://github.com/eclipse-vertx/vert.x/pull/4859/files

Apply feedback from PR #4859

---

src/main/java/io/vertx/core/impl/TaskQueue.java
src/main/java/io/vertx/core/impl/WorkerExecutor.java
src/test/java/io/vertx/core/TaskQueueTest.java

The protocol of the TaskQueue unschedule method is racy, since sometimes the task resume might happen before the thread is suspended. The protocol should be modified to implement a race free interaction.

Task queue suspension fixes

---

src/main/java/io/vertx/core/net/impl/HostAndPortImpl.java
src/test/java/io/vertx/core/net/impl/HostAndPortTest.java

Reverts eclipse-vertx/vert.x#4948

Revert "HostAndPort fails to parse a nip host"

---

src/main/generated/io/vertx/core/net/ConnectOptionsConverter.java
src/main/java/io/vertx/core/http/RequestOptions.java
src/main/java/io/vertx/core/net/Address.java
src/main/java/io/vertx/core/net/ConnectOptions.java
src/main/java/io/vertx/core/net/HostAndPort.java
src/main/java/io/vertx/core/net/SocketAddress.java
src/test/java/io/vertx/core/net/SocketAddressTest.java
src/test/java/io/vertx/core/net/impl/HostAndPortTest.java

`SocketAddress` and `HostAndPort` are actually data objects and shall rather annotated with `@DataObject` than `@VertxGen`

`SocketAddress` and `HostAndPort` shall be data objects

---

src/main/java/io/vertx/core/http/impl/Http1xClientConnection.java
src/main/java/io/vertx/core/http/impl/VertxHttp2Stream.java
src/test/java/io/vertx/core/http/HttpTest.java

Motivation:
See https://github.com/eclipse-vertx/vert.x/issues/4982

Fix issue #4982 racy http writing when a writing from a non event loop thread concurrently

---

src/main/java/io/vertx/core/http/impl/HttpClientImpl.java
src/test/java/io/vertx/core/http/ResolvingHttpClientTest.java

The HTTP client request path when resolving an address does not apply the default proxy options nor performs proxy filtering.

Apply proxy filtering/defaults after we resolve the address to a socket address before interacting with the HTTP connection manager

---

src/main/java/io/vertx/core/json/jackson/HybridJacksonPool.java
src/main/java/io/vertx/core/json/jackson/JacksonCodec.java
src/test/java/io/vertx/core/json/jackson/HybridJacksonPoolTest.java

Forward port to master branch of this https://github.com/eclipse-vertx/vert.x/pull/4920

Use a virtual threads friendly pool with Jackson

---

src/main/java/io/vertx/core/json/jackson/DatabindCodec.java
src/main/java/io/vertx/core/json/jackson/JacksonCodec.java

Motivation:
This pull request fixes both the remarks made [here](https://github.com/eclipse-vertx/vert.x/commit/dd6a58ee4aaeb88416b33d6fa8807495c4d3db59#r138410827) and [here](https://github.com/eclipse-vertx/vert.x/pull/5084#issuecomment-1932979506).

Improve JsonFactory creation and propagate its usage to DatabindCodec

---

src/main/java/io/vertx/core/http/impl/Http1xServerResponse.java
src/main/java/io/vertx/core/http/impl/Http2ServerResponse.java
src/main/java/io/vertx/core/http/impl/HttpUtils.java
src/test/java/io/vertx/core/http/Http2ServerTest.java
src/test/java/io/vertx/core/http/HttpTest.java

Original PR https://github.com/eclipse-vertx/vert.x/pull/5121

Validate content length early during HttpServerResponse#sendFile

---

src/main/java/io/vertx/core/http/impl/Http1xServerResponse.java
src/main/java/io/vertx/core/http/impl/Http2ServerResponse.java
src/main/java/io/vertx/core/http/impl/HttpUtils.java
src/test/java/io/vertx/core/http/HttpTest.java

Improve HttpServerResponse sendFile implementations that should close the file when an early failure is returned, failures also should all be asynchronous and not synchronous so the error flow will predicably happen in the returned future instead of requiring a check in the returned future and a try/catch block around the sendFile method.

Improve HttpServerResponse sendFile implementations 

---

src/main/java/io/vertx/core/http/impl/HttpUtils.java
src/test/java/io/vertx/core/http/Http1xTest.java

See #5141
An exception was thrown when upgrading manually a Firefox WebSocket using io.vertx.core.http.HttpServerRequest#toNetSocket.
This happened because FF doesn't send a normal 'Connection: Upgrade' header for WebSockets.
Instead, it sends: 'Connection: keep-alive, Upgrade'.

Fix HttpUtils#isConnectOrUpgrade for FF WebSockets

---

pom.xml

Motivation:
upgrade to latest version of brotli4j

brotli4j 1.16.0

---

src/main/java/io/vertx/core/http/impl/Http1xServerConnection.java

The `Http1xServerConnection` synchronize itself to guard the internal state of the request/response in progress.
Such synchronization used to be useful before Vert.x 4 and the clear dispatch between connection/request code. Currently read and writes are confined in the event-loop thread and removing this synchronization has no effect on the read/writes of this state.

Remove un-necessary Http1xServerConnection internal state synchronised access

---

src/main/java/io/vertx/core/dns/impl/DnsAddressResolverProvider.java

`DnsClient` implementation relies on building multiple instances of `DnsNameResolver` which by default instantiate a `FastThreadLocal` query server address stream. As side effect this expand the `FastThreadLocal` entry size which can be considered as a leak.
`DnsNameResolverBuilder` now [accepts a query server address stream](https://github.com/netty/netty/pull/13873) instance to override the default `FastThreadLocal instance`, to avoid this (slow but steady) leak.

Avoid DnsNameResolver FastThreadLocal query server address stream implementation

---

src/test/java/io/vertx/core/http/Http1xTest.java

Use shutdown API to demonstrate server rolling update using it.

Add a test for HTTP server rolling update

---

src/main/asciidoc/streams.adoc
src/main/java/examples/StreamsExamples.java
src/main/java/io/vertx/core/streams/ReadStream.java
src/test/java/io/vertx/core/streams/ReadStreamReduceTest.java

Add a general purpose collecting method to ReadStream to facilitate the reduction of streams. The collecting method is a default method.

Read stream collect

---

src/main/java/io/vertx/core/json/JsonArray.java
src/main/java/io/vertx/core/json/JsonObject.java
src/test/java/io/vertx/core/json/JsonObjectTest.java

The code to compare two numbers in json object/array does not correctly compare BigInteger/BigDecimal values.
Fix this issue and also simplify / refactor this code to be more compact and reused between object/array

Fix json object/array BigInteger/BidDecimal value comparison

---

vertx-core/src/main/java/io/vertx/core/streams/impl/OutboundWriteQueue.java
vertx-core/src/test/java/io/vertx/tests/concurrent/OutboundWriteQueueStressTest.java
vertx-core/src/test/java/io/vertx/tests/concurrent/OutboundWriteQueueTest.java

Fix a bug in the queue as well as a racy test sometimes failing.

Outbound write queue fixes

---

vertx-core/src/main/java/examples/HTTPExamples.java
vertx-core/src/main/java/io/vertx/core/http/impl/HttpClientImpl.java
vertx-core/src/main/java/io/vertx/core/http/impl/StatisticsGatheringHttpClientStream.java
vertx-core/src/main/java/io/vertx/core/impl/HostnameResolver.java
vertx-core/src/main/java/io/vertx/core/net/AddressResolver.java
vertx-core/src/main/java/io/vertx/core/net/endpoint/Endpoint.java
vertx-core/src/main/java/io/vertx/core/net/endpoint/EndpointServer.java
vertx-core/src/main/java/io/vertx/core/net/endpoint/InteractionMetrics.java
vertx-core/src/main/java/io/vertx/core/net/endpoint/LoadBalancer.java
vertx-core/src/main/java/io/vertx/core/net/endpoint/ServerInteraction.java
vertx-core/src/main/java/io/vertx/core/net/endpoint/ServerSelector.java
vertx-core/src/main/java/io/vertx/core/net/endpoint/impl/ConsistentHashingSelector.java
vertx-core/src/main/java/io/vertx/core/net/endpoint/impl/EndpointResolverImpl.java
vertx-core/src/main/java/io/vertx/core/net/impl/MappingLookup.java
vertx-core/src/main/java/io/vertx/core/net/impl/MappingResolver.java
vertx-core/src/main/java/io/vertx/core/spi/endpoint/EndpointBuilder.java
vertx-core/src/main/java/io/vertx/core/spi/endpoint/EndpointResolver.java
vertx-core/src/test/java/io/vertx/test/fakeloadbalancer/FakeLoadBalancer.java
vertx-core/src/test/java/io/vertx/test/fakeresolver/FakeEndpointResolver.java
vertx-core/src/test/java/io/vertx/tests/addressresolver/ResolvingHttpClientTest.java
vertx-core/src/test/java/io/vertx/tests/endpoint/DnsResolverTest.java
vertx-core/src/test/java/io/vertx/tests/endpoint/LoadBalancingCornerCasesTest.java
vertx-core/src/test/java/io/vertx/tests/endpoint/LoadBalancingTest.java
vertx-core/src/test/java/io/vertx/tests/endpoint/MappingResolverTest.java

- rename things in resolver/endpoint/loadbalancing
- add a new synchronous mapping resolver useful for example and testing purposes

Address resolver improvements

---

src/test/java/io/vertx/core/http/Http1xTest.java

that needs to probe the actual time to send a chunked file to pass reliably independantly of the test env.

Improve Http1xTest#testHttpServerWithIdleTimeoutSendChunkedFile

---

vertx-core/src/main/java/io/vertx/core/file/impl/FileResolverImpl.java
vertx-core/src/main/java/io/vertx/core/http/impl/HttpUtils.java
vertx-core/src/main/java/io/vertx/core/impl/verticle/CompilingClassLoader.java
vertx-core/src/main/java/io/vertx/core/impl/verticle/PackageHelper.java
vertx-core/src/main/java/io/vertx/core/internal/net/RFC3986.java
vertx-core/src/test/java/io/vertx/tests/net/UriUtilsTest.java

that gathers the URIDecoder static methods as well as some of HttpUtils URI related methods.

Introduce internal RFC3986 helper class

---

vertx-core/src/main/java/io/vertx/core/eventbus/impl/MessageTagExtractor.java
vertx-core/src/main/java/io/vertx/core/http/impl/HttpUtils.java
vertx-core/src/test/java/io/vertx/tests/tracing/EventBusTracerTestBase.java
vertx-core/src/test/java/io/vertx/tests/tracing/EventBusTracingTestBase.java
vertx-core/src/test/java/io/vertx/tests/tracing/HttpTracingTestBase.java

See https://github.com/eclipse-vertx/vertx-tracing/issues/69

Use names specified by OpenTelemetry for tags

---

src/main/java/io/vertx/core/eventbus/ReplyException.java

Let subclasses of ReplyException capture a Throwable cause

---

pom.xml
src/main/java/io/vertx/core/buffer/impl/VertxByteBufAllocator.java
src/test/java/io/vertx/core/buffer/impl/VertxByteBufAllocatorTest.java
src/test/java/io/vertx/it/ReuseNettyAllocatorsTest.java

Follow up of https://github.com/eclipse-vertx/vert.x/pull/5292/commits

Franz1981 4.x unified allocator

---

vertx-core/src/main/java/io/vertx/core/http/impl/HttpUtils.java
vertx-core/src/main/java/io/vertx/core/internal/net/SslChannelProvider.java
vertx-core/src/main/java/io/vertx/core/internal/net/VertxSniHandler.java
vertx-core/src/main/java/io/vertx/core/net/impl/NetServerImpl.java
vertx-core/src/main/java/io/vertx/core/net/impl/NetSocketImpl.java
vertx-core/src/test/java/io/vertx/tests/net/NetTest.java
vertx-core/src/test/java/io/vertx/tests/tls/HttpTLSTest.java

Fixes #5290 , on master branch.

Add peer host and port info for server SslHandler (master)

---

vertx-core/src/main/asciidoc/http.adoc
vertx-core/src/main/asciidoc/index.adoc
vertx-core/src/main/java/examples/CoreExamples.java

Missing docs

---

vertx-core/src/main/java/io/vertx/core/http/impl/Http1xServerResponse.java
vertx-core/src/main/java/io/vertx/core/http/impl/Http2ServerResponse.java
vertx-core/src/main/java/io/vertx/core/http/impl/HttpClientRequestImpl.java
vertx-core/src/main/java/io/vertx/core/http/impl/HttpUtils.java
vertx-core/src/test/java/io/vertx/benchmarks/ContentLengthToString.java

Small content-length values caching

---

vertx-core/src/main/java/io/vertx/core/internal/concurrent/InboundMessageChannel.java
vertx-core/src/test/java/io/vertx/tests/concurrent/InboundMessageChannelSingleThreadTest.java
vertx-core/src/test/java/io/vertx/tests/concurrent/InboundMessageChannelSpScTest.java
vertx-core/src/test/java/io/vertx/tests/concurrent/InboundMessageChannelTest.java

A few improvements have to be made to `InboundMessageChannel`

Inbound message channel improvements

---

vertx-core/src/test/java/io/vertx/tests/streams/IteratorTest.java

Motivation:
Make test suite happy

IteratorTest#testConcurrentReads is racy due to FakeStream implementation

---

vertx-core/src/main/java/io/vertx/core/http/impl/Http2ServerConnection.java
vertx-core/src/test/java/io/vertx/tests/http/Http2ServerTest.java

Motivation:
The code checking the well formdness of an HTTP/2 request leaves the vertx stream in an incorrect state when the validation fails.
The vertx stream remains reachable from the netty stream as a stream property but the back reference to the netty stream is null.
Subsequent stream events expect it to be fully initialized and fails with NPEs.
Changes:
Only set the vertx stream on the netty stream after it has been initialized, subsequent lookup for the vertx stream will return null instead of an invalid vertx stream.

Fix NPE when handling of HTTP/2 upgrade on server with a malformed host header

---

vertx-core/src/test/java/io/vertx/test/fakecluster/FakeClusterManager.java

- when adding a registration, the function should not modify the existing list because it can be invoked several times if several threads attempt a concurrent modification
- remove not so useful usage of streams

Small improvements to the FakeClusterManager

---

src/main/java/io/vertx/core/http/impl/Http1xServerResponse.java
src/test/java/io/vertx/core/http/WebSocketTest.java

Backported from https://github.com/eclipse-vertx/vert.x/pull/5601
See #5600
When the connection is upgraded manually, it's up to the user to manage the handshake, including extensions.
Motivation:
Explain here the context, and why you're making that change, what is the problem you're trying to solve.
Conformance:

HttpServerRequest#toNetSocket make the server report its WebSocket capabilities

---

src/main/java/io/vertx/core/net/impl/TCPServerBase.java
src/test/java/io/vertx/core/DeploymentTest.java

Fixes #5621
Get rid of the servers set that was introduced in 86ca0cf but became redundant when close implementation was reworked using close futures in #4352

Verticle instance leak when using shared servers

---

src/main/asciidoc/http.adoc
src/main/java/examples/HTTPExamples.java
src/main/java/io/vertx/core/net/ProxyOptions.java
src/main/java/io/vertx/core/net/impl/ChannelProvider.java
src/test/java/io/vertx/core/http/Http1xProxyTest.java
src/test/java/io/vertx/test/proxy/HttpProxy.java
src/test/java/io/vertx/test/proxy/Socks4Proxy.java
src/test/java/io/vertx/test/proxy/SocksProxy.java
src/test/java/io/vertx/test/proxy/TestProxyBase.java

HttpClient: introduce a connection timeout in ProxyOptions

---

src/main/java/io/vertx/core/net/impl/TCPServerBase.java

Motivation:
TCP server traffic shaping update reads the traffic shaping handler to reconfigure it but does it in a racy fashion.
Changes:
Make the server traffic shaping handler volatile.

Updates a TCP server traffic shaping config can observe an incorrect server state.
