eclipse-vertx/vert.x

src/main/java/io/vertx/core/impl/ContextImpl.java
src/test/java/io/vertx/test/core/ExecuteBlockingTest.java

Bug fix : unset the TCCL on wrong thread when executing blocking handler

---

src/main/java/io/vertx/core/http/impl/HttpClientImpl.java
src/test/java/io/vertx/test/core/HttpTest.java

`HttpClientImpl.request()` was losing the query params if passing a string absoluteURI.  
From `URL getFile()` Java Docs:
_Gets the file name of this URL. The returned file portion will be the same as getPath(), plus the concatenation of the value of getQuery(), if any. If there is no query portion, this method and getPath() will return identical results._

HttpClientImpl.requestAbs() losing the query params

---

src/main/java/io/vertx/core/parsetools/RecordParser.java
src/main/java/io/vertx/core/parsetools/impl/RecordParserImpl.java
src/test/java/io/vertx/test/core/RecordParserTest.java

Split the RecordParser into an interface annotated with VertxGen and an implementation class.
No logic changes and the existing unit-test still passes. I have tested with vertx-lang-scala that it can be translated.
Signed-off-by: LarsTimm <larsdtimm@gmail.com>

Reworked RecordParser to be able "codegen"

---

src/main/asciidoc/cheatsheet/VertxOptions.adoc
src/main/java/io/vertx/core/VertxOptions.java
src/main/java/io/vertx/core/impl/BlockedThreadChecker.java
src/main/java/io/vertx/core/impl/VertxImpl.java
src/test/java/io/vertx/test/core/BlockedThreadCheckerTest.java
src/test/java/io/vertx/test/core/VertxOptionsTest.java

https://bugs.eclipse.org/bugs/show_bug.cgi?id=466228
added config value warningExceptionTime to VertxOptions to set the threshold value when a stack trace
is included in the blocking warning. changed the log code to put the stack trace into the log statement
so that it is output by the logger and not to stdout
added a unit test for the BlockChecker class

bz466228:  BlockedThreadChecker doesn't have a config value for the time until a stack trace is written

---

src/main/java/io/vertx/core/http/impl/HttpServerRequestImpl.java
src/test/java/io/vertx/test/core/HttpTest.java

There is an issue with decoding parameters in the request body. There are three tests, two of them ('+' and '%' test) will currently fail.
see https://bugs.eclipse.org/bugs/show_bug.cgi?id=465616
Signed-off-by: sibay <sibay@gmx.de>

added encoding test for form_urlencoded parameters in request body.

---

src/main/java/io/vertx/core/http/HttpServerOptions.java
src/main/java/io/vertx/core/net/JksOptions.java
src/main/java/io/vertx/core/net/PemKeyCertOptions.java
src/main/java/io/vertx/core/net/PfxOptions.java
src/test/java/io/vertx/test/core/HttpTest.java
src/test/java/io/vertx/test/core/KeyStoreTest.java

It's also worth considering using the Lombok project to generate boiler plate code like equals, hashcode and getters (https://projectlombok.org/features). Not sure though, whether it would interfere with the CodeGenProcessor class.
Signed-off-by: Radoslaw Busz <radoslaw.busz@gmail.com>

Bug - using a reference comparing operator for string comparison.

---

pom.xml
src/main/asciidoc/java/index.adoc
src/main/java/io/vertx/core/ServiceHelper.java
src/main/java/io/vertx/core/package-info.java

Make vert.x core a valid OSGi bundle.
* Generate OSGi metadata
* Fix ServiceFactory classloading
* Add documentation
This commit fixes https://bugs.eclipse.org/bugs/show_bug.cgi?id=469363
The resulting jar is still a valid jar.

Add OSGi metadata to the vert.x core jar

---

src/main/asciidoc/java/http.adoc
src/main/java/examples/HTTPExamples.java
src/main/java/io/vertx/core/http/package-info.java

Add the paragraph about server sharing and explain the round robin strategy Vert.x uses.

HTTP Server Sharing Documentation

---

src/main/asciidoc/java/index.adoc
src/main/java/io/vertx/core/package-info.java

The documentation is close to the vert.x 2 documentation. I've added the new options (redeploy, ha, hagroup...)

Add vert.x cli documentation

---

src/main/java/io/vertx/core/json/impl/Json.java

Previous version of Json class allows this instruction to fail during runtime instead of compilation time:
```
TypeA instance = Json.decodeValue(str, TypeB.class)
```
Signed-off-by: Radoslaw Busz <radoslaw.busz@gmail.com>

Improve generic type usage

---

src/main/java/io/vertx/core/eventbus/ReplyException.java

Nice stack trace and error message. Makes it easier to spot the problem.
Example:
io.vertx.core.eventbus.ReplyException: (NO_HANDLERS,100) dang!
Signed-off-by: Jochen Bedersdorfer <beders@yahoo.com>

more informative error message for ReplyException

---

src/main/asciidoc/java/http.adoc
src/main/java/examples/HTTPExamples.java
src/main/java/io/vertx/core/http/package-info.java

Was mostly there already, just add an example to handle non 2XX responses.

Provide the client HTTP Error handling documentation

---

src/main/java/io/vertx/core/Starter.java
src/main/java/io/vertx/core/package-info.java

Fix https://bugs.eclipse.org/bugs/show_bug.cgi?id=469604 by checking whether or not `-ha` is the first parameter. In that case, it creates the vert.x instance without deploying a vertical
Also update the command line documentation

Fix bare instance creation

---

src/main/asciidoc/java/eventbus.adoc
src/main/asciidoc/java/index.adoc
src/main/asciidoc/java/override/eventbus_headers.adoc
src/main/asciidoc/java/override/verticle-configuration.adoc
src/main/asciidoc/java/parsetools.adoc
src/main/java/docoverride/eventbus/Examples.java
src/main/java/docoverride/eventbus/headers/package-info.java
src/main/java/docoverride/verticles/configuration/package-info.java
src/main/java/examples/CoreExamples.java
src/main/java/examples/EventBusExamples.java
src/main/java/examples/RecordParserExamples.java
src/main/java/io/vertx/core/eventbus/package-info.java
src/main/java/io/vertx/core/package-info.java
src/main/java/io/vertx/core/parsetools/package-info.java

Here is the replacement of https://github.com/eclipse/vert.x/pull/1072.
Move the non translatable code and language specific parts in the docoverride so it can be customized per languages.
I've signed off all commits, and add the parse tools documentation. This means that all sections of the core documentation are there.

Documentation override and parsetools

---

src/main/java/io/vertx/core/net/impl/SSLHelper.java

Signed-off-by: Piotr Wielgolaski <pwielgolaski@gmail.com>
Change take into account what protocols are enabled and only enable intersection of JDK and Vert.x protocols.
In this way client can use system properties described here http://www.oracle.com/technetwork/java/javase/documentation/cve-2014-3566-2342133.html
It also address issue https://groups.google.com/forum/#!topic/vertx/Wr10ljAPplo
as JDK8 by default disable SSL2vHello for clients, it can be enabled if needed by system properties.

respect JDK properties to limit SSL protocols

---

src/main/java/io/vertx/core/http/package-info.java
src/main/java/io/vertx/core/package-info.java

* Fix the bad anchor names (see https://github.com/vert-x3/vertx-web-site/issues/71)
* Fix the link to the Service Loader class (need a full url, as only vert.x classes can be correctly linked using `{@link ...}`.

Fix links in the documentation

---

src/main/java/io/vertx/core/Starter.java
src/test/java/io/vertx/test/core/StarterTest.java

This change enables subclasses of io.vertx.core.Starter to implement custom behavior before
and after the vertx instance has been started by overriding these methods:
* beforeStartingVertx(VertxOptions options)
* afterStartingVertx()

Add Vertx Start Hooks Methods in io.vertx.core.Starter

---

src/main/java/io/vertx/core/Starter.java
src/test/java/io/vertx/test/core/StarterTest.java

This change enables subclasses of io.vertx.core.Starter to implement
custom behavior (e.g. attach further configuration on the
DeploymentOptions.config) before the verticle managed by the Starter is
deployed:
* beforeDeployingVerticle(DeploymentOptions options)
Signed-off-by: Andreas Weise <andreas.weise@gmail.com>

Add Verticle Deployment Hook Method in io.vertx.core.Starter

---

pom.xml
src/main/asciidoc/java/index.adoc
src/main/asciidoc/java/override/dependencies.adoc
src/main/java/docoverride/dependencies/package-info.java
src/main/java/io/vertx/core/package-info.java

Add  Maven and Gradle dependency information to the documentation.
This is related to: vert-x3/issues#14
As the set of dependencies depends on the language, the content is extracted to a _docoverride_ document that other languages can extend / replace.
It also updates the parent pom (see vert-x3/issues/issues/17)

Documentation Maven / Gradle dependencies

---

src/main/asciidoc/cheatsheet/HttpClientOptions.adoc
src/main/asciidoc/java/http.adoc
src/main/generated/io/vertx/core/http/HttpClientOptionsConverter.java
src/main/java/io/vertx/core/http/HttpClientOptions.java
src/main/java/io/vertx/core/http/HttpServerResponse.java
src/main/java/io/vertx/core/http/impl/HttpClientRequestImpl.java
src/main/java/io/vertx/core/http/impl/HttpServerResponseImpl.java
src/main/java/io/vertx/core/http/package-info.java
src/test/java/io/vertx/test/core/HttpTest.java

Documentation says:
>Non keep-alive connections will be automatically closed by Vert.x when the response is ended.
This was only true for HTTP 1.0 requests, for non keep-alive / non persistent HTTP 1.1 requests (requests with Header "Connection: close") the connection was not closed.
>When keep alive is enabled. Vert.x will add a Connection: Keep-Alive header to each HTTP request sent.
This header was not set for keep-alive HTTP 1.0 request, neither was the "Connection: close" header set for non keep-alive / non persistent HTTP 1.1 requests.
Things changed:
* HTTP server response
* A Request is considered keep-alive if either HTTP 1.1 and "Connection: close" header is **not** set or HTTP 1.0 and "Connection: keep-alive" header is set. This results in the closing of the undelying …

Some discrepancies in the handling of (non) keep-alive HTTP requests

---

src/main/java/io/vertx/core/http/impl/ConnectionManager.java
src/test/java/io/vertx/test/core/HttpTest.java

1. Fixes bug in pipelining which could result in requests waiting indefinitely in waiters queue
2. Changes behaviour of keep alive so keep alive connections are never automatically closed.

Keepalive pipelining

---

src/main/java/io/vertx/core/http/impl/HttpServerResponseImpl.java
src/test/java/io/vertx/test/core/HttpTest.java

http://www.w3.org/Protocols/rfc2616/rfc2616-sec2.html#sec2.2 clearly states that there is no escape for headers except quoted strings which have a special meaning and expected behavior by clients.
The issue with special chars (\r\n) needs to be adressed at vert.x web where we need to make an assumption that clients will parse unescape the value, however this is not a standard so for example web browsers will not do anything about it. Since it is not a standard it should not be part of core.

Revert #48 because spec clearly states that there is no escape of special chars

---

src/main/java/io/vertx/core/buffer/Buffer.java
src/main/java/io/vertx/core/buffer/impl/BufferImpl.java
src/test/java/io/vertx/test/core/BufferTest.java

Add API to copy a Buffer into a byte array more efficiently without array allocation.
Signed-off-by: Testo Nakada <test1@doramail.com>

Add API to copy a Buffer into a byte array more efficiently

---

src/main/asciidoc/java/index.adoc
src/main/java/io/vertx/core/cli/Argument.java
src/main/java/io/vertx/core/cli/CLI.java
src/main/java/io/vertx/core/cli/CommandLine.java
src/main/java/io/vertx/core/cli/InvalidValueException.java
src/main/java/io/vertx/core/cli/MissingValueException.java
src/main/java/io/vertx/core/cli/Option.java
src/main/java/io/vertx/core/cli/TypedArgument.java
src/main/java/io/vertx/core/impl/launcher/VertxCommandLauncher.java
src/main/java/io/vertx/core/impl/launcher/commands/FileSelector.java
src/main/java/io/vertx/core/impl/launcher/commands/RunCommand.java
src/main/java/io/vertx/core/impl/launcher/commands/StartCommand.java
src/main/java/io/vertx/core/impl/launcher/commands/Watcher.java
src/main/java/io/vertx/core/package-info.java
src/test/java/io/vertx/core/impl/launcher/commands/FileSelectorTest.java
src/test/java/io/vertx/core/impl/launcher/commands/HttpTestVerticle.java
src/test/java/io/vertx/core/impl/launcher/commands/RedeployTest.java
src/test/java/io/vertx/core/impl/launcher/commands/RunCommandTest.java
src/test/java/io/vertx/core/impl/launcher/commands/WatcherTest.java

This PR adds the _redeploy_ feature to the `run` command.
It's a process-based redeploy: the application is started in background and restarted on file change. The set of watched file is configured in the command line (`--redeploy=...`).

Launcher process redeploy

---

src/main/java/io/vertx/core/impl/launcher/VertxCommandLauncher.java
src/main/java/io/vertx/core/impl/launcher/commands/RunCommand.java
src/main/java/io/vertx/core/impl/launcher/commands/Watcher.java
src/test/java/io/vertx/core/cli/impl/CLIConfiguratorTest.java
src/test/java/io/vertx/core/cli/impl/DefaultParserTest.java
src/test/java/io/vertx/core/impl/launcher/commands/RedeployTest.java
src/test/java/io/vertx/core/impl/launcher/commands/RunCommandTest.java
src/test/java/io/vertx/core/impl/launcher/commands/WatcherTest.java

Replace the WatcherService by the scanner used in the previous version of vert.x and avoiding quite some issues on linux (ulimit), and on windows (bad latency).
Also fixed a couple of issues in test to make them work on Windows.

Replace the WatcherService by a home-made FS scanner

---

src/main/java/io/vertx/core/http/HttpClient.java
src/main/java/io/vertx/core/http/impl/HttpClientImpl.java
src/test/java/io/vertx/test/core/WebsocketTest.java

Signed-off-by: Michal Wrobel <michal.wrobel@espeo.pl>

added websocket connection failure handler for HttpClient fluent API

---

pom.xml
src/main/asciidoc/dataobjects.adoc
src/main/asciidoc/java/cli-for-java.adoc
src/main/asciidoc/java/override/dependencies.adoc
src/main/java/docoverride/dependencies/package-info.java
src/main/java/io/vertx/core/cli/annotations/package-info.java
src/test/asciidoc/dataobjects.adoc

It avoids the issue when the asciidoc files are rendered to html in a different project.

Replace asciidoc attributes by docgen variables

---

src/main/java/io/vertx/core/spi/launcher/DefaultCommand.java
src/test/java/io/vertx/core/impl/launcher/DefaultCommandTest.java

System properties should not be removed. Removing them introduce a race condition when the verticles are starting asynchronously (they may have been removed before, or still be there...).

Do not remove system properties during the tearDown

---

src/test/java/io/vertx/core/impl/launcher/VertxCommandLineInterfaceTest.java

arg1 [arg2] may be cut on 2 lines if the surefire jar name (generated at runtime) is too long.

Fix CLI test when the surefire jar name is too long

---

src/main/java/io/vertx/core/eventbus/impl/HandlerRegistration.java
src/test/java/io/vertx/test/core/LocalEventBusTest.java

https://bugs.eclipse.org/bugs/show_bug.cgi?id=480001

BZ480001: HandlerRegistration cancels timerID 0 in doUnregister

---

src/main/java/io/vertx/core/logging/Logger.java

The class name is wrong (I suppose it lasted from v2)

Fixed logging delegate name for Log4j

---

src/main/asciidoc/java/index.adoc
src/main/java/io/vertx/core/impl/FileResolver.java
src/main/java/io/vertx/core/package-info.java

Fix https://github.com/vert-x3/issues/issues/69.
Add support for bundleentry: and  bundleresource: protocols (used by equinox)
Update OSGi documentation (especially how to disable the context finder)

Add support for bundleresource and bundleentry urls in the FileResolver

---

src/main/java/io/vertx/core/http/impl/HttpClientRequestImpl.java
src/main/java/io/vertx/core/http/impl/HttpClientResponseImpl.java
src/test/java/io/vertx/test/core/HttpTest.java

Ensure exceptions from the drainHandler in HttpClientRequestImpl and dataHandler and endHandler in HttpClientResponseImpl bubble up through the exceptionHandler.
Signed-off-by: Dave Sinclair <stampy88@yahoo.com>

Call exceptionHandler when error occurs on dataHandler and endHandler

---

src/main/java/io/vertx/core/impl/FileResolver.java
src/test/java/io/vertx/test/core/FileResolverTestBase.java

For example, a resource we want to find in a Spring Boot fat jar might be here:
app.jar!/lib/dependency.jar!/webroot/hello.html
I modified unpackFromJarURL so that, in the case of a Spring Boot fat jar, it
opens the nested jar using getResourceAsStream.
Since we're not dealing with a File anymore, I switched to using ZipInputStream
instead of ZipFile.
I also spotted what looked like a copy/paste error in FileResolverTestBase:
testRecursivelyUnpack and testRecursivelyUnpack2 were the same.
This fixes [481623](https://bugs.eclipse.org/bugs/show_bug.cgi?id=481623)

Changed FileResolver so it can handle nested fat jars

---

src/main/java/io/vertx/core/impl/launcher/ServiceCommandFactoryLoader.java
src/main/java/io/vertx/core/impl/launcher/VertxCommandLauncher.java
src/test/java/io/vertx/core/impl/launcher/ServiceCommandLoaderTest.java

This allows the launcher to find commands when launched using the maven exec plugin.

Fix default classloader in command lookup

---

src/main/java/io/vertx/core/impl/VertxImpl.java
src/main/java/io/vertx/core/spi/metrics/VertxMetrics.java
src/test/java/io/vertx/test/core/MetricsTest.java
src/test/java/io/vertx/test/fakemetrics/FakeVertxMetrics.java

It avoids NPE in metric providers using the event bus.
They still can't use it in their constructor but are notified when the event bus is initialized.
This commit is related to https://github.com/vert-x3/vertx-hawkular-metrics/issues/4

Add a callback invoked when the event bus is initialized. 

---

src/main/java/io/vertx/core/streams/package-info.java

I mostly fixed an error on what {Read/Write}Stream do, as the documentation currently
has it wrong in a key sentence.
I also did a few edits there and there to improve the text flow.
Signed-off-by: Julien Ponge <julien.ponge@insa-lyon.fr>

Stream documentation updates

---

src/main/asciidoc/java/index.adoc
src/main/java/io/vertx/core/package-info.java

Fix issue reported in https://github.com/vert-x3/vertx-web-site/issues/118 (Typo in the class name to implement to change the logging backend)

Fix typo in documentation about logging backend

---

src/main/java/io/vertx/core/impl/launcher/commands/ListCommand.java
src/test/java/io/vertx/core/impl/launcher/commands/StartStopListCommandsTest.java

It adds the name of the fat jar or the verticle that was deployed:
vertx list
```
Listing vert.x applications...
hello	io.vertx.core.impl.launcher.commands.HttpTestVerticle
bae935ad-3df4-4e7d-bd15-3bd1d29ca1cc	io.vertx.core.impl.launcher.commands.HttpTestVerticle
35f291c6-bae3-4f5b-9df6-aa1c552be4ce	io.vertx.core.impl.launcher.commands.HttpTestVerticle2
```

Add details about the application 

---

src/main/java/io/vertx/core/file/impl/AsyncFileImpl.java

writePos variable was touched outside the synchronization block. This may cause a file corruption if the writes are done from various threads.
Signed-off-by: Testo Nakada <test1@doramail.com>

Fix thread safety issue for writePos variable

---

src/main/java/io/vertx/core/http/HttpServerResponse.java
src/main/java/io/vertx/core/http/impl/HttpServerResponseImpl.java
src/test/java/io/vertx/test/core/HttpTest.java

Currently it is very difficult to write an access log containing the response size for a chunked response. By adding the bytesWritten method to HttpServerResponse it simplifies this tremendously.
Signed-off-by: Dave Sinclair <stampy88@yahoo.com>

Added bytesWritten to HttpServerResponse

---

src/main/java/io/vertx/core/http/impl/ClientConnection.java
src/main/java/io/vertx/core/http/impl/ConnectionManager.java
src/test/java/io/vertx/test/core/HttpTest.java

This PR re-adds handling of the Connection: close and HTTP/1.0 missing Connection: keep-alive from the server, that was originally addressed in 2.1.
At one point in the diff you'll see I collapsed an if check against keepalive and pipelining, since you can't create a request with pipelining enabled  and keepalive disables it felt the check against pipelining was redundant.
I also added support for respecting the request Connection header, at least in the case of HTTP/1.1.  It is possible that the client knows that it won't be reusing the connection and it is 'polite' for it to indicate that to the server rather than have it close the connection on idle timeout.   In the HTTP/1.0 case the HttpClientRequestImpl forces the Connection header when keepalive is enabled so it's not possible to …

Added support for respecting the Connection header in Http client connections.

---

src/main/asciidoc/java/index.adoc
src/main/java/io/vertx/core/impl/launcher/commands/RunCommand.java
src/main/java/io/vertx/core/impl/launcher/commands/Watcher.java
src/main/java/io/vertx/core/package-info.java
src/test/java/io/vertx/core/impl/launcher/commands/RedeployTest.java

* Add termination period to redeploy (mainly for windows 10)
* Rename onRedeploy to on-redeploy (still support the previous option)

CLI redeploy improvements (termination, on-redeploy)

---

src/main/asciidoc/java/http.adoc
src/main/asciidoc/java/index.adoc
src/main/asciidoc/java/net.adoc
src/main/asciidoc/java/override/verticles.adoc
src/main/asciidoc/java/parsetools.adoc
src/main/asciidoc/java/streams.adoc
src/main/java/docoverride/verticles/package-info.java
src/main/java/io/vertx/core/http/package-info.java
src/main/java/io/vertx/core/package-info.java
src/main/java/io/vertx/core/parsetools/package-info.java
src/main/java/io/vertx/core/streams/package-info.java

This commit fixes:
* https://github.com/vert-x3/vert-x3.github.io/pull/3
* https://github.com/vert-x3/vert-x3.github.io/pull/4
* https://github.com/vert-x3/vert-x3.github.io/pull/6
* https://github.com/vert-x3/vert-x3.github.io/pull/7
* https://github.com/vert-x3/vert-x3.github.io/pull/8
* https://github.com/vert-x3/vert-x3.github.io/pull/9
It also regenerated the .adoc with the annotation fix in docgen.

Fix typos in documentation

---

src/main/asciidoc/java/index.adoc
src/main/java/io/vertx/core/package-info.java

I was very weird to noticed in production to have a lot of eventloop threads. I did not noticed that in development because I have less cores. It should be written in documentation to avoid WTF moments :).
Signed-off-by: Guillaume Charhon <guillaume@databerries.com>

Add number of NIO loops created by Vert.x in the documentation.

---

src/main/java/io/vertx/core/buffer/Buffer.java

Add some comment to _buffer(ByteBuf)_ method of **_Buffer_** class because previous comment was confusing.
Signed-off-by: Junbong <koliie9039@gmail.com>

Add some comment to buffer(ByteBuf) method of Buffer class

---

src/main/asciidoc/java/index.adoc
src/main/java/io/vertx/core/package-info.java

I found the spelling mistake of -> off. When looking closer in my IDE I also found some unicode long-hyphens where there should have been double ascii hypens on a command line.

fixing some formatting, spelling and unicode characters

---

src/main/asciidoc/dataobjects.adoc
src/main/asciidoc/java/index.adoc
src/main/java/io/vertx/core/package-info.java
src/test/asciidoc/dataobjects.adoc

Fix issue reported in https://github.com/vert-x3/issues/issues/104
Extend Launcher documentation to indicate that the `CLASSPATH` env var (if set) must contain vert.x core.

Extend Launcher documentation when `CLASSPATH` is set

---

src/main/asciidoc/dataobjects.adoc
src/main/java/io/vertx/core/impl/launcher/VertxCommandLauncher.java
src/test/asciidoc/dataobjects.adoc
src/test/java/io/vertx/test/core/LauncherTest.java
src/test/resources/META-INF/MANIFEST-Launcher-Default-Command.MF
src/test/resources/META-INF/MANIFEST-Launcher-run.MF

Fix #1346
Execute the command specified in the manifest if set and not overridden in the command line.

Support command set in the manifest without main verticle.

---

src/main/java/io/vertx/core/impl/launcher/commands/BareCommand.java
src/test/java/io/vertx/core/impl/launcher/commands/ClasspathHandlerTest.java
src/test/java/io/vertx/test/core/LauncherTest.java
src/test/java/io/vertx/test/core/StarterTest.java

Fix #1389 
Close vert.x instances in the LauncherTest and StarterTest

Fix #1389 - Close vert.x instances

---

src/main/java/io/vertx/core/impl/OrderedExecutorFactory.java

The accessor method is not an issue per-se but it causes the Quasar Java agent in the forthcoming release, when used, to print an harmless but annoying error at vert.x boot:
```
ERROR: Unable to instrument class io/vertx/core/impl/OrderedExecutorFactory$OrderedExecutor co.paralleluniverse.fibers.instrument.UnableToInstrumentException: Unable to instrument io/vertx/core/impl/OrderedExecutorFactory$OrderedExecutor#lambda$new$261()V because of synchronization
```
(See https://github.com/puniverse/quasar/issues/160#issuecomment-205977756 and following for details)
An easy workaround for the user is to run the agent with the `=m` suffix ("allow monitors").

Avoid accessor method for `OrderedExecutorFactory::log`

---

src/test/java/io/vertx/test/core/ClusteredEventBusTest.java

Fix for issue #1406.
Signed-off-by: Andrey Gura <andreyn.gura@gmail.com>

ClusteredEventBusTest.testDefaultCodecReplyExceptionSubclass test is fixed

---

src/main/java/io/vertx/core/impl/VertxImpl.java
src/test/java/io/vertx/test/core/VerticleFactoryTest.java

Fix issue #1383
Check that the completion handler is not null before calling it upon failed verticle deployment.

Fix NPE in deployVerticle

---

src/main/java/io/vertx/core/impl/launcher/commands/Watcher.java
src/test/java/io/vertx/core/impl/launcher/commands/RedeployTest.java
src/test/java/io/vertx/core/impl/launcher/commands/WatcherTest.java

Fix issue #1415, on windows when / is used in Ant patterns (watcher), they are replaced by the system-specific file separator.

On windows - allow / in Watch include patterns

---

src/main/asciidoc/java/index.adoc
src/main/java/io/vertx/core/impl/launcher/commands/ExecUtils.java
src/main/java/io/vertx/core/impl/launcher/commands/RunCommand.java
src/main/java/io/vertx/core/impl/launcher/commands/StartCommand.java
src/main/java/io/vertx/core/impl/launcher/commands/StopCommand.java
src/main/java/io/vertx/core/impl/launcher/commands/Watcher.java
src/main/java/io/vertx/core/package-info.java
src/test/java/io/vertx/core/impl/launcher/commands/StartStopListCommandsTest.java
src/test/java/io/vertx/core/logging/Log4J2LogDelegateTest.java

Fix #1401 - exit the process with a non 0 status code when an error is detected
Fix #1402 - the stop command should propagate the exit code from the stopped process
Notice that this support is not enabled when the redeploy mode is enabled.

add exit codes in the launcher commands

---

src/main/java/io/vertx/core/datagram/impl/DatagramSocketImpl.java
src/main/java/io/vertx/core/http/HttpClientRequest.java
src/main/java/io/vertx/core/http/HttpConnection.java
src/main/java/io/vertx/core/http/HttpServer.java
src/main/java/io/vertx/core/http/HttpServerRequest.java
src/main/java/io/vertx/core/http/impl/ClientConnection.java
src/main/java/io/vertx/core/http/impl/Http1xPool.java
src/main/java/io/vertx/core/http/impl/Http2ConnectionBase.java
src/main/java/io/vertx/core/http/impl/HttpClientConnection.java
src/main/java/io/vertx/core/http/impl/HttpClientRequestImpl.java
src/main/java/io/vertx/core/http/impl/HttpServerImpl.java
src/main/java/io/vertx/core/http/impl/HttpServerRequestImpl.java
src/main/java/io/vertx/core/http/impl/ServerConnection.java
src/main/java/io/vertx/core/net/impl/ConnectionBase.java
src/main/java/io/vertx/core/net/impl/NetSocketImpl.java
src/test/java/io/vertx/test/core/Http1xTest.java
src/test/java/io/vertx/test/core/HttpTest.java

This provides a limited impl of HttpConnection for HTTP/1.1 : close / exceptionHandler and closeHandler . These operations are useful for dealing with the underlying connection, for instance when writing a remote proxy.

Implement HttpConnection for HTTP/1.1 client and server

---

src/main/java/io/vertx/core/json/JsonArray.java
src/test/java/io/vertx/test/core/JsonArrayTest.java
src/test/java/io/vertx/test/core/JsonObjectTest.java

Fix #1286.
This is a **breaking change** - do not integrate before the 3.2.1 release.
Fix the type inconsistency of the JsonArray remove method. When the object is a Map, it returns a JsonObject. When it's a List, it returns a JsonArray.

JsonArray.remove(int pos) should return JsonArray or JsonObject

---

pom.xml

this build fixes a Windows dependency issue
I tracked the ssl issues when running the tests in Windows to a dll dependency issue, which is already fixed in new build of tcnative boringssl

update tcnative-boringssl to Fork17

---

src/main/java/io/vertx/core/Future.java
src/main/java/io/vertx/core/ServiceHelper.java
src/main/java/io/vertx/core/Vertx.java
src/main/java/io/vertx/core/buffer/Buffer.java
src/main/java/io/vertx/core/http/WebSocketFrame.java
src/main/java/io/vertx/core/impl/DeploymentManager.java
src/main/java/io/vertx/core/impl/VertxImpl.java
src/main/java/io/vertx/core/impl/launcher/ServiceCommandFactoryLoader.java
src/main/java/io/vertx/core/impl/launcher/commands/BareCommand.java
src/main/java/io/vertx/core/streams/Pump.java
src/test/externals/META-INF/services/io.vertx.test.spi.SomeFactory
src/test/externals/SomeFactoryImplA.java
src/test/java/io/vertx/core/FakeFactoryImplA.java
src/test/java/io/vertx/core/FakeFactoryImplB.java
src/test/java/io/vertx/core/ServiceHelperTest.java
src/test/java/io/vertx/core/impl/launcher/ServiceCommandLoaderTest.java
src/test/java/io/vertx/test/spi/FakeFactory.java
src/test/java/io/vertx/test/spi/NotImplementedSPI.java
src/test/java/io/vertx/test/spi/SomeFactory.java
src/test/resources/META-INF/services/io.vertx.test.spi.FakeFactory

Fix issue #1438 by generalizing the usage of the `ServiceHelper` class.
Also add tests to check the behavior of the `ServiceHelper` when using different classloaders.

Use Service Helper to avoid classloading issue

---

src/main/asciidoc/dataobjects.adoc
src/main/asciidoc/java/http.adoc
src/main/generated/io/vertx/core/http/HttpClientOptionsConverter.java
src/main/java/examples/HTTP2Examples.java
src/main/java/io/vertx/core/http/HttpClientOptions.java
src/main/java/io/vertx/core/http/impl/ClientConnection.java
src/main/java/io/vertx/core/http/impl/ConnectionManager.java
src/main/java/io/vertx/core/http/impl/Http1xPool.java
src/main/java/io/vertx/core/http/package-info.java
src/test/java/io/vertx/test/core/Http1xTest.java
src/test/java/io/vertx/test/core/Http2ClientTest.java

This feature sets an upper limit for the number of pipe-lined requests for which no response have been received yet on an HTTP/1.1 persistent connection. 
When a client creates a very large number HTTP client requests at the same time, the distribution of the requests on the pool is not fair (i.e a few connections can get more connections than others). This feature limits the number of requests sent on an connection, the other pending requests remain in the endpoint queue.

Pipe lined limit

---

src/main/java/io/vertx/core/impl/launcher/commands/RunCommand.java
src/test/java/io/vertx/core/impl/launcher/commands/RedeployTest.java

The inlined configuration was not quoted correctly when passed to the spawn process, and so could not be interpreted as valid json.
Initial discussion here: https://groups.google.com/d/msgid/vertx/a28558c2-345c-4427-9aab-21853ba0ff43%40googlegroups.com?utm_medium=email&utm_source=footer

Fix how is passed inlined configuration in redeploy mode.

---

pom.xml
src/main/asciidoc/java/cli-for-java.adoc
src/main/asciidoc/java/http.adoc
src/main/asciidoc/java/net.adoc
src/main/java/io/vertx/core/http/package-info.java
src/main/java/io/vertx/core/net/impl/ChannelProvider.java
src/main/java/io/vertx/core/net/impl/ProxyChannelProvider.java
src/main/java/io/vertx/core/net/package-info.java

change netty-handler-proxy to a direct dependency, remove the documentation lines about it being optional
(this replaces PR#1454, which handled the error)

fixes vert-x3/issues#129

---

src/main/asciidoc/java/cli-for-java.adoc
src/main/asciidoc/java/override/dependencies.adoc
src/main/java/io/vertx/core/http/impl/ConnectionManager.java

Make sure we build it once - since #createEndpoint is called in the constructor of the queue

Fixes #1469 HttpClientMetrics#createEndpoint may be called multiple times for the same endpoint

---

src/main/java/io/vertx/core/Launcher.java
src/main/java/io/vertx/core/impl/launcher/VertxLifecycleHooks.java
src/main/java/io/vertx/core/impl/launcher/commands/BareCommand.java
src/main/java/io/vertx/core/impl/launcher/commands/RunCommand.java
src/test/java/io/vertx/core/impl/launcher/LauncherExtensibilityTest.java

Allow custom launcher to:
* set whether or not the vert.x instance is clustered (this was not possible before, clearly a bug)
* improve the afterConfigParsed callback to not call the method with a `null` object

custom launcher - set clustered and avoid NPE on afterConfigParsed

---

src/main/java/io/vertx/core/eventbus/impl/MessageProducerImpl.java
src/test/java/io/vertx/test/core/EventBusFlowControlTest.java

Motivation:
We forget to add credit header in MessageProducer when we set it with deliveryOptions.
As a result the drain handler will never be call.
Modification:
Add credit header when we set delivery options.
Result:
The drain handler will be call in every situation.
Signed-off-by: amannocci <adrien.mannocci@gmail.com>

Fix message producer

---

src/test/java/io/vertx/test/core/ConnectHttpProxy.java
src/test/java/io/vertx/test/core/HttpTLSTest.java
src/test/java/io/vertx/test/core/TestProxyBase.java

test that proxy connect requests have the Host header set to the target host, not the the proxy host
issue was fixed in netty, this is only the unit test for it.
Signed-off-by: alexlehm <alexlehm@gmail.com>

test for #1511 Proxying - Host header not formed properly

---

src/main/java/io/vertx/core/impl/launcher/commands/Watcher.java
src/test/java/io/vertx/core/impl/launcher/commands/CommandTestBase.java
src/test/java/io/vertx/core/impl/launcher/commands/WatcherAbsolutePathTest.java
src/test/java/io/vertx/core/impl/launcher/commands/WatcherTest.java

* change how the watching is made to not watch the full root, but watch individual roots. It avoids issues when watching huge directories
* add performance tests
This PR is related to https://github.com/vert-x3/vertx-examples/issues/150

Improve watcher performances

---

src/main/java/io/vertx/core/http/HttpServerResponse.java

The javadoc for bodyEndHandler makes it sound like the handler is called
before the body is written over the wire.
Fix https://github.com/eclipse/vert.x/issues/1553

Fix javadoc for bodyEndHandler

---

src/main/asciidoc/java/cli-for-java.adoc
src/main/asciidoc/java/http.adoc
src/main/asciidoc/java/net.adoc
src/main/java/io/vertx/core/file/impl/AsyncFileImpl.java
src/main/java/io/vertx/core/file/impl/FileSystemImpl.java

Resolving a file is a blocking operation. When creating path as a field, the value is computed when the anonymous class is created (wrong thread), not when the blocking action is executed.
AsyncFileChannel#close operation is also blocking and must executed on a worker thread.

Fixes #1573 Blocked thread warning when opening or closing an AsyncFile

---

src/main/java/io/vertx/core/impl/HAManager.java

When killing multiple nodes with kill -9, all registered message consumers for the killed nodes aren't removed from the distributes subs map.
Further information is in this issue:
https://github.com/vert-x3/vertx-hazelcast/issues/13
Signed-off-by: pontushellgren <phellgren@gmail.com>

always remove subs when removing node in clusterMap

---

src/main/java/io/vertx/core/net/impl/NetClientImpl.java
src/main/java/io/vertx/core/net/impl/NetSocketImpl.java
src/test/java/io/vertx/test/core/NetTest.java

this is a rather unlikely usecase when connecting with a SOCKS proxy to a service that requires upgradeToSsl
e.g. STARTTLS in SMTP, since the ssl helper is constructed with the target address of the tcp connection, the cert is checked against the proxy address (e.g. localhost) instead of the actual address (e.g. smtp.gmail.com)

fixes #1602: NetClient with SOCKS Proxy checks wrong hostname on upgradeToSsl()

---

src/main/java/io/vertx/core/package-info.java

Fix in `package-info.java` rather than the Asciidoc files.

Documentation fix for bare instances

---

src/main/java/io/vertx/core/impl/launcher/commands/ClasspathHandler.java

When the launcher class is used in a fat jar, the classloader field is null when the Vert.x instance is created. So the main thread context classloader is set to null and this can cause issues with third party code (not checking for tccl nullity)

Ensure TCCL is not null

---

src/main/java/io/vertx/core/logging/Log4j2LogDelegate.java
src/test/java/io/vertx/test/it/Log4J2LogDelegateTest.java
src/test/resources/log4j2-test.properties

pass Logger class name to ExtendedLogger.logIfEnabled to enable logging of the correct methodname / line number in Log4j2

fix#1634: Log4j2 impl does not support logging method name and line number properly 

---

src/main/asciidoc/java/cli-for-java.adoc
src/main/java/io/vertx/core/impl/HAManager.java
src/main/java/io/vertx/core/impl/VertxImpl.java

Actually it does not fail in Infinispan CM only, it fails in Hazelcast CM as well.
The reason is that simulateKill returns just after calling "leave" on the CM. So calling tests assumes rebalance and stuff happened already but actually the information may even have not been handed over to the cluster manager.

Fixes vert-x3/vertx-infinispan#3 InfinispanHATest>HATest.testFailureInFailover fails intermittently

---

src/test/java/io/vertx/test/core/AsyncTestBase.java

Otherwise in the build logs we only see the IllegalStateException without the actual problem

In test code, show throwable caught from non main thread

---

src/main/java/io/vertx/core/impl/HAManager.java
src/test/java/io/vertx/test/core/HATest.java

The calling thread might be interrupted and then the test fails like this:
```
java.lang.IllegalStateException: Assert or failure from non main thread but no await() on main thread
at io.vertx.test.core.AsyncTestBase.afterAsyncTestBase(AsyncTestBase.java:161)
at io.vertx.test.core.AsyncTestBase.tearDown(AsyncTestBase.java:71)
at io.vertx.test.core.VertxTestBase.tearDown(VertxTestBase.java:99)
at io.vertx.test.core.HATest.tearDown(HATest.java:47)
at io.vertx.test.core.AsyncTestBase.after(AsyncTestBase.java:81)
at sun.reflect.GeneratedMethodAccessor167.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod. …
```

When simulating kill, wait for result uninterruptedly

---

src/main/java/io/vertx/core/json/JsonObject.java
src/test/java/io/vertx/test/core/JsonObjectTest.java

JsonObject copy() preserves LinkedHashMap - fixes #1611

---

src/main/java/io/vertx/core/package-info.java

Signed-off-by: Richard Perez <riperez@gmail.com>

Fixed command line parameter name to be "hagroup" instead of "ha-group"

---

src/main/asciidoc/java/cli-for-java.adoc
src/test/java/io/vertx/test/core/HATest.java

Simulate kill should not use ordered executeBlocking otherwise the CM
leave operation may not execute before the minute delay expires.

Fixes vert-x3/vertx-hazelcast#49 io.vertx.test.core.HazelcastHATest.testSimpleFailover

---

src/main/java/io/vertx/core/http/impl/HttpClientRequestBase.java

Give all available information about what was actually trying to be requested
when communicating a timeout.

Improve timeout message

---

src/main/java/io/vertx/core/eventbus/Message.java
src/main/java/io/vertx/core/eventbus/impl/EventBusImpl.java
src/main/java/io/vertx/core/eventbus/impl/MessageImpl.java
src/main/java/io/vertx/core/eventbus/impl/clustered/ClusteredEventBus.java
src/test/java/io/vertx/test/core/ClusteredEventBusTestBase.java
src/test/java/io/vertx/test/core/LocalEventBusTest.java

This allows the TCP EventBus bridge to signal to the client that the
serialized message should be treated as a send or publish.
See https://github.com/vert-x3/vertx-tcp-eventbus-bridge/issues/20 for
more details.
Are there any known implementations of the `Message` interface outside of Vert.x core? If so, this change would break them unless we added a default implementation to the interface. However, a default implementation would likely need to return a constant value (possibly `true`), which may not be desirable.

Expose send() as part of the Message interface

---

src/main/java/io/vertx/core/http/impl/HttpClientImpl.java
src/test/java/io/vertx/test/core/Http2ClientTest.java

Throw a meaningful exception when using HTTP_2 in a WorkerVerticle to properly signal that this is not supported. Currently, a NullPointerException is thrown somewhere in the netty code. Discussed in issue #1699

Meaningful Error for Http2 in a WorkerVerticle

---

src/main/asciidoc/java/cli-for-java.adoc
src/test/java/io/vertx/test/core/AsynchronousLockTest.java

The existing clustered lock tests always involve two different Vert.x instances.
In vert-x3/vertx-hazelcast#41, it has been reported that concurrent requests to a clustered lock on the same instance can lead to deadlocking.
It happens because locks are acquired with ordered execute blocking, the same for releasing.
The fix consists in applying the technique used in jdbc client connections: a dedicated worker executor is created for a lock instance, then the lock is acquired in order, but released freely. Consequently, we never find ourselves in a situation where a lock release task is waiting for a lock acquire task to complete.
Pull requests for the cluster managers are ready and will be pushed soon.

Test locking on same Vert.x instance

---

src/main/java/io/vertx/core/http/HttpClientResponse.java
src/main/java/io/vertx/core/http/impl/HttpClientRequestImpl.java
src/main/java/io/vertx/core/http/impl/HttpClientResponseImpl.java

The method is already there, just not exposed in the interface. I suggest to expose it.

Expose the HttpClientRequest in HttpClientResponse

---

src/main/asciidoc/java/cli-for-java.adoc
src/main/java/io/vertx/core/datagram/impl/DatagramSocketImpl.java
src/main/java/io/vertx/core/http/impl/ClientConnection.java
src/main/java/io/vertx/core/http/impl/Http1xPool.java
src/main/java/io/vertx/core/http/impl/Http2ClientConnection.java
src/main/java/io/vertx/core/http/impl/Http2ConnectionBase.java
src/main/java/io/vertx/core/http/impl/Http2Pool.java
src/main/java/io/vertx/core/http/impl/Http2ServerConnection.java
src/main/java/io/vertx/core/http/impl/HttpServerImpl.java
src/main/java/io/vertx/core/http/impl/ServerConnection.java
src/main/java/io/vertx/core/impl/VertxImpl.java
src/main/java/io/vertx/core/impl/VertxInternal.java
src/main/java/io/vertx/core/metrics/impl/DummyVertxMetrics.java
src/main/java/io/vertx/core/net/impl/ConnectionBase.java
src/main/java/io/vertx/core/net/impl/NetClientImpl.java
src/main/java/io/vertx/core/net/impl/NetServerBase.java
src/main/java/io/vertx/core/net/impl/NetServerImpl.java
src/main/java/io/vertx/core/net/impl/NetSocketImpl.java
src/main/java/io/vertx/core/net/impl/VertxHandler.java
src/main/java/io/vertx/core/net/impl/VertxNetHandler.java
src/main/java/io/vertx/core/spi/metrics/VertxMetrics.java
src/test/java/io/vertx/test/core/MetricsContextTest.java
src/test/java/io/vertx/test/fakemetrics/FakeVertxMetrics.java

Provide the `NetServerBase` that manages the state of a TCP server that is extracted from `NetServerImpl` in order to reuse it in _vertx-mqtt-server_ that will benefit of its feature. The _vertx-mqtt-server_ is based on Netty's MQTT codec.

NetServer rework

---

src/main/java/io/vertx/core/json/JsonObject.java
src/test/java/io/vertx/test/core/JsonObjectTest.java

Implementation of a recursive mergeIn method for JsonObject. The existing mergeIn method keeps its semantic of a flat merge. But the new overloads allow deep merges. e.g.:
```
JsonObject defaultConfig = new JsonObject()
.put("mongo", new JsonObject()
.put("db_name", "mydb")
.put("host", "localhost")
.put("port", 27017));
// configFile: { "mongo": { "host": "prod.mongo.dbhost" } }
JsonObject config = defaultConfig.mergeIn(configFile, true);
// config now contains all defaults and the host that was overriden in the configFile
```

Recursive mergeIn for JsonObject

---

src/main/java/io/vertx/core/eventbus/impl/clustered/ClusteredEventBus.java
src/test/java/io/vertx/test/core/EventBusTestBase.java

The io.vertx.core.spi.cluster.ChoosableIterable contract does not guarantee that
after calling io.vertx.core.spi.cluster.ChoosableIterable.isEmpty,
io.vertx.core.spi.cluster.ChoosableIterable.choose returns a non null entry.
This could happen if a consumer is unregistered on another in the cluster.
Publish shouldn't be affected but I still added a test. In order to reproduce
I had to annotate the test with @Repeat(times=1000)
I can't leave the annotation as this would take much too long with real cluster managers.
The issue could be reproduced with the FakeClusterManager anyway.

Fixes #1765 NullPointer in sendToSubs

---

src/main/asciidoc/java/cli-for-java.adoc
src/main/java/io/vertx/core/eventbus/impl/clustered/ClusteredEventBus.java
src/test/java/io/vertx/test/core/EventBusTestBase.java
src/test/java/io/vertx/test/fakecluster/FakeClusterManager.java

We must make sure messages are sent instantly, whether sent from worker verticle or executeBlocking

Fixes vert-x3/issues#75 Send messages instantly

---

src/main/java/io/vertx/core/Future.java

fixes mapper signature in Future.recover()

---

src/main/java/io/vertx/core/Future.java
src/main/java/io/vertx/core/impl/CompositeFutureImpl.java
src/main/java/io/vertx/core/impl/FutureImpl.java
src/test/java/io/vertx/test/core/FutureTest.java

Motivation:
It is actually possible to turn a `Future<T>` into an `Handler<AsyncResult<T>>` using `Future#completer()` method. This is actually the polyglot method to achieve it as `AsyncResult<T>` might not be mapped correctly sometimes (like in JS or Ruby).
The implementations of `Future` actually implements `Handler<AsyncResult<T>>` and return `this` in the `completer()` method.
When using java-ish languages like Java, Kotlin or Groovy, it should be possible to use directly the represented `Future` type directly as an `Handler<AsyncResult>`.
Resolution:
This patch makes `Future<T>` extend `Handler<AsyncResult<T>>` (in addition of `AsyncResult<T>`) and the `handle(AsyncResult<T>)` is annotated with `@GenIgnore`.

Future<T> extends Handler<AsyncResult<T>> - fixes #1826

---

src/main/asciidoc/dataobjects.adoc
src/main/asciidoc/java/http.adoc
src/main/generated/io/vertx/core/http/HttpClientOptionsConverter.java
src/main/generated/io/vertx/core/http/HttpServerOptionsConverter.java
src/main/java/examples/HTTPExamples.java
src/main/java/io/vertx/core/http/HttpClientOptions.java
src/main/java/io/vertx/core/http/HttpServerOptions.java
src/main/java/io/vertx/core/http/WebSocket.java
src/main/java/io/vertx/core/http/WebSocketBase.java
src/main/java/io/vertx/core/http/impl/ClientConnection.java
src/main/java/io/vertx/core/http/impl/HttpServerImpl.java
src/main/java/io/vertx/core/http/impl/ServerConnection.java
src/main/java/io/vertx/core/http/impl/ServerWebSocketImpl.java
src/main/java/io/vertx/core/http/impl/WebSocketImpl.java
src/main/java/io/vertx/core/http/impl/WebSocketImplBase.java
src/main/java/io/vertx/core/http/package-info.java
src/test/java/io/vertx/test/core/WebsocketTest.java

Following the guidance from my pull request against vertx-web (https://github.com/vert-x3/vertx-web/pull/520), I have created this pull request against vertx-core.
I also filed issue #1807 detailing the desired behavior: vertx-core can break large text messages up into websocket frames when sending, and re-assemble multiple frames into a single frame when receiving.
There are a few open questions:
1. In WebSocketImplBase, I am creating buffers to store the frames as I re-assemble them.  These should probably have a maximum size which is configurable.  I am looking for suggestions about the best way to do that.
2. In WebsocketTest, some of the tests I added fail.  Everything that uses Unicode for the text message fails, and also the protocol version 00 fails with plain ascii.  It would be …

Issue #1807 - Add support for websocket text framing.

---

src/main/java/io/vertx/core/shareddata/impl/LocalMapImpl.java
src/main/java/io/vertx/core/shareddata/impl/SharedDataImpl.java

- Adjust LocalMapImpl ctor and SharedDataImpl.localMaps such that the
key parameter of the latter is a String
- Use [ConcurrentMap#computeIfAbsent](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ConcurrentMap.html#computeIfAbsent-K-java.util.function.Function-) for all getLocalXXX implementations. This avoids
the overhead associated with creating a speculative object for use as an
arg in putIfAbsent, while retaining operation atomicity. This
implementation is also more concise

SharedDataImpl: Use ConcurrentMap#computeIfAbsent to atomically get-or-create objects

---

src/main/java/io/vertx/core/http/impl/ServerWebSocketImpl.java
src/main/java/io/vertx/core/http/impl/WebSocketImpl.java
src/main/java/io/vertx/core/http/impl/WebSocketImplBase.java

Motivation:
generate cleanup in websocket impl hierarchy, a recent PR added support for message aggregation and the introduced code could be factored out as an internal frame handler of the `WebSocketServerBase` in order to increase readability. Lot of duplicated code was found in `WebSocketServerBase` sub-interfaces and could be factored out in the `WebSocketServerBase ` interface as well.
Result:
- message aggregation is now handled in an internal frame handler of `WebSocketServerBase `
- common code has been factored in `WebSocketServerBase ` instead of being duplicated in `WebSocketImpl` and `ServerWebSocketImpl`

Websocket cleanup

---

src/main/java/io/vertx/core/http/impl/WebSocketImplBase.java

A bug in binaryMessageHandler() caused it to overwrite an already existing Frame-Aggregator.

Fixed issue with overriding handlers

---

src/main/java/io/vertx/core/dns/impl/DnsClientImpl.java
src/test/java/io/vertx/test/core/DNSTest.java
src/test/java/io/vertx/test/fakedns/FakeDNSServer.java

fix and unit test for the CNAME resolve issue

fixes #1752: DNSclient.lookup4 does not return the ip address when a CNAME is used

---

src/main/java/io/vertx/core/eventbus/impl/clustered/ClusterNodeInfo.java
src/main/java/io/vertx/core/eventbus/impl/clustered/ClusteredEventBus.java
src/main/java/io/vertx/core/impl/HAManager.java
src/main/java/io/vertx/core/spi/cluster/AsyncMultiMap.java
src/test/java/io/vertx/test/core/FaultToleranceTest.java
src/test/java/io/vertx/test/core/FaultToleranceVerticle.java
src/test/java/io/vertx/test/fakecluster/FakeClusterManager.java

This PR supersedes #1735 
It includes the original commit from @rikardscm as well my updates and a test which cluster manager implementations should run. I've tried it with Hazelcast and Infinispan cluster managers successfully.
Note that with this change, it won't be possible connect older versions to the cluster, because the data format of the the subs multimap is not compatible. As a workaround, one can use the TCP bridge.

Fault tolerance for event bus subscription

---

src/main/java/io/vertx/core/eventbus/impl/clustered/ClusteredEventBus.java
src/test/java/io/vertx/test/core/EventBusTestBase.java

This PR reverts a previous patch consisting in sending on an arbitrary EL context if sending from a worker context.

Fixes #1870 In case of NO_HANDLERS, vertx handler executed in wrong context and thread type

---

src/test/java/io/vertx/test/core/ComplexHATest.java
src/test/java/io/vertx/test/fakecluster/FakeClusterManager.java

- Node added/left methods are expected to be called by a cluster manager thread
- join/leave/nodeAdded/nodeLeft should not happen concurrently
- NodeListener should not be invoked if the CM is no longer active
Also, in ComplexHATest, it's not necessary to use ordering for simulating kill.
Besides as most CM implementations use executeBlocking, they would not be able to process the event until the kill timeout expires.

Fixed issues with the FakeClusterManager

---

src/main/java/io/vertx/core/eventbus/impl/HandlerRegistration.java

This only "warning" is very important message about data being lost. We need to known which endpoint failing to be able to fix backpressure in code .. 
Signed-off-by: jzajic <jan.zajic@corpus.cz>

Log target address when more than maxBufferedMessages buffered in consumer

---

src/main/java/io/vertx/core/impl/WorkerExecutorImpl.java
src/test/java/io/vertx/test/core/NamedWorkerPoolTest.java

Fixes #1887 Shared worker executor serializes taks even if ordered = false
WorkerExecutorImpl.executeBlocking should use the context task queue only when ordered = true

Shared worker executor serializes taks even if ordered = false

---

src/main/java/io/vertx/core/eventbus/impl/HandlerRegistration.java

I fix issue #1802 from @rscorer. Message can't be null at catch as being dereferenced 9 lines earlier.
Signed-off-by: jzajic <jan.zajic@corpus.cz>

FIX #1802 - Better failure logging when handleMessage failes

---

pom.xml

It makes importing the Vert.x project in Eclipse/m2e (and VS Code) work OOTB.
Signed-off-by: Fred Bricon <fbricon@gmail.com>

Move to build-helper-maven-plugin 3.0.0

---

src/main/java/io/vertx/core/eventbus/impl/HandlerRegistration.java

In HandlerRegistration, sendAsyncResultFailure is logged only when timeout != -1, which is only set in createReplyHandlerRegistration (tj handler is reply handler). But it logs only field address, which is mostly useless to log for reply handler. It print us usually something like:
Timed out after waiting  for a reply. address: 82 
So we must put breakpoint here and see what repliedAddress is (it's that more interesting address in that case). 
So please merge this enhancement so repliedAddress is in error message as well.
Signed-off-by: jzajic <jan.zajic@corpus.cz>

Add repliedAddress to failure message in case of reply timeout

---

src/test/java/io/vertx/test/core/NamedWorkerPoolTest.java

```
java.lang.AssertionError: expected:<Thread[vert.x-GSTPGFHKBV-0,5,main]> but was:<Thread[vert.x-GSTPGFHKBV-1,5,main]>
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.failNotEquals(Assert.java:834)
at org.junit.Assert.assertEquals(Assert.java:118)
at org.junit.Assert.assertEquals(Assert.java:144)
at io.vertx.test.core.AsyncTestBase.assertEquals(AsyncTestBase.java:354)
at io.vertx.test.core.NamedWorkerPoolTest.lambda$null$3(NamedWorkerPoolTest.java:90)
```
The `submitted` latch must be updated after all blocking tasks have been submitted, not after the test task has been scheduled for execution on context.

Fixes intermittent failure in io.vertx.test.core.NamedWorkerPoolTest.testOrdered

---

src/test/java/io/vertx/test/core/Http2ClientTest.java

```
java.lang.AssertionError: expected:<0> but was:<1>
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.failNotEquals(Assert.java:834)
at org.junit.Assert.assertEquals(Assert.java:645)
at org.junit.Assert.assertEquals(Assert.java:631)
at io.vertx.test.core.AsyncTestBase.assertEquals(AsyncTestBase.java:235)
at io.vertx.test.core.Http2ClientTest.lambda$test100Continue$170(Http2ClientTest.java:1293)
```
We know the body handler should be called after both the request handler and the continue handler have been called.
But we don't know which one will be called first: in Http2ServerConnection.onHeadersRead, we write continue headers to the response then schedule the request handler execution.

Fixes intermittent failure in io.vertx.test.core.Http2ClientTest.test100Continue

---

src/main/java/io/vertx/core/http/impl/Http2ServerResponseImpl.java
src/test/java/io/vertx/test/core/HttpTest.java

The Http2 putHeader implementation did not replace but instead appended.
This broke for example pac4j authentication with Safari browser when using HTTP2 connections.

Fix Http2ServerResponse.putHeader to match the Http1ServerResponse implementation

---

src/main/asciidoc/dataobjects.adoc
src/main/generated/io/vertx/core/http/HttpClientOptionsConverter.java
src/main/generated/io/vertx/core/http/HttpServerOptionsConverter.java
src/main/java/io/vertx/core/http/HttpClientOptions.java
src/main/java/io/vertx/core/http/HttpServerOptions.java
src/main/java/io/vertx/core/http/impl/ConnectionManager.java
src/main/java/io/vertx/core/http/impl/HttpServerImpl.java
src/test/java/io/vertx/test/core/Http1xTest.java

Motivation:
Under load and with HTTP requests or responses with multiple headers, a
lot of CPU-time can be spent on "AppendableCharSequence.append", which
has to always grow and so has to copy char arrays.
Modifications:
Changed HttpClientOptions and HttpServerOptions to allow the user to
pass an initial buffer size for Netty’s HTTP decoder that fits her
needs when not happy with the default initial buffer size, i.e. 128
bytes. Also, fixed some typos in documentation.
Result:
Initial buffer size for HTTP decoder is customisable.

Customization of Netty "initialBufferSize" #1750

---

src/main/java/io/vertx/core/impl/launcher/commands/RunCommand.java

JSON spec states that JSON is UTF-8 encoded, not platform dependent

---

src/main/java/io/vertx/core/metrics/impl/DummyVertxMetrics.java
src/main/java/io/vertx/core/net/impl/NetClientBase.java
src/main/java/io/vertx/core/net/impl/NetClientImpl.java
src/main/java/io/vertx/core/spi/metrics/VertxMetrics.java
src/test/java/io/vertx/test/core/MetricsContextTest.java
src/test/java/io/vertx/test/fakemetrics/FakeVertxMetrics.java

This shall be used by the upcoming mqtt client to reuse the connection handing provided by Vert.x

Make the logic of NetClientImpl reusable in NetClientBase

---

src/main/asciidoc/java/index.adoc
src/main/java/io/vertx/core/package-info.java

Explicitly mention the --java-opts parameter used to configure the forked process.
This issue is related to #1960 (and hopefully fix it)

Improve the redeploy documentation

---

src/main/asciidoc/java/override/dependencies.adoc
src/main/java/docoverride/dependencies/package-info.java

Hi there:
Currently the dependency part in build.gradle is pretty simple and missing single quotation mark which may cause problems in the build.gradle.
Thus we elaborate this part and make it consistent to the other module gradle dependencies descriptor.
using:
```
dependencies {
compile '${maven.groupId}:${maven.artifactId}:${maven.version}'
}
```
to replace
`compile '${maven.groupId}:${maven.artifactId}:${maven.version}`

Elaborating dependencies in the build.gradle

---

src/main/java/io/vertx/core/json/Json.java
src/test/java/io/vertx/test/core/JsonMapperTest.java

See also #539
Usage:
``` java
Map<String, List<String>> map = Json.decodeValue(str, new TypeReference<Map<String, List<String>>(){});
```
Signed-off-by: Konstantin Gribov grossws@gmail.com

Added Json#decodeValue with generic types support

---

src/main/asciidoc/java/index.adoc
src/main/java/io/vertx/core/logging/Logger.java
src/main/java/io/vertx/core/package-info.java

Updated the docs to indicate that parameterized logging:
* is not portable
* may not be supported (log4j backend throws `UnsupportedOperationException`)

Parameterized logging is not portable and may not be supported

---

src/main/asciidoc/java/http.adoc
src/main/java/io/vertx/core/buffer/impl/BufferImpl.java
src/main/java/io/vertx/core/json/Json.java
src/main/java/io/vertx/core/json/JsonArray.java
src/main/java/io/vertx/core/json/JsonObject.java
src/test/java/io/vertx/test/core/JsonArrayTest.java
src/test/java/io/vertx/test/core/JsonMapperTest.java
src/test/java/io/vertx/test/core/JsonObjectTest.java

Implement a `toBuffer` to all json objects.
This PR extends #1976 and fixes the ip-check that was resolved using the github web interface which does not sign off commits.

Amannocci faster json parsing

---

src/main/java/io/vertx/core/eventbus/SendContext.java
src/main/java/io/vertx/core/eventbus/impl/EventBusImpl.java
src/test/java/io/vertx/test/core/EventBusTestBase.java

Fixes #1905 EventBus interceptor does not get message body when clustered
ClusteredMessage#body returns null for a clustered message not yet sent.
The fix consists in using the codec #transform method in this case

Fixes #1905 EventBus interceptor does not get message body when clustered

---

src/main/java/io/vertx/core/net/PemTrustOptions.java
src/test/java/io/vertx/test/core/KeyStoreTest.java

https://github.com/eclipse/vert.x/issues/2038
Signed-off-by: Andrei Iacob <iacobandrei+sfdc@gmail.com>

Override equals and hashCode in PemTrustOptions

---

src/main/java/io/vertx/core/impl/VertxImpl.java
src/test/java/io/vertx/test/core/ClusteredEventBusStartFailureTest.java

Vertx.clusteredVertx() handler not called if cannot bind to address

---

src/main/java/io/vertx/core/eventbus/impl/codecs/JsonArrayMessageCodec.java
src/main/java/io/vertx/core/eventbus/impl/codecs/JsonObjectMessageCodec.java
src/test/benchmarks/io/vertx/benchmarks/JsonDecodeBenchmark.java
src/test/benchmarks/io/vertx/benchmarks/JsonEncodeBenchmark.java
src/test/resources/large.json
src/test/resources/small.json

Fixes #2079 
With this change, codecs encode to and decode from Buffer directly.
The benchmark results are the following:
```
Benchmark                            Mode  Cnt    Score    Error   Units
JsonDecodeBenchmark.directLarge     thrpt   10   99,408 ±  0,592  ops/ms
JsonDecodeBenchmark.directSmall     thrpt   10  570,768 ±  3,802  ops/ms
JsonDecodeBenchmark.viaStringLarge  thrpt   10   79,384 ±  0,715  ops/ms
JsonDecodeBenchmark.viaStringSmall  thrpt   10  430,398 ± 13,331  ops/ms
JsonEncodeBenchmark.directLarge     thrpt   10  147,995 ±  1,050  ops/ms
JsonEncodeBenchmark.directSmall     thrpt   10  817,803 ±  5,216  ops/ms
JsonEncodeBenchmark.viaStringLarge  thrpt   10  111,845 ±  1,348  ops/ms
JsonEncodeBenchmark.viaStringSmall  thrpt   10  623,426 ±  4,568  ops/ms
```
Benefits …

JSON message codecs creates unnecessary intermediate String

---

src/main/java/io/vertx/core/http/HttpConnection.java
src/main/java/io/vertx/core/http/HttpServerRequest.java
src/main/java/io/vertx/core/http/ServerWebSocket.java
src/main/java/io/vertx/core/http/WebSocketBase.java
src/main/java/io/vertx/core/http/impl/Http2ServerRequestImpl.java
src/main/java/io/vertx/core/http/impl/HttpServerRequestImpl.java
src/main/java/io/vertx/core/http/impl/ServerWebSocketImpl.java
src/main/java/io/vertx/core/http/impl/VertxHttp2NetSocket.java
src/main/java/io/vertx/core/http/impl/WebSocketImplBase.java
src/main/java/io/vertx/core/net/NetSocket.java
src/main/java/io/vertx/core/net/impl/ConnectionBase.java

Java SE 5-8 has deprecated usage of SSLSession#getPeerCertificateChain() as described in here:
https://docs.oracle.com/javase/8/docs/api/javax/net/ssl/SSLSession.html#getPeerCertificateChain--
This PR adds support for SSLSession#getPeerCertificates() which has new accessor peerCertificates() to follow naming convention for peerCertificateChain(). peerCertificateChain() is left there with @deprecated note to transition to peerCertificate().
TLS test cases are adapted to use peerCertificates().

SSLSession accessor support to get access to SSL session information

---

src/main/java/io/vertx/core/buffer/impl/BufferImpl.java
src/main/java/io/vertx/core/shareddata/impl/ClusterSerializable.java

Otherwise cluster managers can't create an instance after deserializing.
Follows up on #2019 and fixes build issues

BufferImpl should have a public noarg constructor to be used in AsyncMap

---

src/main/java/io/vertx/core/impl/ContextImpl.java

The user API for context data is unchanged.
However module implementers will be able to use:
- the ConcurrentMap API
- all sorts of keys
The motivation for this change is fixing vert-x3/vertx-hazelcast#73

Remove some constraints on context data for module implementers

---

src/main/java/io/vertx/core/eventbus/impl/EventBusImpl.java
src/main/java/io/vertx/core/eventbus/impl/HandlerRegistration.java
src/test/java/io/vertx/test/core/LocalEventBusTest.java

motivation: currently the MessageConsumer end handler is called only when consumer is unregistered during an event bus close. When the consumer is explicitly unregistered it is not called. This handler is mainly used by RxJava and Kotlin coroutines and it seems it would be best to call the end handler in all case to give an opportunity to end the treatment. In RxJava it would call the complete handler and in Kotlin it would close the underlying channel (so a for-each iteration on the channel would terminate and execute the code after).
change: call the MessageConsumer end handler when the MessageConsumer is unregistered explictly.

Call the MessageConsumer end handler on explicit unregistration

---

src/main/java/io/vertx/core/impl/launcher/commands/BareCommand.java
src/test/java/io/vertx/test/core/LauncherTest.java
src/test/java/io/vertx/test/core/TestUtils.java

allow overriding cluster host and post in launcher by beforeStartingVertx()

overriding clusterHost and clusterPort on start

---

src/main/java/io/vertx/core/eventbus/impl/clustered/ClusteredEventBus.java
src/main/java/io/vertx/core/parsetools/RecordParser.java
src/main/java/io/vertx/core/parsetools/impl/RecordParserImpl.java
src/test/java/io/vertx/test/core/RecordParserTest.java

The `RecordParser` is an `Handler<Buffer>` and one use case is set it as `Handler<Buffer>` on a `ReadStream<Buffer>`.
This PR allows the `RecordParser` to wrap an existing `ReadStream<Buffer>` and act as a `ReadStream<Buffer>` so it can be used in a pump or as an Rx Observable/Flowable or Kotlin channel and propagate back-pressure to the original stream.

RecordParser implement ReadStream<Buffer> - fixes #1741

---

src/main/java/io/vertx/core/impl/DeploymentManager.java
src/test/java/io/vertx/test/core/DeploymentTest.java

Signed-off-by: Blake <blakehowell2@gmail.com>
Accidentally messed up history a bit so had to modify. Signed ECA and commit this time.

Added run context close hooks when verticle deployment fails.

---

src/main/java/io/vertx/core/impl/launcher/commands/BareCommand.java
src/test/java/io/vertx/test/core/LauncherTest.java
src/test/java/io/vertx/test/core/TestUtils.java

should work on osx as well (by only binding to 127.0.0.1)

allow overriding cluster host and post in launcher by beforeStartingVertx()

---

src/main/java/io/vertx/core/http/HttpServer.java
src/main/java/io/vertx/core/http/impl/HttpHandlers.java
src/main/java/io/vertx/core/http/impl/HttpServerImpl.java
src/main/java/io/vertx/core/net/NetServer.java
src/main/java/io/vertx/core/net/impl/NetServerImpl.java
src/test/benchmarks/io/vertx/benchmarks/HttpServerHandlerBenchmark.java
src/test/java/io/vertx/test/core/HttpConnectionEarlyResetTest.java
src/test/java/io/vertx/test/core/HttpTLSTest.java
src/test/java/io/vertx/test/core/NetTest.java

fixes #2128
motivation: currently the `HttpServer` forwards connection errors to the `HttpConnection` associated with the channel. It happens that the channel can fail before an `HttpConnection` is created, e.g SSL handshake failure. Application can have an interest to handle such failures for auditing purposes. In addition an existing internal handler already exists for testing purposes. The same can be done for `NetServer`.
changes: add an exception handler on `HttpServer` to process channel errors before an `HttpConnection` is created. Make sure also that `HttpConnection` is created after the SSL handshake for HTTP/1 as it was for HTTP/2 due to ALPN (the ALPN negotiation defers the creation of `HtppConnection` after the SSL handshake when the negotiated protocol is determined), which …

Provide an exception handler on HttpServer and NetServer to process uncaught connection errors

---

src/main/java/io/vertx/core/json/JsonObject.java
src/test/java/io/vertx/test/core/JsonObjectTest.java

Merge of `java.util.LinkedHashMap` throws NullPointerException when value is null.
Example to force the error.
```
JsonObject json = new JsonObject();
json.put("key", "value");
JsonObject otherJson = new JsonObject();
otherJson.putNull("key");
json.mergeIn(otherJson, true);
```

Fix NullPointerException in JsonObject.mergeIn

---

src/main/java/io/vertx/core/http/impl/HttpServerResponseImpl.java
src/main/java/io/vertx/core/http/impl/ServerConnection.java
src/main/java/io/vertx/core/net/impl/ConnectionBase.java
src/test/java/io/vertx/test/core/Http1xTest.java

motivation: currently the `ConnectionBase` class does not  serialize the messages written with `writeToChannel` to the underlying channel when a message is written outside of the event loop followed by a message written from the event loop thread. This can cause out of order issues when ordering is assumed by the Vert.x code using `ConnectionBase`, for instance calling `HttpClientRequest#end()` outside of the event loop sends an last `HttpContent` message to the channel then release the connection to the pool (with pipelining), this connection might be provided then to a waiter that uses it and send pipelined messages, e.g an `HttpRequest` message.
changes: change the implementation of `writeToChannel` and write the message to the channel when the current thread is the event loop or there …

Serialize messages sent to the connection in the order of the synchronization monitor

---

src/main/java/io/vertx/core/parsetools/impl/JsonParserImpl.java
src/test/java/io/vertx/test/core/JsonParserTest.java

Fixes #2155
Missing switch branch in buffering mode.
Updated the tests (added floating point value and, while at it, base64/byte array value)

JsonParser fails to handle floating point numbers in buffering mode

---

src/main/java/io/vertx/core/impl/DeploymentManager.java
src/test/java/io/vertx/test/core/DeploymentTest.java

When starting multiple verticles, if more than one fails it results in a duplicate call to the completionHandler. 
The boolean that should prevent duplicate calls is never set to true.
Also, in the catch block, the same check should be made as the same error could occur there.

Fix multiple handler completion on deploy fail

---

src/test/java/io/vertx/test/core/ClusteredEventBusStartFailureTest.java

On some networking configurations the CountDownLatch would expire.
Using an improbable dotted hostname fixes the issue and makes the test pass.

Fix ClusteredEventBusStartFailureTest

---

src/main/java/io/vertx/core/datagram/DatagramSocketOptions.java

More accurate documentation for DatagramSocketOptions.setBroadcast().  Option is used for permissioning for sending datagram packets also, not only receiving.

More accurate documentation for DatagramSocketOptions.setBroadcast()

---

src/main/asciidoc/java/shareddata.adoc
src/main/java/examples/SharedDataExamples.java
src/main/java/io/vertx/core/shareddata/SharedData.java
src/main/java/io/vertx/core/shareddata/impl/LocalAsyncMapImpl.java
src/main/java/io/vertx/core/shareddata/impl/SharedDataImpl.java
src/main/java/io/vertx/core/shareddata/package-info.java
src/test/java/io/vertx/test/core/AsyncMapTest.java
src/test/java/io/vertx/test/core/AsyncMapTestDifferentNodes.java
src/test/java/io/vertx/test/core/ClusteredAsyncMapTest.java
src/test/java/io/vertx/test/core/LocalAsyncMapTest.java
src/test/java/io/vertx/test/fakecluster/FakeClusterManager.java

Fixes #2137 
Users often develop and test verticles in local mode and later deploy them in clustered mode. With shared data APIs this can lead to strange behavior:
- counters and locks can be used in local/clustered
- async map can be used in clustered mode only
We got questions/issues about this quite a few times so here's what I did:
- Added #getAsyncMap; the new one works regardless of the cluster status;
- reworked the Javadoc and the doc
- made sure AsyncMap is tested in both local/clustered mode
- implemented a local AsyncMap wich supports TTL correctly (ie an entry stays in the map even if previous binding had a TTL); the FakeClusterManager reuses this implemation

Local async map

---

src/main/java/io/vertx/core/http/HttpClient.java

See https://github.com/vert-x3/issues/issues/319
Signed-off-by: wu-lee <eclipse.wu-lee@noodlefactory.co.uk>

correct claim io.vertx.core.http.HttpClient#websocketStream to be fluent

---

src/main/java/examples/NetExamples.java
src/main/java/io/vertx/core/http/HttpClientOptions.java
src/main/java/io/vertx/core/http/HttpServerOptions.java
src/main/java/io/vertx/core/net/ClientOptionsBase.java
src/main/java/io/vertx/core/net/NetClientOptions.java
src/main/java/io/vertx/core/net/NetServerOptions.java
src/main/java/io/vertx/core/net/TCPSSLOptions.java
src/main/java/io/vertx/core/net/impl/SSLHelper.java
src/test/java/io/vertx/test/core/HttpTLSTest.java
src/test/java/io/vertx/test/core/NetTest.java
src/test/java/io/vertx/test/core/SSLHelperTest.java

Implementation for https://github.com/eclipse/vert.x/issues/2179:
> Right now, `SSLHelper` is 
> 
> 1. taking the `DEFAULT_ENABLED_PROTOCOLS` as a basis protocol list
> 2. removing those protocols from that protocol list which are not already enabled in the `SSLEngine` by default (effectively leaving only those protocols in place which were enabled in the `SSLEngine` already)
> 3. if the developer added protocols to the `options`, the current protocol list is filtered to only leave those
> 
> This means that there is currently no way to add protocols not already enabled in both `SSLHelper` and `SSLEngine` by default - for my Java 8 setup, that is SSLv3 (disabled by both) and SSLv2Hello (enabled by `SSLHelper`, but disabled by `SSLEngine`).
> 
> As I need SSLv3 and SSLv2Hello support for a …

Harmonizing SSL/TLS protocol options

---

src/main/java/io/vertx/core/net/impl/ConnectionBase.java

This change adds a log message to the log output. Which also results in logging the stack trace of the exception. Otherwise only the exception name will be logged which isn't really helpful as the `ConnectionBase` is already missing some handling of the exception in the first place. Finding the root cause of this exception can be rather hard.
Signed-off-by: Jens Reimann <jreimann@redhat.com>

Properly log the exception, showing the trace

---

src/test/java/io/vertx/test/core/SocksProxy.java

Would like to use this in vertx-eventbus-bridge-clients, but netty seems to convert domain name to IP automatically, so lets support those, too.

Add IPv4 addressType support to SocksProxy test class

---

src/main/java/io/vertx/core/MultiMap.java
src/main/java/io/vertx/core/http/impl/HeadersAdaptor.java
src/main/java/io/vertx/core/http/impl/Http2HeadersAdaptor.java
src/main/java/io/vertx/core/http/impl/headers/VertxHttpHeaders.java
src/test/java/io/vertx/test/core/CaseInsensitiveHeadersTest.java
src/test/java/io/vertx/test/core/HttpTest.java

Fixes #2258
There is no easy way to test that an HTTP header is present and has a given value:
```java
String value = HttpHeaders.WEBSOCKET.toString();
boolean upgrade = headers.getAll(HttpHeaders.UPGRADE).stream()
.anyMatch(val -> val.equalsIgnoreCase(value));
```
Drawbacks:
1. Testing a header value is a common task, especially if you write edge services or API gateways
2. The header value in this example should be tested in a case-insensitive way; so the `HttpHeaders` constant must be first converted to `String` (no `equalsIgnoreCase` on `CharSequence`)
3. A list of all headers needs to be created before testing

Provide user-friendly way to test an HTTP header value

---

src/main/java/io/vertx/core/shareddata/impl/LocalAsyncMapImpl.java
src/test/java/io/vertx/test/core/LocalAsyncMapTest.java

Sometimes, the Vert.x timer was fired but the value still looked valid (because of currentTimeMillis).
After this change, SessionHandlerTestBase#testSessionExpires (vertx-web) no longer fails intermittently.

Use nanoTime for LocalAsyncMap expiration instead of currentTimeMillis

---

src/main/java/io/vertx/core/parsetools/JsonEventType.java

Add the missing `VertxGen` annotation to the enum type.

Add missing VertxGen annotation

---

src/main/java/io/vertx/core/http/HttpServerRequest.java
src/main/java/io/vertx/core/http/impl/Http2ServerRequestImpl.java
src/main/java/io/vertx/core/http/impl/HttpServerRequestImpl.java
src/test/java/io/vertx/test/core/Http1xTest.java
src/test/java/io/vertx/test/core/HttpTest.java

This change is to expose `bytesRead` from `HttpServerRequest` similar to `bytesWritten` for the response.
The use case is the following:
Suppose I have a `loggerHandler` (middleware) where I would like to record the bytes read to a log file.
ex. `router.route().handler(loggerHandler);`
The logger handle wants to record bytesRead (not content length). If it isn't a middleware solution I _could_ wrap my request handler ReadStream with a `CountingReadStream` -- however for a more general middleware solution (see below) when `context.next()` is called, downstream handlers won't be using the wrapped CountingReadStream.
```java
@Override
public void handle(RoutingContext context) {
CountingReadStream<Buffer> rs = new CountingReadStream<>(context.request());
context.addBodyEndHandler(event -> { …
```

HttpServerRequest provides a bytesRead() method

---

src/main/java/io/vertx/core/http/impl/HttpClientImpl.java
src/test/java/io/vertx/test/core/HttpTest.java

Related to https://github.com/vert-x3/vertx-web/issues/908
Note, that `http://127.0.0.1:8080?test=something` is valid URL. Provided PR prefixes URL `path` with '/' in case of empty path, because based on HTTP1 spec https://tools.ietf.org/html/rfc2616#section-5.1.2 it should be so.
Netty implements this behaviour as well: https://github.com/netty/netty/issues/719

HTTP client requests should always prefix request URI with / for absolute queries

---

src/main/java/io/vertx/core/http/impl/ConnectionManager.java

Don't search for timed out keep-alive Connections every Millisecond. This burns CPU.
Just search every 1000ms
Fixes #2406

Fixes #2406

---

src/main/asciidoc/index.adoc
src/main/java/examples/CoreExamples.java
src/main/java/io/vertx/core/http/HttpServer.java
src/main/java/io/vertx/core/http/impl/HttpServerImpl.java
src/test/java/io/vertx/test/core/HttpTest.java

enables DomainSockets support when using native transports (BSD &
Linux).
Signed-off-by: Thomas Cataldo <thomas.cataldo@blue-mind.net>

Add support for listening on a SocketAddress to HttpServer. This

---

src/main/asciidoc/dataobjects.adoc
src/main/java/io/vertx/core/VertxOptions.java
src/main/java/io/vertx/core/file/impl/FileResolver.java
src/main/java/io/vertx/core/file/impl/FileSystemImpl.java
src/main/java/io/vertx/core/impl/VertxImpl.java
src/test/java/io/vertx/test/core/FileResolverTestBase.java

this will require changes in some projects (like vertx-web or vertx-dropwizard-metrics) that will break upon this change.

Decouple the FileResolver from a Vertx instance - fixes #2428

---

src/main/java/io/vertx/core/http/impl/headers/VertxHttpHeaders.java

Refactor to remove duplicate methods and use the optimal implementation that can possibly uses `AsciiString` optimised headers.

Vertx http headers refactor

---

src/main/java/io/vertx/core/http/impl/Http2HeadersAdaptor.java

In netty/netty#7633, a method was added to check if a HTTP/2 header is present and has a given value.
Now that Vert.x core requires Netty 4.1.22, we can use it instead of the slower default implementation.
See also #2258

Use Http2Headers.contains instead of default MultiMap implementation

---

src/main/java/io/vertx/core/eventbus/impl/clustered/ClusteredEventBus.java
src/main/java/io/vertx/core/impl/HAManager.java
src/main/java/io/vertx/core/impl/VertxFactoryImpl.java
src/main/java/io/vertx/core/impl/VertxImpl.java
src/main/java/io/vertx/core/impl/VertxInternal.java

Assigned to you @tsegismont , I believe it will be fine for cluster manager implementations as this does not touch anything specific to them. In particular pay attention to the init sequence:
1. init vertx
2. join cluster manager
3. instantiate the ha manager that needs the cluster manager to be joined
4. start the event bus
5. init the ha manager on event bus start callback so that the cluster manager listener are registered after the event bus is initialized

ClusteredEventBus racy initialization - fixes #2438 - fixes #2439

---

src/test/benchmarks/io/vertx/core/impl/VertxExecutorService.java

The following exception is thrown when benchmarks are run:
```
Caused by: java.lang.IllegalArgumentException: Non-positive period.
at java.base/java.util.Timer.schedule(Timer.java:248)
at io.vertx.core.impl.BlockedThreadChecker.<init>(BlockedThreadChecker.java:37)
at io.vertx.core.impl.VertxExecutorService.<init>(VertxExecutorService.java:24)
```
The reason is that when `TimeUnit`s were added (2f61422f1d664e9c5d7f9778badacac36329005f), the values changed from 10000 milliseconds to 10000 nanoseconds (which are less than 1 ms, thus the exception). This PR changes the intervals back to their original values of 10000 ms.

Fix BlockedThreadChecker intervals for benchmarks

---

src/main/generated/io/vertx/core/eventbus/EventBusOptionsConverter.java
src/main/generated/io/vertx/core/net/TCPSSLOptionsConverter.java
src/main/java/io/vertx/core/http/HttpClientOptions.java
src/main/java/io/vertx/core/http/HttpServerOptions.java
src/main/java/io/vertx/core/http/impl/HttpChannelConnector.java
src/main/java/io/vertx/core/http/impl/HttpServerImpl.java
src/main/java/io/vertx/core/net/ClientOptionsBase.java
src/main/java/io/vertx/core/net/NetClientOptions.java
src/main/java/io/vertx/core/net/NetServerOptions.java
src/main/java/io/vertx/core/net/TCPSSLOptions.java
src/main/java/io/vertx/core/net/impl/NetClientImpl.java
src/main/java/io/vertx/core/net/impl/NetServerImpl.java
src/test/java/io/vertx/test/core/Http1xTest.java
src/test/java/io/vertx/test/core/Http2ServerTest.java
src/test/java/io/vertx/test/core/NetTest.java

Motivation:
Provide fix for issue #2376.
Modification:
Just switch to Netty's IdleStateHandler method that allows to provide custom TimeUnit.

Provide implementation for issue #2376

---

src/main/java/io/vertx/core/eventbus/impl/EventBusImpl.java
src/main/java/io/vertx/core/eventbus/impl/clustered/ClusteredEventBus.java
src/main/java/io/vertx/core/http/impl/WebSocketImplBase.java
src/main/java/io/vertx/core/net/impl/NetSocketImpl.java

Addresses are now like: "__vertx.[net|ws|reply].randomUUID"
Fixes #1240

Add discriminator to internal eventbus addresses

---

src/main/java/io/vertx/core/Context.java
src/main/java/io/vertx/core/Vertx.java
src/main/java/io/vertx/core/WorkerExecutor.java
src/main/java/io/vertx/core/shareddata/AsyncMap.java
src/main/java/io/vertx/core/shareddata/impl/SharedDataImpl.java

Fixes #2434
Improves Vert.x RxJava2 API (returns Maybe instead of Single)
With executeBlocking, the future provided to the blocking handler could be completed with null.
In AsyncMap, there are a few cases (get, remove, replace, putIfAbsent) when the result can be null as well.

Missing @Nullable in AsyncMap, Context, Vertx and WorkerExecutor

---

src/main/asciidoc/dataobjects.adoc
src/main/asciidocs/dataobjects.adoc
src/main/generated/io/vertx/core/http/HttpClientOptionsConverter.java
src/main/generated/io/vertx/core/http/HttpServerOptionsConverter.java
src/main/java/io/vertx/core/http/HttpClientOptions.java
src/main/java/io/vertx/core/http/HttpServerOptions.java
src/main/java/io/vertx/core/http/impl/Http1xClientConnection.java
src/main/java/io/vertx/core/http/impl/Http1xServerHandler.java
src/main/java/io/vertx/core/http/impl/HttpClientImpl.java
src/main/java/io/vertx/core/http/impl/HttpServerImpl.java
src/main/java/io/vertx/core/http/impl/WebSocketImplBase.java
src/test/java/io/vertx/test/core/WebsocketTest.java

Server support is enabled by default (but the client must request it).
Client side must be specifically enabled in options.

Enable websocket compression

---

src/main/java/io/vertx/core/eventbus/DeliveryOptions.java
src/main/java/io/vertx/core/eventbus/impl/clustered/ClusteredEventBus.java
src/test/java/io/vertx/core/eventbus/DeliveryOptionsTest.java
src/test/java/io/vertx/test/core/ClusteredEventBusTest.java

When deploying verticles across the cluster, it can be useful to force delivery to a local consumer.
For example, you might deploy audit verticles on all nodes, with local consumers only.
Forcing local delivery avoids paying the price of a cluster manager lookup.
This fixes #1764

EventBus local only delivery

---

src/main/java/io/vertx/core/http/HttpServerResponse.java

Adds missing fluent annotations to some methods in HttpServerResponse. It seems like without these the methods have `MethodKind.OTHER` when they are processed by vertx-codegen due to the condition [here](https://github.com/vert-x3/vertx-codegen/blob/master/src/main/java/io/vertx/codegen/ClassModel.java#L868).

Add missing @Fluent annotations to HttpServerResponse methods

---

src/main/java/io/vertx/core/eventbus/impl/clustered/ClusteredEventBus.java
src/main/java/io/vertx/core/impl/HAManager.java
src/main/java/io/vertx/core/impl/VertxImpl.java

Fixes #1302
Most often, code in HAManager is invoked from cluster manager threads.
Some parts though need to be called from a worker thread.

Make sure haInfo sync map is not invoked on an event-loop

---

src/main/java/io/vertx/core/file/impl/FileResolver.java

The use of `FileResolver` for a directory without a trailing '`/`' will fail since `unpackFromBundleURL()` does not handle this case correctly.
By trying `ClassLoader.getResource()` on such a resource path with an appended '`/`', it can be determined whether or not the resource is really a directory since a URL will only be returned if the resource exists and is a directory.
Fixes #2548.

Fix FileResolver for OSGi bundle resources

---

src/main/java/io/vertx/core/net/impl/KeyStoreHelper.java
src/test/java/io/vertx/test/core/TestUtils.java

…Support retrieving X509 certificates CN if javax.naming package is unavailable.  Android does not contain this package.
Signed-off-by: Hayden James <hayden.james@gmail.com>

Support retrieving X509 certificates CN since javax.naming package is unavailable in Android

---

src/main/asciidoc/index.adoc
src/main/java/io/vertx/core/impl/launcher/commands/BareCommand.java
src/main/java/io/vertx/core/impl/launcher/commands/RunCommand.java
src/main/java/io/vertx/core/spi/VertxMetricsFactory.java
src/test/java/io/vertx/core/CustomMetricsFactory.java
src/test/java/io/vertx/core/CustomMetricsOptions.java
src/test/java/io/vertx/core/LauncherTest.java
src/test/java/io/vertx/core/NestedMetricsOptions.java

Resolves #1729
This allows a user to configure:
- metrics options
- clustering and event bus options
- any base Vert.x options
It relieves users from implementing their own `Launcher` class, only for overriding `beforeStartingVertx` and manipulating options.

Add new CLI arg to support external JSON VertxOptions

---

src/main/java/io/vertx/core/http/impl/VertxHttp2ConnectionHandler.java
src/main/java/io/vertx/core/http/impl/VertxHttp2NetSocket.java
src/main/java/io/vertx/core/http/impl/VertxHttp2Stream.java
src/main/java/io/vertx/core/net/NetSocket.java
src/main/java/io/vertx/core/net/impl/NetSocketImpl.java
src/test/java/io/vertx/core/http/Http2ClientTest.java
src/test/java/io/vertx/core/http/Http2ServerTest.java
src/test/java/io/vertx/core/net/NetTest.java

Add writeHandler interface to NetSocket for notifications after socket writes are executed.  Since socket writes are asynchronous, this allows notifications for when they actually occur.
Signed-off-by: Hayden James <hayden.james@gmail.com>

Create additional write interface to NetSocket for notifications after socket writes are executed

---

src/main/asciidoc/dataobjects.adoc
src/main/asciidoc/index.adoc
src/main/java/examples/CoreExamples.java
src/main/java/io/vertx/core/DeploymentOptions.java

Applies the doc changes discussed in #2431:
- DeploymentOptions.setMultiThreaded Javadoc
- alternative to MT worker verticles (deploy as many as instances as MT worker pool size)

Documentation improvement for MT worker verticles

---

src/main/java/io/vertx/core/impl/VertxImpl.java
src/main/java/io/vertx/core/spi/metrics/VertxMetrics.java
src/test/java/io/vertx/test/fakemetrics/FakeVertxMetrics.java

Closes #2352
Timer metrics hardly provide any meaningful information.

Remove timer callbacks from the metrics SPI

---

src/main/java/io/vertx/core/parsetools/impl/JsonParserImpl.java
src/test/java/io/vertx/core/parsetools/FakeStream.java
src/test/java/io/vertx/core/parsetools/JsonParserTest.java

Hi, 
that is initial bug-fix for #2790.
I have one problem with test - because of closing file is asynchronous I had to handle exception in Vert.x exception handler 
```java
vertx.exceptionHandler(exception -> fail());
```
and also schedule completion to allow vert.x first catch exception and fail test.
```java
vertx.setTimer(10, val -> complete());
```
do you maybe have other idea how to test that case with file-closed case (my seems really ... bad)  ?

provide fix and test for #2790

---

src/main/java/io/vertx/core/Starter.java
src/main/java/io/vertx/core/dns/impl/decoder/RecordDecoder.java
src/main/java/io/vertx/core/http/impl/Http2UpgradedClientConnection.java
src/main/java/io/vertx/core/impl/launcher/commands/BareCommand.java
src/main/java/io/vertx/core/impl/launcher/commands/RunCommand.java
src/main/java/io/vertx/core/impl/launcher/commands/VertxIsolatedDeployer.java
src/main/java/io/vertx/core/net/impl/ConnectionBase.java

there were several places where e.printStackTrace() was used, which messed up the logging for docker containers (e.g. if you change the logging pattern with the used logging framework)

fix logging to system out and err

---

src/main/asciidoc/index.adoc

I fixed a copy paste error in the native transport documentation. `epoll` is only available on Linux and on BSD it should be `kqueue`.
```
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':compileKotlin'.
> Could not resolve all files for configuration ':compileClasspath'.
> Could not find netty-transport-native-epoll-osx-x86_64.jar (io.netty:netty-transport-native-epoll:4.1.15.Final).
Searched in the following locations:
https://repo.maven.apache.org/maven2/io/netty/netty-transport-native-epoll/4.1.15.Final/netty-transport-native-epoll-4.1.15.Final-osx-x86_64.jar
BUILD FAILED in 1s
1 actionable task: 1 executed
```
```
Download https://repo.maven.apache.org/maven2/io/netty/netty-transport-native-kqueue/4.1.15.Final/netty-transport-native-kqueue-4.1.15 …
```

Fix native BSD transport dependency

---

src/main/java/io/vertx/core/impl/DeploymentManager.java
src/test/java/io/vertx/core/impl/DeploymentManagerTest.java
src/test/resources/cpExtraction/exploded/META-INF/MANIFEST.MF

The current implementation of isolation groups [1] requires the
instantiation of a new IsolatingClassLoader, which contains all JARs
from the class path of the SystemClassLoader. Before Java 9, this was
solved by casting the SystemClassLoader to an URLClassLoader to extract
JARs on the class path of the SystemClassLoader.
Due to the fact, that the SystemClassLoader is not longer an
URLClassLoader in Java 9, this approach will not longer work.
This patch implements a way to extract the class path of the
SystemClassLoader which does not require the SystemClassLoader to be an
instance of URLClassLoader.
WARNING: This approach will not work for modules, which were introduces
in Java 9, because modules are living in the "runtime image" [2]. Due to
this, it is not possible to pass the module …

Enable isolation groups for Java 9+

---

src/main/java/io/vertx/core/impl/ContextImpl.java
src/test/java/io/vertx/core/ContextTest.java

Failures not reported when executeBlocking is invoked without a result handler

---

src/main/java/io/vertx/core/AbstractVerticle.java
src/test/java/io/vertx/core/ContextTest.java
src/test/java/io/vertx/core/DeploymentTest.java
src/test/java/io/vertx/core/NamedWorkerPoolTest.java
src/test/java/io/vertx/core/eventbus/ClusteredEventBusTestBase.java
src/test/java/io/vertx/core/http/HttpServerCloseHookTest.java
src/test/java/io/vertx/core/net/NetTest.java
src/test/java/io/vertx/core/spi/metrics/MetricsTest.java
src/test/java/io/vertx/test/verticles/SimpleServer.java
src/test/java/io/vertx/test/verticles/sourceverticle/SourceVerticle.java

I found this while playing with 4.0.0-milestone and my IDE completed with a wrong name.

Rename startFuture parameters to startPromise

---

src/main/java/io/vertx/core/Future.java
src/test/java/io/vertx/core/FutureTest.java

I means Future can auto fail when handler which is passed to `Future.future` throws an Exception.
This is my first PR. 
See also: #3056 
Thank you.

Future will fail when the handler which is passed to `Future.future` throws an Exception.

---

src/test/java/io/vertx/core/eventbus/ClusteredEventBusTest.java
src/test/java/io/vertx/core/eventbus/WriteHandlerLookupFailureTest.java

It shouldn't be part of the clustered event bus test suite.

Move WriteHandlerLookupFailureTest to its own class

---

src/main/java/io/vertx/core/http/impl/HttpServerResponseImpl.java
src/test/java/io/vertx/core/http/HttpTest.java

This is a possible fix for #3077.
We are not confident at all that this is the correct fix, so please review carefully.
Although the tests seem to accept it.

Fix #3077 call endHandler for HttpServerResponse without keepalive

---

src/main/assembly/docs.xml

[ERROR] OS=Windows and the assembly descriptor contains a *nix-specific root-relative-reference (starting with slash) /
Signed-off-by: qxo <qxodream@gmail.com>

fix for maven build Error message on windows

---

src/main/java/io/vertx/core/http/impl/HttpHandlers.java
src/test/java/io/vertx/core/http/WebSocketTest.java

1.websocketExtensionHandler should be added before last "handler". 
2.Added a test to verify compression is enabled

Fixes #3119

---

src/main/java/io/vertx/core/eventbus/EventBus.java
src/main/java/io/vertx/core/eventbus/Message.java
src/main/java/io/vertx/core/eventbus/impl/EventBusImpl.java
src/main/java/io/vertx/core/eventbus/impl/HandlerHolder.java
src/main/java/io/vertx/core/eventbus/impl/HandlerRegistration.java
src/main/java/io/vertx/core/eventbus/impl/MessageConsumerImpl.java
src/main/java/io/vertx/core/eventbus/impl/MessageImpl.java
src/main/java/io/vertx/core/eventbus/impl/MessageProducerImpl.java
src/main/java/io/vertx/core/eventbus/impl/OutboundDeliveryContext.java
src/main/java/io/vertx/core/eventbus/impl/ReplyHandler.java
src/main/java/io/vertx/core/eventbus/impl/clustered/ClusteredEventBus.java
src/main/java/io/vertx/core/eventbus/impl/clustered/ClusteredMessage.java
src/main/java/io/vertx/core/eventbus/impl/clustered/ConnectionHolder.java
src/test/java/io/vertx/core/eventbus/LocalEventBusTest.java
src/test/java/io/vertx/core/spi/metrics/MetricsTest.java
src/test/java/io/vertx/core/spi/tracing/EventBusTracerTestBase.java

A bunch of simplifications for the `EventBus` implementation. The addition of the tracing feature somehow complexified the implementation. The `HandlerRegistration` was also mixing concerns of `MessageConsumer` and `ReplyHandler`, the `HandlerRegistration` class has been made parent of a new `MessageConsumerImpl` and `ReplyHandler` each consuming messages in a different manner, consequently reply handlers shall be a tad more lightweight.

Event bus improvements

---

src/main/java/io/vertx/core/impl/VertxImpl.java

This is an alternative to #3182 that performs equally well to JCTools' queues in tested quarkus scenario. (Despite LTQ had lower performance in the synthetic benchmark).
I believe that this change can't have any negative impact on Vert.x, uses a well-established queue and solves the scaling problem for Quarkus.

Replace LinkedBlockingQueue with LinkedTransferQueue in worker-pool

---

src/main/java/io/vertx/core/cli/Option.java
src/test/java/io/vertx/core/cli/impl/CLIConfiguratorTest.java

The following configuration will throw an exception:
```java
@io.vertx.core.cli.annotations.Option(longName = "acceptValueBoolean", flag = false, acceptValue = true)
```
```
--acceptValueBoolean=false
```
```
io.vertx.core.cli.InvalidValueException: The value 'false' is not accepted by 'acceptValueBoolean'
at io.vertx.core.cli.impl.DefaultParser.handleLongOptionWithEqual(DefaultParser.java:368)
at io.vertx.core.cli.impl.DefaultParser.handleLongOption(DefaultParser.java:313)
at io.vertx.core.cli.impl.DefaultParser.visit(DefaultParser.java:211)
at java.util.Arrays$ArrayList.forEach(Arrays.java:3880)
at io.vertx.core.cli.impl.DefaultParser.parse(DefaultParser.java:116)
at io.vertx.core.cli.impl.DefaultParser.parse(DefaultParser.java:78)
at …
```

fix cli @Option acceptValue support.

---

src/main/java/io/vertx/core/impl/VertxImpl.java
src/test/java/io/vertx/core/AccessEventBusFromInitVerticleFactory.java
src/test/java/io/vertx/core/AccessEventBusFromInitVerticleFactoryTest.java
src/test/java/io/vertx/core/ClasspathVerticleFactoryTest.java
src/test/java/io/vertx/core/VerticleFactoryTest.java
src/test/resources/META-INF/services/io.vertx.core.spi.VerticleFactory

Verticle factories will see an NPE on `vertx.eventBus().xxx()` because the object is only initialized later. Changing the order will avoid it, and allow factories to access the eventbus for doing stuff like registering custom codecs, etc...

Avoid eventbus npe on verticle factories

---

src/main/java/io/vertx/core/impl/ConversionHelper.java
src/main/java/io/vertx/core/json/JsonArray.java
src/main/java/io/vertx/core/json/JsonObject.java
src/main/java/io/vertx/core/json/impl/JsonUtil.java
src/main/java/io/vertx/core/json/jackson/ByteArrayDeserializer.java
src/main/java/io/vertx/core/json/jackson/ByteArraySerializer.java
src/main/java/io/vertx/core/json/jackson/JacksonCodec.java
src/main/java/io/vertx/core/parsetools/impl/JsonEventImpl.java
src/test/java/io/vertx/core/ConversionHelperTest.java
src/test/java/io/vertx/core/json/JacksonDatabindTest.java
src/test/java/io/vertx/core/json/JsonArrayTest.java
src/test/java/io/vertx/core/json/JsonCodecTest.java
src/test/java/io/vertx/core/json/JsonObjectTest.java
src/test/java/io/vertx/core/parsetools/JsonParserTest.java

This Pull request addresses the RFC: https://github.com/vert-x3/wiki/wiki/RFC:JSON-improvements
* `JSON{Object|Array}` allow any type to be stored which allows future POJO mappings
* No serialization is done for non JSON types at insert (less GC)
* No deserialization is done for `Temporal|Binary` data if not in `String` format (*ISODate* or *Base64*)
* No Copy on Read (however copy is still present and will behave like before)
* `Base64` encoding is fixed to properly use the right encoding, however it can be disabled for now using a system property to fall back to the 3.x format (Fixes #3123)
* Missing `JsonArray#add(int, Object)` added (Fixes #3171)
Important takeaways:
1. API is 100% backwards compatible (no breaking changes)
2. Behavior is …

Code changed to solve the JSON RFCs

---

src/main/java/io/vertx/core/http/impl/MimeMapping.java

While experimenting with Rust/WASM I found out that the StaticHandler was using the wrong MIME-Type for WASM files which breaks them in the bbrowser. This is due to the MIME-Type missing in MimeMapping.
This PR adds the **applicsation/wasm**.
See same PR for 4.0:
https://github.com/eclipse-vertx/vert.x/pull/3221

Added application/wasm mimetype

---

src/main/java/io/vertx/core/http/impl/MimeMapping.java

While experimenting with Rust/WASM I found out that the StaticHandler was using the wrong MIME-Type for WASM files which breaks them in the bbrowser. This is due to the MIME-Type missing in MimeMapping.
This PR adds the **applicsation/wasm**.

Added Mime-Type for web assembly

---

src/main/java/io/vertx/core/json/jackson/JacksonCodec.java
src/test/java/io/vertx/core/json/JsonCodecTest.java

Brings JacksonCore codec on par with Databind for enum and big numbers.

Fixes #3227

---

src/main/java/io/vertx/core/Future.java

Otherwise it breaks Rx generation and there's no real interest in these methods there.

Fully @GenIgnore CompletionStage interop methods

---

src/main/java/io/vertx/core/http/HttpConnection.java

This is my first time to make use of vertx to implement a web server and this comment was confusing me a bit...

Fix a typo in the javadoc for HttpConnection.localAddress

---

src/main/java/io/vertx/core/json/JsonArray.java
src/main/java/io/vertx/core/json/JsonObject.java
src/main/java/io/vertx/core/json/impl/JsonUtil.java
src/test/java/io/vertx/core/json/JsonArrayTest.java
src/test/java/io/vertx/core/json/JsonObjectTest.java

This is the follow up of: https://groups.google.com/forum/#!topic/vertx-dev/SNx0XXHO3Pg
* To ease the use of JSON, `getString(key)` will autocast if a value is not of type `String`.
* The `copy()` method will allow besides JSON primitives `Shareable` objects which also implement the `copy()` method making it easy to share such POJOs over the eventbus or shared data.

Allow Shareable on JSON copy + Autocast getString()

---

src/main/asciidoc/enums.adoc
src/main/asciidoc/http.adoc
src/main/java/io/vertx/core/http/HttpClientRequest.java
src/main/java/io/vertx/core/http/HttpMethod.java
src/main/java/io/vertx/core/http/HttpServerRequest.java
src/main/java/io/vertx/core/http/impl/Http1xClientConnection.java
src/main/java/io/vertx/core/http/impl/Http1xServerRequest.java
src/main/java/io/vertx/core/http/impl/Http2ClientConnection.java
src/main/java/io/vertx/core/http/impl/Http2ServerConnection.java
src/main/java/io/vertx/core/http/impl/Http2ServerRequestImpl.java
src/main/java/io/vertx/core/http/impl/Http2ServerStream.java
src/main/java/io/vertx/core/http/impl/Http2UpgradedClientConnection.java
src/main/java/io/vertx/core/http/impl/HttpClientRequestImpl.java
src/main/java/io/vertx/core/http/impl/HttpClientRequestPushPromise.java
src/main/java/io/vertx/core/http/impl/HttpClientStream.java
src/main/java/io/vertx/core/http/impl/HttpMethodImpl.java
src/main/java/io/vertx/core/http/impl/HttpUtils.java
src/test/java/io/vertx/core/http/Http1xTest.java
src/test/java/io/vertx/core/http/HttpMethodTest.java
src/test/java/io/vertx/core/http/HttpTest.java
src/test/java/io/vertx/core/json/JsonCodecTest.java

Currently HttpMethod includes the verbs defined in 2 RFCs:
RFC 2616
RFC 5789
This pull request adds a few more scattered on other RFCs
RFC 2518
RFC 4918
RFC 4791
RFC 3253
RFC 3648
RFC 3744
RFC 5323
This Pull Request depends on #3247 and replaces #3231

Missing methods from rfcs

---

src/main/java/io/vertx/core/json/jackson/JacksonCodec.java
src/test/java/io/vertx/core/json/JsonCodecTest.java

Fix https://github.com/eclipse-vertx/vert.x/issues/3254 to allow adding `byte` to `JsonObject` & `JsonArray`

Fix https://github.com/eclipse-vertx/vert.x/issues/3254

---

src/main/java/io/vertx/core/impl/FailedFuture.java
src/main/java/io/vertx/core/impl/SucceededFuture.java
src/test/java/io/vertx/core/FutureTest.java

SucceededFuture and FailedFuture, like other futures, take a context as constructor param.
If not null, this context should be used to dispatch the execution of future handlers.

Completed futures should operate on provided context

---

src/main/asciidoc/enums.adoc
src/main/asciidoc/http.adoc
src/main/java/io/vertx/core/http/Cookie.java
src/main/java/io/vertx/core/http/CookieSameSite.java
src/main/java/io/vertx/core/http/impl/CookieImpl.java
src/test/java/io/vertx/core/http/HttpTest.java

This PR is a proposal to support same site policy for cookies (server side only). There is no parsing involved (as that is a feature only applicable to browsers).
The Same Site policy is supported by all major browsers and a security feature to prevent cross site request forgery.
Although this isn't present in netty (yet) discussions seem to show that this will only land on the 5.x branch which means vertx can't offer the current owasp recommendation on cookies https://www.owasp.org/index.php/SameSite 
As a workaround this PR allows users to build secure cookie based applications and once support lands upstream we can easily drop this and fully support it.
Also note that the chrome team will be "strict" with this flag: …

Proposal for same site cookie value

---

src/test/java/io/vertx/core/net/NetTest.java

Signed-off-by: Rodrigo Salado Anaya <rodrigo.salado.anaya@gmail.com>
Motivation:
Improvement to the test `testListenInvalidPort`, currently when port 80 is available the test fails.
```java
mvn -Dtest=NetTest#testListenInvalidPort test
```

Use a http server to hold the port busy before the real test.

---

src/main/java/io/vertx/core/eventbus/impl/MessageConsumerImpl.java
src/test/java/io/vertx/core/eventbus/EventBusFlowControlTest.java

Fixes a bug when unregistering a message consumer then registering it again where the new handler would not receive any message.
Spotted in https://github.com/vert-x3/vertx-rx/issues/221 and fixes the corresponding issue on my machine.

Bug when unregistering a message consumer and registering a handler again

---

src/main/java/io/vertx/core/http/impl/HttpClientRequestImpl.java

Motivation:
Don't know why `stream` is public, it seems
to work as private, let's see if anything
goes well.
Conformance:

Make field private

---

src/main/java/io/vertx/core/Starter.java
src/main/java/io/vertx/core/cli/UsageMessageFormatter.java
src/main/java/io/vertx/core/file/impl/FileSystemImpl.java
src/main/java/io/vertx/core/impl/launcher/commands/ListCommand.java
src/main/java/io/vertx/core/impl/launcher/commands/StopCommand.java
src/main/java/io/vertx/core/net/impl/KeyStoreHelper.java
src/test/java/io/vertx/core/LauncherTest.java

Signed-off-by: Michael Panchenko <panchmp@gmail.com>
Motivation:
"try-with-resources" statement should be used  to ensure that resources are closed

Use try -with-resources statement ensures that resource is close

---

src/main/java/io/vertx/core/AbstractVerticle.java

Otherwise IDEs do not report these methods as deprecated, even if the Verticle interface has them deprecated.

Deprecate the start/stop Future-based methods in AbstractVerticle

---

src/main/asciidoc/dataobjects.adoc
src/main/generated/io/vertx/core/VertxOptionsConverter.java
src/main/generated/io/vertx/core/eventbus/EventBusOptionsConverter.java
src/main/java/io/vertx/core/VertxOptions.java
src/main/java/io/vertx/core/eventbus/EventBusOptions.java
src/main/java/io/vertx/core/impl/VertxFactory.java
src/main/java/io/vertx/core/impl/launcher/commands/BareCommand.java
src/main/java/io/vertx/core/impl/launcher/commands/RunCommand.java
src/test/java/io/vertx/core/CreateVertxTest.java
src/test/java/io/vertx/core/HATest.java
src/test/java/io/vertx/core/LauncherTest.java
src/test/java/io/vertx/core/VertxOptionsTest.java
src/test/java/io/vertx/core/eventbus/WriteHandlerLookupFailureTest.java
src/test/java/io/vertx/core/impl/VertxFactoryTest.java
src/test/java/io/vertx/core/impl/launcher/LauncherExtensibilityTest.java
src/test/java/io/vertx/core/spi/metrics/MetricsContextTest.java
src/test/java/io/vertx/test/core/VertxTestBase.java

Signed-off-by: Selim Dincer <wowselim@live.de>
Motivation: This PR implements the change discussed in #3230. I have removed the clustered flag entirely and adjusted the tests accordingly.
There is one test where I don't know whether it should still exist or not:
`LauncherExtensibilityTest#testThatCustomLauncherCanCustomizeTheClusteredOption`

remove clustered flag in favor of createClusteredVertx

---

pom.xml
src/main/asciidoc/dataobjects.adoc
src/main/asciidoc/http.adoc
src/main/asciidoc/index.adoc
src/main/asciidoc/net.adoc
src/main/generated/io/vertx/core/net/NetServerOptionsConverter.java
src/main/java/examples/HTTPExamples.java
src/main/java/examples/NetExamples.java
src/main/java/io/vertx/core/http/HttpConnection.java
src/main/java/io/vertx/core/http/HttpServerOptions.java
src/main/java/io/vertx/core/http/HttpServerRequest.java
src/main/java/io/vertx/core/http/WebSocketBase.java
src/main/java/io/vertx/core/http/impl/HttpServerChannelInitializer.java
src/main/java/io/vertx/core/net/NetServerOptions.java
src/main/java/io/vertx/core/net/NetSocket.java
src/main/java/io/vertx/core/net/impl/ConnectionBase.java
src/main/java/io/vertx/core/net/impl/HAProxyMessageCompletionHandler.java
src/main/java/io/vertx/core/net/impl/NetServerImpl.java
src/test/java/io/vertx/core/http/Http1xTest.java
src/test/java/io/vertx/core/http/HttpTLSTest.java
src/test/java/io/vertx/core/http/HttpTest.java
src/test/java/io/vertx/core/http/WebSocketTest.java
src/test/java/io/vertx/core/net/NetTest.java
src/test/java/io/vertx/it/HAProxyTest.java
src/test/java/io/vertx/test/proxy/HAProxy.java

Signed-off-by: zenios dimitris.zenios@gmail.com
**Notes:**
1. Hardcoded netty version (4.1.48.Final) for netty-codec-haproxy in order to avoid creating a pull request for vertx-dependencies
2. Tests were copied from #1271. That PR can be closed if this one gets merged

HAProxy protocol support

---

src/test/java/io/vertx/core/http/Http1xTest.java
src/test/java/io/vertx/core/http/HttpTest.java
src/test/java/io/vertx/core/net/NetTest.java
src/test/java/io/vertx/test/proxy/HAProxy.java

2.Restore tests that were disabled due to https://github.com/netty/netty/issues/9113
Signed-off-by: Dimitris Zenios <dimitris.zenios@gmail.com>

1.Fix HA PROXY tests that were failing when run with -PtestDomainSockets

---

src/main/java/io/vertx/core/VertxOptions.java

Motivation:
Function `VertxOptions::toString()` erroneously returns addressResolver field twice.

Fix duplicate line

---

src/main/java/io/vertx/core/VertxOptions.java

Motivation:
The copy constructor ignores the value of `addressResolverOptions` from the copied object.

Fix VertxOptions copy constructor

---

src/main/java/io/vertx/core/http/impl/Http2ServerResponseImpl.java
src/test/java/io/vertx/core/http/Http2ServerTest.java
src/test/java/io/vertx/core/http/HttpTest.java
src/test/java/io/vertx/test/core/DetectFileDescriptorLeaks.java
src/test/java/io/vertx/test/core/FileDescriptorLeakDetectorRule.java
src/test/java/io/vertx/test/core/VertxTestBase.java

* Implement file descriptor leak tests
Signed-off-by: Dimitris Zenios <dimitris.zenios@gmail.com>
* Close the AsyncFile once we are finished with it
Closes #3396
Signed-off-by: Dimitris Zenios <dimitris.zenios@gmail.com>
* Comments and refactorings
Signed-off-by: Dimitris Zenios <dimitris.zenios@gmail.com>
* Make sure that FileDescriptorLeakDetectorRule will skip when run in os that does not support getting the open file descriptors
Signed-off-by: Dimitris Zenios <dimitris.zenios@gmail.com>
* Use JMX to collect the open file descriptor count instead of the com.sun API + minor improvements
Co-authored-by: Dimitris Zenios <dimitris.zenios@gmail.com>
Motivation:
Explain here the context, and why you're making that change, what is the problem you're trying to solve.
Conformance:
Your commits …

Implement file descriptor leak tests (#3408)

---

src/main/java/io/vertx/core/spi/cluster/NodeInfo.java
src/main/java/io/vertx/core/spi/cluster/RegistrationInfo.java
src/test/java/io/vertx/core/spi/cluster/NodeInfoSerializationTest.java
src/test/java/io/vertx/core/spi/cluster/RegistrationInfoSerializationTest.java

This will ease CM implementations:
- no need to creating wrappers
- share the serialization implementation in Vert.x core

Make NodeInfo and RegistrationInfo implement ClusterSerializable

---

src/main/java/io/vertx/core/parsetools/impl/RecordParserImpl.java

Signed-off-by: Thomas Cataldo <thomas.cataldo@blue-mind.net>
Motivation:
My workload needs to parse a stream containing 10 chunks with 100MB of fixed sized items inside a bigger string. Performance is abysmal and yourkit pointed to this line.

Prevent extra buffer copies when parsing did not extract anything

---

src/test/java/io/vertx/core/http/HttpTest.java

Motivation:
The test 'testListenInvalidPort' fails on OSX as it is possible to use port 7 in that env,
from reading the test it also looks like this is true in Windows too.
Its test's failure trips up 'mvn clean install' on OSX.
This PR changes the test to first occupy a valid port (by asking for port 0)
exclusively (need to set this on OSX) and then using that occupied port
for the collision. The socket is Closable so the try with resources should
close the port (after the await) meaning the test should not leak socket
resources.
This test is also mentioned as failing in another env in #3051 
Signed-off-by: Gordon Hutchison <Gordon.Hutchison@gmail.com>

testListenInvalidPort now valid for Windows and OSX

---

src/main/java/io/vertx/core/eventbus/impl/EventBusImpl.java
src/main/java/io/vertx/core/eventbus/impl/HandlerRegistration.java

If we register a class we don't keep a reference, the close hook can be collected and lead to not closing the hook when the vertical is underplayed

MessageConsumer should be registered as close hook

---

src/main/java/io/vertx/core/http/impl/Http1xServerConnection.java
src/test/java/io/vertx/core/http/Http1xTest.java

Motivation:
Vertx does not return `431 Request Header Fields Too Large` status for HTTP/1.1 (could not confirm how it works on HTTP/2.0), instead it falls back to the generic `400 Bad Message` (only handling explicitly `414 URI Too Long`).
Since Netty does handle both `414` and `431`, although with the same exception `TooLongFrameException`, the status message is different. I could not find any info whether omitting `431` was on purpose, but in any case if there was reason for sending the generic `400`, could anyone clarify?
In the absence of the whole picture, this my attempt to amend the current Vertx behaviour.
Conformance:
Signed Eclipse Contributor Agreement

Support header size limit exceeded with http status 431

---

src/main/java/io/vertx/core/http/Cookie.java
src/main/java/io/vertx/core/http/impl/CookieImpl.java
src/test/java/io/vertx/core/http/HttpTest.java

Motivation:
Issue: #3482
When using vertx Cookies it is frustrating to not be able to easily make assertions about the value of a cookies httpOnly status, security status and same site policy.

#3482 Add getSameSite, isHttpOnly and isSecure to Cookie interface

---

src/main/java/io/vertx/core/http/HttpHeaders.java

Motivation:
`Vary` is a common header that is missing from the vertx API and forces other modules (e.g.: vertx-web) to refer to netty internal classes or use strings for it. Adding it will not break any API and will allow a consistent experience.

Add missing (but common Vary header name)

---

src/main/java/io/vertx/core/http/impl/headers/HeadersMultiMap.java
src/test/java/io/vertx/core/http/headers/VertxHttpHeadersTest.java

The prev(ous) pointer stays the same when removing.
Signed-off-by: Adam Dickmeiss <adam@indexdata.dk>

Yet another issue related to #3487

---

src/main/java/io/vertx/core/http/impl/MimeMapping.java

Motivation:
I'm serving `m4a` files with `StaticHandler`, and they get served without `Content-Type`
Conformance:
Signed the commit and the ECA

Add m4a mime mapping

---

src/main/java/io/vertx/core/json/JsonArray.java
src/main/java/io/vertx/core/json/JsonObject.java

JsonObject and JsonArray serialization create an intermediate String conversion.
This step can be skipped by serializing and de-serialiazing directly from bytes.

Json ClusterSerializable: skip intermediate String conversion

---

src/main/java/io/vertx/core/eventbus/Message.java
src/test/java/io/vertx/core/spi/metrics/MetricsTest.java

Reverts eclipse-vertx/vert.x#3509
`replyAddress` is used by eventbus bridges.

Revert "Deprecate Message replyAddress method"

---

src/main/java/io/vertx/core/http/HttpServerRequest.java
src/main/java/io/vertx/core/http/impl/Http1xServerRequest.java
src/main/java/io/vertx/core/http/impl/Http2ServerRequestImpl.java
src/main/java/io/vertx/core/http/impl/Http2ServerStream.java
src/main/java/io/vertx/core/spi/metrics/HttpServerMetrics.java
src/test/java/io/vertx/core/http/HttpMetricsTestBase.java
src/test/java/io/vertx/test/fakemetrics/FakeHttpServerMetrics.java
src/test/java/io/vertx/test/fakemetrics/HttpServerMetric.java

Motivation:
In preparation for https://github.com/vert-x3/vertx-web/issues/1431 and https://github.com/vert-x3/vertx-micrometer-metrics/issues/34
* adds `requestRouted(R requestMetric, String route)` to the http server metric SPI as proposed by @vietj [here](https://github.com/vert-x3/vertx-micrometer-metrics/issues/34#issuecomment-462356893)
* adds a `routed(String route)` to `HttpServerRequest` delegating to metrics to avoid exposing `requestMetric`
Companion PRs:
* https://github.com/vert-x3/vertx-web/pull/1682
* https://github.com/vert-x3/vertx-micrometer-metrics/pull/111
* https://github.com/vert-x3/vertx-dropwizard-metrics/pull/101

Add route support to http server metrics.

---

src/main/java/io/vertx/core/CompositeFuture.java
src/test/java/io/vertx/core/FutureTest.java

Motivation:
Retrieving failures from a composite future requires some boilerplate, which can be avoided with this `causes` method.

Added a method to CompositeFuture to retrieve all failure causes

---

src/main/asciidoc/http.adoc
src/main/java/examples/HTTPExamples.java
src/main/java/io/vertx/core/http/HttpClientRequest.java
src/main/java/io/vertx/core/http/HttpClientResponse.java
src/main/java/io/vertx/core/http/impl/Http1xClientConnection.java
src/main/java/io/vertx/core/http/impl/Http2ClientConnection.java
src/main/java/io/vertx/core/http/impl/Http2ConnectionBase.java
src/main/java/io/vertx/core/http/impl/Http2ServerConnection.java
src/main/java/io/vertx/core/http/impl/Http2ServerResponseImpl.java
src/main/java/io/vertx/core/http/impl/Http2UpgradedClientConnection.java
src/main/java/io/vertx/core/http/impl/HttpClientRequestImpl.java
src/main/java/io/vertx/core/http/impl/HttpClientRequestPushPromise.java
src/main/java/io/vertx/core/http/impl/HttpClientResponseImpl.java
src/main/java/io/vertx/core/http/impl/HttpClientStream.java
src/main/java/io/vertx/core/http/impl/HttpNetSocket.java
src/main/java/io/vertx/core/http/impl/HttpUtils.java
src/main/java/io/vertx/core/http/impl/VertxHttp2Stream.java
src/test/java/io/vertx/core/http/Http1xTest.java
src/test/java/io/vertx/core/http/Http2ClientTest.java
src/test/java/io/vertx/core/http/Http2ServerTest.java
src/test/java/io/vertx/core/http/HttpTest.java
src/test/java/io/vertx/core/http/WebSocketTest.java
src/test/java/io/vertx/core/spi/metrics/MetricsTest.java

A few important improvements concerning `NetSocket` on top of HTTP.
The previous API was requiring to set a client `NetSocket` handler on the request which felt quite un-natural. This change was motivated that it was a way to signal the underlying connection that it should clean up the HTTP connection when the server response was received. Instead now we provide a new `connect` method that do the same but should be used in place of `send` or `end`. The `NetSocket` is then obtained with the synchronous `HttpClientResponse#netSocket()` method.
Implementation wise, HTTP/1.1 client `NetSocket` was an actual implementation that replaced the `VertxHandler` by another when the `NetSocket` was created. The downside of this approach is that this `NetSocket` requires to use the connection context …

Rework HttpClient tunnel creation

---

src/main/java/io/vertx/core/file/impl/FileResolver.java
src/test/java/io/vertx/core/file/FileResolverTestBase.java

Motivation:
Cleaning the FileSystem cache happens usually on a shutdown thread, outside the resolver monitor. It also changes the resolver state to set the cache dir object to null.
This has a couple of side effects:
1. A call to resolve while the delete is happening will use the "to be deleted directory" as root.
2. A resolve call during clear cache will see that the `cacheDir` object is `null` which will lead to resolved file to be written to the `${user.dir}`.
3. As `cacheDir` shared the same directory for all instances (by default) a clear for instance A will wipe the cache for instance B
The last item was also reported by https://github.com/eclipse-vertx/vert.x/issues/3510
This PR addresses the issue in the following way:
1. `cacheDir` …

Fixes Resolver delete race against file resolve

---

src/main/java/io/vertx/core/eventbus/ReplyFailure.java
src/main/java/io/vertx/core/eventbus/impl/clustered/ClusteredEventBus.java
src/main/java/io/vertx/core/eventbus/impl/clustered/ClusteredMessage.java
src/test/java/io/vertx/core/eventbus/InternalErrorTest.java
src/test/java/io/vertx/core/eventbus/ReplyFailureErrorTest.java

This is the first part of the solution for #3406.
It allows to communicate an internal error from the receiver side (e.g. protocol mismatch, unknown codec) instead of failing silently.

InternalError eventbus failure type

---

src/main/java/io/vertx/core/json/JsonArray.java
src/main/java/io/vertx/core/json/JsonObject.java

The JavaDoc should state whether the copy is shallow or deep.

JavaDoc that JsonObject#copy and JsonArray#copy make a deep copy

---

src/main/java/io/vertx/core/eventbus/impl/clustered/ClusteredEventBus.java

Fixes #3638
Completion handler, if present, should be called in all cases.
When the cluster manager could not find the subscription, it's not necessary to complete with a failure.

Fix completion handling when removing sub

---

src/test/java/io/vertx/core/eventbus/ClusteredEventBusTestBase.java
src/test/java/io/vertx/core/spi/cluster/WrappedClusterManager.java
src/test/java/io/vertx/core/spi/cluster/WrappedNodeSelector.java
src/test/java/io/vertx/test/core/VertxTestBase.java

The test failed intermittently with Hazelcast on CI.
It failed consistently with Vert.x nodes configured as lite members of the Hazelcast cluster.
When a subscription is removed, it can take some time before the cluster manager invokes our listeners.
It is then possible that we still have in cache a registration that has been effectively removed.
The fix consists in intercepting the registration update event to make sure it has been processed.
Then we can try sending again and we should get the NO_HANDLERS error as expected.

Intermittent failure in testClusteredUnregistration

---

src/main/java/io/vertx/core/CompositeFuture.java
src/main/java/io/vertx/core/file/impl/FileSystemImpl.java
src/main/java/io/vertx/core/http/impl/Http1xClientConnection.java
src/main/java/io/vertx/core/http/impl/HttpServerConnectionHandler.java
src/main/java/io/vertx/core/impl/LoaderManager.java
src/main/java/io/vertx/core/impl/launcher/commands/FileSelector.java
src/main/java/io/vertx/core/impl/launcher/commands/RunCommand.java
src/main/java/io/vertx/core/impl/resolver/DnsResolverProvider.java
src/main/java/io/vertx/core/net/impl/KeyStoreHelper.java

Motivation:
There are two styles to convert a collection to an array: either using a pre-sized array (like c.toArray(new String[c.size()])) or using an empty array (like c.toArray(new String[0]).
In older Java versions using pre-sized array was recommended, as the reflection call which is necessary to create an array of proper size was quite slow. However since late updates of OpenJDK 6 this call was intrinsified, making the performance of the empty array version the same and sometimes even better, compared to the pre-sized version. Also passing pre-sized array is dangerous for a concurrent or synchronized collection as a data race is possible between the size and toArray call which may result in extra nulls at the end of the array, if the collection was concurrently shrunk during the …

using empty array for Collection.toArray()

---

src/main/java/io/vertx/core/tracing/TracingPolicy.java

Motivation:
Missing annotation on public enum

TracingPolicy is used in public options so it should be annotated too

---

src/test/java/io/vertx/core/shareddata/AsyncMapTest.java

Motivation:
Tests the case were a map entry is overridden by a new one with ttl set
This is especially important for cluster setups were the underlying map policies can change this behavior

Add AsyncMap put then put ttl Test

---

src/main/asciidoc/http.adoc

Motivation:
This patch fix some typos in HTTP documentation.
Conformance:

Fix typos at HTTP doc

---

src/main/asciidoc/streams.adoc

Motivation:
Fix typo in fetch sentence
Conformance:

Fix typo in fetch sentence

---

src/main/generated/io/vertx/core/http/HttpServerOptionsConverter.java
src/main/java/io/vertx/core/http/HttpClientRequest.java
src/test/java/io/vertx/core/http/HttpTest.java

Motivation:
fixing the issue reported in #3721 
Conformance:

calling completion handler for HttpClientResponse. fixes issue #3721

---

src/test/java/io/vertx/core/eventbus/ClusteredEventBusTestBase.java

I think the intention of `ClusteredEventBusTestBase.testPublish` is to
1. start 3 nodes, register handlers on 2 of these nodes
1. wait for both handlers to be registered
1. publish *one* message on the remaining node
1. wait for both handlers to receive the message
However, `testPublish` currently publishes *two* messages, one without waiting. Depending on timing, this can cause `testComplete` to be called prematurely. As a consequence, tests [sometimes fail for `vertx-ignite`](https://github.com/vert-x3/vertx-ignite/issues/105).
This PR fixes this and I've also verified that tests for `vertx-hazelcast`, `vertx-zookeeper` and `vertx-infinispan` still pass with this change.

duplicate message in `ClusteredEventBusTestBase.testPublish`

---

src/main/java/io/vertx/core/impl/VertxImpl.java

The current code sets the Netty ResourceLeakDetector to disabled if either of the Netty system properties is set to a non-null value. I believe this is the exact opposite of what you want, you want to disable it if both are not set instead.
Motivation:
I'm trying to enable Netty resource leak detection in my own code, but because I'm setting the system property and I'm loading vert.x as well, the level gets set to disabled instead of the value I specified.

Allow enabling Netty resource leak detection

---

src/main/java/io/vertx/core/impl/VertxImpl.java
src/main/java/io/vertx/core/impl/WorkerExecutorImpl.java
src/test/java/io/vertx/core/NamedWorkerPoolTest.java

Instead, it should update the refCounf and eventually remove the pool for the shared pools map.
Fixes #3786

SharedWorkerPool close method should not force executor termination

---

src/main/generated/io/vertx/core/dns/AddressResolverOptionsConverter.java
src/main/java/io/vertx/core/dns/AddressResolverOptions.java
src/main/java/io/vertx/core/impl/resolver/DnsResolverProvider.java
src/test/java/io/vertx/core/dns/HostnameResolutionTest.java

This PR brings the original contribution from @ybayk (yurgis.baykshtis[at]clarivate[dot]com) in #2902 with minor simplifications.
It adds a config property in AddressResolverOptions that is check in DnsResolverProvider in order to switch between the default Netty AddressResolver and RoundRobinInetAddressResolver.

Implement round robin address selection

---

src/main/java/io/vertx/core/http/impl/Http1xClientConnection.java
src/main/java/io/vertx/core/http/impl/Http2ServerRequest.java

The HttpUtils.CLIENT_HTTP_REQUEST_TAG_EXTRACTOR extracts the tags, the tags ArrayList is no longer needed.

Remove tracer tags ArrayList

---

src/main/java/io/vertx/core/impl/cpu/CpuCoreSensor.java

The InputStreamReader constructor may throw an exception leaving FileInputStream open.
Always using try-with-resources for file streams and readers is defensive programming and puts you one the safe side.

Use try-with-resources for InputStreamReader and FileInputStream

---

src/main/java/io/vertx/core/impl/future/CompositeFutureImpl.java
src/test/java/io/vertx/core/CompositeFutureTest.java

CompositeFutureImpl#future(index) throws
* ArrayIndexOutOfBoundsException if index == results.length
* IndexOutOfBoundsException if index < 0 or index > results.length
This fix changes the index == results.length case to also throw IndexOutOfBoundsException.

Always throw IndexOutOfBoundsException in CompositeFuture

---

src/main/java/io/vertx/core/spi/cluster/impl/DefaultNodeSelector.java
src/main/java/io/vertx/core/spi/cluster/impl/selector/Selectors.java

Otherwise some tests can fail because selector is initialized with intermediate data.

EventBus node selector should always initialize with initial state request

---

src/main/java/io/vertx/core/spi/cluster/NodeSelector.java
src/main/java/io/vertx/core/spi/cluster/impl/DefaultNodeSelector.java
src/main/java/io/vertx/core/spi/cluster/impl/selector/Selectors.java
src/test/java/io/vertx/core/eventbus/ClusteredEventBusTest.java
src/test/java/io/vertx/core/spi/cluster/WrappedNodeSelector.java

This can be useful to reduce load/traffic.
Indeed, cluster managers such as HZ/ISPN/Ignite must query the backend to get a fresh view of the data.
Consequently, if the NodeSelector is not interested, this query can be avoided

Give ClusterManager a chance to know if NodeSelector wants updates for an address

---

src/main/java/io/vertx/core/http/impl/HttpClientRequestBase.java
src/test/java/io/vertx/core/http/impl/HttpClientRequestBaseTest.java

* Invalidate query cache in setURI(uri). This fixes a bug
where query() returns an old and invalid value, the
new unit test run against the old code demonstrates this.
* Use boolean newQuery to invalidate the query cache as
HttpUtils.parseQuery(uri) may return null.
* Remove redundant code from path() as
HttpUtils.parsePath(uri) never returns null.

Fix HttpClientRequest setURI(uri), query(), path()

---

src/main/java/io/vertx/core/eventbus/impl/ReplyHandler.java

Cosmetic fix for the message logged in the ReplyHandler when a ReplyException is thrown on a timeout
In the current implementation the below `3` stands for the timer ID not the milliseconds of the timeout
`Timed out after waiting 3(ms) for a reply. address:`
This PR puts the timeout in milliseconds back into the message

Fix timeout reply exception message in ReplyHandler

---

src/main/java/io/vertx/core/json/JsonArray.java
src/main/java/io/vertx/core/json/JsonObject.java
src/main/java/io/vertx/core/json/impl/JsonUtil.java
src/test/java/io/vertx/core/json/JsonArrayTest.java
src/test/java/io/vertx/core/json/JsonObjectTest.java

Motivation:
Explicitly document and test the `stream()` contract on JSON types.
Fixes #3873

Explicitly document and test the 'stream()' contract

---

src/main/java/io/vertx/core/impl/VertxImpl.java

Signed-off-by: Benjamin Roux <ben.dev@outlook.com>
Motivation:
In many of our projects we ended-up having to inherit from HttpServerImpl and NetServerImpl in order to do custom things that cannot be done elsewhere. After migrating to VertX 4, the server cannot start because it's checking for the exact type instead of type and subtypes (VertX 3 had two methods sharedHttpServers/sharedNetServers so it didn't cause a problem).

Change the sharedTCPServers method to work with custom implementation of HttpServerImpl and NetServerImpl

---

src/main/java/io/vertx/core/http/impl/Http1xServerConnection.java

Motivation:
This is a small fix. I was investigating a build failure [here](https://github.com/yuzawa-san/googolplex-theater/pull/110/checks?check_run_id=2267749072) related to upgrading to netty 4.1.63 and eventually found an issue here relating to the DecoderResult check which will fail in newer versions of netty (in the upgrade from 4.1.60 to 4.1.61). It was specifically [this change](https://github.com/netty/netty/pull/11068) with the introduction of a [subclass](https://github.com/netty/netty/pull/11068/files#diff-e26989b9171ef22c27c9f7d80689cfb059d568c9bd10e75970d96c02d0654878R633) which broke Vert.x since this project uses an instance comparison currently. The solution is to use the DecoderResult.isSuccess() method which [compares within the "Signal" in the DecoderResult …

Use Netty's DecoderResult.isSuccess()

---

src/main/java/io/vertx/core/http/impl/MimeMapping.java

Motivation:
Current vertx static handler serves mjs files with the wrong content type. This simple addition fixes that
Conformance:

add mimetype for es6 js modules

---

src/main/java/io/vertx/core/file/AsyncFile.java
src/main/java/io/vertx/core/file/impl/AsyncFileImpl.java
src/test/java/io/vertx/core/file/FileSystemTest.java

Closes #3892
AsyncFileImpl can get the file size from the underlying AsynchronousFileChannel.
But it was not exposed.

Expose AsyncFile size

---

.gitignore
src/main/java/io/vertx/core/impl/VertxImpl.java

Following the discussion in the following google group thread: https://groups.google.com/g/vertx/c/uRU6PYd3CKs/m/2nRuqCaEAgAJ
I would like to remove the redundant `System.setProperty("io.netty.noJdkZlibDecoder", "false")`
Closes #3907

remove redundant call to set io.netty.noJdkZlibDecoder to false

---

src/main/java/io/vertx/core/file/OpenOptions.java

Motivation:
Just find a little typo reading the javadoc :)

fix: typo in OpenOptions javadoc

---

src/main/asciidoc/http.adoc
src/main/asciidoc/net.adoc
src/main/generated/io/vertx/core/http/RequestOptionsConverter.java
src/main/generated/io/vertx/core/net/ClientOptionsBaseConverter.java
src/main/java/examples/HTTPExamples.java
src/main/java/examples/NetExamples.java
src/main/java/io/vertx/core/http/HttpClient.java
src/main/java/io/vertx/core/http/HttpClientOptions.java
src/main/java/io/vertx/core/http/RequestOptions.java
src/main/java/io/vertx/core/http/WebSocketConnectOptions.java
src/main/java/io/vertx/core/http/impl/EndpointKey.java
src/main/java/io/vertx/core/http/impl/HttpChannelConnector.java
src/main/java/io/vertx/core/http/impl/HttpClientImpl.java
src/main/java/io/vertx/core/net/ClientOptionsBase.java
src/main/java/io/vertx/core/net/NetClientOptions.java
src/main/java/io/vertx/core/net/impl/NetClientImpl.java
src/main/java/io/vertx/core/net/impl/ProxyFilter.java
src/test/java/io/vertx/core/http/Http1xProxyTest.java
src/test/java/io/vertx/core/net/NetTest.java

- nonProxyHost support
- per HTTP request / WebSocket proxy options

Client proxy enhancements

---

src/main/java/io/vertx/core/impl/VertxBuilder.java

While using the tracing feature, together with the new vertx-opentelemetry module, I had some problems in my packaging, where i was mistakenly overwriting `META-INF/services/io.vertx.core.spi.VertxServiceProvider`, hence not loading the proper tracing factory. This PR adds a check that prints a warning when such situation happens.

Log a warning if the tracing factory or the metrics factory are not configured

---

src/main/java/io/vertx/core/http/impl/Http1xClientConnection.java

Motivation:
Fix this issue : https://github.com/eclipse-vertx/vert.x/issues/3980
Vert.x used to throw a NullPointerException when the websocket connection fails and metrics are enabled.

Fix issue 3980 - NPE when a websocket connection fails and metrics are enabled

---

src/main/java/io/vertx/core/http/HttpServerRequest.java
src/test/java/io/vertx/core/http/HttpTest.java

Return default value instead of null if query param is not present. 
- removed unused imports
Improvement based on: [vertx-web#1473](https://github.com/vert-x3/vertx-web/issues/1473)

Added default value for query parameters.

---

src/main/java/io/vertx/core/impl/HAManager.java
src/main/java/io/vertx/core/impl/VertxImpl.java
src/test/java/io/vertx/core/HATest.java
src/test/java/io/vertx/core/VertxStartFailureTest.java

Motivation:
since the rework of ClusteredEventBus it is no longer necessary to have HAManagerImpl around even if HA is disabled.
@tsegismont  what do you think?
Conformance:

do not create HAManager when it is disabled

---

src/main/java/io/vertx/core/impl/BlockedThreadChecker.java

Motivation:
In Quarkus we start & stop many instances of Vertx, and in integration tests for "dev-mode" this is happening quite frequently and intensively as the number of tests grow.
We do close and discard references to terminated instances, so technically there isn't a leak as things get eventually discarded correctly, but can't do this very aggressively.
So in practice, sampled heap snapshots contain several lingering instances of stopped `BlockedThreadChecker` instances - they will be collected eventually but they form rather large clusters of data which leads to spending significant cycles on GC.
This helps with the GC effort and looks harmless enough.

Have BlockedThreadChecker release memory on shutdown

---

src/main/java/io/vertx/core/http/impl/headers/HeadersAdaptor.java
src/main/java/io/vertx/core/http/impl/headers/Http2HeadersAdaptor.java
src/test/java/io/vertx/core/http/headers/HeadersTestBase.java

Signed-off-by:Phillip Kruger <phillip.kruger@gmail.com>
Motivation:
See https://github.com/quarkusio/quarkus/issues/18503
When calling `setAll` with a MultiMap, the clear method is called first, but when calling it with Map, it's not.
Conformance:

clear set all method when calling with Map.

---

src/main/java/io/vertx/core/http/impl/HttpClientImpl.java
src/main/java/io/vertx/core/net/impl/NetClientImpl.java

Motivation:
When this finalizer is run it attempts to notify the empty promise on the IO thread. 
This can result in spawning a new IO thread, which will then inherit the
TCCL and ThreadGroup of the finalizer thread.
This can still be an issue if the client is not closed properly, but
currently there is no way to avoid it even if you do close it properly.
In addition the HTTP client finaliser is not necessary as client cleanup is achieved by the closeFuture listener that is either close directly or by the NetClient finaliser.

Don't create a Promise from the finalizer and un-necessary remove HTTP client finalizer

---

src/main/java/io/vertx/core/Context.java
src/main/java/io/vertx/core/impl/AbstractContext.java
src/main/java/io/vertx/core/impl/ContextInternal.java

Closes #3952
The Context interface used to restrict storage and retrieval of objects in context to String instances.
But the underlying storage permits to use instances of any type.
With this change, users can now store any type of objects in the context, without having to cast to ContextInternal and work with data maps directly.

Context: allow storage and retrieval of instances of any type

---

src/main/java/io/vertx/core/json/jackson/DatabindCodec.java
src/main/java/io/vertx/core/json/jackson/VertxModule.java

Add jackson module with vertx (de)serializers that can be re-use on the plug-able json SPI
Resolves #3972

Add jackson module with vertx (de)serializers

---

src/main/asciidoc/http.adoc
src/main/generated/io/vertx/core/http/WebSocketConnectOptionsConverter.java
src/main/java/examples/HTTPExamples.java
src/main/java/io/vertx/core/http/WebSocketConnectOptions.java
src/main/java/io/vertx/core/http/impl/Http1xClientConnection.java
src/main/java/io/vertx/core/http/impl/HttpClientImpl.java
src/test/java/io/vertx/core/http/WebSocketTest.java

In addition we document how to set a custom origin header value as it can be needed in some situations.
See #4121

Add an option to omit the origin header in the WebSocket client handshake request.

---

src/main/java/io/vertx/core/http/HttpClientRequest.java
src/main/java/io/vertx/core/http/impl/Http1xClientConnection.java
src/main/java/io/vertx/core/http/impl/Http2ClientConnection.java
src/main/java/io/vertx/core/http/impl/Http2UpgradedClientConnection.java
src/main/java/io/vertx/core/http/impl/HttpClientRequestImpl.java
src/main/java/io/vertx/core/http/impl/HttpClientResponseImpl.java
src/main/java/io/vertx/core/http/impl/HttpClientStream.java
src/test/java/io/vertx/core/http/Http1xTest.java
src/test/java/io/vertx/core/http/HttpTest.java

This change is necessary to support WebSocket https://datatracker.ietf.org/doc/html/draft-ietf-hybi-thewebsocketprotocol-00 in a reverse proxy as this version of WebSocket has a body

Do not close connection on http client request connect

---

src/main/java/io/vertx/core/net/KeyStoreOptionsBase.java
src/main/java/io/vertx/core/net/impl/KeyStoreHelper.java

Motivation:
PKCS#11 (Hardware Smart Cards) do not provide a keystore file path or buffer, instead they are expected to be loaded with a `null` inputstream.
Vert.x core on the other hand, assumed that `null` wasn't a valid value.
This PR attempts to fix this by allowing `null` to be used.

Allow loading PKCS#11 keystores (HSM)

---

src/main/java/io/vertx/core/http/impl/CookieImpl.java
src/main/java/io/vertx/core/http/impl/CookieJar.java
src/test/java/io/vertx/core/http/HttpTest.java

Motivation:
Fix #4187 
The problem:
Cookies can have 2 different representations:
1. A full server cookie with many attributes including `name`, `path`, `domain` and `value`
2. A user agent cookie just with `name` and `value`
When adding cookies to the cookie jar a comparator function will run over the cookies and match according to the spec. However one case wasn't taken in consideration. The case when a Cookie is populated from the user agent (the request includes a cookie) and the application adds a server cookie **with the same name** and other attributes.
In this case, as the attributes would not match, the 2 cookies would be counted as different. The example:
```
user-agent: XSRF-TOKEN=c359b44aef83415
server: XSRF-TOKEN=88533580000c314; …
```

Fix the cookie comparator to consider user-agent cookies correctly

---

pom.xml

Motivation:
Address: https://github.com/advisories/GHSA-jfh8-c2jp-5v3q
This is a provided dependency, users **can** only be affected if they explicitly provide the affected version to the runtime.

Bumping log4j: fixes https://github.com/advisories/GHSA-jfh8-c2jp-5v3q

---

pom.xml

Motivation:
log4j provides an additional release that disables JNDI by default to deal better with CVE-2021-44228 and completely remove support for Message Lookups.
* https://logging.apache.org/log4j/2.x/changes-report.html#a2.17.0
Target: master

Bump log4j to 2.17.0 - master

---

pom.xml

Motivation:
log4j provides an additional release that disables JNDI by default to deal better with CVE-2021-44228 and completely remove support for Message Lookups.
* https://logging.apache.org/log4j/2.x/changes-report.html#a2.17.0
Target: 4.1

Bump log4j to 2.17.0 - 4.1

---

pom.xml

Motivation:
log4j provides an additional release that disables JNDI by default to deal better with CVE-2021-44228 and completely remove support for Message Lookups.
* https://logging.apache.org/log4j/2.x/changes-report.html#a2.17.0
Target: 3.9

Bump log4j to 2.17.0 - 3.9

---

src/main/java/io/vertx/core/http/HttpServerRequest.java
src/test/java/io/vertx/core/http/Http1xTest.java

The implementation of the default invalid request handler only send a 400 response (bad_request) in some situation otherwise it will simply close the connection without sending a response message.
It should instead always send a response message (400 when nothing more specific can be sent) and then close the connection since the Netty decoder is in an un-recoverable state.
This commit changes the default invalid request handler to senda 400 response when no specific status code can be sent and then close the response.

Default invalid request handler enhancements.

---

src/main/java/io/vertx/core/http/RequestOptions.java
src/test/java/io/vertx/core/http/RequestOptionsTest.java

See https://github.com/eclipse-vertx/vert.x/issues/4232
Signed-off-by: Nils Renaud <renaud.nils@gmail.com>

Fix issue 4232 - Validate header names in RequestOptions

---

src/main/java/io/vertx/core/net/impl/ConnectionBase.java

See https://github.com/eclipse-vertx/vert.x/issues/4208
Signed-off-by: Nils Renaud <renaud.nils@gmail.com>
Motivation:
Using the Vert.x HTTP client, when a connection takes too long and reaches its time out, we get this exception : `io.vertx.core.VertxException: Connection was closed`
This does not help in understanding the connection timeout has been reached.
I would rather have a dedicated exception or a dedicated message in the `VertxException` but as Julien Viet stated [here](https://github.com/eclipse-vertx/vert.x/issues/4208#issuecomment-1003970313) : we can start with a debug log explaining the closure reason.
Conformance:
Please also make sure you …

Fix issue 4208 - Add more information on timed out connections

---

src/main/java/io/vertx/core/file/impl/FileResolverImpl.java

Motivation:
Fixes #4246 
Conformance:

[Issue-4246] Support vfs protocol in the default FileResolver implementation

---

src/main/java/io/vertx/core/http/impl/HttpClientPush.java
src/main/java/io/vertx/core/json/impl/JsonUtil.java
src/main/java/io/vertx/core/json/jackson/JacksonCodec.java
src/test/java/io/vertx/core/json/JacksonTest.java

Motivation:
* Fix potential NPE: `HttpClientPush`
* Fix invalid branch `Buffer` is also `Sharable` `JsonUtils`
* ~~Fix potential resource leak if `writeUTF` is called: `JacksonCodec`~~ (Jackson is well-behaved and always closes resources)

Fixing small potential bugs: NPE, Resource leak, invalid branch

---

src/main/java/io/vertx/core/http/HttpHeaders.java

Motivation:
pre-work for vertx-web
based on changes from https://github.com/netty/netty/pull/12070
waiting for netty 4.1.74

Add CORS Private Network headers

---

src/main/java/io/vertx/core/impl/ContextInternal.java
src/main/java/io/vertx/core/impl/DuplicatedContext.java
src/test/java/io/vertx/core/ContextTest.java

This method is helpful to know when you can access the context locals without risking a leak.
The method is only added to ContextInternal as it is an advanced use case.
When using context locals, it's important to know if the current context is a duplicated context or a root context.
Accessing locals from a root context is risky, as it could leak data between unrelated activities.
The current approach to do this check is using:
```java
return !(actual instanceof EventLoopContext || actual instanceof WorkerContext);
```
Using `instanceOf` is fragile in the sense that another Context implementation would break the check

Add a method to verify if a given Context is a duplicated context

---

src/main/java/io/vertx/core/MultiMap.java
src/main/java/io/vertx/core/http/impl/headers/HeadersMultiMap.java
src/test/java/io/vertx/core/http/headers/HeadersTestBase.java

Motivation:
When iterating over the HeadersMultiMap (as vertx-http-proxy) does,
it makes sense to not have to allocate a useless Map.Entry container.
This new method provides that functionality

Add forEach method on HeadersMultiMap that avoids object allocation

---

src/main/java/io/vertx/core/net/impl/ConnectionBase.java
src/test/java/io/vertx/core/http/HttpTest.java
src/test/java/io/vertx/core/net/NetTest.java

The ConnectionBase discards incoming message when the connection has been marked as closed, we should always accept such messages otherwise we might lose messages when a connection is closed proactively when a message read is in progress.
see #4285

ConnectionBase discards incoming message when it has been proactively closed

---

src/main/java/io/vertx/core/impl/launcher/commands/RunCommand.java
src/test/java/io/vertx/core/CustomerLauncherLowMemoryTest.java

Fixes #4291
This may happen if memory is low.
To prevent it, we must keep a reference to the hook around (see Javadoc of CloseHook).

Prevent beforeStoppingVertxHook from being GC-ed

---

src/main/java/io/vertx/core/impl/VertxImpl.java
src/main/java/io/vertx/core/impl/VertxInternal.java
src/main/java/io/vertx/core/impl/VertxThread.java
src/main/java/io/vertx/core/impl/btc/BlockedThreadChecker.java
src/main/java/io/vertx/core/impl/btc/BlockedThreadEvent.java
src/test/java/io/vertx/core/BlockedThreadCheckerTest.java
src/test/java/io/vertx/core/ContextTest.java
src/test/java/io/vertx/test/core/BlockedThreadWarning.java

Signed-off-by: Dan O'Reilly <oreilldf@gmail.com>
Adds support for customizing the implementation of BlockedThreadChecker, exposing an API that allows users to pass a callback that will be executed whenever a thread is blocked for longer than the allowed duration. To use the API, users have to call the `blockedThreadChecker()` getter on `VertxInternal`.
**Motivation:**
In my application, I want to be able to restart the JVM if thread stay blocked for an extended period of time, so that my application can potentially self-heal if something goes very wrong and a thread ends up stuck forever. It's currently not possible to do this (at least as far as I can tell). Adding this new API makes it possible.

Support customizing BlockedThreadChecker

---

src/main/java/io/vertx/core/eventbus/EventBusOptions.java
src/test/java/io/vertx/core/VertxOptionsTest.java

Motivation:
Fixes #4304 
Conformance:

[ISSUE-4304] clusterPublicPort should be ignored in toJson() result if     it is the default value

---

src/main/java/io/vertx/core/eventbus/EventBusOptions.java
src/test/java/io/vertx/core/VertxOptionsTest.java

Motivation:
Fixes #4304 in `4.2` branch
This is a back port of PR: #4305 
Conformance:

[4.2] - [ISSUE-4304] clusterPublicPort should be ignored in toJson() result if it is the default value

---

src/main/java/io/vertx/core/file/AsyncFile.java
src/main/java/io/vertx/core/file/AsyncFileLock.java
src/main/java/io/vertx/core/file/impl/AsyncFileImpl.java
src/main/java/io/vertx/core/file/impl/AsyncFileLockImpl.java
src/test/java/io/vertx/core/file/FileSystemTest.java

Closes #3856
The underlying AsynchronousFileChannel has methods to acquire file locks.

Expose file locking operations in AsyncFile

---

src/main/java/io/vertx/core/http/HttpClosedException.java
src/main/java/io/vertx/core/http/impl/Http1xClientConnection.java
src/main/java/io/vertx/core/http/impl/Http1xServerConnection.java
src/main/java/io/vertx/core/http/impl/Http1xServerResponse.java
src/main/java/io/vertx/core/http/impl/Http2ClientConnection.java
src/main/java/io/vertx/core/http/impl/Http2ConnectionBase.java
src/main/java/io/vertx/core/http/impl/Http2ServerConnection.java
src/main/java/io/vertx/core/http/impl/Http2ServerRequest.java
src/main/java/io/vertx/core/http/impl/Http2ServerResponse.java
src/main/java/io/vertx/core/http/impl/Http2ServerStream.java
src/main/java/io/vertx/core/http/impl/HttpNetSocket.java
src/main/java/io/vertx/core/http/impl/HttpUtils.java
src/main/java/io/vertx/core/http/impl/VertxHttp2ConnectionHandler.java
src/main/java/io/vertx/core/http/impl/VertxHttp2Stream.java
src/main/java/io/vertx/core/http/impl/WebSocketImplBase.java
src/test/java/io/vertx/core/http/Http2ClientTest.java
src/test/java/io/vertx/core/http/Http2ServerTest.java

Introduce an `HttpClosedException` that denotes when an HTTP connection has been closed that provides the HTTP go away status when an HTTP/2 connection has been closed intentionally by the remote endpoint. This is useful for the developer that can use it to determine if the remote endpoint was closed intentionally.

HTTP connection closed exception

---

src/main/java/io/vertx/core/http/impl/HttpUtils.java
src/test/java/io/vertx/core/http/Http1xTest.java
src/test/java/io/vertx/core/http/HttpTest.java

According to :
- https://datatracker.ietf.org/doc/html/rfc7230#section-3.2
- https://datatracker.ietf.org/doc/html/rfc5234#appendix-B.1
- https://datatracker.ietf.org/doc/html/rfc7540#section-10.3
For both HTTP/1.1 and HTTP/2.0 versions, bytes allowed for header value are : CR (0x0D), LF (0x0A), SP (0x20), HTAB (0x09) and ranges 0x21 to 0x7E and 0x80 to 0xFF (although the last range is considered as obsolete)
For more information, see the related issue : https://github.com/eclipse-vertx/vert.x/issues/4255
Signed-off-by: Nils Renaud <renaud.nils@gmail.com>

Fix issue 4255 - HTTP header values verifier is laxer than what's advised in the RFCs

---

src/main/java/io/vertx/core/http/WebSocketConnectOptions.java
src/main/java/io/vertx/core/http/impl/Http1xClientConnection.java
src/main/java/io/vertx/core/http/impl/HttpClientImpl.java
src/test/java/io/vertx/core/http/WebSocketTest.java

The HttpClient does not have a timeout for handshake completion. After the connection has been established with the server, we can set a timeout to fire if the server has not responded with the handshake response timely.
See #4323

WebSocket handshake completion timeout

---

src/main/java/io/vertx/core/http/impl/HttpUtils.java
src/test/java/io/vertx/core/http/Http1xTest.java
src/test/java/io/vertx/core/http/HttpTest.java

According to :
https://datatracker.ietf.org/doc/html/rfc7230#section-3.2
https://datatracker.ietf.org/doc/html/rfc5234#appendix-B.1
https://datatracker.ietf.org/doc/html/rfc7540#section-10.3
For both HTTP/1.1 and HTTP/2.0 versions, bytes allowed for header value are : CR (0x0D), LF (0x0A), SP (0x20), HTAB (0x09) and ranges 0x21 to 0x7E and 0x80 to 0xFF (although the last range is considered as obsolete)
For more information, see the related issue : https://github.com/eclipse-vertx/vert.x/issues/4255

Be exhaustive in invalid character for header name

---

src/main/java/io/vertx/core/shareddata/ClusterSerializable.java
src/main/java/io/vertx/core/shareddata/impl/Checker.java
src/main/java/io/vertx/core/shareddata/impl/ClusterSerializable.java
src/main/java/io/vertx/core/shareddata/impl/SharedDataImpl.java

This allows for smooth upgrades (mixing 4.3 and 4.2 nodes during migration)

Make ClusterSerializable extend impl.ClusterSerializable

---

src/main/java/io/vertx/core/http/impl/Http2ClientConnection.java
src/main/java/io/vertx/core/http/impl/Http2ServerConnection.java
src/main/java/io/vertx/core/http/impl/Http2UpgradedClientConnection.java
src/main/java/io/vertx/core/http/impl/HttpChannelConnector.java
src/main/java/io/vertx/core/http/impl/VertxHttp2ConnectionHandler.java
src/test/java/io/vertx/core/http/Http2ClientTest.java

The HttpClient assumes that after a directH2C connection (without HTTP upgrade) has been established with the server, it will always be successfully interacting with an H2 server.
When a server sends invalid data (from the client perspective), e.g a plain HTTP server, the client should handle this case and fail the connection result.
A connect future is added to VertxHttp2ConnectionHandler that is completed when the preface has been read and failed when a connection error happens before the settings have been read. When the client receives a corrupted settings frame, the connection error is triggered and the future is failed.
The connector now interacts with a promise of connection instead of the previous handler, removing the assumption the connection will always be established.
fixes …

HTPP client ignores direct H2C preface errors

---

src/main/java/io/vertx/core/impl/AbstractContext.java
src/main/java/io/vertx/core/impl/VertxImpl.java
src/test/java/io/vertx/core/TimerTest.java

When a timer is created from a non vertx thread, there can be a race with the timer task that executes before the internal timer task is added to the vertx timeout map. When it happens, the timer will not execute since this check is to check whether the task was cancelled by another thread.

Timers created outside event loop might not fire

---

src/test/java/io/vertx/core/spi/metrics/MetricsTest.java

The send timeout defined execrcized in the test is the same as the default timeout in waitUntil thus causing a race between the tested timeout and the test waitUntil timeout.
Motivation:
Explain here the context, and why you're making that change, what is the problem you're trying to solve.
Conformance:

Fix flaky timeout

---

src/main/java/io/vertx/core/file/impl/FileResolverImpl.java
src/test/java/io/vertx/core/file/impl/URLBundleFileResolverTest.java

Motivation:
Fixes: https://github.com/eclipse-vertx/vert.x/issues/4389
Conformance:

[Issue-4389] FileResolverImpl tries to unpack resources from bundle URL on each call for same file resolving

---

src/main/java/io/vertx/core/VertxOptions.java

Motivation:
Just removing an unnecessary semicolon
Conformance:

Remove unnecessary semicolon in VertxOptions

---

src/main/java/io/vertx/core/net/impl/KeyStoreHelper.java
src/main/java/io/vertx/core/net/impl/pkcs1/PrivateKeyParser.java
src/test/java/io/vertx/core/http/HttpTLSTest.java
src/test/java/io/vertx/core/net/KeyStoreHelperTest.java
src/test/java/io/vertx/core/net/impl/pkcs1/PrivateKeyParserTest.java
src/test/java/io/vertx/test/core/TestUtils.java

vert.x currently does not support reading PEM files that contain a EC private key.
However, ECC based keys are much smaller and easier to process than RSA based keys and therefore
are getting used more and more often, in particular when implementing TLS secured network servers that
need to be accessed by constrained clients (e.g. IoT devices).
The KeyStoreHelper has therefore been extended to support reading EC private keys from PEM files
as described in https://datatracker.ietf.org/doc/html/rfc5915#section-4

Support reading PEM file containing EC Private Key

---

src/main/java/io/vertx/core/http/impl/VertxHttp2ConnectionHandler.java
src/test/java/io/vertx/core/http/Http2ClientTest.java

When an HTTP/2 client connects, the failure will not be reported when the server disconnects without sending the initial settings

---

src/main/java/examples/FileSystemExamples.java

Otherwise, a file handle is kept open.

FileSystemExamples: close file after piping

---

src/main/java/io/vertx/core/eventbus/impl/EventBusImpl.java
src/test/java/io/vertx/core/eventbus/EventBusInterceptorTest.java

Fixes #4422
Otherwise, no inbound interceptor will ever be removed.

EventBus removeInboundInterceptor should use the INBOUND_INTERCEPTORS_UPDATER

---

src/main/java/io/vertx/core/eventbus/DeliveryOptions.java
src/test/java/io/vertx/core/eventbus/DeliveryOptionsTest.java

Motivation:
I've run into situations where using re-using a  `*VertxEBProxy` (produced by vertx-service-proxy) sends messages to the wrong consumer because the `DeliveryOptions.headers` contains multiple `action` values.
This ensures the `DeliveryOptions.headers` are properly cloned.

fix: ensure `DeliveryOptions.headers` are properly cloned

---

src/main/java/io/vertx/core/Vertx.java
src/main/java/io/vertx/core/impl/VertxImpl.java
src/test/java/io/vertx/core/TimerTest.java

Motivation:
add a new parameter `initialDelay` in `setPeriodic` method of `Vertx` https://github.com/eclipse-vertx/vert.x/issues/4436

Feature: setPeriodic add argument initialDelay parameter

---

src/main/java/io/vertx/core/file/impl/FileSystemImpl.java

The following bad smells are refactored:
A non-protected constructor in an abstract class is not needed because only subclasses can be instantiated
A local variable is declared and in the next line returned. This can be replaced by an instant return.
- Constructor `io.vertx.core.file.impl.FileSystemImpl$BlockingAction()` is now protected instead of public
- Inlined return statement return `io.vertx.core.buffer.Buffer.buffer(bytes)`
Motivation:
I fixed some easy code style problems an IDE like JetBrains IntelliJ finds. This does not alter any functionality and only increases the code quality.

refactor: fix code style issues

---

src/main/java/io/vertx/core/Vertx.java

Avoids breaking implementations that do not have the method yet.
Follows-up on #4450

Add default implementation for new periodic timer methods in Vertx

---

src/main/java/io/vertx/core/logging/Log4j2LogDelegateFactory.java
src/main/java/io/vertx/core/logging/LoggerFactory.java
src/test/java/io/vertx/core/impl/logging/NoExceptionInInitializerErrorTest.java
src/test/resources/log4j2-test.properties

Fixes reactiverse/reactiverse-contextual-logging#52
Otherwise, a logger extension might use Vert.x classes before they are fully initialized.

Do not log before being LoggerFactory is fully initialized

---

src/main/asciidoc/futures.adoc

Motivation:
I was unable to determine from the existing documentation if the order of results on a `CompositeFuture` are guaranteed to be the same order passed into `CompositeFuture.all` or `CompositeFuture.any`. After checking with @vietj via Discord, the order **IS** guaranteed, so I wanted to clarify the documentation.
This PR makes a small change to the documentation in `core` to explain that the ordering of results should always match the order of the futures passed to `CompositeFuture.all` or `CompositeFuture.any`.

Clarify CompositeFuture resultAt behavior guarntees

---

src/main/java/io/vertx/core/net/impl/SSLHelper.java
src/test/java/io/vertx/core/net/NetTest.java

Motivation:
Fixes: #4487 
Conformance:
This PR proposes to specify a default SslContextFactory (SslProvider.JDK) when there is no TLS configuration set

[ISSUE-4487] NPE when NetSocket.upgradeToSsl() is called if no TLS configuration in NetClientOptions

---

src/main/java/io/vertx/core/http/impl/EndpointKey.java
src/test/java/io/vertx/core/http/impl/EndPointKeyTest.java

Motivation:
When I read the changes in EndPointKey:
https://github.com/eclipse-vertx/vert.x/blob/0e3b061c463ebc357f8f18a377218729218fa497/src/main/java/io/vertx/core/http/impl/EndpointKey.java#L71-L74
I think it is a typo, it should return here.
Conformance:

Fix hashCode in EndpointKey

---

src/main/asciidoc/http.adoc

Motivation:
The Gradle configuration instructions of Brotli4j in the docs are incomplete and lead to class initialization errors.
Conformance:

Improve the Gradle configuration instructions of Brotli4j in the docs

---

src/main/java/io/vertx/core/http/impl/Http1xServerRequest.java
src/main/java/io/vertx/core/http/impl/Http2ServerConnection.java
src/main/java/io/vertx/core/http/impl/Http2ServerRequest.java
src/main/java/io/vertx/core/http/impl/Http2ServerResponse.java
src/main/java/io/vertx/core/http/impl/Http2ServerStream.java
src/main/java/io/vertx/core/http/impl/Http2ServerStreamHandler.java
src/main/java/io/vertx/core/http/impl/HttpServerRequestInternal.java
src/main/java/io/vertx/core/http/impl/HttpServerRequestWrapper.java

Make `HttpServerRequestInternal` an abstract class to avoid hotspot type pollution, since this interface extends HttpServerRequest and can be implemented multiple times.

Abstract http server request internal

---

src/main/asciidoc/index.adoc

Motivation:
The vertx-core docs miss some code formatting in the [Rules for mapping a verticle name to a verticle factory](https://vertx.io/docs/vertx-core/java/#_rules_for_mapping_a_verticle_name_to_a_verticle_factory) section.
This PRs addresses it and formats the relevant parts in this section as code.

Fix code formatting in verticle mapping docs

---

src/main/java/io/vertx/core/net/KeyCertOptions.java
src/main/java/io/vertx/core/net/KeyManagerFactoryOptions.java
src/main/java/io/vertx/core/net/TrustManagerFactoryOptions.java
src/main/java/io/vertx/core/net/TrustOptions.java

TrustOptions class already contains a static `wrap()` method to create an instance using the provided `TrustManager` instance. The same is true for `KeyCertOptions.wrap(KeyManager)`. If we want to use several trust or key managers, we need to deal with `Trust/KeyManagerFactory`.
This PR contains 2 more convenient `wrap()` methods which receive `TrustManagerFactory` or `KeyManagerFactory`. The changes are pretty compact so far as`Trust/KeyManagerFactoryOptions` already have suitable package-private constructors.

Add convenient Trust/KeyCertOptions wrap() methods

---

src/main/java/io/vertx/core/http/impl/Http2UpgradeClientConnection.java
src/main/java/io/vertx/core/http/impl/HttpChannelConnector.java
src/test/java/io/vertx/core/http/Http2ClientTest.java

The HTTP upgrade to H2C connection does not handle properly upgrade rejections leading to retrying an upgrade for every subsequent request on the same connection and accumulating upgrade request handler in the channel pipeline.
The HTTP upgrade connection after an upgrade (succesfull or not) should always delegate to the the current connection (HTTP/1 or HTTP/2) the creation of streams and avoid using upgrading stream.
The HTTP upgrade stream should also cleanup the temporary upgrade request handler from the pipeline after the upgrade.
see also #4476

Clear test upgrade to HTTP/2 fixes

---

src/main/java/io/vertx/core/http/impl/Http1xServerResponse.java
src/test/java/io/vertx/core/http/HttpTest.java

Fixes #4546
This aligns behaviors of Http 1 and Http2 servers.

Response#end should throw ISE if used inside headers end handler

---

src/main/asciidoc/net.adoc
src/main/generated/io/vertx/core/net/SSLOptionsConverter.java
src/main/java/examples/NetExamples.java
src/main/java/io/vertx/core/http/HttpClient.java
src/main/java/io/vertx/core/http/HttpServer.java
src/main/java/io/vertx/core/http/impl/Http1xServerConnection.java
src/main/java/io/vertx/core/http/impl/Http1xUpgradeToH2CHandler.java
src/main/java/io/vertx/core/http/impl/HttpClientImpl.java
src/main/java/io/vertx/core/http/impl/HttpServerImpl.java
src/main/java/io/vertx/core/http/impl/HttpServerWorker.java
src/main/java/io/vertx/core/http/impl/SharedHttpClient.java
src/main/java/io/vertx/core/net/NetClient.java
src/main/java/io/vertx/core/net/NetServer.java
src/main/java/io/vertx/core/net/SSLOptions.java
src/main/java/io/vertx/core/net/TCPSSLOptions.java
src/main/java/io/vertx/core/net/impl/ChannelProvider.java
src/main/java/io/vertx/core/net/impl/NetClientImpl.java
src/main/java/io/vertx/core/net/impl/NetServerImpl.java
src/main/java/io/vertx/core/net/impl/NetSocketImpl.java
src/main/java/io/vertx/core/net/impl/SSLHelper.java
src/main/java/io/vertx/core/net/impl/SslContextProvider.java
src/main/java/io/vertx/core/net/impl/TCPServerBase.java
src/test/java/io/vertx/core/http/HttpTLSTest.java
src/test/java/io/vertx/core/net/SSLHelperTest.java
src/test/java/io/vertx/it/SSLEngineTest.java

Provides support for reloading of a TCP server or client, a new `SSLOptions` class has been introducing which captures the reloadable part of the current configuration.
Reconfiguration is explicit and requires a call to a new `updateSSLOptions` method that loads and validates the configuration and then updates the SSL context when it succeeds. 
```java
vertx.setPeriodic(REFRESH_PERIOD, id -> {
Optional<SSLOptions> options = refreshUpdatedConfiguration();
if (options.isPresent()) {
Future<Void> fut = server.updateSSLOptions(options.get());
}
});
```

Provide SSLOptions to allow update the certificate of a TCP server or client

---

src/main/generated/io/vertx/core/net/OpenSSLEngineOptionsConverter.java
src/main/java/io/vertx/core/net/JdkSSLEngineOptions.java
src/main/java/io/vertx/core/net/OpenSSLEngineOptions.java
src/main/java/io/vertx/core/net/SSLEngineOptions.java
src/main/java/io/vertx/core/net/impl/SSLHelper.java
src/main/java/io/vertx/core/net/impl/SslContextProvider.java
src/test/java/io/vertx/core/http/HttpTLSTest.java
src/test/java/io/vertx/core/net/NetTest.java

By default SSL blocking operations are executed on the event-loop, it should be possible to execute SSL blocking operations on the internal worker pool of Vert.x.

SSL blocking operations can now be executed on the vertx internal worker pool

---

src/main/java/io/vertx/core/net/impl/pool/CombinerExecutor.java
src/main/java/io/vertx/core/net/impl/pool/Task.java
src/test/java/io/vertx/core/net/impl/pool/ConnectionPoolTest.java

The connection pool post action task execution can lead to a stack overflow since those actions are simply executed by the owner thread after pool tasks execution. Post actions task should be trampolined to avoid this case.

Connection pool post task stack overflow

---

src/main/java/io/vertx/core/net/impl/pool/CombinerExecutor.java
src/main/java/io/vertx/core/net/impl/pool/Task.java
src/test/java/io/vertx/core/net/impl/pool/ConnectionPoolTest.java

The connection pool post action task execution can lead to a stack overflow since those actions are simply executed by the owner thread after pool tasks execution. Post actions task should be trampolined to avoid this case.

Connection pool post task stack overflow fix

---

src/main/java/io/vertx/core/logging/SLF4JLogDelegate.java

See #4582
Otherwise, we cannot delegate to loggers written in Kotlin (which does not allow null variable arguments).

Avoid invoking SLF4J logger API with null parameters

---

src/main/java/io/vertx/core/http/impl/Http1xClientConnection.java
src/main/java/io/vertx/core/http/impl/Http2ClientConnection.java
src/test/java/io/vertx/core/spi/tracing/HttpTracerTestBase.java

See #4572
Otherwise, the tracing implementation may try to add invalid header name/value directly to Netty headers.

Tracer call for HTTP Client should use headers adaptors

---

src/main/java/io/vertx/core/http/impl/HttpUtils.java
src/test/benchmarks/io/vertx/benchmarks/HeadersContainsBenchmark.java
src/test/benchmarks/io/vertx/benchmarks/HeadersEncodeBenchmark.java
src/test/benchmarks/io/vertx/benchmarks/HeadersSetBenchmark.java
src/test/benchmarks/io/vertx/benchmarks/HeadersUtils.java

In most of our benchmarks, HTTP validation is not enabled and it doesn't make easy to spot which cost it has.
This PR is addressing this by adding special flags to both test it with/without ASCII values and it improves it by removing branches out of its validation path.

Http validation improvements

---

src/main/java/io/vertx/core/http/impl/HttpUtils.java
src/main/java/io/vertx/core/net/impl/URIDecoder.java

Http parsing and Vertx-web routing can improve performance on common path.
This changes:
- makes `decodeURIComponent` inlinable (but moving away unlikely paths)
- speedup `decodeURIComponent`  for the `plus = false` case, leveraging on `indexOf(char)` intrinsic (see https://chriswhocodes.com/hotspot_intrinsics_openjdk11.html)
- speedup string concatenation on `normalizePath` with https://bugs.openjdk.org/browse/JDK-8085796
- speedup `normalizePath` adding a zero garbage fast-path and reducing bytecode size

Improved path normalization and URI decoding

---

src/main/generated/io/vertx/core/net/OpenSSLEngineOptionsConverter.java
src/main/java/io/vertx/core/net/JdkSSLEngineOptions.java
src/main/java/io/vertx/core/net/OpenSSLEngineOptions.java
src/main/java/io/vertx/core/net/SSLEngineOptions.java
src/main/java/io/vertx/core/net/impl/SSLHelper.java
src/test/java/io/vertx/core/http/HttpTLSTest.java
src/test/java/io/vertx/core/net/NetTest.java

SSL blocking operations can now be executed on the vertx internal worker pool, the default remaining on event-loop thread.
The configuration is on the SSLEngineOptions as this configures how the SSLEngine behaviour.

 SSL blocking operations can now be executed on the vertx internal worker pool

---

src/main/java/io/vertx/core/parsetools/impl/JsonParserImpl.java
src/test/java/io/vertx/core/parsetools/JsonParserTest.java

The JsonParser class does not progress as much as it could when the processing faulty input.
When the JsonParser process malformed input, it does halt the parsing and handle the error leaving unprocessed tokens in the underlying Jackson parser. These tokens will be processed when the JsonParser handle another input. When the Jackson parser fails we handle the error and then give up and reported behavior is a consequence.

JsonParser should process fully the possible events when processing malformed input

---

src/main/java/io/vertx/core/impl/VertxImpl.java
src/main/java/io/vertx/core/impl/VertxThread.java
src/main/java/io/vertx/core/impl/btc/BlockedThreadChecker.java
src/main/java/io/vertx/core/impl/btc/ThreadInfo.java
src/test/java/io/vertx/core/ContextTest.java
src/test/java/io/vertx/core/VertxTest.java

The blocked thread checker implementation leak Vert.x named worker threads that are no longer available (due to shared worker executor disposal or verticle named worker pool undeployment).

Blocked thread checker named worker threads leak

---

src/main/java/io/vertx/core/http/impl/Http1xServerConnection.java
src/main/java/io/vertx/core/http/impl/Http1xUpgradeToH2CHandler.java
src/main/java/io/vertx/core/http/impl/HttpServerImpl.java
src/main/java/io/vertx/core/http/impl/HttpServerWorker.java
src/main/java/io/vertx/core/net/impl/ChannelProvider.java
src/main/java/io/vertx/core/net/impl/NetClientImpl.java
src/main/java/io/vertx/core/net/impl/NetServerImpl.java
src/main/java/io/vertx/core/net/impl/NetSocketImpl.java
src/main/java/io/vertx/core/net/impl/SSLHelper.java
src/main/java/io/vertx/core/net/impl/SslChannelProvider.java
src/main/java/io/vertx/core/net/impl/SslContextProvider.java
src/main/java/io/vertx/core/net/impl/TCPServerBase.java
src/main/java/io/vertx/core/net/impl/VertxSniHandler.java
src/test/java/io/vertx/core/http/HttpTLSTest.java
src/test/java/io/vertx/core/net/SSLHelperTest.java
src/test/java/io/vertx/it/SSLEngineTest.java

- refactor the code to decouple the `SslContext` creation and SSL handlers creation
- the SNI mapping function should be executed on the internal worker pool
- SNI SSL engine should use the internal worker pool when configured to do so
- cleanup `VertxSniHandler` handshake timeout since now it is supported in `SniHandler`

SSL improvements

---

src/main/java/io/vertx/core/net/JdkSSLEngineOptions.java
src/main/java/io/vertx/core/net/OpenSSLEngineOptions.java

Some `SSLEngineOptions` subclasses's constructor don't call super, this should be fixed.

Fix SSLEngineOptions subclasses constructors not calling super

---

src/main/java/io/vertx/core/http/HttpClientRequest.java
src/main/java/io/vertx/core/http/HttpServerResponse.java
src/main/java/io/vertx/core/http/impl/Http1xClientConnection.java
src/main/java/io/vertx/core/http/impl/Http1xServerConnection.java
src/main/java/io/vertx/core/http/impl/Http1xServerResponse.java
src/main/java/io/vertx/core/http/impl/Http2ClientConnection.java
src/main/java/io/vertx/core/http/impl/Http2ServerResponse.java
src/main/java/io/vertx/core/http/impl/Http2UpgradeClientConnection.java
src/main/java/io/vertx/core/http/impl/HttpClientRequestImpl.java
src/main/java/io/vertx/core/http/impl/HttpClientRequestPushPromise.java
src/main/java/io/vertx/core/http/impl/HttpClientStream.java
src/test/java/io/vertx/core/http/Http2ServerTest.java
src/test/java/io/vertx/core/http/HttpTest.java

Motivation:
Currently it's not possible to send an early-hints response (103 Early Hints (RFC 8297))

Implement 103 early hints

---

src/test/java/io/vertx/core/spi/metrics/MetricsTest.java

Sometimes the build fails with this error:
MetricsTest.testThreadPoolMetricsWithInternalExecuteBlocking:1010->AsyncTestBase.assertTrue:378 null
Switching from assertTrue to assertWaitUntil mitigates the race condition.

Await hadIdle in testThreadPoolMetricsWithInternalExecuteBlocking

---

src/main/java/io/vertx/core/streams/impl/InboundBuffer.java

InboundBuffer's allocation create 16 pending entries by default while it could delay it when the initial size information
is available.
This change is going to lazy allocate it: it's less elegant due to the many null checks, but it's effective to reduce allocations in the hot paths.
Subsequent allocations will make uses of the ArrayDeque enlarging strategy but starting with a much lower number (double capacity, but starting from 1 instead of 16)

Reduce InboundBuffer pending queue's allocation pressure

---

src/main/java/io/vertx/core/impl/VertxImpl.java

Swap the init order of log and nonVertxContextDispatch so that the log init can access the Context.
Fixes #4611.

VertxImpl init order for logger that reads Context

---

src/main/java/io/vertx/core/http/impl/Http1xConnectionBase.java
src/main/java/io/vertx/core/net/impl/ConnectionBase.java
src/main/java/io/vertx/core/net/impl/NetSocketImpl.java

Metrics size of connection messages are computed even though no metrics is configured to report to. We can refactor the internal API a bit to only compute the message size when it shall be effectively reported.

Optimise connection metrics reporting

---

src/main/java/io/vertx/core/net/impl/ConnectionBase.java

It allow to have the same performance of no metrics configured, improving the inlining chances when no metrics reporting is configured.

Favour inlining without metrics reporting

---

src/main/generated/io/vertx/core/http/HttpClientOptionsConverter.java
src/main/java/io/vertx/core/http/HttpClientOptions.java
src/main/java/io/vertx/core/http/impl/Http2UpgradeClientConnection.java
src/main/java/io/vertx/core/http/impl/HttpChannelConnector.java
src/test/java/io/vertx/core/http/Http2ClientTest.java

Vert.x HTTP client initially sends an HTTP/1.1 request to the origin server while perfoming the HTTP upgrade to h2c when establishing an h2c connection without prior knowledge. This cause the first request to use HTTP/1.1 and subsequent requests using the same connection to use HTTP/2.
This adds an option to have the client perform a preflight OPTIONS request before, consequently the client will always provide an HTTP/2 request since the preflight request will establish the connection.
fixes #4638

Vert.x HTTP h2c client gets an option to ensure client connection is always HTTP/2 when using h2c

---

src/main/generated/io/vertx/core/http/HttpServerOptionsConverter.java
src/main/generated/io/vertx/core/http/WebSocketConnectOptionsConverter.java
src/main/generated/io/vertx/core/net/NetClientOptionsConverter.java
src/main/generated/io/vertx/core/net/NetServerOptionsConverter.java
src/main/java/io/vertx/core/http/HttpServerOptions.java
src/main/java/io/vertx/core/http/WebSocketBase.java
src/main/java/io/vertx/core/http/WebSocketConnectOptions.java
src/main/java/io/vertx/core/http/impl/Http1xClientConnection.java
src/main/java/io/vertx/core/http/impl/Http1xServerConnection.java
src/main/java/io/vertx/core/http/impl/HttpClientImpl.java
src/main/java/io/vertx/core/http/impl/ServerWebSocketImpl.java
src/main/java/io/vertx/core/http/impl/WebSocketImpl.java
src/main/java/io/vertx/core/http/impl/WebSocketImplBase.java
src/main/java/io/vertx/core/net/NetClientOptions.java
src/main/java/io/vertx/core/net/NetServerOptions.java
src/main/java/io/vertx/core/net/NetSocket.java
src/main/java/io/vertx/core/net/impl/NetClientImpl.java
src/main/java/io/vertx/core/net/impl/NetServerImpl.java
src/main/java/io/vertx/core/net/impl/NetSocketImpl.java
src/test/java/io/vertx/core/http/WebSocketTest.java
src/test/java/io/vertx/core/net/NetTest.java

Disable writeHandlers by default

---

src/main/asciidoc/net.adoc

https: //www.oracle.com/java/technologies/javase/8-whats-new.html "Hardware intrinsics were added to use Advanced Encryption Standard (AES)."
https: //openjdk.org/jeps/164 "JEP 164: Leverage CPU Instructions for AES Cryptography"
https: //docs.oracle.com/javase/9/whatsnew/#d1373e94 "Improves performance ranging from 34x to 150x for AES/GCM/NoPadding"
https: //openjdk.org/jeps/246 "JEP 246: Leverage CPU Instructions for GHASH and RSA"

Openssl no longer has much better performance

---

pom.xml
src/main/java/io/vertx/core/http/impl/Http1xServerConnection.java
src/main/java/io/vertx/core/http/impl/VertxHttpRequestDecoder.java
src/main/java/io/vertx/core/http/impl/VertxHttpResponseEncoder.java
src/test/benchmarks/io/vertx/core/http/impl/HttpServerHandlerBenchmark.java

JDK-8180450 has forced Netty http encoding/decoding to order type checks in order to save a huge scalability hit.
And still this is not enough, perf-wise: vertx, as a Netty users, still consume Netty types and cannot ignore such ordering, or would have a similar performance hit.
Moreover, there are cases (outlined on https://github.com/TechEmpower/FrameworkBenchmarks/pull/7942) where the existing JDK mechanism for interface type checks waste CPU resources, but the "constrained" vertx http types can save it to happen both performing exact class type checks and/or instanceof vs concrete and known types.

Save expensive interface type checks (related JDK-8180450 and https://github.com/netty/netty/issues/12708)

---

src/main/java/io/vertx/core/datagram/impl/PacketWriteStreamImpl.java
src/main/java/io/vertx/core/file/impl/AsyncFileImpl.java
src/main/java/io/vertx/core/http/HttpClientRequest.java
src/main/java/io/vertx/core/http/HttpServerResponse.java
src/main/java/io/vertx/core/http/WebSocketBase.java
src/main/java/io/vertx/core/http/impl/Http1xServerResponse.java
src/main/java/io/vertx/core/http/impl/Http2ServerResponse.java
src/main/java/io/vertx/core/http/impl/HttpClientRequestImpl.java
src/main/java/io/vertx/core/http/impl/HttpClientRequestPushPromise.java
src/main/java/io/vertx/core/http/impl/HttpClientStream.java
src/main/java/io/vertx/core/http/impl/HttpNetSocket.java
src/main/java/io/vertx/core/http/impl/WebSocketImplBase.java
src/main/java/io/vertx/core/net/NetSocket.java
src/main/java/io/vertx/core/net/impl/NetSocketImpl.java
src/main/java/io/vertx/core/streams/WriteStream.java
src/test/java/io/vertx/core/streams/PumpTest.java
src/test/java/io/vertx/core/streams/WriteStreamTest.java
src/test/java/io/vertx/test/fakestream/FakeStream.java
src/test/java/io/vertx/test/fakestream/FakeStreamTest.java

Remove the callback methods in the `WriteStream` interface. This is a preliminary step of the vertx 5 callback removal. This one is specifically done ahead because other vertx components implement the `WriteStream` interface.

Remove callback methods from the WriteStream interface

---

src/main/java/io/vertx/core/json/JsonArray.java
src/main/java/io/vertx/core/json/JsonObject.java
src/main/java/io/vertx/core/json/impl/Inspector.java
src/main/java/io/vertx/core/json/impl/JsonUtil.java
src/test/java/io/vertx/core/LauncherTest.java
src/test/java/io/vertx/core/json/JsonArrayTest.java
src/test/java/io/vertx/core/json/JsonCodecTest.java
src/test/java/io/vertx/core/json/JsonInspectorTest.java
src/test/java/io/vertx/core/json/JsonObjectTest.java
src/test/java/io/vertx/it/CustomJsonCodecTest.java
src/test/java/io/vertx/it/JsonCodecTest.java
src/test/java/io/vertx/it/JsonTest.java

Motivation:
Vert.x JsonObject/JsonArray `toString()` methods call the codec encode method. While this is handy for debugging it has several drawbacks. When dealing with very large objects, a log statement or debug can incur on some performance penalty. Worse, when debugging, IDEs will try to show you a string representation of the object so it can impact your productivity.
When debugging circular references, you will notice that the debugger will constantly throw `StackOverflowError` slowing your IDE to a non use state.
This PR introduces a breaking change in the `toString()` methods of `JsonObject` and `JsonArray`, note that this should not impact most users as JSON encoding should always be done with `encode()` or `encodePrettilly()`.
The changes try to follow what other runtimes do. …

Update the JSON toString() to allow better debugging

---

src/main/java/io/vertx/core/eventbus/impl/clustered/ClusteredMessage.java
src/test/java/io/vertx/core/eventbus/ClusteredEventBusTest.java

**Motivation:**
This commit fixes an issue with message header encoding/decoding when using a clustered event bus. Without this change, headers have the potential to be lost when decoding. The reason for the header loss is that when encoding headers, the header length that gets written is based upon the `.size()` method. This method is based on the number of _unique_ header names. If a `MultiMap` has a header that contains more than one value, this causes a problem. The problem manifests itself during decoding. During decoding, the number of headers is read and then subsequently iterated over:
```
...
int numHeaders = wireBuffer.getInt(headersPos);
headersPos += 4;
headers = MultiMap.caseInsensitiveMultiMap();
for (int i = 0; i < numHeaders; i++) {
...
```
If there are any headers with …

use entries().size() when encoding headers to fix missing headers

---

src/main/java/io/vertx/core/http/impl/WebSocketImplBase.java
src/test/java/io/vertx/core/http/WebSocketTest.java

Motivation:
Addresses #4660
This is the simplest change - always increase the fetch whenever there's a ping or pong.  However the pong case is debatable since there is the ability to set a pong handler - if someone is already handling this situation in their pong handler, then this change will further increase the fetch.  
Conformance:

fix #4660: incrementing the fetch for ping/pong

---

src/main/asciidoc/streams.adoc
src/main/java/io/vertx/core/TimeoutStream.java
src/main/java/io/vertx/core/Vertx.java
src/main/java/io/vertx/core/datagram/DatagramSocket.java
src/main/java/io/vertx/core/http/HttpServer.java
src/main/java/io/vertx/core/net/NetServer.java

A few streams were introduced in Vert.x 3 for the only purpose of RX like generated APIs. It turns out that such benefits are low compared to the cost of cluttering the API. These streams will be removed in Vert.x 5

Deprecate un-necessary streams

---

src/main/java/io/vertx/core/eventbus/impl/clustered/ClusteredMessage.java
src/test/java/io/vertx/core/eventbus/ClusteredEventBusTest.java

**Motivation:**
This pull request cherry-picks to `master` the commit from  #4664 made on the `4.x` branch that fixes an issue which caused missing headers under certain circumstances.
**Conformance:**

Fix missing headers bug when using clustered event bus

---

src/main/java/io/vertx/core/net/KeyCertOptions.java
src/main/java/io/vertx/core/net/KeyManagerFactoryOptions.java
src/main/java/io/vertx/core/net/KeyStoreOptionsBase.java
src/main/java/io/vertx/core/net/PemKeyCertOptions.java
src/main/java/io/vertx/core/net/impl/KeyStoreHelper.java
src/main/java/io/vertx/core/net/impl/SSLHelper.java
src/main/java/io/vertx/core/net/impl/SslContextProvider.java

When using SNI, SslContextProvider will always convert the mapped key manager to a key manager factory, that can be an expensive operation.
This conversion of the key manager to a factory has been moved to the KeyCertOptions interface as a default method, to let implementations of this interface override it with caching. The default Vert.x implementation based on KeyStoreOptionsBase caches the created factories.

Create SNI KeyManagerFactory in KeyCertOptions instead of SslContextProvider so it can be cached

---

src/main/java/io/vertx/core/net/KeyCertOptions.java
src/main/java/io/vertx/core/net/KeyManagerFactoryOptions.java
src/main/java/io/vertx/core/net/KeyStoreOptionsBase.java
src/main/java/io/vertx/core/net/PemKeyCertOptions.java
src/main/java/io/vertx/core/net/impl/KeyStoreHelper.java
src/main/java/io/vertx/core/net/impl/SSLHelper.java
src/main/java/io/vertx/core/net/impl/SslContextProvider.java
src/test/java/io/vertx/core/http/HttpTLSTest.java

When using SNI, SslContextProvider will always convert the mapped key manager to a key manager factory, that can be an expensive operation.
This conversion of the key manager to a factory has been moved to the KeyCertOptions interface to let implementations of this interface implement it with caching. Now KeyStoreOptionsBase caches the created factories.
This is a breaking of the KeyCertOptions SPI due to the removal of keyManagerMapper method removal.

Create SNI KeyManagerFactory in KeyCertOptions instead of SslContextProvider so it can be cached 

---

src/main/java/io/vertx/core/net/KeyCertOptions.java

This way there is no need to implement this method anymore and KeyCertOptions implementations will not get a compilation warning.

4700 Provide a default implementation for KeyCertOptions.keyManagerMapper

---

src/main/asciidoc/futures.adoc
src/main/java/examples/CoreExamples.java
src/main/java/io/vertx/core/CompositeFuture.java
src/main/java/io/vertx/core/Future.java

Deprecate `CompositeFuture` static methods and provide alternatives on the `Future` type that declares generic types using wildcard instead of using raw types. Raw types were necessary because of a limitation with the code generator when `Future` / `CompositeFuture` were generated types. Since this limitation is gone we can provide better declarations.
Deprecated methods are removed in Vert.x 5 : https://github.com/vert-x3/wiki/wiki/4.4.3-Deprecations-and-breaking-changes

Introduce generic version of CompositeFuture static methods

---

src/main/java/io/vertx/core/http/impl/HttpClientImpl.java
src/main/java/io/vertx/core/net/impl/pool/ConnectionManager.java
src/test/java/io/vertx/core/VertxTest.java
src/test/java/io/vertx/core/http/Http1xTest.java

The switch to Java cleaners has made HttpClient collection close request in progress aggressively. In some tests this can lead to closing the request because the test method is async and the HTTP client created within the method has been collected.
The new behavior soften this and will first shutdown the pool forbidding any new request to be made and then finally close it when all connections have been closed.

Make HTTP client collection be less aggressive with request in progress

---

src/test/java/io/vertx/test/core/AsyncTestBase.java
src/test/java/io/vertx/test/core/AsyncTestBaseTest.java

The vertx test suite forbids failures to be reported from any thread after the test is considered as completed. While this is a good behavior, it seems too restrictive from the main thread (thus coordinating the thread and reporting the erros to the runner) and prevents from writing assertions after the test has completes, e.g use AsyncTestBase methods to assert a predicate after an await() call.

Allow late failure from main thread.

---

src/main/java/io/vertx/core/eventbus/impl/codecs/ClusterSerializableCodec.java
src/main/java/io/vertx/core/impl/JavaVerticleFactory.java
src/main/java/io/vertx/core/impl/VertxBuilder.java
src/main/java/io/vertx/core/logging/LoggerFactory.java

Motivation:
Quoting from the Javadocs 
> Deprecated
> This method propagates any exception thrown by the nullary constructor, including a checked exception. Use of this method effectively bypasses the compile-time exception checking that would otherwise be performed by the compiler. The Constructor.newInstance method avoids this problem by wrapping any exception thrown by the constructor in a (checked) InvocationTargetException.
> The call
>  clazz.newInstance()
> can be replaced by
>  clazz.getDeclaredConstructor().newInstance()
> The latter sequence of calls is inferred to be able to throw the additional exception types InvocationTargetException and NoSuchMethodException. Both of these exception types are subclasses of ReflectiveOperationException.

Use class declared constructor

---

src/main/java/io/vertx/core/impl/transports/EpollTransport.java

Motivation:
These constants have been deprecated

Migrate to new TCP Fast Open constants

---

src/main/java/io/vertx/core/net/OpenSSLEngineOptions.java

Motivation:
The existing usage is deprecated 
>     /**
>      * Returns {@code true} if the used version of openssl supports
>      * <a href="https://tools.ietf.org/html/rfc7301">ALPN</a>.
>      *
>      * @deprecated use {@link SslProvider#isAlpnSupported(SslProvider)} with {@link SslProvider#OPENSSL}.
>      */
>     @Deprecated
>     public static boolean isAlpnSupported() {
>         return version() >= 0x10002000L;
>
>    }

Update `isAlpnAvailable`  method

---

src/main/java/io/vertx/core/eventbus/impl/EventBusImpl.java
src/main/java/io/vertx/core/impl/DeploymentManager.java

Motivation:
Remove the deprecated usages.
Result:
Clean code.

=core Remove deperecated usages of CompositeFuture.

---

src/main/java/io/vertx/core/net/impl/pool/CombinerExecutor.java
src/main/java/io/vertx/core/net/impl/pool/Task.java

Thanks to make the list single linked, fixing GC nepotism is now simpler, but this has forced to remove `pollAndExecute`
because we need 2 state variables to hold the current head/tail of the task list.
For this same reason, we are forced to define an additional `InProgressHead` class to keep up to date the current head in order to allow reentrant tasks to keep on being added to the current one.

Use fast thread local and fix GC nepotism (Fixes #4749)

---

src/main/java/io/vertx/core/net/impl/pool/EndpointResolver.java
src/main/java/io/vertx/core/spi/resolver/AddressResolver.java
src/test/java/io/vertx/core/http/ResolvingHttpClientTest.java

The AddressResolver interface now defines a method to check the validity of the resolver state, the endpoint now can call this method before obtaining a socket address and refresh the result when the state is stale.
This facilitates the implementation of resolvers returning results with a TTL.

Address resolver state validity check

---

src/main/java/io/vertx/core/net/impl/pool/CombinerExecutor.java
src/main/java/io/vertx/core/net/impl/pool/Task.java

* Use fast thread local and fix GC nepotism (Fixes #4749)
* Replace order of reentrant task's merge

Use fast thread local and fix GC nepotism (Fixes #4749) (#4750)

---

src/main/asciidoc/http.adoc
src/main/java/io/vertx/core/http/HttpClientRequest.java
src/main/java/io/vertx/core/http/HttpServerRequest.java
src/main/java/io/vertx/core/http/HttpServerResponse.java
src/main/java/io/vertx/core/http/ServerWebSocket.java
src/main/java/io/vertx/core/http/impl/Http1xServerRequest.java
src/main/java/io/vertx/core/http/impl/Http1xServerResponse.java
src/main/java/io/vertx/core/http/impl/Http2ServerConnection.java
src/main/java/io/vertx/core/http/impl/Http2ServerRequest.java
src/main/java/io/vertx/core/http/impl/Http2ServerResponse.java
src/main/java/io/vertx/core/http/impl/Http2ServerStream.java
src/main/java/io/vertx/core/http/impl/HttpClientRequestBase.java
src/main/java/io/vertx/core/http/impl/HttpServerRequestWrapper.java
src/main/java/io/vertx/core/http/impl/HttpUtils.java
src/main/java/io/vertx/core/http/impl/ServerWebSocketImpl.java
src/main/java/io/vertx/core/net/HostAndPort.java
src/main/java/io/vertx/core/net/impl/HostAndPortImpl.java
src/test/java/io/vertx/core/http/Http2ClientTest.java
src/test/java/io/vertx/core/http/Http2ServerTest.java
src/test/java/io/vertx/core/http/HttpTest.java
src/test/java/io/vertx/core/http/HttpUtilsTest.java
src/test/java/io/vertx/core/http/WebSocketTest.java
src/test/java/io/vertx/core/net/impl/HostAndPortTest.java

The HttpClientRequest/HttpServerRequest exposes the HTTP request auth…ority using a host/port combination for the client request and a single host header for the server. In addition this terminology is also confusing with the server host and port.
Deprecate and provide the request host/port accessors, replaced by an authority property modelled as an HostAndPort object.
This also handle HTTP/2 server request whose host header differs from authority pseudo header when present to treat them as malformed requests.

Deprecate HTTP client host/port properties by an authority property

---

src/main/asciidoc/http.adoc
src/main/java/io/vertx/core/http/HttpClientRequest.java
src/main/java/io/vertx/core/http/HttpServerRequest.java
src/main/java/io/vertx/core/http/HttpServerResponse.java
src/main/java/io/vertx/core/http/ServerWebSocket.java
src/main/java/io/vertx/core/http/impl/Http1xServerRequest.java
src/main/java/io/vertx/core/http/impl/Http1xServerResponse.java
src/main/java/io/vertx/core/http/impl/Http2ServerConnection.java
src/main/java/io/vertx/core/http/impl/Http2ServerRequest.java
src/main/java/io/vertx/core/http/impl/Http2ServerResponse.java
src/main/java/io/vertx/core/http/impl/Http2ServerStream.java
src/main/java/io/vertx/core/http/impl/HttpClientRequestBase.java
src/main/java/io/vertx/core/http/impl/HttpServerRequestWrapper.java
src/main/java/io/vertx/core/http/impl/HttpUtils.java
src/main/java/io/vertx/core/http/impl/ServerWebSocketImpl.java
src/main/java/io/vertx/core/net/HostAndPort.java
src/main/java/io/vertx/core/net/impl/HostAndPortImpl.java
src/test/java/io/vertx/core/http/Http1xTest.java
src/test/java/io/vertx/core/http/Http2ClientTest.java
src/test/java/io/vertx/core/http/Http2ServerTest.java
src/test/java/io/vertx/core/http/HttpTest.java
src/test/java/io/vertx/core/http/HttpUtilsTest.java
src/test/java/io/vertx/core/http/WebSocketTest.java
src/test/java/io/vertx/core/net/impl/HostAndPortTest.java

this has been deprecated in 4.x branch for removal

Replace HTTP client host/port properties by an authority property

---

src/main/asciidoc/index.adoc
src/main/java/examples/CoreExamples.java
src/main/java/io/vertx/core/Context.java
src/main/java/io/vertx/core/Vertx.java
src/main/java/io/vertx/core/WorkerExecutor.java
src/main/java/io/vertx/core/impl/ContextBase.java
src/main/java/io/vertx/core/impl/ContextInternal.java
src/main/java/io/vertx/core/impl/DuplicatedContext.java
src/main/java/io/vertx/core/impl/NoStackTraceException.java
src/main/java/io/vertx/core/impl/VertxInternal.java
src/main/java/io/vertx/core/impl/VertxWrapper.java
src/main/java/io/vertx/core/impl/WorkerExecutorImpl.java
src/test/java/io/vertx/core/FakeContext.java

The Vert.x API for executing blocking actions uses a pattern with handler completing or failing a promise, instead this can be replaced with `java.util.concurrent.Callable` that returns the same value or throws an exception.
```java
// Deprecated
Future<String> fut = vertx.executeBlocking(promise -> promise.complete("result"));
// Instead use
Future<String> fut = vertx.executeBlocking(() -> "result");
```
This existing API is deprecated for removal in Vert.x 5.
There should be no ambiguity with existing lambda usage of such methods as new methods uses a callable that has no arguments.
See https://github.com/eclipse-vertx/vert.x/pull/4782

Execute blocking uses callable 4.x

---

src/main/java/io/vertx/core/net/SSLOptions.java

Motivation:
As explained in https://github.com/eclipse-vertx/vert.x/issues/4787, I am interested in updating the keystore used by an `HttpServer` object. However, the keystore at the path given in the `JksOptions` doesn't change; the keystore itself changes. So when attempting to call `updateSSLOptions(SSLOptions)` on the `HttpServer` object, vert.x thinks that the options have not changed, and thus wont reread the certificate. I was hoping to force vertx to reread the keystore by changing the `sslHandshakeTimeout` variable, as that is really the only one that can be modified without security concerns. However, in doing so, I noticed that the `equals()` method on the `SSLOptions` class incorrectly returned `true` when the SSL handshake timeout was different.

Fix SSLOptions equals method to use sslHandshakeTimeout from argument

---

src/main/java/io/vertx/core/Vertx.java
src/main/java/io/vertx/core/buffer/Buffer.java
src/main/java/io/vertx/core/impl/VertxInternal.java
src/test/java/io/vertx/core/dns/HostnameResolutionTest.java

The Vert.x API exposes the Netty API in its public API, allowing interactions with the Netty API. Since Netty is evolving toward Netty 5, we should remove Netty API from the Vert.x public API in Vert.x 5 to have the opportunity to change the underlying Netty version used by Vert.x without worrying about the version of the Netty version.
Such API continues to exist in Vert.x 5 but is moved to internal API which more easily change, therefore experimented users of this API can continue to use it granted that the version of Vert.x 5 uses Netty 4.
In practice most users should not use this API, and the deprecation should be seen also as a signal toward users of this API.

Deprecate Netty 4 API exposure in Vert.x API

---

src/main/java/io/vertx/core/net/impl/pool/CombinerExecutor.java
src/main/java/io/vertx/core/net/impl/pool/SemaphoreExecutor.java
src/main/java/io/vertx/core/net/impl/pool/SimpleConnectionPool.java
src/main/java/io/vertx/core/net/impl/pool/Task.java
src/test/java/io/vertx/core/net/impl/pool/ConnectionPoolTest.java

The pool asynchronously removes connection slots when they are identified as removable. This create races, e.g a connection can be evicted from the pool and then acquired before the removal happens.
Connection slots are now removed synchronously when the pool identifies connections to be removed immediately within the pool logic. The post action removal are now enqueued in the main post action (when there is one), the combiner executor has been modified to take in account the fact that a post action might next actions to execute.

Pool evict/acquire race fix

---

src/main/java/io/vertx/core/http/impl/WebSocketImplBase.java

The WebSocketBase implementation reuses the frame handler to aggregate binary/text frames, this overrides a frame handler that could be set to handle frames in addition of processing them.
The implementation has been modified so that the frame aggregator for binary/text frames has its own handler, the frame aggregator and the frame handler are both notified with incoming frames.

Decouple the WebSocketBase frame aggregator from the frame handler

---

src/main/java/io/vertx/core/http/impl/VertxHttp2ConnectionHandler.java
src/test/java/io/vertx/core/http/Http2WithUpgradeServerFileUploadTest.java
src/test/java/io/vertx/core/http/HttpServerFileUploadTest.java

When the server upgrades an HTTP/1.1 connection to H2C, it forwards inbound HTTP messages to the H2 encoder and updates the frame controller with the received amount of bytes. Actually such messages are not taken in account by the H2 flow controller and therefore when the window size becomes zero, it will not process message anymore.
This impacts HTTP/1.1 upgrades to H2C sending messages payload greater than the flow control window size.

HTTP/1.1 upgrade to H2C cannot process fully request entity with a size greater than the initial window size

---

src/main/java/io/vertx/core/net/ProxyOptions.java

Motivation:
Javadoc cuts lines with a dot short as it consider that the end of the first sentence, so using e.g. does not work as expected
the result was "3128 is the default port for e.g."
Conformance:

avoid using e.g. in javadoc to not cut short the line

---

src/main/java/io/vertx/core/http/impl/Http1xServerConnection.java
src/main/java/io/vertx/core/http/impl/Http1xServerRequest.java
src/main/java/io/vertx/core/http/impl/Http1xServerResponse.java
src/main/java/io/vertx/core/http/impl/HttpUtils.java
src/test/java/io/vertx/core/http/Http1xTest.java

The implementation of HTTP/1.x connection close immediately close the HTTP connection when the response has been sent regargless of the request status.
The responsibility of closing the connection has been moved from Http1xServerResponse to Http1xServerConnection which now computes and maintains the keep alive status of the connection and becomes responsible to close the connection when it should not be kept alive at the appropriate lifecycle of the connection (that is when the response has been sent and the corresponding request received).

Fix HTTP/1.1 server connection close header processing that close the connection too early

---

src/main/asciidoc/http.adoc
src/main/java/io/vertx/core/http/HttpServerRequest.java
src/main/java/io/vertx/core/http/HttpServerResponse.java
src/main/java/io/vertx/core/http/impl/Http1xServerRequest.java
src/main/java/io/vertx/core/http/impl/Http1xServerRequestHandler.java
src/main/java/io/vertx/core/http/impl/Http1xServerResponse.java
src/main/java/io/vertx/core/http/impl/Http2ServerResponse.java
src/test/java/io/vertx/core/http/Http1xTest.java
src/test/java/io/vertx/core/http/HttpClientConnectionTest.java
src/test/java/io/vertx/core/http/HttpTest.java
src/test/java/io/vertx/core/spi/metrics/MetricsContextTest.java

The HttpServerResponse close method closes the HTTP connection, it can be misleading as there are better API to interact with the current request/connection lifecycle which are HttpServerResponse#reset and HttpConnection#close.
This commits removes the close method of HtttpServerResponse.

HttpServerResponse close removal

---

src/main/java/io/vertx/core/http/HttpServerResponse.java

The `HttpServerResponse` close method closes the HTTP connection, it can be misleading as there are better API to interact with the current request/connection lifecycle which are `HttpServerResponse#reset` and `HttpConnection#close`.

Deprecate HttpServerResponse close method

---

src/main/java/io/vertx/core/buffer/Buffer.java
src/main/java/io/vertx/core/buffer/impl/BufferImpl.java
src/main/java/io/vertx/core/buffer/impl/BufferInternal.java
src/test/java/io/vertx/core/buffer/BufferTest.java
src/test/java/io/vertx/core/buffer/impl/VertxBufferTest.java

**Title:** Add Little Endian Support for Floats and Doubles in Buffer Class
**Body:**
This pull request aims to add support for Little Endian representation in floats and doubles within the `Buffer` class.
**New Methods:**
In `Buffer`:
- `double getDoubleLE(int pos);`
- `float getFloatLE(int pos);`
- `Buffer appendFloatLE(float f);`
- `Buffer appendDoubleLE(double d);`
- `Buffer setDoubleLE(int pos, double d);`
- `Buffer setFloatLE(int pos, float f);`
Corresponding changes have been made to the `BufferInternal`, `BufferImpl` classes, and `BufferTest` to accommodate these new methods.
---

Buffer adding support for float le and double le

---

src/main/java/io/vertx/core/http/impl/HttpClientRequestBase.java
src/main/java/io/vertx/core/http/impl/HttpClientRequestImpl.java
src/test/java/io/vertx/core/http/HttpTest.java

When an HTTP client request timeout fires, the corresponding stream is reset with a cancel code, the application cannot be aware of the cancellation because the netty stream reset will simply notify the stream to be closed.
We can keep track of the timeout in the HttpClientRequest and replace the HTTP closed exception with the timeout exception when this happens to better inform the application.

HTTP2 timeout exception

---

src/main/asciidoc/dns.adoc
src/main/java/io/vertx/core/dns/DnsClient.java
src/main/java/io/vertx/core/dns/impl/DnsClientImpl.java
src/test/java/io/vertx/core/dns/DNSTest.java
src/test/java/io/vertx/test/fakedns/FakeDNSServer.java

The DnsClient does not have a close method to release the underlying networking resources.
Add a close method to the client that closes the datagram channel, inflight queries are failed.

DnsClient can now be closed

---

src/main/java/io/vertx/core/Future.java
src/test/java/io/vertx/core/FutureTest.java

The Vertx `Future#eventually` method takes as parameter a `Function<Void, Future<T>>`, this was developed for codegen which did not support `Supplier`. The `Future` object is not code generated anymore since Vert.x 4, we can therefore use `Supplier` which is more suitable.
Add `Future#eventually(Supplier<Future<T>>)` and deprecate `Future#eventually(Function<Void, Future<T>>)` for removal in Vert.x 5.
The method is defined as a default method of Future and therefore all Future implementations will have it automatically.

Add Future eventually method with a supplier of future and deprecate the method with a function

---

src/main/java/examples/FileSystemExamples.java
src/main/java/io/vertx/core/Future.java
src/main/java/io/vertx/core/http/impl/Http2ServerResponse.java
src/main/java/io/vertx/core/http/impl/HttpNetSocket.java
src/main/java/io/vertx/core/impl/DeploymentManager.java
src/main/java/io/vertx/core/impl/future/Eventually.java
src/main/java/io/vertx/core/impl/future/FutureBase.java
src/test/java/io/vertx/core/FutureTest.java
src/test/java/io/vertx/core/http/WebSocketTest.java

The` Future#eventually` should use a `Supplier<Future<T>>` instead of a function, the new method was added in Vert.x 4 and the function version has been deprecated.
Replace `Future#eventually(Function<Void, Future<T>>)` by `Future#eventually(Supplier<Future<T>>)`.

Replace Future eventually function argument by a supplier argument

---

src/main/asciidoc/shareddata.adoc
src/main/java/examples/SharedDataExamples.java
src/main/java/io/vertx/core/file/AsyncFile.java
src/main/java/io/vertx/core/file/impl/AsyncFileImpl.java
src/main/java/io/vertx/core/shareddata/SharedData.java
src/main/java/io/vertx/core/shareddata/impl/SharedDataImpl.java
src/test/java/io/vertx/core/file/FileSystemTest.java
src/test/java/io/vertx/core/shareddata/AsynchronousLockTest.java

Acquire/release asynchronous API can be modelled as a function returning a future that is called when the lock is available until the returned future commits.
```java
Future<T> fut = sharedData.lock("the-lock").compose(lock ->
return getAsyncFalue().andThen(ar -> lock.release());
});
```
can be replaced with
```java
Future<T> fut = sharedLock.withLock("the-lock", v -> getAsyncValue());
```
This can be backported to Vert.x 4.x

Simplified API for locks

---

src/main/generated/io/vertx/core/dns/AddressResolverOptionsConverter.java
src/main/java/io/vertx/core/dns/AddressResolverOptions.java
src/main/java/io/vertx/core/impl/AddressResolver.java
src/main/java/io/vertx/core/impl/VertxImpl.java
src/main/java/io/vertx/core/impl/resolver/DnsResolverProvider.java
src/main/java/io/vertx/core/spi/resolver/ResolverProvider.java
src/test/java/io/vertx/core/dns/HostnameResolutionTest.java

The Vert.x DNS address resolver can load an hosts configuration file and cache the content forever. Sometimes the content of the file can change and the cached content becomes stale.
Add a new AddressResolverOptions hostsRefreshPeriod property to let the resolver refresh the hosts file when its cached content is older than the last read + refresh period.

Dns address resolver hosts configuration refresh period.

---

src/main/java/io/vertx/core/Future.java
src/main/java/io/vertx/core/impl/future/FutureImpl.java
src/test/java/io/vertx/core/FutureTest.java

Add Future implementation
Add FutureImpl implementations
Refactor to re-use new code for onSuccess and onFailure
Motivation:
Add onComplete method to Future class with onSuccess and onFailure mappers
Closes https://github.com/eclipse-vertx/vert.x/issues/4829
Cherry-pick of #4830

feat: onComplete method new signature

---

src/main/asciidoc/datagrams.adoc
src/main/asciidoc/http.adoc
src/main/asciidoc/index.adoc
src/main/asciidoc/net.adoc
src/main/asciidoc/streams.adoc

Motivation:
To refine documentation.
Conformance:

Correct document typo

---

src/main/java/io/vertx/core/http/impl/HttpNetSocket.java
src/main/java/io/vertx/core/net/ConnectOptions.java
src/main/java/io/vertx/core/net/NetSocket.java
src/main/java/io/vertx/core/net/impl/NetClientImpl.java
src/main/java/io/vertx/core/net/impl/NetSocketImpl.java
src/test/java/io/vertx/core/net/NetTest.java

Make sure to use the correct options when upgrading a NetSocket, in addition we can now provide an SSL upgrade with a specified SSLOptions instead of using the client/connect options if desired.

NetSocket upgrade with options

---

src/main/java/io/vertx/core/impl/DeploymentManager.java
src/test/java/io/vertx/core/NamedWorkerPoolTest.java

The recent changes in worker pool affected worker verticles with a regression: the named verticle worker pool is closed before undeploying the verticle which leads to have the worker verticle undeployment fail when the worker pool is used only by this verticle.
Close the worker pool after the verticle has been deployed instead of before.

Fix worker verticle using named worker pool regression

---

src/main/asciidoc/http.adoc
src/main/java/examples/HTTP2Examples.java
src/main/java/examples/HTTPExamples.java
src/main/java/io/vertx/core/Vertx.java
src/main/java/io/vertx/core/http/HttpClient.java
src/main/java/io/vertx/core/http/HttpClientBuilder.java
src/main/java/io/vertx/core/http/impl/CleanableHttpClient.java
src/main/java/io/vertx/core/http/impl/HttpClientBuilderImpl.java
src/main/java/io/vertx/core/http/impl/HttpClientImpl.java
src/main/java/io/vertx/core/http/impl/HttpClientInternal.java
src/main/java/io/vertx/core/impl/VertxImpl.java
src/main/java/io/vertx/core/impl/VertxInternal.java
src/main/java/io/vertx/core/impl/VertxWrapper.java
src/test/java/io/vertx/core/http/Http1xTLSTest.java
src/test/java/io/vertx/core/http/Http1xTest.java
src/test/java/io/vertx/core/http/Http2ClientTest.java
src/test/java/io/vertx/core/http/Http2ServerTest.java
src/test/java/io/vertx/core/http/Http2TLSTest.java
src/test/java/io/vertx/core/http/Http2Test.java
src/test/java/io/vertx/core/http/HttpBandwidthLimitingTest.java
src/test/java/io/vertx/core/http/HttpTLSTest.java
src/test/java/io/vertx/core/http/HttpTest.java
src/test/java/io/vertx/core/http/HttpTestBase.java
src/test/java/io/vertx/core/http/ResolvingHttpClientTest.java
src/test/java/io/vertx/core/spi/metrics/MetricsContextTest.java
src/test/java/io/vertx/core/spi/metrics/MetricsTest.java
src/test/java/io/vertx/test/proxy/HttpProxy.java

Implement a builder for HttpClient, this will be useful for configuring the address resolver for service discovery.
The builder allows to retrofit the client redirect/connect handlers like done in SQL client.

HTTP client builder API

---

src/main/java/io/vertx/core/http/HttpClientBuilder.java
src/main/java/io/vertx/core/http/impl/HttpClientBuilderImpl.java
src/main/java/io/vertx/core/http/impl/HttpClientImpl.java
src/main/java/io/vertx/core/http/impl/StatisticsGatheringHttpClientStream.java
src/main/java/io/vertx/core/net/AddressLookup.java
src/main/java/io/vertx/core/net/impl/pool/EndpointResolver.java
src/main/java/io/vertx/core/spi/lookup/AddressResolver.java
src/test/java/io/vertx/core/http/ResolvingHttpClientTest.java

The new address resolver implementations must be passed a Vert.x instance, given that most of the time such resolver is used within a client that already references a vertx instance, we can lazy init the resolver and pass it the vertx instance of the client which removes a step in the client configuration and make sure that the vertx instance used by the client and the resolver are the same.

Address resolver initialisation

---

src/main/java/io/vertx/core/http/impl/HttpClientBuilderImpl.java
src/main/java/io/vertx/core/http/impl/HttpClientImpl.java
src/main/java/io/vertx/core/http/impl/StatisticsGatheringHttpClientStream.java
src/main/java/io/vertx/core/net/AddressResolver.java
src/main/java/io/vertx/core/net/impl/pool/ConnectionLookup.java
src/main/java/io/vertx/core/net/impl/pool/EndpointResolver.java
src/main/java/io/vertx/core/spi/net/AddressResolver.java
src/test/java/io/vertx/core/http/ResolvingHttpClientTest.java

The address resolver is missing the notion of endpoint which is an intermediary between the resolved address and the socket address the client eventually uses. This forces address resolver implementation to determine which internal endpoint was selected based on the socket address the resolver choose, specially when the client report usage statistics to the resolver.
Introduce endpoint in the address resolver, the resolver now does select an endpoint for which a socket address can be determined, metrics can now use the endpoint type to properly report usage statistics.

Add missing first class endpoint in address resolver

---

src/main/java/io/vertx/core/eventbus/impl/EventBusImpl.java
src/main/java/io/vertx/core/eventbus/impl/HandlerHolder.java
src/main/java/io/vertx/core/eventbus/impl/HandlerRegistration.java
src/main/java/io/vertx/core/eventbus/impl/MessageConsumerImpl.java
src/main/java/io/vertx/core/eventbus/impl/MessageProducerImpl.java
src/main/java/io/vertx/core/eventbus/impl/OutboundDeliveryContext.java
src/main/java/io/vertx/core/eventbus/impl/ReplyHandler.java
src/main/java/io/vertx/core/eventbus/impl/clustered/ClusteredEventBus.java
src/main/java/io/vertx/core/eventbus/impl/clustered/ClusteredHandlerHolder.java
src/main/java/io/vertx/core/eventbus/impl/clustered/ConnectionHolder.java
src/main/java/io/vertx/core/eventbus/impl/clustered/Serializer.java
src/main/java/io/vertx/core/spi/cluster/NodeSelector.java
src/main/java/io/vertx/core/spi/cluster/impl/DefaultNodeSelector.java
src/main/java/io/vertx/core/spi/cluster/impl/selector/Selectors.java
src/main/java/io/vertx/core/spi/metrics/EventBusMetrics.java
src/test/java/io/vertx/core/eventbus/CustomNodeSelectorTest.java
src/test/java/io/vertx/core/eventbus/MessageQueueOnWorkerThreadTest.java
src/test/java/io/vertx/core/eventbus/WriteHandlerLookupFailureTest.java
src/test/java/io/vertx/core/spi/cluster/WrappedNodeSelector.java
src/test/java/io/vertx/core/spi/metrics/MetricsContextTest.java
src/test/java/io/vertx/core/spi/metrics/MetricsTest.java
src/test/java/io/vertx/test/fakemetrics/FakeEventBusMetrics.java
src/test/java/io/vertx/test/fakemetrics/HandlerMetric.java

See also https://github.com/eclipse-vertx/vert.x/pull/4712
EventBus streaming requires to send messages that does not go through the interceptor chain, e.g. establishing a stream requires to send such messages. The sendOrPub method and the downstream chain of calls (sendLocally, sendOrPublishFailed, sendToNode, sendToNodes) are coupled to OutboundDeliveryContext by convenience. The EventBus#sendOrPub is refactored to carry the messages and the delivery options instead of the OutboundDeliveryContext.
Main changes
- `EventBusImpl#sendOrPub(OutboundDeliveryContext) -> EventBusimpl#sendOrPub(ContextInternal,MessageImpl,DeliveryOptions,Promise)`
- same for `sendLocally`, `sendOrPublishFailed`, `sendToNode`, `sendToNodes`
The clustered event bus is aware of the nature of the `HandlerHolder`: …

Event bus internal improvements

---

src/main/java/io/vertx/core/http/HttpServerRequest.java
src/main/java/io/vertx/core/net/impl/HostAndPortImpl.java
src/test/java/io/vertx/core/http/Http1xTest.java
src/test/java/io/vertx/core/net/impl/HostAndPortTest.java

Fix a regression with the introduction of HTTP authority handling with HTTP/1.1 in which the server fails when handling an empty host portion of the host header. The authority method can also return null when no host header is present for HTTP/1.x

Fix incorrect handling of empty host portion of the host header

---

src/main/java/io/vertx/core/file/FileSystemProps.java
src/main/java/io/vertx/core/file/impl/FileSystemImpl.java
src/main/java/io/vertx/core/file/impl/FileSystemPropsImpl.java
src/test/java/io/vertx/core/file/FileSystemTest.java

Motivation:
The file store name is part of the `java.nio.file.FileStore` object which is used to build the `io.vertx.core.file.impl.FileSystemPropsImpl` object. However, the name is not defined as part of the `io.vertx.core.file.FileSystemProps` interface.
This piece of information is important including when logging information about the `io.vertx.core.file.FileSystemProps` concrete object when consuming it through `vertx.fileSystem().fsProps()` calls.
Conformance:

Add file store name to the FileSystemProps interface

---

src/main/java/io/vertx/core/http/impl/Http1xClientConnection.java
src/main/java/io/vertx/core/http/impl/Http1xServerConnection.java
src/test/java/io/vertx/core/http/WebSocketTest.java

The Vert.x HTTP server does not handle anymore WebSocket upgrades when the client presents a request with a connection header containing a close header (like nginx can send) and instead close the connection.
The server now will not close the connection when it is not persistent in case of a WebSocket upgrade.

HTTP server should not close a WebSocket when the connection is not persistent

---

src/main/java/io/vertx/core/net/TrafficShapingOptions.java
src/main/java/io/vertx/core/net/impl/TCPServerBase.java

Motivation:
When setting non-zero values for `io.vertx.core.net.TrafficShapingOptions` `maxDelayToWait` and `checkIntervalForStats` properties, a NullPointerException is encountered because `options.getCheckIntervalForStatsTimeUnit()` returns `null`, as it never is set.
Additionally, the time units expected in netty’s `io.netty.handler.traffic.GlobalTrafficShapingHandler` are milliseconds, however we are incorrectly passing seconds while initializing the `GlobalTrafficShapingHandler` object.
Conformance:

Fix traffic shaping options

---

src/main/java/io/vertx/core/net/TrafficShapingOptions.java
src/main/java/io/vertx/core/net/impl/TCPServerBase.java

* Fix traffic shaping options
When setting non-zero values for `io.vertx.core.net.TrafficShapingOptions` `maxDelayToWait` and `checkIntervalForStats` properties, a NullPointerException is encountered because `options.getCheckIntervalForStatsTimeUnit()` returns `null`, as it never is set.
Additionally, the time units expected in netty’s `io.netty.handler.traffic.GlobalTrafficShapingHandler` are milliseconds, however we are incorrectly passing seconds while initializing the `GlobalTrafficShapingHandler` object.
* Remove unnecessary null check

Fix traffic shaping options (#4888)

---

src/main/java/io/vertx/core/http/HttpServerOptions.java
src/main/java/io/vertx/core/http/impl/HttpServerWorker.java
src/main/java/io/vertx/core/http/impl/VertxHttp2ConnectionHandlerBuilder.java

Netty 4.1.100.Final added an HTTP/2 RST frame flood protection, this makes it configurable.

HTTP/2 RST frame flood protection configuration

---

src/main/java/io/vertx/core/net/impl/KeyStoreHelper.java
src/test/java/io/vertx/core/net/KeyStoreHelperTest.java

Motivation:
Fix for https://github.com/eclipse-vertx/vert.x/issues/4906
Hopefully trivial enough to have no wrong side-effect.

Use a long password on generated in-memory KeyStore

---

src/main/java/io/vertx/core/impl/TaskQueue.java
src/test/java/io/vertx/core/impl/TaskQueueTest.java

Closes #4900
Motivation:
This is a PR to address #4900. It is rather crude, and uses package visibility. While this does the job to make the assertions, I'd be happy to receive advice on how to change it to match the Vert.x's project way.
Conformance:

Ensure that the task is not in the tasks queue when it is rejected from the executor

---

src/main/java/io/vertx/core/impl/TaskQueue.java
src/test/java/io/vertx/core/impl/TaskQueueTest.java

Closes #4900
This is an adapted backport of #4901 that adds the also the handling of rejected executions which was previously only available in the 5.x branch.

[4.x] Ensure that the task is not in the tasks queue when it is rejected from the executor

---

src/main/java/io/vertx/core/net/impl/KeyStoreHelper.java
src/test/java/io/vertx/core/net/KeyStoreHelperTest.java

Motivation:
Fix for https://github.com/eclipse-vertx/vert.x/issues/4906 on 4.x branch
Hopefully trivial enough to have no wrong side-effect.

Use a long password on generated in-memory KeyStore (4.x branch)

---

src/main/java/examples/VirtualThreadExamples.java
src/main/java/io/vertx/core/Future.java
src/test/java/io/vertx/core/ContextTest.java
src/test/java/io/vertx/core/FutureTest.java
src/test/java/io/vertx/core/VirtualThreadContextTest.java
src/test/java/io/vertx/core/VirtualThreadDeploymentTest.java
src/test/java/io/vertx/core/eventbus/VirtualThreadEventBusTest.java
src/test/java/io/vertx/core/http/VirtualThreadHttpTest.java

Add a Future#await() method that is more convenient than the static Future#await(Future) developed in 4.x

Add a Future#await() instance method

---

src/main/java/io/vertx/core/http/impl/Http1xServerRequest.java
src/main/java/io/vertx/core/http/impl/Http2ServerRequest.java
src/main/java/io/vertx/core/http/impl/HttpServerRequestWrapper.java
src/main/java/io/vertx/core/impl/VertxWrapper.java
src/test/java/io/vertx/core/wrapper/HttpServerRequestWrapperImpl.java
src/test/java/io/vertx/core/wrapper/VertxWrapperImpl.java

Add test to ensure that HttpServerRequestWrapper and VertxWrapper can be extended without declaring any method of the wrapper's interfaces.

Wrapper classes testing

---

src/main/java/io/vertx/core/net/impl/NetClientImpl.java

In the hot path while sending requests (spotted in some grpc client's tests) we keep on creating "peer" addresses, even if not required ie when no SSL is used or we already copy the fields of the existing INET remote socket address.
This change aim to reduce both the allocation pressure (which is fairly low, it's just a single socket addr instance), but saving a useless validation too, saving CPU resources too.

Save creating (and validating) a peer INET address if not required

---

src/main/java/io/vertx/core/dns/impl/DnsClientImpl.java
src/main/java/io/vertx/core/dns/impl/decoder/RecordDecoder.java
src/test/java/io/vertx/core/dns/DNSTest.java
src/test/java/io/vertx/test/fakedns/DnameRecordEncoder.java
src/test/java/io/vertx/test/fakedns/DnsMessageEncoder.java
src/test/java/io/vertx/test/fakedns/FakeDNSServer.java

Motivation:
When trying to resolve any record type using `DnsClient`, if the DNS server replies back with a DNAME record, the handler passed to `DnsClient#resolve*()` methods is never called. This is because internally, `DnsClientImpl` uses `RecordDecoder` which currently throws `IllegalStateException` if it encounters a record type it does not know how to decode. `DnsClientImpl` does not catch this exception, causing the query to never be completed.
If you try to do this:
```
dnsClient.resolveMX("some-domain-with-dname-record.com", System::out::println);
```
The handler that would print the result is never called, instead this is logged:
```
WARNING: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not …
```

Fix IllegalStateException in DnsClient when DNS server responds with DNAME record

---

src/main/java/io/vertx/core/http/HttpClientRequest.java
src/main/java/io/vertx/core/http/impl/Http1xClientConnection.java
src/main/java/io/vertx/core/http/impl/Http2ClientConnection.java
src/main/java/io/vertx/core/http/impl/Http2UpgradeClientConnection.java
src/main/java/io/vertx/core/http/impl/HttpClientConnection.java
src/main/java/io/vertx/core/http/impl/HttpClientImpl.java
src/main/java/io/vertx/core/http/impl/HttpClientInternal.java
src/main/java/io/vertx/core/http/impl/HttpClientRequestBase.java
src/main/java/io/vertx/core/http/impl/HttpClientRequestImpl.java
src/main/java/io/vertx/core/http/impl/HttpClientRequestPushPromise.java
src/main/java/io/vertx/core/http/impl/SharedHttpClient.java
src/test/java/io/vertx/core/http/HttpClientConnectionTest.java
src/test/java/io/vertx/core/http/HttpTest.java

In some scenario (e.g. load-testing), it is preferable to use un-pooled HTTP connection.
This expose at the internal API level, the creation of HTTP connection and HTTP requests. This will eventually be exposed in the Vert.x API but the current API is still not mature enough to do that and require more work and might require breaking changes.

Expose HTTP client control over creation of un-pooled HTTP connections

---

src/main/java/io/vertx/core/eventbus/MessageProducer.java
src/main/java/io/vertx/core/eventbus/impl/EventBusImpl.java
src/main/java/io/vertx/core/eventbus/impl/OutboundDeliveryContext.java
src/test/java/io/vertx/core/eventbus/ClusteredEventBusTest.java

See #4922
When publishing, the OutboundDeliveryContext (promise) can be completed or failed several times. This leads to confusing exceptions in application logs.
The promise should be completed with tryFail/tryComplete to avoid redundant exceptions.
Besides, the MessageProducer write future behavior should be clarified. The returned Future completion depends on the producer type:
- send or request: the future is completed successfully if the message has been written; otherwise, the future is failed
-  publish: the future is failed if there is no recipient; otherwise, the future is completed successfully
In any case, a successfully completed Future is not a delivery guarantee.

Clarify MessageProducer write future behavior

---

src/main/asciidoc/http.adoc
src/main/generated/io/vertx/core/http/RequestOptionsConverter.java
src/main/java/examples/HTTPExamples.java
src/main/java/io/vertx/core/Future.java
src/main/java/io/vertx/core/http/HttpClientRequest.java
src/main/java/io/vertx/core/http/RequestOptions.java
src/main/java/io/vertx/core/http/WebSocketConnectOptions.java
src/main/java/io/vertx/core/http/impl/HttpClientBase.java
src/main/java/io/vertx/core/http/impl/HttpClientImpl.java
src/main/java/io/vertx/core/http/impl/HttpClientRequestBase.java
src/main/java/io/vertx/core/http/impl/SharedClientHttpStreamEndpoint.java
src/main/java/io/vertx/core/impl/NoStackTraceTimeoutException.java
src/main/java/io/vertx/core/impl/future/FutureBase.java
src/test/java/io/vertx/core/FutureTest.java
src/test/java/io/vertx/core/http/Http1xMetricsTest.java
src/test/java/io/vertx/core/http/Http1xTest.java
src/test/java/io/vertx/core/http/Http2MetricsTest.java
src/test/java/io/vertx/core/http/Http2TestBase.java
src/test/java/io/vertx/core/http/HttpBandwidthLimitingTest.java
src/test/java/io/vertx/core/http/HttpClientConnectionTest.java
src/test/java/io/vertx/core/http/HttpClientTimeoutTest.java
src/test/java/io/vertx/core/http/HttpMetricsTestBase.java
src/test/java/io/vertx/core/http/HttpServerFileUploadTest.java
src/test/java/io/vertx/core/http/HttpTest.java
src/test/java/io/vertx/core/http/HttpTestBase.java
src/test/java/io/vertx/core/http/RequestOptionsTest.java

The way HTTP client timeouts does not meet all the expectations.
The `timeout` present on `RequestOptions` applies for the time to obtain a connection and then configures the idle timeout of the request.
It is preferable to deprecate `RequestOptions#timeout` property an `HttpClientRequest#setTimeout` because its naming is too broad and introduce a connect timeout and an idle timeout.
`RequestOptions` now has a `connectTimeout` applied when a request is obtained from the client pool and an `idleTimeout` applied to the `HttpClientRequest` after it has been obtained from the pool.
`HttpClientRequest` now has a `setIdleTimeout` method which is a bare rename of `setTimeout` and better carries the meaning of the method.
In addition it should be easier to define a global timeout when interacting …

HTTP client timeout improvements

---

src/test/java/io/vertx/core/http/Http1xTLSTest.java
src/test/java/io/vertx/core/http/Http2TLSTest.java
src/test/java/io/vertx/core/http/HttpTLSTest.java

- creation of base options should be achieved in create base options methods for each protocol
- SSL options update tests are actually not configured for HTTP/2

 HTTP TLS tests improvements

---

src/main/asciidoc/net.adoc
src/main/java/examples/NetExamples.java
src/main/java/io/vertx/core/http/HttpClient.java
src/main/java/io/vertx/core/http/HttpServer.java
src/main/java/io/vertx/core/http/WebSocketClient.java
src/main/java/io/vertx/core/http/impl/HttpClientBase.java
src/main/java/io/vertx/core/http/impl/SharedHttpClient.java
src/main/java/io/vertx/core/http/impl/SharedWebSocketClient.java
src/main/java/io/vertx/core/net/NetClient.java
src/main/java/io/vertx/core/net/NetServer.java
src/main/java/io/vertx/core/net/impl/NetClientImpl.java
src/main/java/io/vertx/core/net/impl/SSLHelper.java
src/main/java/io/vertx/core/net/impl/SslContextUpdate.java
src/main/java/io/vertx/core/net/impl/TCPServerBase.java
src/test/java/io/vertx/core/http/HttpTLSTest.java

The TCP server/client updateSslOptions method does not update the options when the comparison using equals against the previous options returns true. Sometimes this behavior is not desirable, e.g. when the path to the certificate does not change and such certificates has been overwritten.

TCP SslOptions update force option

---

src/main/java/io/vertx/core/http/impl/Http2ClientConnection.java
src/test/java/io/vertx/core/http/Http1xClientTimeoutTest.java
src/test/java/io/vertx/core/http/Http2ClientTimeoutTest.java
src/test/java/io/vertx/core/http/HttpClientTimeoutTest.java

HTTP client idle timeout should reset the stream with CANCEL (8) the HTTP/2 stream instead of resetting with a NO_ERROR (0) code.
Expand the timeout tests to HTTP/2

HTTP client idle timeout should reset the stream with CANCEL error code

---

src/main/java/io/vertx/core/http/impl/HttpClientRequestBase.java
src/main/java/io/vertx/core/http/impl/HttpClientRequestImpl.java
src/main/java/io/vertx/core/http/impl/HttpClientRequestPushPromise.java
src/test/java/io/vertx/core/http/Http2Test.java

The HttpClientRequest implementation does have a mapping of HTTP closed exception when a timeout occurs so the client is signaled with a stream exception for better usability. Actually we can generify this for the generic reset exception case instead of just being for idle timeouts.

Generify HttpClientRequest stream reset exception remapping

---

src/main/java/io/vertx/core/net/impl/HostAndPortImpl.java
src/test/java/io/vertx/core/net/impl/HostAndPortTest.java

See #4947
If `parseIPv4Address` finds an IP address, and the string still has characters which do not begin with `:`, this is not an IP address.
In other words, `10.0.0.1.nip.io` should not be parsed as IP address.

HostAndPort fails to parse a nip host

---

src/main/java/io/vertx/core/eventbus/EventBusOptions.java
src/main/java/io/vertx/core/http/HttpClientOptions.java
src/main/java/io/vertx/core/http/HttpServerOptions.java
src/main/java/io/vertx/core/http/WebSocketClientOptions.java
src/main/java/io/vertx/core/net/ClientOptionsBase.java
src/main/java/io/vertx/core/net/NetClientOptions.java
src/main/java/io/vertx/core/net/NetServerOptions.java
src/main/java/io/vertx/core/net/TCPSSLOptions.java

The TCPSSLOptions data object class has setters overload for keyCertOptions and trustOptions with different sub interfaces of the base interfaces, e.g. setPfxTrustOptions(PfxTrustOptions) for setTrustOptions(TrustOptions). This was initially done to let the JSON generated converter work since KeyCertOptions and TrustOptions are used through their implementations.
This deprecates those un-necessary. The corresponding methods are removed in Vert.x 5

TCPSSLOptions keyCertOptions/trustOptions accessors overload deprecation

---

src/main/asciidoc/index.adoc
src/main/java/examples/CoreExamples.java
src/main/java/io/vertx/core/Vertx.java
src/main/java/io/vertx/core/VertxBuilder.java
src/main/java/io/vertx/core/VertxOptions.java
src/main/java/io/vertx/core/impl/VertxBuilder.java
src/main/java/io/vertx/core/metrics/MetricsOptions.java
src/main/java/io/vertx/core/spi/VertxMetricsFactory.java
src/main/java/io/vertx/core/spi/VertxTracerFactory.java
src/main/java/io/vertx/core/tracing/TracingOptions.java
src/test/java/io/vertx/core/CreateVertxTest.java
src/test/java/io/vertx/core/HATest.java
src/test/java/io/vertx/core/VertxBuilderTest.java
src/test/java/io/vertx/core/VertxOptionsTest.java
src/test/java/io/vertx/core/VertxStartFailureTest.java
src/test/java/io/vertx/core/eventbus/ClusterHostTest.java
src/test/java/io/vertx/core/eventbus/ClusteredEventBusTest.java
src/test/java/io/vertx/core/eventbus/ClusteredEventBusTestBase.java
src/test/java/io/vertx/core/eventbus/EventBusRegistrationRaceTest.java
src/test/java/io/vertx/core/http/HttpMetricsTestBase.java
src/test/java/io/vertx/core/impl/VertxFactoryTest.java
src/test/java/io/vertx/core/spi/metrics/MetricsContextTest.java
src/test/java/io/vertx/core/spi/metrics/MetricsOptionsTest.java
src/test/java/io/vertx/core/spi/metrics/MetricsTest.java
src/test/java/io/vertx/core/spi/tracing/EventBusTracingTestBase.java
src/test/java/io/vertx/test/core/VertxTestBase.java

- Vertx has an internal builder API that is used by the launcher
- VertxOptions exposes services like the cluster manager, the metrics instance, the tracer instance which are not suited for options, since options should focus on configuration data
This PR provides a `VertxBuilder` API that can be used to override the the vertx services exposed in `VertxOptions`, `VertxOptions` related services have been removed.
```java
// Before
Future<Vertx> fut = Vertx.clusteredVertx(new VertxOptions().setClusterManager(clusterManager));
// After
Future<Vertx> fut = Vertx.builder().withClusterManager(clusterManager).buildClustered();
```
This should be back-ported to 4.x branches.

Vertx Builder API + remove cluster manager from VertxOptions

---

src/main/java/io/vertx/core/eventbus/impl/EventBusImpl.java
src/main/java/io/vertx/core/eventbus/impl/MessageImpl.java
src/main/java/io/vertx/core/eventbus/impl/MessageProducerImpl.java
src/main/java/io/vertx/core/eventbus/impl/clustered/ClusteredEventBus.java

Motivation:
When operating in clustered mode I want to allow local messages to perform the codec lookup as local.
Conformance:

- allows for local only codec lookup when in clustered mode

---

src/main/asciidoc/index.adoc
src/main/java/examples/CoreExamples.java
src/main/java/io/vertx/core/Vertx.java
src/main/java/io/vertx/core/VertxBuilder.java
src/main/java/io/vertx/core/VertxOptions.java
src/main/java/io/vertx/core/metrics/MetricsOptions.java
src/main/java/io/vertx/core/tracing/TracingOptions.java
src/test/java/io/vertx/core/VertxBuilderTest.java

VertxOptions exposes services like the cluster manager, the metrics factory, the tracer factory which are not suited for options, since options should focus on configuration data.
This provides a `VertxBuilder` API that can be used to override the vertx services exposed in `VertxOptions`, `VertxOptions` related services have been deprecated.
```java
// Before
Future<Vertx> fut = Vertx.clusteredVertx(new VertxOptions().setClusterManager(clusterManager));
// After
Future<Vertx> fut = Vertx.builder().withClusterManager(clusterManager).buildClustered();
```

Introduce a VertxBuilder API

---

src/main/java/io/vertx/core/parsetools/impl/RecordParserImpl.java
src/test/java/io/vertx/core/http/ClientResponseParserTest.java
src/test/java/io/vertx/core/http/Http1xClientResponseParserTest.java
src/test/java/io/vertx/core/http/Http2ClientResponseParserTest.java
src/test/java/io/vertx/core/parsetools/RecordParserTest.java

See #4811
This can be a problem if the received [Buffer](url) is backed by a Netty `ByteBuff` with low capacity.
Also, we shouldn't assume we can modify input.

RecordParser may grow the initial buffer until the first event is emitted

---

src/main/asciidoc/net.adoc
src/main/generated/io/vertx/core/http/RequestOptionsConverter.java
src/main/java/examples/NetExamples.java
src/main/java/io/vertx/core/http/HttpClient.java
src/main/java/io/vertx/core/http/WebSocketClient.java
src/main/java/io/vertx/core/http/impl/CleanableHttpClient.java
src/main/java/io/vertx/core/http/impl/CleanableWebSocketClient.java
src/main/java/io/vertx/core/http/impl/HttpClientBase.java
src/main/java/io/vertx/core/http/impl/HttpClientBuilderImpl.java
src/main/java/io/vertx/core/http/impl/HttpNetSocket.java
src/main/java/io/vertx/core/impl/VertxImpl.java
src/main/java/io/vertx/core/net/NetClient.java
src/main/java/io/vertx/core/net/NetSocket.java
src/main/java/io/vertx/core/net/impl/CleanableNetClient.java
src/main/java/io/vertx/core/net/impl/NetClientInternal.java
src/main/java/io/vertx/core/net/impl/NetSocketImpl.java
src/test/java/io/vertx/core/http/Http1xTest.java
src/test/java/io/vertx/core/net/NetTest.java

- Rename shutdown to close to avoid confusion since shutdown is used internally and does not have the same effect
- Add a NetSocket shutdown handler so protocol can be aware of client shutdown

Improve the new client shutdown mechanism

---

src/main/java/io/vertx/core/buffer/impl/VertxHeapByteBuf.java
src/main/java/io/vertx/core/buffer/impl/VertxUnsafeHeapByteBuf.java
src/main/java/io/vertx/core/json/jackson/JacksonCodec.java
src/test/benchmarks/io/vertx/benchmarks/JsonEncodeBenchmark.java

Some numbers:
baseline:
```
Benchmark                                                  Mode  Cnt     Score    Error   Units
JsonEncodeBenchmark.tinyBufferJackson                      avgt   10     0.363 ±  0.001   us/op
JsonEncodeBenchmark.tinyBufferJackson:·gc.alloc.rate.norm  avgt   10   704.000 ±  0.001    B/op
```
With ba66dfa628ada94d9dac1d589255b0bcd080fdd0:
```
Benchmark                                                  Mode  Cnt     Score    Error   Units
JsonEncodeBenchmark.tinyBufferJackson                      avgt   10     0.350 ±  0.001   us/op
JsonEncodeBenchmark.tinyBufferJackson:·gc.alloc.rate.norm  avgt   10   512.000 ±  0.001    B/op
```
Performance is slightly increased (and will get better with highly concurrent allocations), but most importantly,
the GC pressure is …

Reduce garbage with small jackson encoded data (Fixes #4977)

---

src/main/java/io/vertx/core/http/impl/HttpClientBuilderInternal.java
src/main/java/io/vertx/core/http/impl/HttpClientImpl.java
src/main/java/io/vertx/core/http/impl/StatisticsGatheringHttpClientStream.java
src/main/java/io/vertx/core/impl/VertxImpl.java
src/main/java/io/vertx/core/net/impl/resolver/EndpointResolverImpl.java
src/main/java/io/vertx/core/spi/resolver/endpoint/EndpointLookup.java
src/main/java/io/vertx/core/spi/resolver/endpoint/EndpointRequest.java
src/main/java/io/vertx/core/spi/resolver/endpoint/EndpointResolver.java

Expose the high level EndpointResolver as SPI as it is more convenient for some integration levels.

Expose the high level EndpointResolver as SPI as it is more convenient for some integration levels

---

src/main/java/io/vertx/core/buffer/Buffer.java

`io.vertx.core.buffer.Buffer` has historically been part of the API as an async generated type, annotated by `@VertxGen`. It it has always been wrapped/unwrapped with reactive stream based like generators.
In Vert.x 5 this type becomes a data object since it does not have asynchronous methods and actually wraps a byte array. As consequence reactive streams like generators will not need anymore to wrap/unwrap this type which avoids un-necessary allocation, as trade of for a breaking change.

The Buffer type becomes a data object instead of a generated type.

---

src/test/java/io/vertx/core/http/headers/HeadersTestBase.java

**Problem**
The `testAddAll2` function checks the output of MultiMap against a hard-coded test string. This causes the unit test to fail sometimes, even though the code under test works as expected. 
**Solution**
The idea is to sort the MultiMap output so that we have a deterministic test assertion. I have used the function defined in the test class itself, to sort the mmap output lines.
https://github.com/eclipse-vertx/vert.x/blob/b4fd4d691cfa802189c5a5d25688ea739440bf4a/src/test/java/io/vertx/core/http/headers/HeadersTestBase.java#L476-L485
There are 4 unit tests which can be fixed with this change -
```
io.vertx.core.http.headers.Http2HeadersAdaptorsTest#testAddAll2
io.vertx.core.http.headers.CaseInsensitiveHeadersTest#testAddAll2 …
```

sortByLine MultiMap output - fixes 4 flaky unit tests

---

src/main/java/io/vertx/core/eventbus/impl/EventBusImpl.java
src/main/java/io/vertx/core/eventbus/impl/MessageImpl.java
src/main/java/io/vertx/core/eventbus/impl/MessageProducerImpl.java
src/main/java/io/vertx/core/eventbus/impl/clustered/ClusteredEventBus.java

Motivation:
Allows for local codec lookup when in clustered mode. 
Conformance:

- allows for local codec lookup when in clustered mode.

---

src/main/java/io/vertx/core/Timer.java
src/main/java/io/vertx/core/Vertx.java
src/main/java/io/vertx/core/impl/TimerImpl.java
src/main/java/io/vertx/core/impl/VertxImpl.java
src/main/java/io/vertx/core/impl/VertxWrapper.java
src/main/java/io/vertx/core/impl/future/FutureImpl.java
src/test/java/io/vertx/core/TimerTest.java

A timer task that extends a vertx future and can be used as a starting point in future chain or can be used within future compositions. This task is also more suitable for being awaited by a virtual thread.
When the context/vertx instance is disposed or the timer is cancelled, the future is signalled with a failure.

Timer task as a Vert.x future

---

src/main/asciidoc/http.adoc
src/main/java/io/vertx/core/http/HttpServerOptions.java
src/main/java/io/vertx/core/http/impl/Http1xUpgradeToH2CHandler.java
src/main/java/io/vertx/core/http/impl/HttpServerImpl.java
src/main/java/io/vertx/core/http/impl/HttpServerWorker.java
src/main/java/io/vertx/core/spi/tls/DefaultSslContextFactory.java
src/test/java/io/vertx/core/http/Http2ClientTest.java
src/test/java/io/vertx/core/http/Http2Test.java
src/test/java/io/vertx/core/http/HttpTLSTest.java

When the server cannot select a protocol sent by the ALPN extension sent by the client, we should fail the SSL handshake immediately instead of having a successful handshake.
This also documents the HTTP server protocol selection according to the TLS configuration and explains how to disable HTTP/2 on the server accordingly.

Fail SSL handshake when ALPN protocol selection fails and document better HTTP server protocol selection

---

src/main/java11/io/vertx/core/DeploymentOptions.java

In DeploymentOptions for Java 11 (MRS jar) the deprecation has been set on threadingModel rather than the worker property.

Fix incorrect Java 11 DeploymentOptions deprecation on threading model property

---

src/main/java/io/vertx/core/streams/Pump.java

Stream Pump has been superseded by io.vertx.core.streams.Pipe since Vert.x 4. The documentation does not reference Pump since 4.0.0, only the vertx-examples were still merely referring to it.

Deprecate pump for pipe

---

src/main/java/io/vertx/core/eventbus/impl/MessageTagExtractor.java
src/main/java/io/vertx/core/http/impl/HttpUtils.java
src/test/java/io/vertx/core/spi/tracing/EventBusTracingTestBase.java
src/test/java/io/vertx/core/spi/tracing/HttpTracingTestBase.java

Closes https://github.com/eclipse-vertx/vertx-tracing/issues/67

Tracing: more eventbus and HTTP tags

---

src/main/java/io/vertx/core/file/impl/FileCache.java
src/main/java/io/vertx/core/file/impl/FileResolverImpl.java
src/test/java/io/vertx/core/file/CustomJarFileResolverTest.java
src/test/java/io/vertx/core/file/NestedJarFileResolverTest.java
src/test/java/io/vertx/core/file/NestedRootJarResolverTest.java
src/test/java/io/vertx/core/file/NestedZipFileResolverTest.java

Best effort in Vert.x file resolver to support jar file resolution for simple jar file entries without recursion when the URL to resolve provides a custom protocol that provides a valid jar url connection to a jar file. The file resolver unpacking mechanism is changed to get the jar file to unpack from the jar url connection instead of reconstructing the jar URL deduced from the initial URL to resolve (according to what the classloader resolved).
The extraction of the list of jar entries from the URL has been rewritten in a more generic fashion with a relaxed parsing to accommodate URL with a file that use custom conventions which actually seems fine with the jar url documentation.
This provides a *best* effort support for Spring boot `nested` custom protocol …

File resolver supports custom jar URL connection

---

src/main/java/io/vertx/core/file/impl/FileResolverImpl.java
src/test/java/io/vertx/core/file/ZipFileResolverTest.java

FileResolver uses the JarURLConnection to unpack zip content, by default the zip is cached and shared between connections, since the resolver closes the zip file after use, it closes the pending resources openeded from this file.
FileResolver now only closes the zip content when the url connection is not cached to avoid interferring with classloader url connections.

Avoid closing zip file when accessing a jar url connection caching the zip file

---

src/main/java/io/vertx/core/impl/VertxImpl.java
src/test/java/io/vertx/core/TimerTest.java

Periodic tasks will reuse any context to deliver timer events independantly of the context. Unlike timers (which reuse the current context whether it is a duplicate) a periodic should not capture duplicate context as they would extend the lifecycle of the duplicated context. Instead a periodic should duplicate the current context so each timer event will have its own independant lifecycle.
Update the implementation of internal schedule tasks to unwrap the context of the scheduler timer task and then duplicate it when an timer event is emitted.

Duplicate context on periodic event notifications

---

src/main/java/io/vertx/core/http/impl/VertxHttp2ConnectionHandler.java

This is performing 2 changes:
- Fixes #5039 by using a companion class: the problem is due to the various generic collections operations in Netty
eg
the entry in the issue 
```    
io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultEndpoint.addStream(DefaultHttp2Connection.java:805)
class: io.netty.handler.codec.http2.Http2Connection$Listener
count: 7912545
```
matches with https://github.com/netty/netty/blob/013c38298f6d28ec14543d02ede9bb6a6472ca3f/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2Connection.java#L805
which `listeners` collections contains:
```
0 = {WeightedFairQueueByteDistributor$1@5819} 
1 = {DefaultHttp2RemoteFlowController$1@5855} 
2 = {DefaultHttp2LocalFlowController$1@5856} 
3 = {VertxHttp2ConnectionHandler@5851} 
```
meaning that the …

Reduce chances of type check scalability issues (Fixes #5039)

---

src/main/java/io/vertx/core/dns/AddressResolverOptions.java
src/test/java/io/vertx/core/dns/HostnameResolutionTest.java

instead AddressResolverOptions#DEFAULT_SEARCH_DOMAINS shall be used

Deprecate AddressResolverOptions#DEFAULT_SEACH_DOMAINS (typo)

---

src/main/java/io/vertx/core/dns/AddressResolverOptions.java
src/test/java/io/vertx/core/dns/HostnameResolutionTest.java

AddressResolverOptions#DEFAULT_SEACH_DOMAINS is renamed to DEFAULT_SEARCH_DOMAINS

---

src/main/java/io/vertx/core/http/impl/HttpUtils.java
src/test/benchmarks/io/vertx/benchmarks/HttpUtilsAsciiToLowerCaseBenchmark.java

In some simple HTTP 2 hello world benchmarks, `HttpUtils::toLowerCase` has pop-up due to how Quarkus handle HTTP headers using Jax-RS HTTP header name constants ie using capital letters in `String`s eg "Content-Type".
This is speeding up the `String` lowercase transformation case improving the others, where possible.
baseline:
```
Benchmark                                       (lowerCase)   (type)  Mode  Cnt   Score   Error  Units
HttpUtilsAsciiToLowerCaseBenchmark.toLowerCase        false    ascii  avgt   20  29.698 ± 0.195  ns/op
HttpUtilsAsciiToLowerCaseBenchmark.toLowerCase        false   string  avgt   20  23.967 ± 0.791  ns/op
HttpUtilsAsciiToLowerCaseBenchmark.toLowerCase        false  builder  avgt   20  24.155 ± 0.905  ns/op
HttpUtilsAsciiToLowerCaseBenchmark.toLowerCase …
```

Speedup HTTP headers lowercase transformation

---

src/main/java/io/vertx/core/json/jackson/DatabindCodec.java
src/test/java/io/vertx/core/json/JacksonDatabindTest.java

There is no need to keep two object mappers if a single one can be used to encode json in compact and pretty form. This change relieves users from configuring two object mappers if they have customizations.

Deprecate DatabindCodec pretty mapper

---

src/main/java/io/vertx/core/json/jackson/HybridJacksonPool.java
src/main/java/io/vertx/core/json/jackson/JacksonCodec.java
src/test/java/io/vertx/core/json/jackson/HybridJacksonPoolTest.java

This pull request is a follow up of the work done to make the [internal pool used by Jackson configurable and pluggable](https://github.com/FasterXML/jackson-core/pull/1064). It is not intended to be merged until Jackson 2.16 won't be released. Also this is the porting of the [same pull request sent to quarkus](https://github.com/quarkusio/quarkus/pull/35816).

Use a virtual threads friendly pool with Jackson

---

src/main/java/io/vertx/core/http/impl/Http1xClientConnection.java
src/main/java/io/vertx/core/http/impl/Http1xConnectionBase.java
src/main/java/io/vertx/core/http/impl/Http1xServerConnection.java
src/main/java/io/vertx/core/http/impl/WebSocketImplBase.java
src/test/java/io/vertx/core/http/WebSocketTest.java

Linked to this issue : https://github.com/eclipse-vertx/vert.x/issues/5074
The ConnectionBase exception handler was not set when `webSocket.exceptionHandler(...)` is called. This was leading `ConnectionBase` to consider the exception as uncaught and to print it, ignoring the exception handler set at the WebSocketImplBase level.
Moreover, this WebSocket handler was also called after the call to `ConnectionBase#handleException(...)`.
So I decided to set the `ConnectionBase` exception handler with the WebSocketImplBase.
The replacement of `Http1xConnectionBase conn` with `Http1xConnectionBase<?> conn` was needed otherwise the compiler complains.

5074 Fix the WebSocket exception handling strategy

---

src/main/java/io/vertx/core/http/impl/VertxHttp2ConnectionHandlerBuilder.java

The default stream byte distributor use stream priorities to determine the amount of bytes to be sent for each stream, this change allows to use a strategy that does not use stream priorities and yields better performance since it consumes less CPU.
The default implementation is now `UniformStreamByteDistributor` instead of `WeightedFairQueueByteDistributor `.

A replacement of the HTTP/2 priority handling with a uniform stream byte distributor

---

src/main/java/io/vertx/core/net/impl/pool/CombinerExecutor.java
src/test/java/io/vertx/core/net/impl/pool/ConnectionPoolTest.java
src/test/java/io/vertx/core/net/impl/pool/SynchronizationTest.java

The CombinerExecutor class creates an instance of FastThreadLocal for each combiner executor leading to an increase of the InternalThreadLocalMap index. Consequently each thread local map of FastThreadLocalThread will get a new map sized accordingly, leading to an eventual memory leak.
Use a static FastThreadLocal in CombinerExecutor instead of a instance field, the data structure stored in this thread local map keeps track of the CombinerExecutor running in order to allow interleaved execution of CombinerExecutor post tasks without interfering each other. The structure is optimized for the most frequent case.
Fixes https://access.redhat.com/security/cve/CVE-2024-1023

Use a static FastThreadLocal in CombinerExecutor instead of a instance field

---

pom.xml
src/main/java/io/vertx/core/json/jackson/JacksonCodec.java
src/test/java/io/vertx/it/NoRecyclerPoolJacksonTest.java

The upgrade to Jackson 2.16.x brought the new recycler pool feature. We should support Jackson versions that do not support this feature to avoid forcing users to move Jackson 2.16.x
Use reflection to configure the pool instead and gracefully fail when configuration cannot be achieved.

Graceful handling of Jackson 2.15.x series

---

src/main/asciidoc/net.adoc
src/main/java/examples/NetExamples.java
src/main/java/io/vertx/core/http/HttpServer.java
src/main/java/io/vertx/core/net/NetServer.java
src/main/java/io/vertx/core/net/TrafficShapingOptions.java
src/main/java/io/vertx/core/net/impl/TCPServerBase.java
src/test/java/io/vertx/core/http/HttpBandwidthLimitingTest.java
src/test/java/io/vertx/core/net/NetBandwidthLimitingTest.java

Motivation:
Allowing dynamic updates of read and write limits set for HttpServer and NetServers created through Vert.x would be helpful during rate limit threshold setting tests. Currently dynamic updates are not possible, hence servers created have to be bounced and recreated. This could cause downtime. With this patch server thresholds can be updated dynamically.

Allow dynamic update of read and write limits set for Servers

---

src/main/java/io/vertx/core/json/jackson/DatabindCodec.java
src/test/java/io/vertx/core/json/JacksonDatabindTest.java

Follows-up on https://github.com/eclipse-vertx/vert.x/pull/5060
Since the pretty mapper is deprecated, any customization of the object mapper should be used when pretty printing with `Json.encodePrettily`.

ObjectMapper configuration should apply when pretty printing

---

src/main/java/io/vertx/core/http/impl/HttpUtils.java
src/test/java/io/vertx/core/http/Http1xTest.java

Vert.x Web And Vert.x HTTP Proxy have similar code. This method covers all cases and can be reused.

Add helper method to determine if request can be upgraded to websocket.

---

src/main/java/io/vertx/core/net/impl/SSLHelper.java
src/main/java/io/vertx/core/net/impl/SslChannelProvider.java
src/main/java/io/vertx/core/net/impl/SslContextProvider.java
src/main/java/io/vertx/core/net/impl/TCPServerBase.java
src/test/java/io/vertx/core/net/NetTest.java
src/test/java/io/vertx/core/net/SSLHelperTest.java
src/test/java/io/vertx/it/SSLEngineTest.java

The `SslChannelProvider` class maintains a map of server name to Netty `SslContext` that is filled when a client provides a server name. When a server name does not resolve to a `KeyManagerFactory` or `TrustManagerFactory`, the default factories are used and the entry is stored in the map. Instead no specific factory is resolved the default Netty `SslContext` is used, since this can lead to a a memory leak when a client specifies spurious SNI server names. This affects only a TCP server when SNI is set in the `HttpServerOptions`.
In addition fix: the TCP client will not send the correct server name to the client due to SSL client resumption performed by the SSL implementation although we are using a new engine implementation.

Fix TCP TLS server SNI server name leak

---

src/main/java/io/vertx/core/http/HttpConnection.java
src/main/java/io/vertx/core/http/impl/Http1xClientConnection.java
src/main/java/io/vertx/core/http/impl/Http1xConnectionBase.java
src/main/java/io/vertx/core/http/impl/Http1xServerConnection.java
src/main/java/io/vertx/core/http/impl/Http1xServerRequest.java
src/main/java/io/vertx/core/http/impl/Http2ConnectionBase.java
src/main/java/io/vertx/core/http/impl/Http2UpgradeClientConnection.java
src/main/java/io/vertx/core/http/impl/HttpServerWorker.java
src/test/benchmarks/io/vertx/core/http/impl/HttpServerHandlerBenchmark.java
src/test/java/io/vertx/core/http/Http1xTest.java

HTTP/2 and HTTP/1.x client connection support the HTTP connection shutdown.
This implements HTTP/1.x server connection shutdown in order to fully support this method.
In addition the HTTP connection shutdown method is deprecated and replaced by a version that contains a time unit.

Add support for HTTP 1.x server connection shutdown

---

src/main/java/io/vertx/core/http/HttpConnection.java
src/main/java/io/vertx/core/http/impl/Http1xClientConnection.java
src/main/java/io/vertx/core/http/impl/Http1xConnectionBase.java
src/main/java/io/vertx/core/http/impl/Http2ConnectionBase.java
src/main/java/io/vertx/core/http/impl/Http2UpgradeClientConnection.java

Add to HttpConnection shutdown variants with a time unit for the timeout, deprecate methods with only the timeout in milliseconds.

Deprecate HTTP connection shutdown variants with a timeout value for a variant with a time unit

---

src/main/asciidoc/net.adoc
src/main/java/examples/NetExamples.java
src/main/java/io/vertx/core/eventbus/impl/clustered/ClusteredEventBus.java
src/main/java/io/vertx/core/net/NetClientOptions.java
src/main/java/io/vertx/core/net/impl/NetClientImpl.java
src/main/java/io/vertx/core/net/impl/NetSocketImpl.java
src/test/java/io/vertx/core/net/NetTest.java
src/test/java/io/vertx/core/spi/metrics/MetricsTest.java

Vert.x TCP client does configure the TLS hostname verification algorithm to the empty string which means no checks of the server identity shall be performed beyond checking the validity of the certificate.
This set the default algorithm to null instead of the empty string, any usage of the TCP client must set the verification algorithm when used over TLS, valid values are empty string, HTTPS or LDAPS.
This is a breaking change when using NetClient over TLS.

Explicit configuration of the TCP over TLS client hostname verification

---

src/main/java/io/vertx/core/net/impl/KeyStoreHelper.java
src/test/java/io/vertx/core/net/KeyStoreHelperTest.java

Motivation:
Fix for https://github.com/eclipse-vertx/vert.x/issues/4906 on 4.4 branch
(backport of PR #4910 already merged in 4.x).
The Quarkus 3.2.x LTS release stream still uses the 4.4 releases of Vert.x.
Including this PR in the 4.4 branch propagate it in Quarkus 3.2 LTS next releases.

Use a long password on generated in-memory KeyStore (4.4 branch)

---

src/main/java/io/vertx/core/http/impl/Http1xServerResponse.java
src/main/java/io/vertx/core/http/impl/Http2ServerResponse.java
src/test/java/io/vertx/core/http/Http2ServerTest.java
src/test/java/io/vertx/core/http/HttpTest.java

In `HttpServerResponse#sendFile`, when the offset is greater than the file length, the calculated content length is negative. Currently, the value is not validated until after the head (response status and other headers) is written. An application might have downstream processing that would act on the `IllegalArgumentException` thrown when validating the content length. However, it is too late for the downstream processor to write a different response status (for example a 400 BAD REQUEST), to signal the client that the request is not valid. The problem is exacerbated when the downstream processor tries to write a status code, because the `IllegalStateException` exception will be thrown because the `Response head is already sent`. This leaves the connection hanging on the server side, …

Validate content length early during HttpServerResponse#sendFile

---

src/main/asciidoc/net.adoc

(cherry picked from commit cc1997fa47798e4bdc3252747d4f44636f995d3e)

4.x: Fix asciidoc link syntax in "Client trust configuration" section

---

src/main/java/io/vertx/core/impl/future/CompositeFutureImpl.java
src/main/java/io/vertx/core/impl/future/FailedFuture.java
src/main/java/io/vertx/core/impl/future/FutureImpl.java
src/main/java/io/vertx/core/impl/future/FutureInternal.java
src/main/java/io/vertx/core/impl/future/SucceededFuture.java
src/main/java/io/vertx/core/net/impl/pool/SimpleConnectionPool.java
src/test/java/io/vertx/core/CompositeFutureTest.java
src/test/java/io/vertx/core/FutureInternalTest.java

A `CompositeFuture` should unregister itself against its components when the composite future completes since the composite future is not interested anymore by the completion of the uncompleted futures. Otherwise the composite future might remain forever in the list of a promise pending completion, which could lead in some situation to a memory leak.
The implementation of `CompositeFuture` now does unregister when it completes, the registration against the component new uses the internal listener interface instead of the API `onComplete` method in order to keep a reference to the listener that was registered in order to unregister the same listener. In addition a single listener is now used, reducing the number of listener required to implement the composition behavior to a single …

CompositeFuture implementation must unregister against its component on completion

---

src/main/java/io/vertx/core/net/impl/SSLHelper.java
src/main/java/io/vertx/core/net/impl/TCPServerBase.java
src/test/java/io/vertx/core/http/WebSocketTest.java
src/test/java/io/vertx/core/net/NetTest.java

Backporting https://access.redhat.com/security/cve/CVE-2024-1300

Backport fix for CVE-2024-1300

---

pom.xml
src/main/java/io/vertx/core/impl/ContextBase.java
src/main/java/io/vertx/core/impl/ContextImpl.java
src/main/java/io/vertx/core/impl/ContextInternal.java
src/main/java/io/vertx/core/impl/ContextLocalImpl.java
src/main/java/io/vertx/core/impl/DuplicatedContext.java
src/main/java/io/vertx/core/impl/LocalSeq.java
src/main/java/io/vertx/core/impl/VertxImpl.java
src/main/java/io/vertx/core/spi/context/storage/AccessMode.java
src/main/java/io/vertx/core/spi/context/storage/ContextLocal.java
src/test/benchmarks/io/vertx/core/impl/BenchmarkContext.java
src/test/classpath/customcontextlocal/META-INF/services/io.vertx.core.spi.VertxServiceProvider
src/test/java/io/vertx/core/ContextTest.java
src/test/java/io/vertx/core/FakeContext.java
src/test/java/io/vertx/core/impl/ContextLocalHelper.java
src/test/java/io/vertx/core/spi/tracing/EventBusTracerTestBase.java
src/test/java/io/vertx/core/spi/tracing/HttpTracerTestBase.java
src/test/java/io/vertx/core/spi/tracing/LocalEventBusTracerTest.java
src/test/java/io/vertx/it/CustomContextLocal.java
src/test/java/io/vertx/it/CustomContextLocalTest.java
src/test/java/io/vertx/test/faketracer/FakeTracer.java

The existing implementation uses on a concurrent hash map guarded by the context instance.
This new implementation relies on prior knowledge of the set of context locals, so the context allocates upfront the required space to hold the local storage, reducing synchronisation and simplifying lookup that uses allocated index instead of hashed string lookups.
The existing local context data is retrofit as a context local.

An SPI for interacting with local context storage

---

src/main/java/io/vertx/core/impl/future/FutureBase.java
src/main/java/io/vertx/core/impl/future/Transformation.java
src/test/java/io/vertx/core/FutureTest.java

The `Future` transformation operation keep a reference on the future to transform as an argument of the transformation function that only needs an async result by its design. This can create a leak when a chain of transformation for serialization purpose is used, like in the `SSLHelper` update operation.
Instead the transformation operation should recreate the appropriate async result from the value/failure it obtains to avoid this leak.
Change the transformation operation to remove the ref on the future and instead create a succeeded/failed future to pass to the transformation function.

Future transformation operation should not keep a reference to the creating future

---

src/main/java/io/vertx/core/net/ClientSSLOptions.java
src/main/java/io/vertx/core/net/impl/ChannelProvider.java
src/main/java/io/vertx/core/net/impl/NetSocketImpl.java
src/main/java/io/vertx/core/net/impl/SSLHelper.java
src/main/java/io/vertx/core/net/impl/SslChannelProvider.java
src/main/java/io/vertx/core/net/impl/SslContextProvider.java
src/main/java/io/vertx/core/net/impl/TrustAllOptions.java
src/test/java/io/vertx/core/net/NetTest.java

The `SslContextProvider`/`SslChannelProvider` do not need to handle the trust all flag of the `SslClientOptions` and therefore could be decoupled from that.
Extract the trust all manager in a `TrustAllOptions` implementation configured by the `SSLHelper`, the `SslContextProvide`r/`SslChannelProvider` is now decoupled from this.

Decouple the trust all manager from SslContextHelper/SslChannelProvider

---

src/main/java/io/vertx/core/buffer/Buffer.java

The `Buffer` `toJson` method is being renamed to `JsonValue` since `toJson` is actually used by data object as a convention to convert a data object to a json value. Actually `toJson` should return a base64 representation of the `Buffer` instead of parsing the content and provide an appropriate JSON value mapping.
Deprecate `Buffer` `toJson` in favor of `toJsonValue`.

Deprecate Buffer#toJson in favour of Buffer#toJsonValue

---

src/main/java/io/vertx/core/http/impl/Http1xClientConnection.java
src/test/java/io/vertx/core/http/Http1xTest.java

The `Http1xClientConnection` does close the stream when the response ends ignoring the status of the request. As consequence when a server sends a response and then close the connection, the connection gets recycled and reused to allocate a new stream. Since the connection is still in use, the stream is allocated and parked until the stream that recycled the connection has finished sending the request. When the connection is closed the allocated stream promise is not failed.
This modifies the stream close to happen when both the request and response are ended instead of the response ended only. As consequence a connection is recycled when the request is ended.

HTTP/1.1 stream allocation should only happen when the request and response are ended.

---

src/main/java/io/vertx/core/http/impl/HttpClientImpl.java
src/test/java/io/vertx/core/http/HttpTest.java
src/test/java/io/vertx/test/proxy/HttpProxy.java

Motivation:
Fixes #5136
This can also be fixed by setting the original proxy on `HttpClientRequest` but this way it works with custom handlers.
`WebClient` can be fixed naturally via this commit OR can have its own fix, since it contains other ways to retrieve the proxy in request chain

fix: Dropped proxy on redirect

---

src/main/java/io/vertx/core/http/impl/Http1xServerRequest.java
src/main/java/io/vertx/core/http/impl/Http2ServerRequest.java
src/main/java/io/vertx/core/http/impl/HttpUtils.java
src/test/java/io/vertx/core/http/HttpTest.java

This is a fix for #2797 and https://github.com/eclipse-vertx/vertx-tracing/issues/74
A proposal was made originally by @aruis but it did not address all possible cases, as described in https://www.w3.org/Protocols/rfc2616/rfc2616-sec5.html
This PR covers all cases and adds tests for them.

Refactor HttpUtils#absoluteURI

---

src/main/generated/io/vertx/core/http/HttpServerOptionsConverter.java
src/main/java/io/vertx/core/http/HttpServerOptions.java
src/main/java/io/vertx/core/http/impl/Http1xServerRequest.java
src/main/java/io/vertx/core/http/impl/Http2ServerRequest.java
src/test/java/io/vertx/core/http/HttpServerFileUploadTest.java

Provide configuration for HTTP post request decoder limits rather than using the default limits.

Provide configuration for HTTP post request decoder limits rather than using the default limits

---

src/main/java/io/vertx/core/loadbalancing/LoadBalancer.java
src/main/java/io/vertx/core/spi/loadbalancing/EndpointSelector.java
src/test/java/io/vertx/core/loadbalancing/LoadBalancingCornerCasesTest.java
src/test/java/io/vertx/core/loadbalancing/LoadBalancingTest.java

Fixes #5154
Add Random and Power of 2 choices policies.
Also, adjust the Round Robin policy to handle a special case.

More load balancing policies

---

src/main/java/io/vertx/core/http/impl/Http1xServerRequest.java
src/main/java/io/vertx/core/http/impl/Http2ServerRequest.java
src/test/java/io/vertx/core/http/HttpServerFileUploadTest.java

Fix a regression in `HttpServerRequest#isExpectMultipart` due to the cleanup of the form

HttpServerRequest#isExpectMultipart regression fix

---

pom.xml
src/main/java/io/vertx/core/impl/DeploymentManager.java
src/main/java/io/vertx/core/impl/VertxImpl.java
src/main/java/io/vertx/core/impl/VertxInternal.java
src/main/java/io/vertx/core/impl/VertxWrapper.java
src/main/resources/META-INF/native-image/io.vertx/vertx-core/reflect-config.json
src/test/java/io/vertx/core/ContextTest.java
src/test/java/io/vertx/core/VirtualThreadContextTest.java
src/test/java/io/vertx/core/VirtualThreadDeploymentTest.java
src/test/java/io/vertx/core/eventbus/VirtualThreadEventBusTest.java
src/test/java/io/vertx/core/http/VirtualThreadHttpTest.java
src/test/java/io/vertx/test/core/VertxTestBase.java

A Vertx uses cached reflection to build the virtual thread factory in order to remain compatible with Java 8. When running in a native image Vert.x will assume that the runtime might not have virtual thread incorrectly.
Defer the virtual thread factory availability when a Vertx instance is created, in addition declares that virtual thread factory API should not be cached so the Vertx instance is able to build the virtual thread factory correctly.
Native image metadata are held in the _native-image_ classifier jar since this is experimental and might collide with existing solution for managing native image where framework is embedded.

Vertx should build its virtual thread factory at runtime with correct reflection calls

---

src/main/java/io/vertx/core/http/impl/Http1xServerRequest.java

HTTP/1 server request does execute twice the delivery of the content to the handler.
Remove the context execution in `Http1xServerRequest#handleContent` since this method is already executed on the context by `Http1xServerConnection`.

Remove context execution in Http1xServerRequest#handleContent that is not necessary

---

src/main/java/io/vertx/core/http/HttpServerRequest.java
src/main/java/io/vertx/core/http/impl/Http1xServerRequest.java
src/main/java/io/vertx/core/http/impl/Http2ServerRequest.java
src/main/java/io/vertx/core/http/impl/HttpServerRequestWrapper.java
src/main/java/io/vertx/core/http/impl/HttpUtils.java
src/test/java/io/vertx/core/http/HttpTest.java
src/test/java/io/vertx/core/http/headers/VertxHttpHeadersTest.java
src/test/java/io/vertx/core/http/impl/HttpUtilsTest.java

Close #4588.
This PR adds an option `uriQuerySemicolonIsNormalChar` to `HttpServerOptions` to support treating `;` a normal character instead of query parameter seperator, since it has already been supported in netty `QueryStringDecoder`.
And the default behavior is still to treat `;` as a seperator to ensure compatibility.
References:
- https://github.com/netty/netty/pull/9701
- https://stackoverflow.com/questions/3481664/semicolon-as-url-query-separator

Add option for whether semicolon is treated as normal character or not

---

src/main/java/io/vertx/core/http/HttpServerRequest.java
src/main/java/io/vertx/core/http/impl/Http1xServerRequest.java
src/main/java/io/vertx/core/http/impl/Http2ServerRequest.java
src/main/java/io/vertx/core/http/impl/HttpServerRequestWrapper.java
src/main/java/io/vertx/core/http/impl/HttpUtils.java
src/test/java/io/vertx/core/http/HttpTest.java
src/test/java/io/vertx/core/http/headers/VertxHttpHeadersTest.java
src/test/java/io/vertx/core/http/impl/HttpUtilsTest.java

This PR backports #5150 to `4.x`.
Conformance:

[4.x Backport] Add option for whether semicolon is treated as normal character or not

---

src/main/java/io/vertx/core/http/HttpServer.java
src/main/java/io/vertx/core/http/ServerWebSocket.java
src/main/java/io/vertx/core/http/impl/Http1xClientConnection.java
src/main/java/io/vertx/core/http/impl/Http1xConnection.java
src/main/java/io/vertx/core/http/impl/Http1xServerConnection.java
src/main/java/io/vertx/core/http/impl/Http1xServerRequestHandler.java
src/main/java/io/vertx/core/http/impl/HttpServerImpl.java
src/main/java/io/vertx/core/http/impl/ServerWebSocketHandshaker.java
src/main/java/io/vertx/core/http/impl/ServerWebSocketImpl.java
src/main/java/io/vertx/core/http/impl/WebSocketClientImpl.java
src/main/java/io/vertx/core/http/impl/WebSocketConnection.java
src/main/java/io/vertx/core/http/impl/WebSocketEndpoint.java
src/main/java/io/vertx/core/http/impl/WebSocketImpl.java
src/main/java/io/vertx/core/http/impl/WebSocketImplBase.java
src/main/java/io/vertx/core/http/impl/WebSocketInternal.java
src/main/java/io/vertx/core/net/impl/ConnectionBase.java
src/main/java/io/vertx/core/net/impl/NetClientImpl.java
src/test/java/io/vertx/core/http/WebSocketTest.java
src/test/java/io/vertx/core/spi/metrics/MetricsContextTest.java
src/test/java/io/vertx/core/spi/metrics/MetricsTest.java
src/test/java/io/vertx/test/fakemetrics/FakeHttpServerMetrics.java

Internal refactor of the WebSocket connection implementation
- Move WebSocket related code from `Http1xConnectionBase` to its own `ConnectionBase` subclass in order to simplify `Http1xConnectionBase` and ease its maintenance. The WebSocket connection has now its own Netty handler instead of relying on the HTTP/1.x handler. The HTTP/1.x handler now does not need to take in account WebSocket frames and WebSocket state. 
- Simplify server WebSocket code by moving the code related to WebSocket accept/reject API to a WebSocket implementation that proxies an accepted `WebSocket` using the same approach than `ClientWebSocket`

WebSocket connection

---

src/main/java/io/vertx/core/json/JsonObject.java
src/test/java/io/vertx/core/json/JsonObjectTest.java

Motivation:
The motivation is to fix the bug: https://github.com/eclipse-vertx/vert.x/issues/5185
Context:
The current implementation of JsonObject#equals fails to equate numeric types correctly, leading to false comparisons:
1. `2f` is not considered equal to `2`.
2. `2D` is not considered equal to `2`.
Changes:
This PR updates JsonObject#equals to correctly handle comparisons between different numeric types (float, double, intege, long), ensuring logical equivalence where expected. Additionally, new assertions have been added to JsonObjectTest#testNumberEquality to validate these changes.
This PR tries to fix exactly the same by modifying the JsonObject#equals. Adds new assertions to JsonObjectTest#testNumberEquality.

fix-JsonObject#equals-method-fails-when-comparing-integers-with-floats

---

src/main/java/io/vertx/core/json/JsonObject.java
src/test/java/io/vertx/core/json/JsonObjectTest.java

Motivation:
The motivation is to fix the bug: https://github.com/eclipse-vertx/vert.x/issues/5185
Context:
The current implementation of JsonObject#equals fails to equate numeric types correctly, leading to false comparisons:
2f is not considered equal to 2.
2D is not considered equal to 2.
Changes:
This PR updates JsonObject#equals to correctly handle comparisons between different numeric types (float, double, intege, long), ensuring logical equivalence where expected. Additionally, new assertions have been added to JsonObjectTest#testNumberEquality to validate these changes.
This PR tries to fix exactly the same by modifying the JsonObject#equals. Adds new assertions to JsonObjectTest#testNumberEquality.

Back port fix json object#equals method fails when comparing integers with floats

---

src/main/java/io/vertx/core/http/impl/Http1xClientConnection.java
src/main/java/io/vertx/core/http/impl/Http1xServerConnection.java
src/main/java/io/vertx/core/http/impl/Http1xServerRequest.java
src/main/java/io/vertx/core/http/impl/ServerWebSocketHandshaker.java
src/main/java/io/vertx/core/http/impl/ServerWebSocketImpl.java
src/main/java/io/vertx/core/http/impl/WebSocketConnection.java
src/main/java/io/vertx/core/http/impl/WebSocketImpl.java
src/main/java/io/vertx/core/http/impl/WebSocketImplBase.java
src/main/java/io/vertx/core/net/impl/InboundMessageQueue.java
src/main/java/io/vertx/core/net/impl/NetSocketImpl.java
src/main/java/io/vertx/core/net/impl/VertxConnection.java
src/main/java/io/vertx/core/streams/impl/InboundReadQueue.java
src/test/benchmarks/io/vertx/core/http/impl/HttpServerHandlerBenchmark.java
src/test/java/io/vertx/core/http/Http1xTest.java
src/test/java/io/vertx/core/http/HttpTest.java
src/test/java/io/vertx/core/http/WebSocketTest.java
src/test/java/io/vertx/core/http/impl/Http1xServerConnectionTest.java
src/test/java/io/vertx/core/net/impl/ConnectionBaseTest.java
src/test/java/io/vertx/core/streams/InboundMessageQueueTest.java
src/test/java/io/vertx/core/streams/InboundReadQueueTest.java
src/test/java/io/vertx/test/core/TestUtils.java

The Vert.x event-loop thread to context thread message transfer relies on the `InboundBuffer` implementation.
`InboundBuffer` performs the add/dispatch in the same method call assuming that the same thread actually handles the dispatch of the message, forcing the dispatch to then schedule the message delivery on the context thread.
The `InboundReadQueue` design actually split this operation in two separate operations providing control to the caller of the message dispatch.
- the `add` operation queues a message and let the producer knows whether messages should be drained from the queue (e.g. if a drain operation is already in progress, then there is no need to schedule another drain).
- the `drain` operation let consumer consume messages from the queue until needed
The event-loop to …

Provide a better event-loop to context message transfer queue

---

src/main/asciidoc/http.adoc
src/main/java/examples/HTTPExamples.java
src/main/java/io/vertx/core/Expectation.java
src/main/java/io/vertx/core/Future.java
src/main/java/io/vertx/core/http/HttpClientResponse.java
src/main/java/io/vertx/core/http/HttpResponseExpectation.java
src/main/java/io/vertx/core/http/HttpResponseHead.java
src/main/java/io/vertx/core/impl/future/Expect.java
src/main/java/io/vertx/core/impl/future/FutureBase.java
src/test/java/io/vertx/core/ExpectationTest.java
src/test/java/io/vertx/core/FutureTest.java
src/test/java/io/vertx/core/http/HttpResponseExpectationTest.java

`Future` control flow using predicates.
`Future` has already synchronous operations modifying the control flow
- `map` : transforms a mapper failure into a failed future (e.g. `future.map(val -> throw new VertxException())`)
- `otherwise` : transforms a failure into a success
This contribution aims to transform a success into a failure based on the result of a predicate.
Goals
- capture useful predicates that modify the control flow, e.g. a predicate that checks the HTTP client response  (status code, headers, etc...)
- provide inline guards using lambda expressions
Vert.x Web Client has something close to this with HTTP expectations:
```java
client
.get(8080, "myserver.mycompany.com", "/some-uri")
.expect(ResponsePredicate.SC_SUCCESS)
.expect(ResponsePredicate.JSON)
.send() …
```

Future control flow using predicates

---

src/main/generated/io/vertx/core/http/RequestOptionsConverter.java
src/main/java/io/vertx/core/http/RequestOptions.java
src/main/java/io/vertx/core/http/impl/HttpClientImpl.java
src/main/java/io/vertx/core/impl/HostnameResolver.java
src/main/java/io/vertx/core/loadbalancing/ConsistentHashingSelector.java
src/main/java/io/vertx/core/loadbalancing/LoadBalancer.java
src/main/java/io/vertx/core/loadbalancing/LoadBalancer2.java
src/main/java/io/vertx/core/net/impl/endpoint/EndpointManager.java
src/main/java/io/vertx/core/net/impl/resolver/EndpointResolverImpl.java
src/main/java/io/vertx/core/spi/loadbalancing/DefaultEndpointMetrics.java
src/main/java/io/vertx/core/spi/loadbalancing/Endpoint.java
src/main/java/io/vertx/core/spi/loadbalancing/EndpointSelector.java
src/main/java/io/vertx/core/spi/resolver/address/AddressResolver.java
src/main/java/io/vertx/core/spi/resolver/address/EndpointListBuilder.java
src/main/java/io/vertx/core/spi/resolver/endpoint/EndpointResolver.java
src/test/java/io/vertx/core/http/HttpTest.java
src/test/java/io/vertx/core/http/ResolvingHttpClientTest.java
src/test/java/io/vertx/core/loadbalancing/LoadBalancingCornerCasesTest.java
src/test/java/io/vertx/core/loadbalancing/LoadBalancingTest.java
src/test/java/io/vertx/test/fakeloadbalancer/FakeLoadBalancer.java
src/test/java/io/vertx/test/fakeresolver/FakeAddressResolver.java
src/test/java/io/vertx/test/fakeresolver/FakeState.java

Routing key based load balancing with consistent hashing implementation

---

src/main/java/io/vertx/core/http/impl/Http1xServerRequest.java
src/main/java/io/vertx/core/streams/impl/InboundBuffer.java
src/test/java/io/vertx/core/streams/InboundBufferTest.java

This patch improve Quarkus techempower plaintext throughput of ~5% in our lab; nothing fancy but seems related to the excessive synchronization which, by using instance field to synchronize with, doesn't allow the JVM to perform the https://shipilev.net/jvm/anatomy-quarks/1-lock-coarsening-for-loops/ (lock coarsening) optimization.
I've applied an optimization to `onEnd` which benefit vertx as well, which often observe non-paused requests 
i.e. reducing the synchronization over the connection while completing the request.

Fix InboundBuffer::pause & write performance

---

src/main/java/io/vertx/core/http/impl/Http1xServerConnection.java

The `Http1xServerConnection` synchronize itself to guard the internal state of the request/response in progress.
Such synchronization used to be useful before Vert.x 4 and the clear dispatch between connection/request code. Currently read and writes are confined in the event-loop thread and removing this synchronization has no effect on the read/writes of this state.

Remove un-necessary Http1xServerConnection internal state synchronised access

---

src/main/java/io/vertx/core/Context.java
src/main/java/io/vertx/core/ServiceHelper.java
src/main/java/io/vertx/core/VertxOptions.java
src/main/java/io/vertx/core/file/FileSystemOptions.java
src/main/java/io/vertx/core/file/impl/FileResolverImpl.java
src/main/java/io/vertx/core/http/HttpHeaders.java
src/main/java/io/vertx/core/http/impl/HttpServerImpl.java
src/main/java/io/vertx/core/impl/ContextImpl.java
src/main/java/io/vertx/core/impl/SysProps.java
src/main/java/io/vertx/core/impl/VertxBuilder.java
src/main/java/io/vertx/core/impl/logging/LoggerFactory.java
src/main/java/io/vertx/core/impl/verticle/CompilingClassLoader.java
src/main/java/io/vertx/core/json/impl/JsonUtil.java
src/main/java/io/vertx/core/spi/dns/AddressResolverProvider.java
src/main/java/io/vertx/core/spi/metrics/Metrics.java
src/test/benchmarks/io/vertx/benchmarks/ContextBenchmark.java
src/test/benchmarks/io/vertx/core/http/impl/HttpServerHandlerBenchmark.java
src/test/java/io/vertx/core/impl/logging/LoggingBackendSelectionTest.java
src/test/java/io/vertx/core/impl/logging/NoExceptionInInitializerErrorTest.java

Core system properties cleanup

---

pom.xml
src/main/java/io/vertx/core/http/HttpHeaders.java
src/main/java/io/vertx/core/http/impl/Http1xClientConnection.java
src/test/java/io/vertx/core/http/Http1xZstdCompressionTest.java
src/test/java/io/vertx/core/http/Http2ClientTest.java

Netty supports zstd compression.
Google Chrome recently added support for zstd
https://www.phoronix.com/news/Zstd-1.5.6-Zstandard

support zstd compression

---

src/test/java/io/vertx/core/file/FileResolverTestBase.java
src/test/java/io/vertx/core/file/FileSystemTest.java
src/test/java/io/vertx/core/http/Http1xTest.java
src/test/java/io/vertx/core/http/Http2ClientTest.java
src/test/java/io/vertx/core/http/Http2Test.java
src/test/java/io/vertx/core/http/HttpBandwidthLimitingTest.java
src/test/java/io/vertx/core/http/HttpClientConnectionTest.java
src/test/java/io/vertx/core/http/HttpClientTimeoutTest.java
src/test/java/io/vertx/core/http/HttpTest.java
src/test/java/io/vertx/core/http/ResolvingHttpClientTest.java
src/test/java/io/vertx/core/net/NetTest.java
src/test/java/io/vertx/core/shareddata/AsyncMapTest.java
src/test/java/io/vertx/core/spi/tracing/HttpTracingTestBase.java
src/test/java/io/vertx/it/SSLEngineTest.java
src/test/java/io/vertx/test/core/AssertExpectations.java

Replace future.andThen(onSuccess(A)) by future.expecting(that(P)) in vertx tests.

Improve tests by replacing onSuccess (which fails the test) by expecting which fails the future and the flow

---

src/main/asciidoc/streams.adoc
src/main/java/examples/StreamsExamples.java
src/main/java/io/vertx/core/streams/ReadStream.java
src/test/java/io/vertx/core/streams/ReadStreamReduceTest.java

Add a general purpose collecting method to ReadStream to facilitate the reduction of streams. The collecting method is a default method.

Read stream collect

---

src/main/java/io/vertx/core/file/impl/AsyncFileImpl.java
src/test/java/io/vertx/core/http/Http2Test.java

The `AsyncFile` implementation will continue to read the file when the handler is set to null, instead it should stop reading. In addition report async file exception to the context when no exception handler is set.

Async file should stop reading the file when the handler is null

---

src/main/java/io/vertx/core/spi/context/storage/AccessMode.java
src/main/java/io/vertx/core/spi/context/storage/ConcurrentAccessMode.java
src/test/benchmarks/io/vertx/benchmarks/AccessModeBenchmark.java

This is fixing #5216 
Benchmarks results show the improvement (magnified by clearly the "nano"-benchmarking effect):
```
Benchmark                   Mode  Cnt  Score   Error  Units
AccessModeBenchmark.getNew  avgt   20  0.835 ± 0.008  ns/op
AccessModeBenchmark.getOld  avgt   20  6.253 ± 0.065  ns/op
AccessModeBenchmark.putNew  avgt   20  1.921 ± 0.012  ns/op
AccessModeBenchmark.putOld  avgt   20  8.474 ± 0.211  ns/op
```

AccessMode.CONCURRENT's VarHandle should be a constant (Fixes #5216)

---

src/main/java/io/vertx/core/http/impl/Http2ServerStream.java
src/main/java/io/vertx/core/http/impl/VertxHttp2ConnectionHandler.java
src/main/java/io/vertx/core/http/impl/VertxHttp2Stream.java
src/test/java/io/vertx/core/http/Http1xMetricsTest.java
src/test/java/io/vertx/core/http/Http1xWorkerMetricsTest.java
src/test/java/io/vertx/core/http/Http2MetricsTest.java
src/test/java/io/vertx/core/http/HttpMetricsTestBase.java

- Incorrect HTTP server metrics report for non event-loop thread writes #5222
- HTTP/2 push is not flushed when written from a non event-loop thread #5223

Fix a few bugs related to non event-loop thread writes

---

src/main/java/io/vertx/core/http/impl/Http2ServerStream.java
src/main/java/io/vertx/core/http/impl/VertxHttp2ConnectionHandler.java
src/main/java/io/vertx/core/http/impl/VertxHttp2Stream.java
src/test/java/io/vertx/core/http/Http1xMetricsTest.java
src/test/java/io/vertx/core/http/Http1xWorkerMetricsTest.java
src/test/java/io/vertx/core/http/Http2MetricsTest.java
src/test/java/io/vertx/core/http/HttpMetricsTestBase.java

- Incorrect HTTP server metrics report for non event-loop thread writes #5222
- HTTP/2 push is not flushed when written from a non event-loop thread #5223

Fix a few bugs related to non event-loop thread writes.

---

src/main/java/io/vertx/core/json/JsonArray.java
src/main/java/io/vertx/core/json/JsonObject.java
src/test/java/io/vertx/core/json/JsonObjectTest.java

The code to compare two numbers in json object/array does not correctly compare BigInteger/BigDecimal values.
Fix this issue and also simplify / refactor this code to be more compact and reused between object/array

Fix json object/array BigInteger/BidDecimal value comparison

---

src/main/java/io/vertx/core/json/jackson/JacksonCodec.java

The JacksonCodec implementation of toString/toBuffer lacks of efficiency compared to the DatabindCodec implementation which uses the buffer recyler of Jackson.
Update the JacksonCodec implementation to use the buffer recycler instead.

JacksonCodec use recycler pool

---

vertx-core/pom.xml
vertx-core/src/main/java/io/vertx/core/VertxOptions.java
vertx-core/src/main/java/io/vertx/core/impl/VertxBuilder.java
vertx-core/src/main/java/io/vertx/core/impl/VertxImpl.java

vertx-core does not need to depend on netty-transport-native-XXX instead it can depend on netty-transport-classes-XXX

Improve native dependencies of vertx-core

---

vertx-core/src/main/java/io/vertx/core/http/impl/HttpNetSocket.java
vertx-core/src/main/java/io/vertx/core/net/NetSocket.java
vertx-core/src/main/java/io/vertx/core/net/impl/NetSocketImpl.java
vertx-core/src/test/java/io/vertx/tests/net/NetTest.java

Modify the TCP SSL tests to run the server and client on different event loops.
As consequence the TLS upgrade tests fail intermittently due to a race where the client can receive the server message then proceeds to upgrade while the server has not yet switched to upgrade mode and will receive the upgrade in plain text. Therefore there is an update of the upgrade method to give the opportunity to send a message and guarantee this message is sent after the upgrade configures the pipeline correctly.
Make sure also tests running with TLSv1.3 fails differently on the client for client authentication.

Various SSL improvements

---

vertx-core/src/main/java/io/vertx/core/impl/DeploymentManager.java
vertx-core/src/main/java/io/vertx/core/impl/VertxImpl.java
vertx-core/src/main/java/io/vertx/core/internal/VertxInternal.java
vertx-core/src/main/java/io/vertx/core/internal/VertxWrapper.java
vertx-core/src/test/java/io/vertx/tests/deployment/DeploymentTest.java

The deployment manager will create an event-loop per worker verticle instance, like it does for event-loop verticles.
As consequence a worker server will be scaled on that number of event-loop while being processed on the same number of workers.
There is no strong interest for this use case and a single event-loop might actually work better and consume less resources.
This modify the worker deployment to use a single event-loop per worker instances in a deployment.
We might add later a setting to control this, e.g. specify the number of event-loop that shall be created per worker deployment.

Use a single event-loop per worker/virtual-thread verticle deployment instances

---

vertx-core/src/main/java/io/vertx/core/internal/concurrent/OutboundMessageQueue.java
vertx-core/src/test/java/io/vertx/tests/concurrent/OutboundMessageQueueTest.java

An outbound message queue might schedule a drain operation and get closed. When the drain happens, it should check that it has not been closed since the queue elements are not present and the queue does not expect a drain.

The outbound message queue should not try to drain its write queue after it has been closed

---

vertx-core/src/main/java/io/vertx/core/ThreadingModel.java
vertx-core/src/main/java/io/vertx/core/http/impl/Http1xClientConnection.java
vertx-core/src/main/java/io/vertx/core/impl/ContextBase.java
vertx-core/src/main/java/io/vertx/core/impl/ContextImpl.java
vertx-core/src/main/java/io/vertx/core/impl/DuplicatedContext.java
vertx-core/src/main/java/io/vertx/core/impl/EventExecutor.java
vertx-core/src/main/java/io/vertx/core/impl/EventLoopExecutor.java
vertx-core/src/main/java/io/vertx/core/impl/ShadowContext.java
vertx-core/src/main/java/io/vertx/core/impl/VertxImpl.java
vertx-core/src/main/java/io/vertx/core/impl/WorkerExecutor.java
vertx-core/src/main/java/io/vertx/core/impl/WorkerExecutorImpl.java
vertx-core/src/main/java/io/vertx/core/impl/WorkerPool.java
vertx-core/src/main/java/io/vertx/core/internal/ContextInternal.java
vertx-core/src/test/benchmarks/io/vertx/benchmarks/BenchmarkContext.java
vertx-core/src/test/java/io/vertx/tests/context/ContextTest.java
vertx-core/src/test/java/io/vertx/tests/context/ShadowContextTest.java
vertx-core/src/test/java/io/vertx/tests/eventbus/ClusteredEventBusTest.java
vertx-core/src/test/java/io/vertx/tests/eventbus/EventBusInterceptorTest.java
vertx-core/src/test/java/io/vertx/tests/http/HttpTest.java
vertx-core/src/test/java/io/vertx/tests/net/NetTest.java
vertx-core/src/test/java/io/vertx/tests/timer/TimerTest.java
vertx-core/src/test/java/module-info.java

A shadow context is a vertx context that references a context belonging to a different vertx instance.
Such context enables the usage of a vertx instance (e.g. a client) from another vertx instance and ensure that callbacks are on the correct thread.
One use case is the usage of a Vert.x client from a Vert.x server with different instances. This provides event-loop segregation between vertx instance ensuring that the server event-loop only process server IO and are disjoint from the client io operations.
Shadow context happens when a context is obtained from a vertx thread of another vertx instance:
```java
Context ctx = vertx1.getOrCreateContext();
ctx.runOnContext(v1 -> {
Thread expected = Thread.currentThread();
Context shadowCtx = vertx2.getOrCreateContext();
shadowCtx.runOnContext(v2 …
```

Shadow context

---

vertx-core/pom.xml
vertx-core/src/main/java/io/vertx/core/ThreadingModel.java
vertx-core/src/main/java/io/vertx/core/Vertx.java
vertx-core/src/main/java/io/vertx/core/impl/ContextBase.java
vertx-core/src/main/java/io/vertx/core/impl/ContextImpl.java
vertx-core/src/main/java/io/vertx/core/impl/DuplicatedContext.java
vertx-core/src/main/java/io/vertx/core/impl/EventLoopExecutor.java
vertx-core/src/main/java/io/vertx/core/impl/ShadowContext.java
vertx-core/src/main/java/io/vertx/core/impl/VertxBootstrapImpl.java
vertx-core/src/main/java/io/vertx/core/impl/VertxImpl.java
vertx-core/src/main/java/io/vertx/core/impl/VertxThread.java
vertx-core/src/main/java/io/vertx/core/impl/WorkerExecutor.java
vertx-core/src/main/java/io/vertx/core/internal/ContextInternal.java
vertx-core/src/main/java/io/vertx/core/internal/EventExecutor.java
vertx-core/src/main/java/io/vertx/core/internal/VertxBootstrap.java
vertx-core/src/main/java/io/vertx/core/spi/context/executor/EventExecutorProvider.java
vertx-core/src/main/java/module-info.java
vertx-core/src/test/benchmarks/io/vertx/benchmarks/BenchmarkContext.java
vertx-core/src/test/classpath/customeventexecutor/META-INF/services/io.vertx.core.spi.VertxServiceProvider
vertx-core/src/test/java/io/vertx/it/eventexecutor/CustomEventExecutorProvider.java
vertx-core/src/test/java/io/vertx/it/eventexecutor/CustomEventExecutorTest.java
vertx-core/src/test/java/io/vertx/it/eventexecutor/CustomThread.java
vertx-core/src/test/java/io/vertx/tests/context/ContextTest.java
vertx-core/src/test/java/io/vertx/tests/context/EventExecutorProviderTest.java
vertx-core/src/test/java/io/vertx/tests/context/ShadowContextTest.java

An SPI that associates `EventExecutor` for non Vertx thread.
The use case is the utilisation of vertx based middleware from a non vertx thread, allowing callbacks from vertx (futures/event) to be processed by an executor provided by the framework, i.e. let the embedder execute the tasks on the thread of their choice instead of an event-loop context.

EventExecutor provide SPI

---

vertx-core/src/main/java/io/vertx/core/impl/DeploymentManager.java
vertx-core/src/test/java/io/vertx/tests/deployment/DeploymentTest.java

When a vertx instance is closed, there might be pending verticles in deployment which might leave resources unreleased.
When a verticle is deploying and not yet deployed, we should keep track of it until it is deployed, when the deployment manager undeploys all verticles, it should first check the pending deployments and fail their start promise.

Fail pending deployments when a vertx instance is closed

---

vertx-core/src/main/java/io/vertx/core/impl/HAManager.java
vertx-core/src/test/java/io/vertx/tests/ha/HAQuorumTest.java

Fixes #5272
The key idea is to wait until `clusterMap` get information from other nodes like it done in `nodeAdded` method.

HAManager couldn't see quorum if during its initialization cluster manager has all nodes joined already #5272

---

vertx-core/src/main/java/io/vertx/core/eventbus/impl/HandlerRegistration.java
vertx-core/src/test/java/io/vertx/tests/eventbus/EventBusTestBase.java

Instead it should be on the caller context.

Unregistration of an event-bus consumer is performed on the consumer context

---

vertx-core/src/main/java/io/vertx/core/impl/VertxImpl.java
vertx-core/src/main/java/io/vertx/core/spi/context/executor/EventExecutorProvider.java
vertx-core/src/test/java/io/vertx/it/eventexecutor/CustomEventExecutorProvider.java
vertx-core/src/test/java/io/vertx/tests/context/EventExecutorProviderTest.java

So that the provider does not need to implement inThread since it can be achieved internally by Vert.x

Improve the event executor SPI

---

vertx-core/src/main/java/io/vertx/core/Future.java
vertx-core/src/main/java/io/vertx/core/impl/WorkerExecutor.java
vertx-core/src/test/java/io/vertx/it/tls/ConnectToTLSTrustedServerTest.java
vertx-core/src/test/java/io/vertx/it/vertx/ExecutorServiceFactoryTest.java
vertx-core/src/test/java/io/vertx/test/proxy/HttpProxy.java
vertx-core/src/test/java/io/vertx/tests/context/ContextTest.java
vertx-core/src/test/java/io/vertx/tests/deployment/VirtualThreadDeploymentTest.java
vertx-core/src/test/java/io/vertx/tests/eventbus/MessageQueueOnWorkerThreadTest.java
vertx-core/src/test/java/io/vertx/tests/future/FutureAwaitTest.java
vertx-core/src/test/java/io/vertx/tests/future/FutureTest.java
vertx-core/src/test/java/io/vertx/tests/http/Http1xTest.java
vertx-core/src/test/java/io/vertx/tests/http/HttpClientTimeoutTest.java
vertx-core/src/test/java/io/vertx/tests/http/HttpTest.java
vertx-core/src/test/java/io/vertx/tests/http/VirtualThreadHttpTest.java
vertx-core/src/test/java/io/vertx/tests/http/WebSocketTest.java
vertx-core/src/test/java/io/vertx/tests/metrics/MetricsTest.java
vertx-core/src/test/java/io/vertx/tests/tls/HttpTLSTest.java
vertx-core/src/test/java/io/vertx/tests/vertx/CloseFutureTest.java
vertx-core/src/test/java/io/vertx/tests/vertx/VertxBootstrapTest.java
vertx-core/src/test/java/io/vertx/tests/vertx/VertxTest.java

Motivation:
`Future#await()` was initially meant to be called by a vertx virtual thread and reject any other  thread. However this method can facilitate the workflow of synchrononous thread interacting with a vertx runtime, e.g. a unit test, from non-vertx threads.
Changes:
Change the implementation of `Future#await()` to permit non-vertx thread to block until the future completes. In addition a variant with a timeout has been added which can be useful for testing.
Results:
Any non-vertx thread can now await a future.

Calling Future#await() from a non vertx thread should be allowed.

---

src/main/java/io/vertx/core/ServiceHelper.java

Motivation:
The ServiceHelper utility class is mostly used internally by vertx service providers to load plugins. Users should not use this class. In addition service loading strategies might change in Vert.x 5 due to the support of JPMS. In addition this reduces the API surface.
Changes:
Deprecate io.vertx.core.ServiceHelper
Result:
ServiceHelper is deprecated.

Deprecate io.vertx.core.ServiceHelper

---

src/main/java/io/vertx/core/http/impl/Http1xServerRequest.java
src/main/java/io/vertx/core/http/impl/HttpServerRequestInternal.java
src/main/java/io/vertx/core/http/impl/HttpServerRequestWrapper.java
src/main/java/io/vertx/core/net/impl/HostAndPortImpl.java
src/test/benchmarks/io/vertx/core/net/impl/HostAndPortBenchmark.java
src/test/java/io/vertx/core/http/Http1xTest.java
src/test/java/io/vertx/core/net/impl/HostAndPortTest.java

Using machines which provide `Host` headers in the form "y.x.z.w:port" (ith y, x, z, w numeric) will cause `HostAndPortImpl ::parseHost` to execute an additional `parseRegName` because `parseIPv4Address` returns `-1`, failing to detect the address as a valid numeric address with a maybe valid port.

Save parsing twice numeric IPv4 address

---

src/main/asciidoc/override/verticles.adoc

(cherry picked from commit 31a03d7ae8075d29519272214989e111ef4e374e)
Motivation:
Avoid callback handlers in the MyVerticle examples, use a Future instead.
Conformance:

Futurize MyVerticle start/stop example - backport to 4.x

---

vertx-core/src/main/asciidoc/http.adoc
vertx-core/src/main/java/io/vertx/core/http/HttpHeaders.java
vertx-core/src/main/java/io/vertx/core/http/impl/Http1xClientConnection.java
vertx-core/src/test/java/io/vertx/tests/http/Http2ClientTest.java
vertx-core/src/test/java/io/vertx/tests/http/compression/Http1xSnappyCompressionTest.java

Motivation:
Support snappy as a compression mechanism 
Explain here the context, and why you're making that change, what is the problem you're trying to solve.
Similar to https://github.com/eclipse-vertx/vert.x/pull/5176/files but Snappy support is already inside netty so I don't need to include any other dependencies
Conformance:

Support snappy compression

---

vertx-core/src/main/java/io/vertx/core/eventbus/EventBusOptions.java
vertx-core/src/main/java/io/vertx/core/eventbus/impl/clustered/ClusteredEventBus.java
vertx-core/src/main/java/io/vertx/core/impl/VertxBootstrapImpl.java
vertx-core/src/main/java/io/vertx/core/impl/VertxImpl.java
vertx-core/src/main/java/io/vertx/core/spi/cluster/ClusterManager.java
vertx-core/src/main/java/io/vertx/core/spi/cluster/RegistrationListener.java
vertx-core/src/main/java/io/vertx/core/spi/cluster/impl/DefaultNodeSelector.java
vertx-core/src/main/java/io/vertx/core/spi/cluster/impl/NodeSelector.java
vertx-core/src/test/java/io/vertx/test/fakecluster/FakeClusterManager.java
vertx-core/src/test/java/io/vertx/tests/eventbus/ClusteredEventBusTest.java
vertx-core/src/test/java/io/vertx/tests/eventbus/ClusteredEventBusTestBase.java
vertx-core/src/test/java/io/vertx/tests/eventbus/CustomNodeSelectorTest.java
vertx-core/src/test/java/io/vertx/tests/eventbus/MessageQueueOnWorkerThreadTest.java
vertx-core/src/test/java/io/vertx/tests/eventbus/WrappedClusterManager.java
vertx-core/src/test/java/io/vertx/tests/eventbus/WrappedNodeSelector.java
vertx-core/src/test/java/io/vertx/tests/eventbus/WriteHandlerLookupFailureTest.java

Motivation:
The `NodeSelector` interface has currently a single implementation and is exposed to the cluster manager. The `NodeSelector` interface combines two API, an API selecting node used by the event bus, an API for broadcasting changes to the node selector implementation used by the cluster manager. The cluster manager exposed API should be reduced to the methods it is intended to use, this also allows to reduce the SPI surface of the cluster manager SPI.
Changes:
Extract the `RegistrationListener` out of `NodeSelector`, the `ClusterManager` interface gets getter/setter for the registration listener, similar to the `NodeListener`.
The `NodeSelector` is moved to the cluster manager SPI impl package and is not exposed anymore.
This is an SPI breaking change.

Decouple the cluster manager interface from NodeSelector and make this class an implementation details

---

src/main/java/io/vertx/core/impl/launcher/VertxLifecycleHooks.java
src/main/java/io/vertx/core/impl/launcher/commands/BareCommand.java
src/test/java/io/vertx/core/impl/launcher/LauncherExtensibilityTest.java

Given methods like TracingOptions#setTracer have been deprecated, a new hook can help users configure the Vert.x instance.

Vertx lifecycle hook for VertxBuilder customization

---

vertx-core/src/main/java/io/vertx/core/MultiMap.java
vertx-core/src/main/java/io/vertx/core/datagram/impl/DatagramSocketImpl.java
vertx-core/src/main/java/io/vertx/core/http/impl/Http1xClientConnection.java
vertx-core/src/main/java/io/vertx/core/http/impl/Http1xServerConnection.java
vertx-core/src/main/java/io/vertx/core/http/impl/headers/HeadersMultiMap.java
vertx-core/src/main/java/io/vertx/core/internal/buffer/BufferInternal.java
vertx-core/src/main/java/io/vertx/core/internal/http/HttpHeadersInternal.java
vertx-core/src/main/java/io/vertx/core/net/impl/NetSocketImpl.java
vertx-core/src/main/java/io/vertx/core/net/impl/VertxHandler.java
vertx-core/src/main/java/module-info.java
vertx-core/src/test/java/io/vertx/test/core/FileDescriptorLeakDetectorRule.java
vertx-core/src/test/java/io/vertx/test/core/VertxTestBase.java
vertx-core/src/test/java/io/vertx/tests/eventbus/CustomNodeSelectorTest.java
vertx-core/src/test/java/io/vertx/tests/eventbus/MessageQueueOnWorkerThreadTest.java
vertx-core/src/test/java/io/vertx/tests/eventbus/WriteHandlerLookupFailureTest.java
vertx-core/src/test/java/io/vertx/tests/metrics/MetricsContextTest.java
vertx-core/src/test/java/io/vertx/tests/vertx/VertxBootstrapTest.java
vertx-core/src/test/java/module-info.java

Also update the tests jar for more reusability in projects relying on it for their testing.

Expose some of the implementation to internals required by MQTT

---

vertx-core/src/test/java/io/vertx/tests/http/Http1xTest.java

that needs to probe the actual time to send a chunked file to pass reliably independantly of the test env.

Improve Http1xTest#testHttpServerWithIdleTimeoutSendChunkedFile

---

vertx-core/src/main/java/io/vertx/core/http/impl/CleanableHttpClient.java
vertx-core/src/main/java/io/vertx/core/http/impl/Http1xClientConnection.java
vertx-core/src/main/java/io/vertx/core/http/impl/Http1xServerRequest.java
vertx-core/src/main/java/io/vertx/core/http/impl/VertxHttp2Stream.java
vertx-core/src/main/java/io/vertx/core/http/impl/WebSocketImplBase.java
vertx-core/src/main/java/io/vertx/core/impl/ContextBase.java
vertx-core/src/main/java/io/vertx/core/impl/ContextImpl.java
vertx-core/src/main/java/io/vertx/core/impl/DuplicatedContext.java
vertx-core/src/main/java/io/vertx/core/impl/EventLoopExecutor.java
vertx-core/src/main/java/io/vertx/core/impl/ShadowContext.java
vertx-core/src/main/java/io/vertx/core/impl/VertxImpl.java
vertx-core/src/main/java/io/vertx/core/internal/ContextInternal.java
vertx-core/src/main/java/io/vertx/core/internal/concurrent/InboundMessageQueue.java
vertx-core/src/main/java/io/vertx/core/internal/http/HttpClientInternal.java
vertx-core/src/main/java/io/vertx/core/net/impl/NetSocketImpl.java
vertx-core/src/main/java/io/vertx/core/streams/impl/InboundReadQueue.java
vertx-core/src/test/java/io/vertx/benchmarks/BenchmarkContext.java
vertx-core/src/test/java/io/vertx/tests/concurrent/InboundMessageQueueTest.java
vertx-core/src/test/java/module-info.java

- as we want to drop InboundBuffer, make InboundMessageQueue more flexible
- expose redirect handler on HttpClientInternal used by vertx-web-client

Various JPMS related changes

---

src/main/java/io/vertx/core/http/impl/ServerWebSocketImpl.java
src/test/java/io/vertx/core/http/WebSocketTest.java

Motivation:
When we upgrade a WebSocket request, the pre-existing headers set on the response are ignored. This PR attempts to fix this issue by reusing the response.header when doing the websocket handshake.
Conformance:

Use pre existing response headers to do websocket handshake

---

vertx-core/src/main/java/io/vertx/core/http/impl/ServerWebSocketHandshaker.java
vertx-core/src/test/java/io/vertx/tests/http/WebSocketTest.java

Motivation:
Same as #5324 but on master.
Conformance:

Use pre-existing response headers to do websocket handshake

---

vertx-core/src/main/java/io/vertx/core/http/HttpClientAgent.java
vertx-core/src/main/java/io/vertx/core/http/impl/DefaultRedirectHandler.java
vertx-core/src/main/java/io/vertx/core/http/impl/HttpClientImpl.java

_Motivation:_
This is useful for building redirect handlers
for clients that need to delegate to the default behavior. In Quarkus we will leverage this to get rid of the deprecated (and since removed) [calls](https://github.com/quarkusio/quarkus/blob/3.15.1/independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/impl/ClientImpl.java#L209-L210) to redirectHandler

Provide access to the default redirect handler

---

src/main/java/io/vertx/core/http/impl/Http1xServerResponse.java
src/main/java/io/vertx/core/http/impl/Http2ServerResponse.java
src/main/java/io/vertx/core/http/impl/HttpClientRequestImpl.java
src/main/java/io/vertx/core/http/impl/HttpUtils.java
src/test/benchmarks/io/vertx/benchmarks/ContentLengthToString.java

Not a biggie, but currently small content-length (0-255) require allocating  (and parsing) a fresh new `String` value.
This is clearly bad for benchmarks - but not only.
I'm adding a lazy cache (of small) content length `String`s, to speeup both http 1.1 and 2.
the benchmark shows 
```Benchmark                                     (maxContentLength)  Mode  Cnt  Score   Error  Units
ContentLengthToString.contentLengthHttpUtils                 255  avgt   20  1.094 ± 0.002  ns/op
ContentLengthToString.contentLengthHttpUtils                 511  avgt   20  7.479 ± 0.164  ns/op
ContentLengthToString.contentLengthHttpUtils                1023  avgt   20  6.822 ± 0.182  ns/op
ContentLengthToString.contentLengthToString                  255  avgt   20  7.876 ± 0.024  ns/op …
```

Small content-length values caching

---

vertx-core/src/main/asciidoc/http.adoc
vertx-core/src/main/java/examples/HTTPExamples.java
vertx-core/src/main/java/io/vertx/core/http/HttpServer.java
vertx-core/src/main/java/io/vertx/core/http/ServerWebSocket.java
vertx-core/src/main/java/io/vertx/core/http/ServerWebSocketHandshake.java
vertx-core/src/main/java/io/vertx/core/http/WebSocketConnection.java
vertx-core/src/main/java/io/vertx/core/http/impl/Http1xClientConnection.java
vertx-core/src/main/java/io/vertx/core/http/impl/Http1xServerConnection.java
vertx-core/src/main/java/io/vertx/core/http/impl/Http1xServerRequest.java
vertx-core/src/main/java/io/vertx/core/http/impl/Http1xServerRequestHandler.java
vertx-core/src/main/java/io/vertx/core/http/impl/HttpServerConnectionHandler.java
vertx-core/src/main/java/io/vertx/core/http/impl/HttpServerImpl.java
vertx-core/src/main/java/io/vertx/core/http/impl/ServerWebSocketHandshaker.java
vertx-core/src/main/java/io/vertx/core/http/impl/ServerWebSocketImpl.java
vertx-core/src/main/java/io/vertx/core/http/impl/WebSocketConnectionImpl.java
vertx-core/src/test/java/io/vertx/test/fakemetrics/FakeHttpServerMetrics.java
vertx-core/src/test/java/io/vertx/tests/http/WebSocketTest.java
vertx-core/src/test/java/io/vertx/tests/metrics/MetricsTest.java

Motivation:
The server WebSocket API can control handshake implicitly (e.g. sending a message) or explicitly (accept or any WebSocket interaction). This result in a more complex implementation than it should be for such API.
Changes:
Extract the handshake API of the `ServerWebSocket` API in a new `ServerWebSocketHandshake` API for which an handler can be set when WebSocket handshake needs to be controlled.

Decouple the handshake part ServerWebSocket API

---

vertx-core/src/main/java/io/vertx/core/MultiMap.java
vertx-core/src/main/java/io/vertx/core/datagram/DatagramPacket.java
vertx-core/src/main/java/io/vertx/core/dns/MxRecord.java
vertx-core/src/main/java/io/vertx/core/dns/SrvRecord.java
vertx-core/src/main/java/io/vertx/core/file/FileProps.java
vertx-core/src/main/java/io/vertx/core/file/FileSystemProps.java
vertx-core/src/main/java/io/vertx/core/http/Cookie.java
vertx-core/src/main/java/io/vertx/core/http/HttpFrame.java
vertx-core/src/main/java/io/vertx/core/http/WebSocketFrame.java
vertx-core/src/main/java/io/vertx/core/net/SelfSignedCertificate.java
vertx-core/src/main/java/io/vertx/core/parsetools/JsonEvent.java

MultiMap, DatagramPacket, MxRecord, SrvRecord, FilePropos, FileSystemProps, Cookie, HttpFrame, WebSocketFrame, JsonEvent, SelfSignedCertificate

Convert to data object a few types that are not asynchronous

---

vertx-core/src/main/java/examples/HTTPExamples.java
vertx-core/src/main/java/io/vertx/core/net/endpoint/Endpoint.java
vertx-core/src/main/java/io/vertx/core/net/endpoint/LoadBalancer.java
vertx-core/src/main/java/io/vertx/core/net/endpoint/ServerEndpoint.java
vertx-core/src/main/java/io/vertx/core/net/endpoint/impl/ConsistentHashingSelector.java
vertx-core/src/main/java/io/vertx/core/net/endpoint/impl/EndpointResolverImpl.java
vertx-core/src/test/java/io/vertx/test/fakeloadbalancer/FakeLoadBalancer.java
vertx-core/src/test/java/io/vertx/test/fakeresolver/FakeEndpointResolver.java
vertx-core/src/test/java/io/vertx/test/fakeresolver/FakeState.java
vertx-core/src/test/java/io/vertx/tests/addressresolver/ResolvingHttpClientTest.java
vertx-core/src/test/java/io/vertx/tests/endpoint/LoadBalancingCornerCasesTest.java
vertx-core/src/test/java/io/vertx/tests/endpoint/LoadBalancingTest.java
vertx-core/src/test/java/io/vertx/tests/endpoint/MappingResolverTest.java

Currently it checks the state is still valid before accessing it which does not have a lot of value and is debatable.
Instead on each access we should check whether the state remains valid so it can be fetched when the state is not anymore valid.

The endpoint resolver implementation should better use the address resolver validity check

---

src/main/java/io/vertx/core/http/impl/WebSocketImplBase.java
src/main/java/io/vertx/core/http/impl/ws/WebSocketFrameImpl.java

Websocket txt messages perform an additional byte[] copy, because:
1. `Buffer::buffer(String)` is performing `String::getBytes` -> first byte[] allocation
2. It than allocates `VertxByteBufAllocator.DEFAULT.heapBuffer`  to write the copy in -> second byte[] allocation + copy
`VertxByteBufAllocator.DEFAULT.heapBuffer` could allocate, based on `Unsafe` presence:
- `UnpooledHeapByteBuf`
- `UnpooledUnsafeHeapByteBuf`
Both the Vertx childrens of these 2 Netty buffers are NOT exposing directly the ability to wrap a given byte[] and that's why we currently perform the copy: in theory `UnpooledHeapByteBuf` vertx variant could be modified to do it, but `UnpooledUnsafeHeapByteBuf` nope, because it doesn't expose its parent constructor which enable setting the byte[] array without copying it (see …

Save intermediate text encoded buffer copies

---

vertx-core/src/main/java/io/vertx/core/impl/ContextImpl.java
vertx-core/src/main/java/io/vertx/core/impl/DuplicatedContext.java
vertx-core/src/main/java/io/vertx/core/impl/VertxImpl.java
vertx-core/src/main/java/io/vertx/core/impl/WorkerExecutor.java
vertx-core/src/main/java/io/vertx/core/impl/WorkerExecutorImpl.java
vertx-core/src/test/java/io/vertx/benchmarks/BenchmarkContext.java
vertx-core/src/test/java/io/vertx/tests/context/ContextTest.java
vertx-core/src/test/java/io/vertx/tests/worker/NamedWorkerPoolTest.java

Motivation:
Execute blocking operations use the context ordered task queue shared with context worker tasks. This prevents context execute blocking tasks to be executed concurrently with worker tasks, e.g. an execute blocking task prevents virtual thread context tasks to be executed.
Changes:
The context ordered task queue is now encapsulated in the worker event executor and not anymore part of the context. The context now creates an internal task queue for execute blocking tasks. As consequence worker contexts have dedicated task queue for context tasks / execute blocking ordered tasks. Event loop contexts still have a single task queue for execute blocking ordered tasks.

Execute blocking operations and context worker tasks should be concurrent

---

src/main/java/io/vertx/core/http/impl/ServerWebSocketImpl.java
src/main/java/io/vertx/core/http/impl/WebSocketImplBase.java

Vertx is using a nested series of synchronized over the connection field which costs keep on piling-up; this cost is particularly evident while executing writeFrame outside of I/O threads.
https://github.com/franz1981/java-puzzles/blob/583d468a58a6ecaa5e7c7c300895392638f688dd/src/main/java/red/hat/puzzles/concurrent/LockCoarsening.java#L76-L85
contains some microbenchmarks results which show how bad the performance is even in the uncontended case, and it can just become worse under contention.
This is addressing https://github.com/quarkusio/quarkus/issues/39148#issuecomment-2396314537 
by removing the nested serie of synchronized over connection, reducing them to the bare minimum i.e. just 2 in the best case scenario

Save recursive locks on websocket writeFrame

---

src/main/java/io/vertx/core/http/impl/HttpServerWorker.java
src/main/java/io/vertx/core/http/impl/HttpUtils.java
src/main/java/io/vertx/core/net/impl/NetServerImpl.java
src/main/java/io/vertx/core/net/impl/NetSocketImpl.java
src/main/java/io/vertx/core/net/impl/SslChannelProvider.java
src/main/java/io/vertx/core/net/impl/VertxSniHandler.java
src/test/java/io/vertx/core/http/HttpTLSTest.java
src/test/java/io/vertx/core/net/NetTest.java

Add peer host and port info for server SslHandler (4.x)

---

vertx-core/src/main/java/examples/CoreExamples.java

Motivation:
As described in #5369 :
The documentation at https://vertx.io/docs/vertx-core/java/#_are_you_fluent compares two code snippets; (1) using a fluent API:
```Java
public void example3(HttpServerRequest request) {
request.response().putHeader("Content-Type", "text/plain").end("some text");
}
```
(2) and the non-fluent approach:
```Java
public void example4(HttpServerRequest request) {
HttpServerResponse response = request.response();
response.putHeader("Content-Type", "text/plain");
response.write("some text");
response.end();
}
```
The first example writes using the `end` method, while the second example also call `write`. I suggest making both examples write in the same way, so that the focus stays on the difference in style.
This PR changes the second example to:
```Java
public …
```

Improve documentation consistency #5369

---

vertx-core/src/main/generated/io/vertx/core/http/WebSocketConnectOptionsConverter.java
vertx-core/src/main/java/io/vertx/core/http/WebSocketConnectOptions.java
vertx-core/src/main/java/io/vertx/core/http/WebSocketVersion.java
vertx-core/src/main/java/io/vertx/core/http/impl/Http1xClientConnection.java
vertx-core/src/main/java/io/vertx/core/http/impl/WebSocketClientImpl.java
vertx-core/src/test/java/io/vertx/tests/http/WebSocketTest.java
vertx-core/src/test/java/io/vertx/tests/json/JsonCodecTest.java

Motivation:
There has been a typo in `WebSocketVersion` enum for ages, it seems reasonable to fix it in Vert.x 5.0
Changes:
Rename `WebsocketVersion` to `WebSocketVersion`

Rename WebsocketVersion to WebSocketVersion

---

vertx-core/src/main/java/io/vertx/core/http/impl/Http2ServerConnection.java
vertx-core/src/main/java/io/vertx/core/http/impl/Http2ServerRequest.java
vertx-core/src/main/java/io/vertx/core/http/impl/Http2ServerResponse.java
vertx-core/src/main/java/io/vertx/core/http/impl/Http2ServerStream.java
vertx-core/src/main/java/io/vertx/core/http/impl/VertxCompressorHttp2ConnectionEncoder.java
vertx-core/src/main/java/io/vertx/core/http/impl/VertxHttp2ConnectionHandlerBuilder.java
vertx-core/src/test/java/io/vertx/tests/http/Http2ServerTest.java
vertx-core/src/test/java/io/vertx/tests/http/compression/HttpCompressionTest.java

The Http2 server-implementation handles content encoding differently compared to the Http1.x server-implementation, which leads to issues.
Http1.x:
The HttpContentCompressor determines the encoding based on the Accept-Encoding header right before writing the headers. If the request handler has already set a Content-Encoding header there will be no further encoding and if the Content-Encoding header is set to "identity" the header is removed by HttpChunkContentCompressor and the response is returned as-is.
Http2:
The encoding is determined already when setting up the stream in Http2ServerConnection and is then passed down to Http2ServerRequest and Http2ServerResponse where it is set using the Content-Encoding-header. The header content is later picked up by the …

Fixes Vert.x issue 5371

---

vertx-core/pom.xml
vertx-core/src/main/java/io/vertx/core/impl/buffer/VertxByteBufAllocator.java
vertx-core/src/main/java/io/vertx/core/net/impl/NetClientImpl.java
vertx-core/src/main/java/io/vertx/core/net/impl/NetServerImpl.java
vertx-core/src/main/java/io/vertx/core/net/impl/VertxHandler.java
vertx-core/src/test/java/io/vertx/it/buffer/TcpAllocationTest.java
vertx-core/src/test/java/io/vertx/tests/buffer/VertxBufferTest.java
vertx-core/src/test/java/io/vertx/tests/net/NetTest.java

Motivation:
Vert.x should use Netty's default allocator whenever possible in order to minimize the resources for pooled allocation (thread-local direct buffers, arenas).
Changes:
`VertxByteBufAllocator.POOLED_ALLOCATOR` reuses `ByteBufAllocator.DEFAULT` when it is pooled otherwise uses `AdaptiveByteBufAllocator.DEFAULT`.
TCP server/client should use `VertxByteBufAllocator.POOLED_ALLOCATOR` instead of `PooledByteBufAllocator.DEFAULT`.

Use Netty default allocator whenever it is pooled otherwise fallback to adaptive allocator

---

src/main/java/io/vertx/core/net/JdkSSLEngineOptions.java
src/main/java/io/vertx/core/net/impl/NetClientImpl.java
src/main/java/io/vertx/core/net/impl/SSLHelper.java
src/main/java/io/vertx/core/net/impl/SslContextProvider.java
src/main/java/io/vertx/core/net/impl/TCPServerBase.java
src/test/java/io/vertx/core/net/NetTest.java
src/test/java/io/vertx/core/net/impl/NetAllocatorsTest.java
src/test/java/io/vertx/core/net/impl/SSLAllocatorTest.java

SSL JDK is very memory allocation intensive, see https://github.com/netty/netty/issues/14208: by default Vertx is using unpooled heap buffers of 16 KB for each interaction with SSL/TSL, which can lead to increase significantly the memory footprint.
In order to fix it I've created a new ssl configuration property (which should become the default in vertx 5) to enable pooling of heap buffers using JDK SSL, while keeping the existing behaviour by default.

Enable buffer pooling settings with a SSL configurable option

---

vertx-core/src/main/java/io/vertx/core/impl/future/CompositeFutureImpl.java
vertx-core/src/test/java/io/vertx/tests/future/CompositeFutureTest.java

See #5399
`CompositeFuture` expected every future to extend `FutureBase`. But sometimes users may come with their own implementation.

CompositeFuture should support custom future implementations

---

vertx-core/src/test/java/io/vertx/tests/shareddata/ClusteredAsyncMapTest.java
vertx-core/src/test/java/io/vertx/tests/shareddata/ClusteredAsynchronousLockTest.java
vertx-core/src/test/java/io/vertx/tests/shareddata/ClusteredSharedCounterTest.java

Motivation:
`ClusteredSharedCounterTest` uses only 2 nodes. When testing with Hazelcast CP subsystem, we need 3 nodes, using 3 nodes makes it easier for us to re-use the test.
I have also unified the common parts in the clustered tests. There is some code duplication, but we can't simply create a common parent to move the code there, because they already extend other classes. Maybe a junit rule would make sense here. Let me know if you want to do something with the duplication, it was already there before this PR.

Use 3 nodes for clustered all tests

---

src/main/java/io/vertx/core/http/impl/Http1xClientConnection.java
src/main/java/io/vertx/core/http/impl/Http2ClientConnection.java
src/main/java/io/vertx/core/http/impl/VertxHttp2Stream.java
src/test/java/io/vertx/core/http/HttpTest.java

Motivation:
Vert.x HTTP client stream does not allocate a stream when the stream has been reset by the application before its allocation. When such stream is being written, the stream behaves normally and fails since the internal state is not correct.
Changes:
Record the reset state of a stream and guard against writes in such case.

HTTP client stream should handle a write to a stream which has been reset without having being allocated

---

vertx-core/src/main/java/io/vertx/core/http/HttpClientRequest.java
vertx-core/src/main/java/io/vertx/core/http/HttpServerResponse.java
vertx-core/src/main/java/io/vertx/core/http/impl/Http1xClientConnection.java
vertx-core/src/main/java/io/vertx/core/http/impl/Http1xServerResponse.java
vertx-core/src/main/java/io/vertx/core/http/impl/Http2ClientConnection.java
vertx-core/src/main/java/io/vertx/core/http/impl/Http2ServerConnection.java
vertx-core/src/main/java/io/vertx/core/http/impl/Http2ServerResponse.java
vertx-core/src/main/java/io/vertx/core/http/impl/Http2ServerStream.java
vertx-core/src/main/java/io/vertx/core/http/impl/Http2UpgradeClientConnection.java
vertx-core/src/main/java/io/vertx/core/http/impl/HttpClientRequestBase.java
vertx-core/src/main/java/io/vertx/core/http/impl/HttpClientStream.java
vertx-core/src/main/java/io/vertx/core/http/impl/StatisticsGatheringHttpClientStream.java
vertx-core/src/main/java/io/vertx/core/http/impl/VertxHttp2ConnectionHandler.java
vertx-core/src/main/java/io/vertx/core/http/impl/VertxHttp2Stream.java
vertx-core/src/test/java/io/vertx/tests/http/Http1xTest.java
vertx-core/src/test/java/io/vertx/tests/http/Http2Test.java
vertx-core/src/test/java/io/vertx/tests/http/HttpTest.java

Motivation:
HTTP stream reset API was incorrectly designed to return a synchronous boolean indicating the outcome of the reset. Resetting a stream involves an interaction with the HTTP connection and instead should be asynchrnous.
Changes:
Change the HTTP stream API to asynchronous.

HTTP stream reset should be asynchronous.

---

vertx-core/src/main/java/io/vertx/core/http/impl/Http1xClientConnection.java
vertx-core/src/main/java/io/vertx/core/http/impl/VertxHttp2Stream.java
vertx-core/src/test/java/io/vertx/tests/http/HttpTest.java

Motivation:
Vert.x HTTP client stream does not allocate a stream when the stream has been reset by the application before its allocation. When such stream is being written, the stream behaves normally and fails since the internal state is not correct.
Changes:
Record the reset state of a stream and guard against writes in such case.

HTTP client stream should handle a write to a stream which has been reset without having being allocated.

---

vertx-core/src/main/java/io/vertx/core/json/JsonArray.java
vertx-core/src/test/java/io/vertx/tests/json/JsonArrayTest.java

Fixes https://github.com/eclipse-vertx/vert.x/issues/5397

Fix JsonArray contains for non-wrapped JsonArray/JsonObject

---

vertx-core/src/main/java/io/vertx/core/http/impl/VertxHttp2Stream.java
vertx-core/src/test/java/io/vertx/tests/net/NetBandwidthLimitingTest.java

Motivation:
The recent changes in HTTP reset API introduced a returned future to signal when the stream reset is performed. The implementation completes the future when the stream reset has been written, instead we should complete it as soon as the frame is written.
Changes:
Complete the H2 reset future after the reset frame has been written.

Complete H2 reset promise as soon as the reset frame has been sent

---

vertx-core/src/main/java/io/vertx/core/Context.java
vertx-core/src/main/java/io/vertx/core/internal/ContextInternal.java

Motivation:
Context local methods should not have been part of the contract of Context initially. This API has been replaced by the ContextLocal API which should be used instead. This API is not going away in 5.0 but we want to get the opportunity to remove it at any time.

Move Context methods getLocal/removeLocal/putLocal to ContextInternal and deprecate them for removal

---

vertx-core/src/main/java/io/vertx/core/impl/HostnameResolver.java
vertx-core/src/main/java/io/vertx/core/impl/verticle/JavaSourceContext.java

The former avoids creating a copy of byte array,
so it's slightly more performant

Use Files.readString instead of Files.readAllBytes

---

vertx-core/src/main/java/io/vertx/core/file/AsyncFile.java

Motivation:
See
https://vertx.io/docs/5.0.0.CR3/apidocs/io/vertx/core/file/AsyncFile.html#exceptionHandler(io.vertx.core.Handler) The inherited javadoc say that it sets the exception handler on the read stream only.
Fix: Mention that is also sets it on the write stream.
Conformance:

Fix wrong inherited javadoc of AsyncFile#exceptionHandler

---

vertx-core/src/main/java/io/vertx/core/impl/ShadowContext.java
vertx-core/src/main/java/io/vertx/core/impl/WorkerExecutorImpl.java
vertx-core/src/test/java/io/vertx/tests/context/ShadowContextTest.java

Motivation:
The implementation of worker executor assumes that a context is always a `ContextImpl`. Since we added support for shadow contexts, the implementation should handle this case as well.
Changes:
Update the worker executor implementation to handle the case of a shadow context.

Handle properly shadow context in worker executor implementation

---

vertx-core/src/main/java/io/vertx/core/impl/VertxImpl.java
vertx-core/src/test/java/io/vertx/tests/context/ContextTest.java
vertx-core/src/test/java/io/vertx/tests/context/EventExecutorProviderTest.java
vertx-core/src/test/java/io/vertx/tests/worker/NamedWorkerPoolTest.java

Motivation:
Thread sticky context was introduced in Vert.x 4 in order to maintain callback ordering when submitting tasks from a non vertx thread.
Vert.x 5 introduces the sticky event-loop feature that implements the same idea for shadow contexts.
In addition shadow context references cannot be reasonnably maintained.
Dropping sticky context support does not break the original intent of the feature and brings behavior consistency when deadling with foreign contexts.
Changes:
Drop stick context feature.

Remove thread sticky context feature

---

src/main/java/io/vertx/core/http/impl/WebSocketEndpoint.java
src/test/java/io/vertx/core/http/WebSocketTest.java

Motivation:
The client WebSocket pool implementation (which is not really a pool but instead a semaphore + a wait queue) does not decrement the semaphore when the connection fail to be established.
Currently, no operation is done beside calling back the caller. As consequence, the wait queue fills with new requests and never satisfy them since.
Changes:
When the connection fails, the semaphore should be released and check the wait queue for pending requests.

The WebSocket client pool should not starve on connect error.

---

src/main/java/io/vertx/core/http/impl/Http2ServerConnection.java
src/test/java/io/vertx/core/http/Http2ServerTest.java

here's a take at solving the issue
happy to take feedback and adjust the solution as needed
see https://github.com/eclipse-vertx/vert.x/issues/5425 for context

allow the 'host' header to be used on HTTP/2 requests if the ':authority' header if missing

---

vertx-core/src/main/java/io/vertx/core/http/impl/Http2ServerConnection.java
vertx-core/src/test/java/io/vertx/tests/http/Http2ServerTest.java

See https://github.com/eclipse-vertx/vert.x/issues/5425
Corresponding PR for 4.x: https://github.com/eclipse-vertx/vert.x/pull/5426

allow the 'host' header to be used on HTTP/2 requests if the ':authority' header if missing [5.x]

---

src/main/java/io/vertx/core/net/TrafficShapingOptions.java
src/main/java/io/vertx/core/net/impl/TCPServerBase.java
src/test/java/io/vertx/core/http/HttpBandwidthLimitingTest.java

Motivation:
This fixes the update-path for traffic shaping options to check for the existence of the traffic shaping handler only for the actual server. Currently, updating traffic-shaping options in a shared-server setting results in `IllegalStateException`, as the traffic-shaping handler is not set for the worker (non-main) servers.
Conformance:

 Fixes updates to traffic shaping options with shared servers

---

vertx-core/src/main/java/io/vertx/core/http/HttpServer.java
vertx-core/src/main/java/io/vertx/core/http/impl/HttpServerImpl.java
vertx-core/src/main/java/io/vertx/core/net/NetServer.java
vertx-core/src/main/java/io/vertx/core/net/TrafficShapingOptions.java
vertx-core/src/main/java/io/vertx/core/net/impl/NetServerImpl.java
vertx-core/src/test/java/io/vertx/tests/http/HttpBandwidthLimitingTest.java
vertx-core/src/test/java/io/vertx/tests/net/NetBandwidthLimitingTest.java

This fixes the update-path for traffic shaping options to check for the existence of the traffic shaping handler only for the actual server. Currently, updating traffic-shaping options in a shared-server setting results in IllegalStateException, as the traffic-shaping handler is not set for the worker (non-main) servers.

Fixes updates to traffic shaping options with shared servers

---

src/main/java/io/vertx/core/impl/ContextBase.java
src/main/java/io/vertx/core/impl/ContextImpl.java
src/main/java/io/vertx/core/impl/ContextInternal.java
src/main/java/io/vertx/core/impl/ContextLocalImpl.java
src/main/java/io/vertx/core/impl/DuplicatedContext.java
src/main/java/io/vertx/core/impl/LocalSeq.java
src/main/java/io/vertx/core/impl/VertxImpl.java
src/main/java/io/vertx/core/spi/context/storage/ContextLocal.java
src/test/java/io/vertx/core/ContextTest.java

Motivation:
Duplicating a duplicated context is supported but the duplication semantic is not defined.
Changes:
This update the duplicated context duplication by doing a copy of each local in the duplicated duplicate. This introduce a duplicator for each local that is responsible for copying the object when it is not null.

Support duplicate context duplication.

---

vertx-core/src/main/java/io/vertx/core/impl/ContextImpl.java
vertx-core/src/main/java/io/vertx/core/impl/ContextLocalImpl.java
vertx-core/src/main/java/io/vertx/core/impl/DuplicatedContext.java
vertx-core/src/main/java/io/vertx/core/impl/LocalSeq.java
vertx-core/src/main/java/io/vertx/core/impl/VertxImpl.java
vertx-core/src/main/java/io/vertx/core/internal/ContextInternal.java
vertx-core/src/main/java/io/vertx/core/internal/VertxInternal.java
vertx-core/src/main/java/io/vertx/core/internal/VertxWrapper.java
vertx-core/src/main/java/io/vertx/core/spi/context/storage/ContextLocal.java
vertx-core/src/test/java/io/vertx/tests/context/ContextTest.java

Duplicating a duplicated context is supported but the semantic of the actual locals is not defined.
This update the duplicated context duplication by doing a copy of each local in the duplicated duplicate. This introduce a duplicator for each local that is responsible for copying the object when it is not null.

Support duplicated context duplication

---

src/main/java/io/vertx/core/impl/VertxImpl.java
src/main/java/io/vertx/core/impl/VertxInternal.java
src/main/java/io/vertx/core/impl/VertxWrapper.java
src/test/java/io/vertx/core/ContextTest.java

Motivation:
Expose the list of registered context locals of the vertx instance, so it gives knowledge for interacting with context locals.

Provide access to context locals

---

src/main/java/io/vertx/core/http/impl/HttpUtils.java
src/test/benchmarks/io/vertx/benchmarks/BenchmarkBase.java
src/test/benchmarks/io/vertx/benchmarks/HeadersValidationBenchmark.java

This change is mostly to improve native-image performance on validation due to closed-world assumption which lead to virtual calls while reading the chars to validate and no loop unrolling during validation.
Additionally, it takes care of moving out of the hot path unlikely validation scenarios for http header values e.g. presence of CRLF or non-printable control chars: this should help JVM mode as well.
Another thing which can help, despite the duplicated code, is the specialized latin head name validation because doesn't require to turn `byte` into `char`s for `AsciiString`.
Without this change the validation of ASCII heard names was slower than normal strings!
FYI @galderz

Improve HTTP validation for inlining and specialized types

---

vertx-core/src/main/java/io/vertx/core/internal/concurrent/InboundMessageQueue.java

Indicate which executor are callbacks invoked from.

Fix InboundMessageQueue Javadoc

---

vertx-core/src/main/asciidoc/http.adoc
vertx-core/src/main/java/examples/HTTPExamples.java
vertx-core/src/main/java/io/vertx/core/http/ClientForm.java
vertx-core/src/main/java/io/vertx/core/http/ClientMultipartForm.java
vertx-core/src/main/java/io/vertx/core/http/HttpClientRequest.java
vertx-core/src/main/java/io/vertx/core/http/HttpHeaders.java
vertx-core/src/main/java/io/vertx/core/http/impl/ClientMultipartFormDataPart.java
vertx-core/src/main/java/io/vertx/core/http/impl/ClientMultipartFormImpl.java
vertx-core/src/main/java/io/vertx/core/http/impl/ClientMultipartFormUpload.java
vertx-core/src/main/java/io/vertx/core/http/impl/HttpClientRequestImpl.java
vertx-core/src/main/java/io/vertx/core/http/impl/HttpClientRequestPushPromise.java
vertx-core/src/test/java/io/vertx/tests/http/HttpTest.java
vertx-core/src/test/java/io/vertx/tests/http/fileupload/HttpClientFileUploadTest.java

Motivation:
HTTP client form submission has been available for ages in Vert.x Web Client exclusively. Since there is no good reason for that, this has been implemented in HTTP client as well.
Changes:
HTTP client form submission implementation.

HTTP client form submission

---

src/main/java/io/vertx/core/eventbus/impl/MessageConsumerImpl.java
src/test/java/io/vertx/core/eventbus/MessageConsumerTest.java

Motivation:
same as in https://github.com/eclipse-vertx/vert.x/pull/5456 just backporting to 4.x
Conformance:

Do consume messages on the correct thread after resume vert.x 4.x backporting

---

vertx-core/src/main/java/io/vertx/core/json/jackson/JacksonCodec.java
vertx-core/src/main/java/io/vertx/core/parsetools/JsonEvent.java
vertx-core/src/main/java/io/vertx/core/parsetools/impl/JsonEventImpl.java
vertx-core/src/test/java/io/vertx/tests/json/JacksonDatabindTest.java
vertx-core/src/test/java/io/vertx/tests/json/JsonCodecTest.java
vertx-core/src/test/java/io/vertx/tests/parsetools/JsonParserTest.java

Remove usage of Jackson `TypeReference`.
Motivation:
Jackson's `TypeReference` is only supported by the `DatabindCodec`. A few methods declaring `TypeReference` are still available on `JacksonCodec` and `JsonEvent`, such methods should be removed because the lead to incomplete usage of `JacksonCodec` and will simply not work at all with potential other implementations of the JSON spi.
Changes:
Remove methods declaring `TypeReference` and update tests accordingly.

Remove usage of jackson type reference where it is not needed

---

vertx-core/src/main/generated/io/vertx/core/eventbus/MessageConsumerOptionsConverter.java
vertx-core/src/main/java/io/vertx/core/eventbus/EventBus.java
vertx-core/src/main/java/io/vertx/core/eventbus/MessageConsumer.java
vertx-core/src/main/java/io/vertx/core/eventbus/MessageConsumerOptions.java
vertx-core/src/main/java/io/vertx/core/eventbus/impl/EventBusImpl.java
vertx-core/src/main/java/io/vertx/core/eventbus/impl/HandlerRegistration.java
vertx-core/src/main/java/io/vertx/core/eventbus/impl/MessageConsumerImpl.java
vertx-core/src/main/java/io/vertx/core/eventbus/impl/ReplyHandler.java
vertx-core/src/test/java/io/vertx/tests/eventbus/EventBusRegistrationRaceTest.java
vertx-core/src/test/java/io/vertx/tests/eventbus/LocalEventBusTest.java
vertx-core/src/test/java/io/vertx/tests/metrics/MetricsTest.java
vertx-core/src/test/java/io/vertx/tests/tracing/EventBusTracingTestBase.java

Motivation:
Reimplement `MessageConsumer` message delivery using `InboundMessageChannel`.
Changes:
`MessageConsumer` uses now an instance of `InboundMessageChannel` to handle message delivery. The dynamic upper bound of buffered messages becomes static to facilitate the implementation. This is a breaking change.
`MessageConsumerOptions` have been introduced to facilitate the configuration of a consumer, this will be back-ported to 4.5.x, in addition the dynamic buffered message upper bound will be deprecated in that branch.

Message consumer message delivery reimplementation

---

vertx-core/src/main/java/io/vertx/core/parsetools/impl/JsonParserImpl.java
vertx-core/src/test/java/io/vertx/tests/parsetools/JsonParserTest.java

Motivation:
Large number representations are not handled by the async JSON parser, leading to a decoder exception since the async parser tries to obtain a long number from the Jackson parser. The parser should be able to handle this case using a big integer.
Changes:
Obtain a java number from the Jackson parser instead of a Long.
Result:
When a large integer number is parsed, the async parser parses the value succesfully and the json event value will be a big integer.

Async JSON parser should handle large integer (literaly speaking) number representations

---

vertx-core/src/main/java/io/vertx/core/impl/deployment/DefaultDeploymentManager.java

This is done because bootstrapping the plumbing
needed by the JDK to produce a UUID value
is expensive, it thus doesn't make sense to
pay this cost when the property isn't actually
needed
As requested in https://github.com/eclipse-vertx/vert.x/pull/5450#discussion_r1936894987

Avoid UUID.randomUUID() in Verticle deployment startup code

---

vertx-core/src/main/java/io/vertx/core/eventbus/impl/clustered/ClusteredEventBus.java
vertx-core/src/main/java/io/vertx/core/eventbus/impl/clustered/InboundConnection.java
vertx-core/src/main/java/io/vertx/core/eventbus/impl/clustered/OutboundConnection.java
vertx-core/src/test/java/io/vertx/tests/eventbus/ClusteredEventBusTest.java

Changes:
Introduce proper `OutboundConnection` (previously `ConnectionHolder`) and handle socket wiring concerns outside of this class. Move the connection cleanup (removing from map and pending message write notifications) to be consistently triggered by the socket close handler.
Introduce proper `InboundConnection` (previously a lambda) and handle socket wiring concerns outside of this class which only cares about decoding clustered messages and relaying them to the event-bus local delivery.
Close the TCP server when the event bus is closed.

Clustered event-bus inbound/outbound connection separation of concerns.

---

vertx-core/src/main/java/io/vertx/core/impl/HostnameResolver.java
vertx-core/src/test/java/io/vertx/tests/dns/HostnameResolutionTest.java

Use simple parser instead of regex for parsing resolv.conf

---

vertx-core/pom.xml
vertx-core/src/main/asciidoc/json.adoc
vertx-core/src/main/java/io/vertx/core/impl/SysProps.java
vertx-core/src/main/java/io/vertx/core/json/jackson/JacksonCodec.java
vertx-core/src/test/java/io/vertx/it/json/JacksonConfigOverrideTest.java
vertx-core/src/test/java/io/vertx/tests/json/JacksonTest.java

Motivation:
Read constraints were added since Jackson 2.15 to provide upper bounds for input such as the maximum number of a name. These constraints can be configured per json factory, Vert.x static json factory should provide configurability for it.
Changes:
Add system properties that configure the Vert.x static Jackson json factory.

Vert.x Jackson json factory read constraint configuration should be overridable

---

vertx-core/src/main/java/io/vertx/core/internal/streams/ReadStreamIterator.java
vertx-core/src/main/java/module-info.java
vertx-core/src/test/java/io/vertx/tests/streams/IteratorTest.java

Motivation:
With virtual threads, it might be a common thing to adapt a Vert.x read stream to a blocking Java iterator. The primary use case of this is the gRPC blocking client generation.
Changes:
An iterator adapter for a Vert.x read stream.
The implementation uses java lock and lock conditions to let the producer thread signal consumer threads.
While the iterator should be consumed by a single thread (because of the hasNext/next racy sequence), the iterator is thread safe and tolerate multiple consumers.
The implementation consumer side is similar to a Java blocking queue and relies on lock conditions to signal state change to consumers.

Add a blocking iterator utility for Vert.x read streams.

---

src/main/java/io/vertx/core/Future.java
src/main/java/io/vertx/core/impl/WorkerExecutor.java
src/test/java/io/vertx/core/FutureAwaitTest.java
src/test/java/io/vertx/core/FutureTest.java
src/test/java/io/vertx/core/VirtualThreadContextTest.java

Motivation:
`Future#await` ensures that we use a virtual thread context to obtain an execute to suspend the virtual thread, however this check also includes execute blocking tasks.
Changes:
When obtaining the worker executor to suspend the current task, ensure that we are on the context thread, so execute blocking tasks are not included.

Handle correctly future await from an execute blocking on a virtual thread

---

vertx-core/src/main/java/io/vertx/core/file/FileSystem.java
vertx-core/src/main/java/io/vertx/core/file/impl/FileSystemImpl.java
vertx-core/src/test/java/io/vertx/tests/file/FileSystemTest.java

Instead deleteRecursive or delete should be used

Remove FileSystem recursive deletion that uses a recursive parameter

---

vertx-core/src/main/java/io/vertx/core/Context.java
vertx-core/src/main/java/io/vertx/core/internal/ContextInternal.java
vertx-core/src/main/java/io/vertx/core/spi/context/storage/ContextLocal.java

Motivation:
Context local data is a feature we should support for users even though it is a more advanced feature.
Changes:
Move API to `io.vertx.core.Context`, improve Javadoc and add missing API methods.

Promote context local to API

---

vertx-core/src/main/java/io/vertx/core/net/impl/VertxConnection.java
vertx-core/src/main/java/io/vertx/core/net/impl/VertxHandler.java
vertx-core/src/test/java/io/vertx/tests/net/ConnectionBaseTest.java

Motivation:
1. the implementation of `VertxConnection` performs un-necessary flushes when a resume operation happens during a outbound drain that will flush the connection
2. resuming the connection while during a read in progress should be a no-op and handled by the `channelRead`/`channelReadComplete` operations

VertxConnection enhancements

---

vertx-core/src/main/java/io/vertx/core/dns/DnsException.java
vertx-core/src/main/java/io/vertx/core/impl/NoStackTraceException.java
vertx-core/src/main/java/io/vertx/core/impl/NoStackTraceThrowable.java
vertx-core/src/test/java/io/vertx/tests/future/FutureAwaitTest.java
vertx-core/src/test/java/io/vertx/tests/virtualthread/VirtualThreadContextTest.java
vertx-core/src/test/java/io/vertx/tests/worker/ExecuteBlockingTest.java

Motivation:
`NoStackTraceThrowable` currently extends `Throwable` and has been moved to the implementation package not exported in `module-info`.
There are several concerns we need to solve:
1. Virtual threads and Kotlin coroutines need to catch a throwable which is not a recommended practice, e.g. an `Exception` catch declaration let the `NoStackTraceThrowable` go through.
2. Users relying on `NoStackTraceThrowable` developing a modular application have to catch `Throwable` instead since the type is not exported.
We should provide a transitory path to remove `NoStackTraceThrowable` in Vert.x 6.
Changes:
`NoStackTraceThrowable` extends `VertxException` instead of `Throwable`.
Users catching `NoStackTraceThrowable` (which is deprecated) can instead catch `VertxException` and achieve the …

Mitigate usage of NoStackTraceThrowable

---

vertx-core/src/main/java/io/vertx/core/json/JsonArray.java
vertx-core/src/main/java/io/vertx/core/json/JsonObject.java
vertx-core/src/main/java/io/vertx/core/json/impl/JsonUtil.java
vertx-core/src/test/java/io/vertx/tests/json/JsonObjectTest.java

Motivation:
`JsonArray`/`JsonObject` hashCode implementations rely on the wrapped data structure hashCode implementation and on the generic `Object` hashCode function.
1. The hash value might differ from data structure implementations.
2. Number coercion is performed in equals which allows case were we do have equality (after coercion) but hash differs (e.g. `4L` and `4D`).
Changes:
- `JsonObject`/`JsonArray` implement `hashCode` methods.
- Number's hashCode is computed against the `hashCode` of their double value.

Provide a coherent implementation of hashCode for JsonObject/JsonArray with respect to equals

---

src/main/java/io/vertx/core/json/JsonArray.java
src/main/java/io/vertx/core/json/JsonObject.java
src/main/java/io/vertx/core/json/impl/JsonUtil.java
src/test/java/io/vertx/core/json/JsonObjectTest.java

Motivation:
`JsonArray`/`JsonObject` hashCode implementations rely on the wrapped data structure hashCode implementation and on the generic Object `hashCode` function.
1. The hash value might differ from data structure implementations.
2. Number coercion is performed in equals which allows case were we do have equality (after coercion) but hash differs (e.g. 4L and 4D)
Changes:
`JsonObject`/`JsonArray` implement `hashCode` methods.
Number's `hashCode` is computed against the `hashCode` of their double value.

Provide a coherent implementation of hashCode for JsonObject/JsonArray with respect to equals.

---

vertx-core/src/main/java/io/vertx/core/impl/ContextImpl.java
vertx-core/src/main/java/io/vertx/core/impl/HAManager.java
vertx-core/src/main/java/io/vertx/core/impl/VertxImpl.java
vertx-core/src/main/java/io/vertx/core/impl/deployment/DefaultDeployment.java
vertx-core/src/main/java/io/vertx/core/impl/deployment/DefaultDeploymentManager.java
vertx-core/src/main/java/io/vertx/core/impl/verticle/VerticleManager.java
vertx-core/src/main/java/io/vertx/core/internal/ContextInternal.java
vertx-core/src/main/java/io/vertx/core/internal/VertxInternal.java
vertx-core/src/main/java/io/vertx/core/internal/VertxWrapper.java
vertx-core/src/main/java/io/vertx/core/internal/deployment/Deployment.java
vertx-core/src/main/java/io/vertx/core/internal/deployment/DeploymentContext.java
vertx-core/src/main/java/io/vertx/core/internal/deployment/DeploymentManager.java
vertx-core/src/test/java/io/vertx/tests/deployment/DeploymentTest.java
vertx-core/src/test/java/io/vertx/tests/ha/ComplexHATest.java
vertx-core/src/test/java/io/vertx/tests/ha/HATest.java

Motivation:
The deployment manager API is currently an implementation, this API is used by Vert.x Shell to extract deployment information.
Changes:
Expose the deployment manager API.
Implementation cleanups.

Expose the deployment manager internal API

---

src/main/java/io/vertx/core/http/impl/Http2ServerConnection.java
src/test/java/io/vertx/core/http/Http2ServerTest.java

Motivation:
The code checking the well formd-ness of an HTTP/2 request leaves the Vert.x stream in an incorrect state when the validation fails.
The Vert.x stream remains reachable from the Netty stream as a stream property but the back reference to the Netty stream is null.
Subsequent stream events expect it to be fully initialised and fails with NPEs.

Fix NPE when handling of HTTP/2 upgrade on server with a malformed host header.

---

vertx-core/src/main/java/io/vertx/core/eventbus/impl/clustered/ClusteredEventBus.java
vertx-core/src/main/java/io/vertx/core/impl/ContextBuilderImpl.java
vertx-core/src/main/java/io/vertx/core/impl/deployment/DefaultDeployment.java
vertx-core/src/main/java/io/vertx/core/internal/pool/ConnectionPool.java
vertx-core/src/test/java/io/vertx/tests/benchmark/Http1xServerConnectionTest.java
vertx-core/src/test/java/io/vertx/tests/context/ContextTest.java
vertx-core/src/test/java/io/vertx/tests/net/ConnectionBaseTest.java
vertx-core/src/test/java/io/vertx/tests/pool/ConnectionPoolTest.java

The Javadoc implies that it is the default, but the implementation leaves it to null, forcing callers to set the EL model everywhere.
With this change, EL threading model is the default and invoking the withThreadingModel method with a null parameter is forbidden.

Make sure ContextBuilder defaults to EL threading model

---

vertx-core/src/test/java/io/vertx/tests/eventbus/ClusteredEventBusTest.java

If the test starts sending messages before the consumer has been fully registered, it might miss some of the messages.

Rework ClusteredEventBusTest#testPreserveMessageOrderingOnContext

---

vertx-core/src/main/java/io/vertx/core/json/JsonArray.java

Using multiplier as in array/list hash code implementations.
Follows-up on #5513

Change JsonArray hashCode to reduce collisions

---

vertx-core/src/main/asciidoc/virtualthreads.adoc
vertx-core/src/main/java/examples/VirtualThreadExamples.java
vertx-core/src/main/java/io/vertx/core/internal/streams/ReadStreamIterator.java
vertx-core/src/main/java/io/vertx/core/streams/ReadStream.java
vertx-core/src/test/java/io/vertx/tests/http/VirtualThreadHttpTest.java
vertx-core/src/test/java/io/vertx/tests/streams/IteratorTest.java

Motivation:
The Vert.x virtual stream programming model provides async/await to interact with asynchronous futures, yet the stream approach has been left naked.
Changes:
A new `ReadStream` blockingStream default method is added to convert a `ReadStream` to a `java.util.stream.Stream`.
This blocking stream can be used from a Vert.x virtual thread or a non Vert.x thread.
When used from a Vert.x virtual thread, each blocking interaction with the stream suspends the virtual thread and release the context ownership to let other tasks process tasks, allowing the context execution to happen and handle pending context tasks.

ReadStream can be adapted to a Java blocking stream

---

vertx-core/src/main/java/io/vertx/core/http/impl/Http1xClientConnection.java
vertx-core/src/main/java/io/vertx/core/http/impl/Http1xServerConnection.java
vertx-core/src/main/java/io/vertx/core/http/impl/WebSocketImplBase.java
vertx-core/src/main/java/io/vertx/core/net/impl/ConnectionBase.java
vertx-core/src/main/java/io/vertx/core/net/impl/DelegatingChannelPromise.java
vertx-core/src/main/java/io/vertx/core/net/impl/NetSocketImpl.java
vertx-core/src/main/java/io/vertx/core/net/impl/VertxConnection.java
vertx-core/src/test/java/io/vertx/tests/net/VertxConnectionTest.java

Motivation:
Channel write promise returned by Vert.x are a mirror of Netty channel promise through a `FutureListener`. We can instead use a custom `ChannelPromise` implementation wrapping a Vert.x promise.
Changes:
Add an implementation of `ChannelPromise` delegating to a Vert.x future, the promise lazily creates an actual `ChannelPromise` if dispatch to a listener is required such as the idle state handler.

Use an implementation of ChannelPromise that delegates to a Vert.x promise

---

vertx-core/src/main/java/io/vertx/core/eventbus/impl/MessageConsumerImpl.java
vertx-core/src/main/java/io/vertx/core/http/impl/ClientMultipartFormUpload.java
vertx-core/src/main/java/io/vertx/core/http/impl/Http1xClientConnection.java
vertx-core/src/main/java/io/vertx/core/http/impl/Http1xServerRequest.java
vertx-core/src/main/java/io/vertx/core/http/impl/VertxHttp2Stream.java
vertx-core/src/main/java/io/vertx/core/http/impl/WebSocketImplBase.java
vertx-core/src/main/java/io/vertx/core/internal/concurrent/InboundMessageQueue.java
vertx-core/src/main/java/io/vertx/core/internal/concurrent/OutboundMessageQueue.java
vertx-core/src/main/java/io/vertx/core/net/impl/NetSocketImpl.java
vertx-core/src/main/java/io/vertx/core/net/impl/VertxConnection.java
vertx-core/src/main/java/io/vertx/core/streams/impl/MessagePassingQueue.java
vertx-core/src/test/java/io/vertx/tests/concurrent/InboundMessageQueueSingleThreadTest.java
vertx-core/src/test/java/io/vertx/tests/concurrent/InboundMessageQueueSpScTest.java
vertx-core/src/test/java/io/vertx/tests/concurrent/InboundMessageQueueTest.java
vertx-core/src/test/java/io/vertx/tests/concurrent/InboundReadQueueTest.java
vertx-core/src/test/java/io/vertx/tests/concurrent/MessagePassingQueueStressTest.java
vertx-core/src/test/java/io/vertx/tests/concurrent/MessagePassingQueueTest.java
vertx-core/src/test/java/io/vertx/tests/concurrent/OutboundMessageQueueTest.java

Motivation:
Channel name implies bidirectionality, in our case this is one way so queue is better naming.

Rename concurrent message channel to message queue

---

vertx-core/src/main/java/io/vertx/core/http/impl/Http1xServerRequest.java

Motivation:
`Http1xServerRequest` should not create an inbound queue for request that do not need it (e.g. GET).
Changes:
Lazy create the inbound queue which avoids instantiating the queue and using it for delivering the request end event.

Http1xServerRequest should lazy create the inbound queue

---

vertx-core/src/main/java/io/vertx/core/http/impl/VertxHttpRequestDecoder.java
vertx-core/src/main/java/io/vertx/core/http/impl/VertxHttpResponseEncoder.java
vertx-core/src/main/java/io/vertx/core/impl/SysProps.java
vertx-core/src/test/java/io/vertx/benchmarks/HttpServerHandlerBenchmark.java
vertx-core/src/test/java/io/vertx/tests/http/Http1xTest.java

Motivation:
Netty `HttpRequestDecoder` only interns HTTP common request headers (such as _content-type_) to their camel case version (e.g. _Content-Type_).
Changes:
Intern common HTTP request headers to their case insensitive constant version as used by Vert.x to query headers. This noticeably avoids full string comparison when looking for certain headers such as determining whether a connection is persistent (_connection_ header).

Add system property to intern common HTTP/1.x request headers to their lower case version

---

vertx-core/src/main/java/io/vertx/core/http/impl/AssembledFullHttpRequest.java
vertx-core/src/main/java/io/vertx/core/http/impl/AssembledFullHttpResponse.java
vertx-core/src/main/java/io/vertx/core/http/impl/AssembledHttpContent.java
vertx-core/src/main/java/io/vertx/core/http/impl/AssembledHttpObject.java
vertx-core/src/main/java/io/vertx/core/http/impl/AssembledHttpRequest.java
vertx-core/src/main/java/io/vertx/core/http/impl/AssembledHttpResponse.java
vertx-core/src/main/java/io/vertx/core/http/impl/Http1xServerConnection.java
vertx-core/src/main/java/io/vertx/core/http/impl/Http1xServerResponse.java
vertx-core/src/main/java/io/vertx/core/net/impl/VertxConnection.java

Motivation:
We incorrectly send incorrect pre response messages (like continue) that makes `Http1xServerResponse` state invalid.
Changes:
Emit messages that correctly reports when a response ends.

Correctly report the response end during Http1xServerResponse lifecycle

---

vertx-core/src/main/java/io/vertx/core/http/impl/VertxHttp2Stream.java
vertx-core/src/main/java/io/vertx/core/internal/concurrent/OutboundMessageQueue.java
vertx-core/src/main/java/io/vertx/core/net/impl/VertxConnection.java
vertx-core/src/test/java/io/vertx/tests/concurrent/OutboundMessageQueueTest.java

Motivation:
In order to reuse `OutboundMessageQueue` elsewhere than in vertx-core, this queue should use an `EventExecutor` instead of an `EventLoop`.
Changes:
Now `OutboundMessageQueue` uses an `EventExecutor` instead of an vEventLoop`

Decouple OutboundMessageQueue from EventLoop

---

vertx-core/src/main/java/io/vertx/core/http/impl/Http1xServerConnection.java
vertx-core/src/main/java/io/vertx/core/http/impl/HttpServerConnectionInitializer.java
vertx-core/src/main/java/io/vertx/core/http/impl/HttpServerImpl.java
vertx-core/src/test/java/io/vertx/benchmarks/HttpServerHandlerBenchmark.java
vertx-core/src/test/java/io/vertx/tests/benchmark/Http1xServerConnectionTest.java
vertx-core/src/test/java/io/vertx/tests/http/Http1xTest.java

Motivation:
50adff0f881bd1dcdb00881a2f29428ffc3233d7 introduced a regression that creates a race situation when the threading model is not event-loop: when the handler pause request, the end event has already been processed and the request end handling event will be lost.
Changes:
Servers bound with a non event-loop threading model must always create the queue to channel event execution in the worker in order to avoid a race situation.

Http1xServerRequest should eagerly create the inbound queue for threading models other than event-loop

---

vertx-core/src/main/java/io/vertx/core/Future.java
vertx-core/src/test/java/io/vertx/tests/future/FutureAwaitTest.java

Motivation:
`Future#await` delegates to its overload with a specifiable timeout and catches the timeout exception that should not occur. That does not take in account the fact that the future itself could throw such exception and swallows it.
Changes:
Rewrite the code to avoid delegation and fix the bug.

Avoid swallowing a TimeoutException on Future#await

---

vertx-core/src/main/java/io/vertx/core/internal/net/NetSocketInternal.java
vertx-core/src/main/java/io/vertx/core/net/impl/NetSocketImpl.java
vertx-core/src/main/java/io/vertx/core/net/impl/VertxConnection.java
vertx-core/src/test/java/io/vertx/tests/net/NetTest.java
vertx-core/src/test/java/io/vertx/tests/net/VertxConnectionTest.java

Motivaiton:
The `NetSocketInternal` should emit read completion events to signal this event and implement batching.
Changes:
Add a new `NetSocketInternal#readCompletionHandler` that signals when the socket has finished reading messages. This should be used when a message handler, it should not be used when using the socket the classic way with a buffer handler.

NetSocketInternal read completion handler

---

vertx-core/src/main/generated/io/vertx/core/http/HttpClientOptionsConverter.java
vertx-core/src/main/java/io/vertx/core/http/HttpClientOptions.java
vertx-core/src/main/java/io/vertx/core/http/impl/Http2UpgradeClientConnection.java
vertx-core/src/test/java/io/vertx/tests/http/Http1xTest.java

Relates to: https://github.com/quarkusio/quarkus/issues/47649

Introduce an option for HTTP/2 upgrade max content length

---

vertx-core/pom.xml
vertx-core/src/main/java/io/vertx/core/ThreadingModel.java
vertx-core/src/main/java/io/vertx/core/impl/ShadowContext.java
vertx-core/src/main/java/io/vertx/core/impl/VertxBootstrapImpl.java
vertx-core/src/main/java/io/vertx/core/impl/VertxImpl.java
vertx-core/src/main/java/io/vertx/core/internal/VertxBootstrap.java
vertx-core/src/main/java/io/vertx/core/spi/context/executor/EventExecutorProvider.java
vertx-core/src/test/java/io/vertx/it/eventexecutor/CustomEventExecutorTest.java
vertx-core/src/test/java/io/vertx/tests/context/EventExecutorProviderTest.java
vertx-core/src/test/java/io/vertx/tests/context/ShadowContextTest.java

Motivation:
For Vert.x 5.0 disable the shadow context feature as we are still lacking good naming and documentation for it. It should be promoted when it becomes more mature.
Changes:
Disable shadow context by default, it can still be configured on a `VertxBootstrap`.

Disable shadow context

---

vertx-core/src/main/java/io/vertx/core/http/PoolOptions.java
vertx-core/src/main/java/io/vertx/core/http/impl/Http1xClientConnection.java
vertx-core/src/main/java/io/vertx/core/http/impl/Http2ClientConnection.java
vertx-core/src/main/java/io/vertx/core/http/impl/Http2UpgradeClientConnection.java
vertx-core/src/main/java/io/vertx/core/http/impl/HttpChannelConnector.java
vertx-core/src/main/java/io/vertx/core/http/impl/HttpClientImpl.java
vertx-core/src/main/java/io/vertx/core/http/impl/WebSocketClientImpl.java
vertx-core/src/test/java/io/vertx/tests/http/HttpTest.java

Closes #5360
It would help in some cases:
- make sure a connection does not live longer than authorized by some firewall
- give an opportunity to the client to find new backend replicas started after the pool reached its maximum size

Support max lifetime on HTTP Client pool

---

vertx-core/src/main/java/io/vertx/core/Vertx.java

Motivation:
Since codegen supports wildcard declarations for permitted types we can promote `Vertx#deploy(Supplier<? extends Deployable>)` to a permitted type translation.
Changes:
Change `Vertx#deploy(Supplier<? extends Deployable>)` from `@GenIgnore` to `@GenIgnore("permitted-type")`

Let Vertx#deploy(Supplier<? extends Deployable>) to be present in RxJava like generators

---

vertx-core/src/main/java/io/vertx/core/Closeable.java
vertx-core/src/main/java/io/vertx/core/datagram/impl/DatagramSocketImpl.java
vertx-core/src/main/java/io/vertx/core/eventbus/impl/HandlerRegistration.java
vertx-core/src/main/java/io/vertx/core/http/impl/CleanableHttpClient.java
vertx-core/src/main/java/io/vertx/core/http/impl/CleanableWebSocketClient.java
vertx-core/src/main/java/io/vertx/core/http/impl/HttpClientBase.java
vertx-core/src/main/java/io/vertx/core/http/impl/HttpClientImpl.java
vertx-core/src/main/java/io/vertx/core/http/impl/HttpServerImpl.java
vertx-core/src/main/java/io/vertx/core/http/impl/WebSocketClientImpl.java
vertx-core/src/main/java/io/vertx/core/impl/SharedResourceHolder.java
vertx-core/src/main/java/io/vertx/core/impl/VertxImpl.java
vertx-core/src/main/java/io/vertx/core/internal/CloseFuture.java
vertx-core/src/main/java/io/vertx/core/internal/CloseSequence.java
vertx-core/src/main/java/io/vertx/core/net/impl/CleanableNetClient.java
vertx-core/src/main/java/io/vertx/core/net/impl/NetClientImpl.java
vertx-core/src/main/java/io/vertx/core/net/impl/NetServerImpl.java
vertx-core/src/test/java/io/vertx/tests/deployment/DeploymentTest.java
vertx-core/src/test/java/io/vertx/tests/vertx/CloseFutureTest.java
vertx-core/src/test/java/io/vertx/tests/vertx/CloseSequenceTest.java
vertx-core/src/test/java/io/vertx/tests/vertx/VertxTest.java

Motivation:
`Closeable#close` should declare its argument with the type `Completable` instead of `Promise` which is more suitable for this since the `Closeable` implementation only cares about completing it and the semantic of `Promise` is not useful here.

Replace Promise<Void> by Completable<Void> in Closeable contract.

---

vertx-core/src/main/java/io/vertx/core/http/impl/SharedHttpClientConnectionGroup.java
vertx-core/src/main/java/io/vertx/core/internal/pool/ConnectionPool.java
vertx-core/src/main/java/io/vertx/core/internal/pool/PoolWaiter.java
vertx-core/src/main/java/io/vertx/core/internal/pool/SimpleConnectionPool.java
vertx-core/src/test/java/io/vertx/test/core/AsyncTestBase.java
vertx-core/src/test/java/io/vertx/tests/pool/ConnectionPoolTest.java
vertx-core/src/test/java/io/vertx/tests/pool/StressTest.java

Motivation:
The connection pool cares about signalling as simply as possible the caller which is often Vert.x middleware. It does not need to expose an API based on Future and instead Completable can be used, leading to less garbage and reduce stack usage in pool signals.
Changes:
- remove the deprecated Handler<AsyncResult> callbacks
- transform Future returning methods to Completable methods

Update connection pool contract to use Completable over Future

---

vertx-core/src/main/java/io/vertx/core/eventbus/impl/EventBusImpl.java
vertx-core/src/main/java/io/vertx/core/eventbus/impl/HandlerRegistration.java
vertx-core/src/main/java/io/vertx/core/eventbus/impl/ReplyHandler.java
vertx-core/src/main/java/io/vertx/core/eventbus/impl/clustered/ClusteredEventBus.java
vertx-core/src/main/java/io/vertx/core/eventbus/impl/clustered/DefaultNodeSelector.java
vertx-core/src/main/java/io/vertx/core/impl/HAManager.java
vertx-core/src/main/java/io/vertx/core/impl/VertxImpl.java
vertx-core/src/main/java/io/vertx/core/spi/cluster/ClusterManager.java
vertx-core/src/main/java/io/vertx/core/spi/cluster/ClusteredNode.java
vertx-core/src/test/java/io/vertx/test/fakecluster/FakeClusterManager.java
vertx-core/src/test/java/io/vertx/tests/cluster/DefaultNodeSelectorTest.java
vertx-core/src/test/java/io/vertx/tests/eventbus/WrappedClusterManager.java
vertx-core/src/test/java/io/vertx/tests/vertx/CreateVertxTest.java
vertx-core/src/test/java/io/vertx/tests/vertx/VertxStartFailureTest.java

The node selector implementation can be simplified to use an drain/loop pattern approach which simplifies its implementation. The current implementation already has a queue approach with a linked list of waiters but it mandates to perform CAS like operations in the entries map.
Instead we can use a wip/mpsc queue node entry which is equivalent but simpler to understand.
instead of Promise as callback argument, this does not force to pass a full promise.

Cluster manager updates

---

vertx-core/src/main/java/io/vertx/core/http/impl/Http1xClientConnection.java
vertx-core/src/test/java/io/vertx/tests/http/WebSocketTest.java

Motivation:
When the HTTP client connection ugprades to a WebSocket it sets a timeout for the WebSocket handshake, when the upgrade is succesfull it cancels the timeout timer.
The current cancellation check does not account for the initial timer ID that is 0.
Changes:
Cancel correctly the timeout timer.

Fix incorrect client WebSocket upgrade handshake timeout cancellation.

---

vertx-core/src/main/java/io/vertx/core/http/impl/Http1xClientConnection.java
vertx-core/src/test/java/io/vertx/tests/http/WebSocketTest.java

Motivation:
When the HTTP client connection ugprades to a WebSocket it sets a timeout for the WebSocket handshake, when the upgrade is succesfull it cancels the timeout timer.
The current cancellation check does not account for the initial timer ID that is 0.
Changes:
Cancel correctly the timeout timer.

Fix incorrect client WebSocket upgrade handshake timeout cancellation

---

src/main/java/io/vertx/core/http/impl/Http2ClientConnection.java
src/test/java/io/vertx/core/http/Http2Test.java

Motivation:
The HTTP/2 client connection sets the connection expiration timestamp when the connection is recycled, assuming it will have at least one stream created.
When no streams is created, the expiration timestamp is not set and the connection is not recycled by the pool.
Changes:
Set the connection expiration timestamp in the connection constructor.

Initialize the HTTP/2 client connection expiration timestamp before recycle gets called

---

vertx-core/src/test/java/io/vertx/tests/http/Http2Test.java

Motivation:
Port test from 4.x branch.

Ensure the HTTP/2 client connection expiration timestamp before recycle gets called

---

vertx-core/src/main/java/io/vertx/core/http/HttpClientRequest.java
vertx-core/src/main/java/io/vertx/core/http/HttpServerResponse.java

Motivation:
`HttpServerResponse#writehead` has been added, `HttpClientRequest#sendHead` is the same operation. The semantic of send is to fully handle the operation and send the entire body. It is preferrable to rename `sendHead` to `writeHead` and align with other write operations on the API.
Changes:
- add default method `HttpClientRequest#writeHead` that delegates to `HttpClientRequest#sendHead`
- deprecate `HttpClientRequest#sendHead` for removal in Vert.x 6

Rename HttpClientRequest#sendHead to HttpClientResponse#writeHead

---

src/main/java/io/vertx/core/http/HttpServerResponse.java
src/main/java/io/vertx/core/http/impl/AssembledHttpResponse.java
src/main/java/io/vertx/core/http/impl/Http1xServerResponse.java
src/main/java/io/vertx/core/http/impl/Http2ServerResponse.java
src/main/java/io/vertx/core/http/impl/VertxHttpResponse.java
src/main/java/io/vertx/core/http/impl/VertxHttpResponseEncoder.java
src/test/java/io/vertx/core/http/HttpTest.java

Let `HttpServerResponse` API send response headers pretty much like `HttpClientRequest#sendHead`
Changes:
Add a new `HttpServerResponse#writeHead` method.

Add HttpServerResponse#writeHead method

---

src/main/java/io/vertx/core/impl/DuplicatedContext.java
src/main/java/io/vertx/core/impl/VertxImpl.java
src/test/java/io/vertx/core/ContextTest.java

Motivation:
Copying the local data of a duplicated context was introduced to duplicate a context and copy its local data in order to implement specific behavior such as the support of grpc context. This behavior is only necessary in Vert.x 5 and this change has been back-ported to Vert.x 4.x to provide a similar implementation of context locals.
This behavior is unexpected for some users of this API and we should preserve the previous behavior by default.
Changes:
Context duplication does not anymore copy the local data of a context.

Revert the default behavior of the internal duplication of a context to avoid the copy of local context data

---

vertx-core/src/main/java/io/vertx/core/http/impl/Http1xServerResponse.java
vertx-core/src/test/java/io/vertx/tests/http/WebSocketTest.java

Backported from #5601
See #5600
When the connection is upgraded manually, it's up to the user to manage the handshake, including extensions.

HttpServerRequest#toNetSocket make the server report its WebSocket capabilities

---

vertx-core/src/main/java/io/vertx/core/http/impl/WebSocketImplBase.java
vertx-core/src/test/java/io/vertx/tests/http/WebSocketTest.java

Motivation:
When closing a client WebSocket, the client sends a close frame and expects the server to respond with a close frame and then close the connection.
Some servers can misbhave by ignoring the close frame and this let the client deal with the socket.
For this case we should the specific status code.
Changes:
When a WebSocket closes without receiving a close frame, the WebSocket status code is the value 1006 (per https://datatracker.ietf.org/doc/html/rfc6455#section-7.1.5)

Let the WebSocket indicate the correct status code when no close frame has been received

---

vertx-core/src/test/java/io/vertx/tests/http/WebSocketTest.java

Incidentally left disabled after https://github.com/eclipse-vertx/vert.x/pull/5195

Re-enable WebSocket TLS tests

---

vertx-core/src/main/java/io/vertx/core/http/HttpHeaders.java
vertx-core/src/main/java/io/vertx/core/http/HttpServerResponse.java
vertx-core/src/main/java/io/vertx/core/http/impl/Http1xServerResponse.java
vertx-core/src/main/java/io/vertx/core/http/impl/Http2ServerResponse.java
vertx-core/src/test/java/io/vertx/tests/http/HttpTest.java

Motivation:
The implementation of HTTP/1.1 send file can be simplied by using two arguments `FileChannel`/`RandomAccessFile` instead of trying to abstract them.
In addition we can set the response content type earlier when a file name is provided.
Changes:
Make `Http1xServerResponse#sendFileInternal` accept both `FileChannel`/`RandomAccessFile` as those are the only arguments we can actually use.
Set the response content type when a file name is available and to _application/octet-stream_ in the generic case.
Add test for sending `RandomAccessFile` instances.

Improve HTTP/1.1 response send file implementation

---

vertx-core/src/main/java/io/vertx/core/http/impl/Http1xServerResponse.java
vertx-core/src/main/java/io/vertx/core/net/impl/NetSocketImpl.java
vertx-core/src/main/java/io/vertx/core/net/impl/VertxConnection.java
vertx-core/src/test/java/io/vertx/tests/http/HttpTest.java

`FileChannel`/`RandomAccessFile` passed to `HttpServerResponse#sendFile` are currently closed and they should not be per contract.

Avoid closing FileChannel/RandomAccessFile passed to HttpServerResponse#sendFile

---

vertx-core/src/main/java/io/vertx/core/http/impl/Http1xUpgradeToH2CHandler.java
vertx-core/src/main/java/io/vertx/core/http/impl/Http2ClientConnection.java
vertx-core/src/test/java/io/vertx/tests/http/fileupload/Http1xClientFileUploadTest.java
vertx-core/src/test/java/io/vertx/tests/http/fileupload/Http2ClientFileUploadTest.java
vertx-core/src/test/java/io/vertx/tests/http/fileupload/Http2WithUpgradeClientFileUploadTest.java
vertx-core/src/test/java/io/vertx/tests/http/fileupload/HttpClientFileUploadTest.java

Motivation:
One should use `setChunked` on `HttpClientRequest` to set the chunked encoding header when necessary, however the user of the request might not be aware of this and set manually a chunked transfer-encoding header, such as the client form API.
Changes:
Remove the transfer encoding header in HTTP/2 client stream before passing headers to the actual implementation.
Add client multipart / form tests.

Vert.x HTTP client should sanitize chunked transfer encoding header for HTTP/2

---

vertx-core/src/main/java/io/vertx/core/impl/VertxThread.java
vertx-core/src/test/java/io/vertx/tests/worker/ExecuteBlockingTest.java

Motivation:
Netty's `BlockHoundIntegration` currently treats `vert.x-internal-blocking` threads as non-blocking by default: https://github.com/netty/netty/blob/4.2/common/src/main/java/io/netty/util/internal/Hidden.java#L189 However, these threads are actually meant for blocking operations in Vert.x. To prevent `BlockHound` from incorrectly flagging blocking calls, we should explicitly override `FastThreadLocalThread.permitBlockingCalls()`.
Modifications:
- Overrode `FastThreadLocalThread.permitBlockingCalls()` for threads `vert.x-internal-blocking-*` to allow blocking operations.
Result:
- Blocking calls from `vert.x-internal-blocking` threads are no longer falsely flagged by `BlockHound`.

Allow blocking calls from vert.x-internal-blocking threads

---

vertx-core/src/main/java/io/vertx/core/http/impl/HttpServerImpl.java
vertx-core/src/test/java/io/vertx/tests/http/HttpServerCloseSequenceTest.java

Motivation:
This is rather an internal implementation detail that is useful for gRPC server to be notified of the server shutdown to close its bound services.
We might make this more formal in the future with an API.

Let an HTTP server request handler implement Closeable to be notified of the server closing

---

vertx-core/src/main/java/io/vertx/core/buffer/impl/BufferImpl.java
vertx-core/src/test/java/io/vertx/benchmarks/BufferReadBenchmark.java

Motivation:
It fixes #5643
on `JDK 17`:
The old results vs Netty were:
```
Benchmark                                        (batchSize)  Mode  Cnt   Score   Error  Units
BufferReadBenchmark.getByteBatchNetty                     64  avgt   20  57.338 ± 0.176  ns/op
BufferReadBenchmark.getByteBatchVertx                     64  avgt   20  81.085 ± 0.109  ns/op
BufferReadBenchmark.getBytesConstantOffsetNetty           64  avgt   20   3.764 ± 0.040  ns/op
BufferReadBenchmark.getBytesConstantOffsetVertx           64  avgt   20   6.233 ± 0.196  ns/op
BufferReadBenchmark.getBytesNetty                         64  avgt   20   6.225 ± 0.022  ns/op
BufferReadBenchmark.getBytesVertx                         64  avgt   20   6.124 ± 0.038  ns/op
```
With these changes:
```
Benchmark …
```

Optimize Buffer's bound checks (Fixes #5643)

---

vertx-core/src/main/java/io/vertx/core/net/impl/NetServerImpl.java
vertx-core/src/test/java/io/vertx/tests/deployment/DeploymentTest.java

See #5621
Get rid of the servers set that was introduced in 86ca0cf but became redundant when close implementation was reworked using close futures in #4352

Verticle instance leak when using shared servers

---

vertx-core/src/main/java/io/vertx/core/http/impl/Http1xClientConnection.java
vertx-core/src/main/java/io/vertx/core/http/impl/HttpClientRequestBase.java
vertx-core/src/test/java/io/vertx/tests/http/Http1xTest.java
vertx-core/src/test/java/io/vertx/tests/http/Http2ClientTest.java

Motivation:
In some cases it is desirable to send an HTTP request that does not carry the http2 pseudo authority header, nor the host header.

Allow an HTTP client request to have a null authority

---

vertx-core/src/main/java/io/vertx/core/http/impl/Http1xClientConnection.java
vertx-core/src/main/java/io/vertx/core/http/impl/HttpClientRequestBase.java
vertx-core/src/test/java/io/vertx/tests/http/Http1xTest.java
vertx-core/src/test/java/io/vertx/tests/http/Http2ClientTest.java

Motivation:
In some cases it is desirable to send an HTTP request that does not carry the http2 pseudo authority header, nor the host header.

Allow an HTTP client request to have a null authority.

---

src/main/java/io/vertx/core/http/impl/Http1xClientConnection.java
src/test/java/io/vertx/core/http/Http1xTest.java

Motivation:
`Http1xClientResponse` flow control uses a read window (an amount of pending bytes received but not yet delivered) that is decremented when the buffer is consumed by the application. When the response is fully received it can happen that the client has not yet consumed it fully, leaving the connection paused until the remaining bytes are consumed. While this is correct, the connection is returned to the pool and we assume capable of servicing a new request and it actually is not.
Changes:
When the last chunk of a response is received, ack the entirety of the stream pending bytes. To do this we introduce a stream read windows that is incremented when a chunk is received and decremented when the chunk is acked. When the last chunk is received we can substract the stream read …

Http1xClientResponse should be acked its read window when it has been fully received

---

vertx-core/src/main/generated/io/vertx/core/dns/AddressResolverOptionsConverter.java
vertx-core/src/main/java/io/vertx/core/dns/AddressResolverOptions.java
vertx-core/src/main/java/io/vertx/core/dns/impl/DnsAddressResolverProvider.java
vertx-core/src/test/java/io/vertx/tests/dns/NameResolverTest.java

Introduce a time unit option that defaults to nanoseconds for hostsRefreshPeriod of AddressResolverOptions

---

src/main/java/io/vertx/core/http/impl/Http2ConnectionBase.java
src/main/java/io/vertx/core/http/impl/HttpServerWorker.java
src/main/java/io/vertx/core/http/impl/VertxHttp2ConnectionHandlerBuilder.java
src/test/java/io/vertx/core/http/Http2MYRServerTest.java

Motivation:
HTTP/2 servers can be vulnerable to MadeYouReset attacks, to protect against this attach Netty can detect a RST flood attack and close the connection in response.
Changes:
Configure the HTTP/2 server connection builder encoder RST flood protection with the same setting than the decoder RST flood protection.
In addition ignore headers frame when the server has received or sent a go away to avoid creating un-necessary request handler calls.

Allow an HTTP/2 server to be protected against MadeYouReset attacks

---

src/main/java/io/vertx/core/http/impl/Http1xClientConnection.java
src/test/java/io/vertx/core/http/Http1xTest.java

Motivation:
The recent change of the HTTP client response flow control to avoid releasing a connection to the pool not fully received introduced a bug creating a data race when acking the response window bytes. This happens when the stream event-loop is different from the connection event-loop.
Changes:
Ack the response window from the connection thread instead of the stream thread.

Ack the HTTP client response window from the correct event-loop thread.

---

vertx-core/src/main/java/io/vertx/core/eventbus/impl/DeliveryContextBase.java
vertx-core/src/test/java/io/vertx/tests/eventbus/EventBusInterceptorTest.java

Motivation:
The current implementation of `DeliveryContext#next` assumes the same thread makes interceptor delivery progress, this API however assumes any thread can make interceptor progress.
Changes:
Rewrite the implementation of `DeliveryContext#next` with an atomic interceptor index that guarantees that progress is visible accross threads until the last interceptor is invoked.

Let the DeliveryContext next implementation work correctly when used by different threads

---

vertx-core/src/main/java/io/vertx/core/eventbus/impl/DeliveryContextImpl.java
vertx-core/src/main/java/io/vertx/core/eventbus/impl/EventBusImpl.java
vertx-core/src/main/java/io/vertx/core/eventbus/impl/HandlerRegistration.java
vertx-core/src/main/java/io/vertx/core/eventbus/impl/MessageConsumerImpl.java
vertx-core/src/main/java/io/vertx/core/eventbus/impl/ReplyHandler.java
vertx-core/src/main/java/io/vertx/core/eventbus/impl/SendContext.java

Motivation:
When the event-bus interceptor chain is empty we can skip the delivery context machinery that is not necessary as it involves creating garbage and atomics. This is possible due to a recent refactoring change.
Changes:
When the interceptor chain is obtained, bypass the delivery context machinery when the chain is empty.

Avoid the event-bus delivery context machinery when there are not interceptors.

---

vertx-core/src/main/java/io/vertx/core/json/jackson/JacksonCodec.java
vertx-core/src/test/java/io/vertx/tests/json/JacksonTest.java

Motivation:
Parsing a vertx structure from a Jackson `JsonParser` should be a possible thing.
Changes:
Expose the `parseObject`/`parseArray`/`parseAny` private methods.

Expose JacksonCodec private parse methods.

---

pom.xml
src/test/java/io/vertx/core/http/HttpTLSTest.java
src/test/java/io/vertx/core/net/NetTest.java

Mottivation
`SelfSignedCertificate` does not seem to work anymore with most recent Java 8 OpenJDK distributions, we need to use instead Bouncy Castle APIs.

Use org.bouncycastle:bcprov-jdk15on for using SelfSignedCertificate in test scope

---

src/main/java/io/vertx/core/http/impl/Http1xServerResponse.java
src/test/java/io/vertx/core/spi/tracing/HttpTracerTestBase.java

Motivation:
`HttpServerResponse#endHandler` and `HttpServerResponse#bodyEndHandler` are after `VertxTracer#sendResponse` for HTTP/1.x and before for HTTP/2.
We should have a consistent behaviour on ordering in order to guarantee predictability for users of this API and ensure that those handlers are invoked before the span end is signalled.

Ensure HttpServerResponse#endHandler and HttpServerResponse#bodyEndHandler are always executed before VertxTracer#sendResponse

---

vertx-core/pom.xml
vertx-core/src/main/asciidoc/net.adoc
vertx-core/src/main/java/examples/NetExamples.java
vertx-core/src/main/java/io/vertx/core/net/SelfSignedCertificate.java
vertx-core/src/test/java/io/vertx/tests/net/NetTest.java
vertx-core/src/test/java/io/vertx/tests/tls/HttpTLSTest.java

Motivation:
`SelfSignedCertificate` does not work consistently on stock Java distribution and requires Bouncy Castle. As consequence it cannot really be used for testing and is complicated to test as well.
Changes:
- Deprecate `SelfSignedCertificate`
- Replace usage of `SelfSignedCertificate` in testing
- Remove `SelfSignedCertificate` from documentation

Deprecate SelfSignedCertificate and update accordingly
